- cmd/down.go
- cmd/root.go
- cmd/up.go
> remove --namespace flag

- README.md
This PR updates README to make it clear on the installation and building section. This also adds a section for testing the installer on minikube latest.
> update README: add installation, build instruction

- cmd/down.go
- cmd/root.go
- cmd/up.go
I have improved a bit the messages and help (specially the Long description of the up and root commands)
> Improved a bit the messages and help we are giving to the user.

- README.md
Here is my take on an intro for the readme to explain what is included in kubeapps
> Introduction for Readme

- LICENSE
- cmd/down.go
- cmd/fs.go
- cmd/root.go
- cmd/root_test.go
- cmd/up.go
- cmd/version.go
- main.go
> add LICENSE

- cmd/dashboard.go
requires latest manifests from kubeapps/manifest
> adds dashboard command

- static/kubeapps-objs.yaml
> stick kubeless to v0.2.4

- pkg/gke/gke.go
- pkg/gke/gke_test.go
Add missing license header to files in pkg/gke
> add license header to pkg

- cmd/down.go
- cmd/root.go
- cmd/root_test.go
- cmd/up.go
- cmd/up_test.go
- scripts/sync-manifest.sh
- static/kubeapps-objs.yaml
This PR aims to generate a base64-ed random password for mongodb and inject it into `static/kubeapps-objs.yaml`
> generate and inject random base64 mongo pw

- cmd/root.go
> use URLEncode base64

- cmd/dashboard.go
- cmd/dashboard_test.go
> assign dynamically available local port for port-forward call

- cmd/root.go
Turns value of `--verbose` to string and add more choices: debug, info, warning, error, fatal, panic
> update verbosity, add more log levels

- README.md
update README to mention `go get`
> add go get to README

- .travis.yml
this will pick up the right binaries to upload for each commit to master branch
> fix files to be uploaded

- docs/ci_builds.md
> add link for CI binaries

- cmd/dashboard.go
- cmd/down.go
- cmd/up.go
Fixed KubeApps -> Kubeapps spelling
> Fix Kubeapps spelling

- .gitignore
- Makefile
- cmd/kubeapps/dashboard.go
- cmd/kubeapps/dashboard_test.go
- cmd/kubeapps/down.go
- cmd/kubeapps/fs.go
- cmd/kubeapps/root.go
- cmd/kubeapps/root_test.go
- cmd/kubeapps/up.go
- cmd/kubeapps/up_test.go
- cmd/kubeapps/version.go
- main.go
This will allow us to put more commands inside the cmd/ dir
> move cmd to cmd/kubeapps

- Makefile
update Makefile to set VERSION var in correct place
> fix kubeapps version cmd

- docs/install.md
Added an extra entry to the install document about required changes to expose the service externally after getting help from slack.
> Added extra information to docs about exposing the dashboard externally

- .gitmodules
- .travis.yml
- Makefile
- removes cross-compilation toolchain for cgo (fixes #173)
- CGO_ENABLED=0 to static builds
- removes faked GOPATH, CI will catch missing deps (fixes #128)
> improve CI builds

- dashboard/package.json
- dashboard/src/actions/functions.ts
- dashboard/src/components/FunctionView/FunctionLogs.css
- dashboard/src/components/FunctionView/FunctionLogs.tsx
- dashboard/src/components/FunctionView/FunctionTester.tsx
- dashboard/src/components/FunctionView/FunctionView.tsx
- dashboard/src/containers/FunctionViewContainer/FunctionViewContainer.tsx
- dashboard/src/react-lazylog.d.ts
- dashboard/src/reducers/functions.ts
- dashboard/src/shared/Function.ts
- dashboard/src/shared/types.ts
- dashboard/yarn.lock
- allows you to test a function with GET/POST params
- allows you to view the logs of a function
> add FunctionTester and FunctionLogs components

- dashboard/package.json
- dashboard/src/actions/functions.ts
- dashboard/src/components/FunctionList/FunctionDeployButton.tsx
- dashboard/src/components/FunctionList/FunctionList.tsx
- dashboard/src/components/FunctionView/FunctionView.tsx
- dashboard/src/containers/FunctionListContainer/FunctionListContainer.tsx
- dashboard/src/moniker-native.d.ts
- dashboard/src/reducers/functions.ts
- dashboard/src/shared/Function.ts
- dashboard/src/shared/types.ts
- dashboard/yarn.lock
> add deploy function form

- dashboard/src/components/ProvisionButton/index.tsx
corrects the firewall parameters to fix osba binding.
> fixes service provisioning for osba

- dashboard/src/components/BindingList/BindingList.tsx
- dashboard/src/components/BindingList/BindingListEntry.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/ConfirmDialog/index.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/FunctionList/FunctionDeployButton.tsx
- dashboard/src/components/InstanceView/AddBindingButton.tsx
- dashboard/src/components/InstanceView/InstanceView.tsx
- dashboard/src/components/ProvisionButton/index.tsx
- dashboard/src/shared/ServiceBinding.ts
> bug fix: catch and display errors when creating bindings

- dashboard/README.md
> docs: update dashboard development docs

- dashboard/src/actions/auth.ts
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/shared/Auth.ts
sends a request to the kubernetes API root to and shows an error if we
get a 401
closes #250
> validate token when logging in

- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/InstanceListView/InstanceCardList.tsx
> fix unnamespaced links

- dashboard/src/actions/catalog.ts
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/index.tsx
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.tsx
- dashboard/src/components/Config/ServiceCatalog/index.tsx
- dashboard/src/components/ErrorAlert/ServiceBrokersNotFoundAlert.tsx
- dashboard/src/components/ErrorAlert/ServiceCatalogNotInstalledAlert.tsx
- dashboard/src/components/ErrorAlert/index.tsx
- dashboard/src/components/InstanceListView/index.tsx
- dashboard/src/containers/RepoListContainer.ts
- dashboard/src/containers/ServiceCatalogContainer.ts
- dashboard/src/reducers/catalog.ts
- dashboard/src/reducers/repos.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceCatalog.ts
adds error handling to App Repos and Service Brokers pages in the Configuration dropdown
> fixes config views error handling

- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/Card/Card.css
- dashboard/src/components/ChartList/ChartListItem.css
- dashboard/src/components/ChartList/ChartListItem.tsx
- dashboard/src/components/FunctionList/FunctionListItem.tsx
> layout CardContent to use screen real-estate effectively

- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/ErrorAlert/MessageAlert.tsx
- dashboard/src/components/ErrorAlert/MessageAlertHeader.tsx
- dashboard/src/components/ErrorAlert/index.tsx
- dashboard/src/components/FunctionList/FunctionList.tsx
> display no apps/functions message

- Makefile
pushd and popd are not available in travis
> fixes getting kubeless version tag in travis ci

- dashboard/src/actions/functions.ts
- dashboard/src/components/FunctionList/FunctionList.tsx
- dashboard/src/shared/KubelessConfig.ts
uses the authz axios instance and updates required permissions
> fix kubeless-config fetching when authz enabled

- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/ChartList/ChartListItem.css
- dashboard/src/components/ErrorAlert/MessageAlert.tsx
- dashboard/src/components/ErrorAlert/MessageAlertHeader.css
- dashboard/src/components/ErrorAlert/MessageAlertHeader.tsx
- dashboard/src/components/FunctionList/FunctionDeployButton.tsx
> consistent button naming for deploying a function/app, message icon

- README.md
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/ProvisionButton/index.tsx
- docs/access-control.md
- docs/authorization.md
- docs/getting-started.md
- manifests/kubeapps.jsonnet
- manifests/user-roles.jsonnet
- Adds a set of ClusterRoles and Roles to make it easier to bind to user
accounts
- Adds a new docuemntation page for configuring Auth in Kubeapps
> add preset RBAC roles and authorization documentation

- docs/install.md
> update instructions for exposing externally

- .travis.yml
- cmd/kubeapps/up.go
- pkg/gke/gke.go
- pkg/gke/gke_test.go
> call out to gcloud CLI to get GKE active user

- .travis.yml
- dashboard/src/components/ErrorAlert/ErrorAlertHeader.test.tsx
- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.test.tsx
- dashboard/src/components/ErrorAlert/helpers.test.tsx
> add tests for PermissionsErrorAlert component

- dashboard/src/components/ErrorAlert/ErrorAlertHeader.test.tsx
- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.test.tsx
- dashboard/src/components/ErrorAlert/PermissionsListItem.test.tsx
- dashboard/src/components/ErrorAlert/__snapshots__/ErrorAlertHeader.test.tsx.snap
- dashboard/src/components/ErrorAlert/__snapshots__/PermissionsErrorAlert.test.tsx.snap
- dashboard/src/components/ErrorAlert/__snapshots__/PermissionsListItem.test.tsx.snap
also add snapshot tests for PermissionsErrorAlert and ErrorAlertHeader
> add tests for PermissionsListItem

- cmd/apprepository-controller/controller_test.go
> cmd/apprepository-controller: unit tests

- dashboard/package.json
- dashboard/src/actions/index.ts
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/ChartList/ChartList.tsx
- dashboard/src/components/ChartList/ChartListItem.tsx
- dashboard/src/components/ErrorAlert/MessageAlert.tsx
- dashboard/src/components/FunctionList/FunctionList.tsx
- dashboard/src/components/InstanceListView/index.tsx
- dashboard/src/components/PageHeader/PageHeader.css
- dashboard/src/components/PageHeader/PageHeader.tsx
- dashboard/src/components/PageHeader/index.tsx
- dashboard/src/components/SearchFilter/SearchFilter.css
- dashboard/src/components/SearchFilter/SearchFilter.tsx
- dashboard/src/components/SearchFilter/index.tsx
- dashboard/src/containers/AppListContainer/AppListContainer.tsx
- dashboard/src/containers/ChartListContainer/ChartListContainer.tsx
- dashboard/src/containers/FunctionListContainer/FunctionListContainer.tsx
- dashboard/src/containers/InstanceListViewContainer.ts
- dashboard/src/shared/utils.ts
- dashboard/yarn.lock
> add search component to pages

- dashboard/src/components/PrivateRoute/PrivateRoute.test.tsx
- dashboard/src/components/PrivateRoute/PrivateRoute.tsx
> add PrivateRoute component tests

- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/LoginForm/__snapshots__/LoginForm.test.tsx.snap
> LoginForm component tests

- manifests/helm-crd.jsonnet
> Update helm-crd version

- dashboard/package.json
- dashboard/src/components/ClassView/index.tsx
- dashboard/src/components/ProvisionButton/index.tsx
- dashboard/src/components/SchemaForm/ArrayFieldTemplate.test.tsx
- dashboard/src/components/SchemaForm/ArrayFieldTemplate.tsx
- dashboard/src/components/SchemaForm/CustomObjectField.test.tsx
- dashboard/src/components/SchemaForm/CustomObjectField.tsx
- dashboard/src/components/SchemaForm/FieldTemplate.test.tsx
- dashboard/src/components/SchemaForm/FieldTemplate.tsx
- dashboard/src/components/SchemaForm/SchemaForm.css
- dashboard/src/components/SchemaForm/SchemaForm.test.tsx
- dashboard/src/components/SchemaForm/SchemaForm.tsx
- dashboard/src/components/SchemaForm/__snapshots__/ArrayFieldTemplate.test.tsx.snap
- dashboard/src/components/SchemaForm/index.tsx
- dashboard/src/react-jsonschema-form.d.ts
- dashboard/src/shared/ServiceCatalog.ts
- dashboard/yarn.lock
fixes #239
cc @sameersbn @jeremyrickard @mhrivnak
> [Service Catalog] render provision form using broker-provided schema

- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.test.tsx
- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.tsx
- dashboard/src/components/ErrorAlert/__snapshots__/PermissionsErrorAlert.test.tsx.snap
- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/LoginForm/__snapshots__/LoginForm.test.tsx.snap
> docs: fix access-control docs link from Kubeapps dashboard

- docs/user/getting-started.md
This has now been fixed in AKS as per https://github.com/Azure/AKS/issues/408#issuecomment-399360101
> docs: remove AKS workaround

- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/ChartView/ChartHeader.test.tsx
- dashboard/src/components/ChartView/ChartMaintainers.test.tsx
- dashboard/src/components/ChartView/ChartReadme.test.tsx
- dashboard/src/components/ChartView/ChartVersionsList.test.tsx
- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/__snapshots__/ChartHeader.test.tsx.snap
- dashboard/src/components/ChartView/index.test.tsx
> add ChartView and subcomponent unit tests

- manifests/tiller-proxy.jsonnet
> Use tagged version for tiller-proxy

- dashboard/src/actions/catalog.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/BindingList/BindingDetails.css
- dashboard/src/components/BindingList/BindingDetails.tsx
- dashboard/src/components/BindingList/BindingList.tsx
- dashboard/src/components/BindingList/BindingListEntry.tsx
- dashboard/src/components/DeploymentForm/DeploymentBinding.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/InstanceView/InstanceView.tsx
- dashboard/src/components/InstanceView/RemoveBindingButton.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/containers/InstanceView.tsx
- dashboard/src/reducers/catalog.ts
- dashboard/src/shared/ServiceBinding.ts
- also adds BindingDetails component for sharing the description list for
binding details
fixes #363
> support for generic secret structures in bindings

- pkg/auth/auth.go
- pkg/auth/auth_test.go
> Add clusterWide property to forbidden response

- dashboard/src/components/Header/Header.tsx
> remove Functions from navigation

- manifests/apprepository.jsonnet
- manifests/kubeapps-dashboard.jsonnet
> kubeapps cli fixes

- README.md
- Improves explanation of what Kubeapps is
- Fix grammatical errors in the readme
- Dial down Kubeless references
> improve Kubeapps readme

- dashboard/src/components/Footer/Footer.tsx
Since we now have a single repo instead of multiple repositories, I've updated the GitHub link in the footer of the Dashboard
> Update GitHub link

- Makefile
- chart/kubeapps/README.md
- docs/developer/README.md
- docs/developer/apprepository-controller.md
- docs/developer/build.md
- docs/developer/chartsvc.md
- docs/developer/dashboard.md
- docs/developer/kubeapps.md
- docs/user/securing-kubeapps.md
Prepares the developers documentation for the upcoming release which deprecates the Kubeapps CLI and also ships a new component, Helm Proxy.
> Update developer documentation

- docs/user/migrating-to-v1.0.0-alpha.5.md
- docs/user/securing-kubeapps.md
* Update migration guide to point to the published chart
* Fix link to Kubeless 0.6.0 manifest
> Migration guide minor fixes

- README.md
- chart/kubeapps/README.md
- docs/user/getting-started.md
- docs/user/install.md
* Point to our Securing Kubeapps guide in every install reference
* Remove the install.md file, as it doesn't have useful information
> Documentation updates

- .circleci/config.yml
- script/e2e-test.sh
- script/libtest.sh
- script/start-gke-env.sh
> Add GKE e2e tests to CircleCI

- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/AppView/AppControls.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/ChartList/ChartListItem.css
- dashboard/src/components/DeploymentStatus/DeploymentStatus.css
- dashboard/src/components/DeploymentStatus/DeploymentStatus.tsx
- dashboard/src/icons/README.md
- dashboard/src/icons/Warning.tsx
- dashboard/src/shared/types.ts
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Fixes #436 
Report the status of the release both in the the `AppList` view and `AppView`. If the application has been deleted (but not purged) hide control buttons:
> Report Application status

- docs/developer/tiller-proxy.md
```console
$ k get deployment kubeapps-tiller-proxy -o name
deployment.extensions/kubeapps-tiller-proxy
```
> Fix tiller proxy image swap info

- cmd/chartsvc/handler.go
- cmd/chartsvc/handler_test.go
- cmd/chartsvc/main_test.go
- dashboard/src/components/ChartList/ChartList.tsx
> Catch empty chart list

- dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
> AppUpgradeComponent tests

- dashboard/src/components/AppView/AppControls.test.tsx
- dashboard/src/components/AppView/AppDetails.test.tsx
- dashboard/src/components/AppView/AppNotes.test.tsx
- dashboard/src/components/AppView/__snapshots__/AppDetails.test.tsx.snap
> AppControls Details and Notes tests

- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/ChartInfo.test.tsx
- dashboard/src/components/AppView/DeploymentItem.test.tsx
- dashboard/src/components/AppView/DeploymentTable.test.tsx
- dashboard/src/components/AppView/ServiceItem.test.tsx
- dashboard/src/components/AppView/ServiceTable.test.tsx
- dashboard/src/components/AppView/__snapshots__/ChartInfo.test.tsx.snap
- dashboard/src/components/AppView/__snapshots__/DeploymentItem.test.tsx.snap
- dashboard/src/components/AppView/__snapshots__/DeploymentTable.test.tsx.snap
- dashboard/src/components/AppView/__snapshots__/ServiceItem.test.tsx.snap
Continuation of #527
Closes #306
Add basic renderization tests for the components of AppView that didn't have them yet.
> Add more unit tests to AppView components

- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Show a single version per application. Fixes #542
> [tiller-proxy] Filter old versions

- chart/kubeapps/Chart.yaml
Also set the default appVersion value for the chart in this repo to "UNRELEASED", it will be set correctly when pushing to bitnami/charts.
> update chart for v1.0.0-alpha.7 release

- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/ChartList/ChartList.tsx
- dashboard/src/components/ChartList/ChartListItem.tsx
- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/ChartView/ChartHeader.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentErrors.tsx
- dashboard/src/components/ErrorAlert/ServiceCatalogNotInstalledAlert.tsx
- dashboard/src/components/ProvisionButton/index.tsx
- dashboard/src/components/UpgradeForm/SelectRepoForm.tsx
- dashboard/src/shared/url.ts
- dashboard/tslint.ci.json
- dashboard/tslint.json
This prevents strings like `hello` that don't actually do any
interpolation.
> add tslint rule to avoid the template strings if not interplating

- script/chart_sync.sh
> Use chart version instead of appVersion

- dashboard/.sass-lint.yml
- dashboard/package.json
- dashboard/src/components/AppView/ServiceItem.scss
- dashboard/src/components/Card/Card.scss
- dashboard/src/components/Card/CardGrid.scss
- dashboard/src/components/ChartList/ChartListItem.scss
- dashboard/src/components/ChartView/ChartReadme.scss
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.scss
- dashboard/src/components/DeploymentStatus/DeploymentStatus.scss
- dashboard/src/components/ErrorAlert/ErrorAlertHeader.scss
- dashboard/src/components/LoginForm/LoginForm.scss
- dashboard/src/components/PageHeader/PageHeader.scss
- dashboard/yarn.lock
- adds sass-lint and sass-lint-auto-fix
- adds package.json scripts for linting sass and autofix
- updates husky precommit hooks to run linter and autofix
- updates existing scss files to match linter
> add sass-lint to project

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
Includes change from https://github.com/helm/charts/pull/7441 to fix label issue in Deployment
> chart: update MongoDB dep to 4.3.1 to fix label selector issue

- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.tsx
> Change generic error message

- docs/developer/dashboard.md
Comply with https://github.com/kubeapps/kubeapps/pull/622
> Update documentation to reflect pod name changes

- .circleci/config.yml
- script/chart-template-test.sh
this adds a helm template test to the CircleCI configuration to test
that the chart renders okay in PRs
> add a helm template test in CI

- dashboard/src/components/ChartList/ChartList.test.tsx
- dashboard/src/components/ChartList/ChartListItem.test.tsx
- dashboard/src/components/ChartList/__snapshots__/ChartList.test.tsx.snap
- dashboard/src/components/ChartList/__snapshots__/ChartListItem.test.tsx.snap
> ChartList tests

- docs/developer/release-process.md
- docs/developer/releases.md
Closes https://github.com/kubeapps/kubeapps/issues/562
> New release documentation

- dashboard/src/actions/apps.ts
- dashboard/src/actions/auth.ts
- dashboard/src/actions/catalog.ts
- dashboard/src/actions/charts.ts
- dashboard/src/actions/config.ts
- dashboard/src/actions/functions.ts
- dashboard/src/actions/namespace.ts
- dashboard/src/actions/repos.ts
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/ChartList/ChartList.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/ClassList/index.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/components/Config/AppRepoList/index.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/FunctionView/FunctionView.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/NamespaceSelector.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/ClassListContainer.ts
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
It updates the ReduxThunk action creators signature types. It also removes unnecessary returned values since an action creator should just do that, dispatch actions, not to be consumed directly. There are still a couple of actions returning a boolean that we could change later. 
Closes https://github.com/kubeapps/kubeapps/issues/658
> Update TS ThunkAction types and returned values in action creators

- chart/kubeapps/Chart.yaml
Bump chart version to pick up v1.0.0-beta.2 release.
> Bump chart version to match v1.0.0-beta.2

- script/release_utils.sh
See diff below: Change applied in `Add \"id\" to headings (#709)`
```
diff /tmp/before.txt /tmp/after.txt 
1c1
< \n\n\n## Installation\n\nTo install this release, ensure you add the [Bitnami charts repository](https://github.com/bitnami/charts) to your local Helm cache:\n\n```\nhelm repo add bitnami https://charts.bitnami.com/bitnami\nhelm repo update\n```\n\nInstall the Kubeapps Helm chart:\n\n```\nhelm install --name kubeapps --namespace kubeapps bitnami/kubeapps\n```\n\nTo get started with Kubeapps, checkout this [walkthrough](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md).\n\n## Changelog- Avoid to submit empty params (#735) 1dc3a2bfe8f63a5fe48ecf696c2735bb66636048 (Andres)\n- Refactor Card list for service instances (#732) …
```
> Fix double quotes escaping

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
changes the troubleshooting with instructions to install Tiller with a
cluster-admin service account
> chart docs: update install troubleshooting for RBAC issues

- chart/kubeapps/Chart.yaml
> Bump chart version for v1.0.0-beta.4 release

- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/components/ChartView/ChartHeader.test.tsx
- dashboard/src/components/ChartView/ChartHeader.tsx
- dashboard/src/components/ChartView/__snapshots__/ChartHeader.test.tsx.snap
Fixes some missing links
Refs https://github.com/kubeapps/kubeapps/pull/788
> Fix catalog links

- dashboard/src/components/ServiceClassList/ServiceClassList.tsx
- dashboard/src/components/ServiceClassList/__snapshots__/ServiceClassList.test.tsx.snap
Quick fix for https://kubernetes.slack.com/archives/C9D3TSUG4/p1542191311062300
> Add missing space

- dashboard/src/components/ServiceInstanceView/DeprovisionButton.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceInfo.test.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceInfo.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceStatus.test.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceStatus.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceView.test.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceView.tsx
- dashboard/src/components/ServiceInstanceView/__snapshots__/ServiceInstanceInfo.test.tsx.snap
- dashboard/src/components/ServiceInstanceView/__snapshots__/ServiceInstanceStatus.test.tsx.snap
- dashboard/src/components/ServiceInstanceView/__snapshots__/ServiceInstanceView.test.tsx.snap
- aligns the page with the AppView layout
- creates two new components
- ServiceInstanceInfo - displays a card with info about the Service Instance
- ServiceInstanceStatus - renders the current status for the Service Instance
- adds a warning above the Service Instance View page to explain that
the page needs to be refreshed for updates and that the Service
Catalog integration is experimental.kkk
fixes #688
> reorganise service instance view layout

- dashboard/src/components/ServiceClassView/ProvisionButton.test.tsx
- dashboard/src/components/ServiceClassView/ProvisionButton.tsx
- dashboard/src/components/ServiceClassView/ServiceClassPlan.test.tsx
- dashboard/src/components/ServiceClassView/ServiceClassPlan.tsx
- dashboard/src/components/ServiceClassView/ServiceClassView.test.tsx
- dashboard/src/components/ServiceClassView/ServiceClassView.tsx
- dashboard/src/components/ServiceClassView/__snapshots__/ProvisionButton.test.tsx.snap
- dashboard/src/components/ServiceClassView/__snapshots__/ServiceClassPlan.test.tsx.snap
- dashboard/src/components/ServiceClassView/__snapshots__/ServiceClassView.test.tsx.snap
- dashboard/src/containers/ServiceClassViewContainer/ServiceClassViewContainer.ts
Ref: #743
Review `ServiceClassView`, `ProvisionButton` and `ServiceClassViewContainer`:
- Add tests
- Split code into a new component `ServiceClassPlan`
- Refactor error rendering (`ErrorSelector`)
- Add `LoadingWrapper`
> Refactor ServiceClassView

- docs/user/securing-kubeapps.md
> [Docs] Avoid using --tls-verify flag by default

- README.md
- docs/user/getting-started.md
> add Roadmap wiki link to docs

- script/start-gke-env.sh
Closes https://github.com/kubeapps/kubeapps/issues/913
Refs https://cloud.google.com/preemptible-vms/
> Preemptible VMs in CI

- docs/architecture/design-proposals/README.md
> Design proposals index

- docs/architecture/design-proposals/README.md
Adds link to the new OIDC proposal, listed alphabetically.
NOTE: I added the acronyms and extended terms to improve search hit chances.
Refs https://github.com/kubeapps/kubeapps/issues/883
> Add link to proposal

- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.test.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/components/AppView/AccessURLTable/__snapshots__/AccessURLTable.test.tsx.snap
- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.tsx
- dashboard/src/containers/AccessURLTableContainer/index.ts
- dashboard/src/containers/helpers/index.test.ts
- dashboard/src/containers/helpers/index.ts
- dashboard/src/shared/ResourceRef.test.ts
- dashboard/src/shared/ResourceRef.ts
- wraps AccessURLTable in a container to load resources from Redux
- AccessURLTable initiates fetches for Ingresses (loads faster than watching)
- Errors fetching Ingresses are shown
refs #882
> Improves loading resources for the AccessURLTable in AppView

- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.tsx
- dashboard/src/containers/DeploymentItemContainer/DeploymentItemContainer.ts
- dashboard/src/containers/ServiceItemContainer/ServiceItemContainer.ts
- dashboard/src/shared/ResourceRef.test.ts
- dashboard/src/shared/ResourceRef.ts
> get plural from ResourceRef rather than hardcoding

- chart/kubeapps/values.yaml
> Update chart-svc version

- chart/kubeapps/Chart.yaml
bumps chart version to v1.3.0 as per semver for a feature release
> bump chart version for v1.2.0 release

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-rbac.yaml
also fixes an issue where the write role was being created even if
rbac.create=false
> corrects names of chart AppRepository roles to match documentation

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
> bump chart-repo to 1.4.0-r1 to fix uid issue

- dashboard/src/components/ConfirmDialog/ConfirmDialog.test.tsx
- dashboard/src/components/ConfirmDialog/ConfirmDialog.tsx
- dashboard/src/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap
> switch to using LoadingWrapper instead of LoadingSpinner

- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/ChartView/ChartDeployButton.tsx
- dashboard/src/components/ChartView/ChartHeader.scss
- dashboard/src/components/ChartView/ChartHeader.test.tsx
- dashboard/src/components/ChartView/ChartHeader.tsx
- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/ChartView/__snapshots__/ChartHeader.test.tsx.snap
Fixes #984 
I suggest to (apart than changing the text of the button) move the Deploy button to the title just like the AppList and ServiceList views have it:
> Revamp deploy button

- dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
> Fix go back button in the upgrade form

- chart/kubeapps/Chart.yaml
> bump chart version to 1.6.2 for kubeapps v1.3.2 release

- dashboard/src/actions/helpers/object.ts
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/AppView/SecretsTable/SecretsTable.tsx
- dashboard/src/components/AppView/helpers/index.ts
- dashboard/src/components/Catalog/CatalogItem.test.tsx
- dashboard/src/components/ChartView/ChartVersionsList.tsx
- dashboard/src/components/ServiceInstanceList/ServiceInstanceCardList.tsx
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.tsx
- dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.ts
- dashboard/src/containers/SecretItemContainer/SecretItemContainer.ts
- dashboard/src/containers/ServiceItemContainer/ServiceItemContainer.ts
- dashboard/src/containers/WorkloadItemContainer/WorkloadItemContainer.ts
- dashboard/src/containers/helpers/index.ts
- dashboard/src/reducers/kube.ts
> Remove global imports of lodash

- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.test.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.tsx
> Remove service watching from AccessURLTable

- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/OtherResourceItem/OtherResourceItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/OtherResourceItem/__snapshots__/OtherResourceItem.test.tsx.snap
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.tsx
Ref: #848
Follow up: #1063
Minor review of #1063
> Refactor tables in the AppView (cont)

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
Support for https://kubernetes.slack.com/archives/C9D3TSUG4/p1540379223000100
> chart: update nginx image tag

- dashboard/src/components/SchemaForm/SchemaForm.tsx
> Avoid validation of the SchemaForm

- docs/user/private-app-repository.md
Fix #1069.
@migmartri @andresmgot please help review.
> Add doc for enabling Harbor authentication

- chart/kubeapps/values.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- dashboard/package.json
- dashboard/yarn.lock
The @types/json-schema version in dashboard/package.json is out of date. So make it consistent with the version in yarn.lock.
> Fix @types/json-schema version in dashboard/package.json

- chart/kubeapps/Chart.yaml
For including the new version v1.4.2
> Bump chart version

- chart/kubeapps/README.md
See #1111 for details.
/cc @prydonius , @migmartri
> Document Kubeapps frontend proxying to k8s api

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/reducers/apps.ts
Fixes #1126
Dispatch actions every time we perform an operation over an application. Avoid duplicated dispatch.
> Add redux actions for app operations

- pkg/chart/chart.go
- pkg/chart/chart_test.go
Small prequel to clean up #1137, based on https://github.com/kubeapps/kubeapps/pull/1137/files#r317539976
Ref #1110
> Replace chart.Auth types with those in apprepo types.

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
Add comment in the `values.yaml` file with the global storage class parameter.
> Add global storage class to values.yaml

- pkg/chart/chart.go
- pkg/chart/chart_test.go
Removes code no longer required after #1151 .
This required a bit of refactoring for one of the tests, now that we only support the auth from the AppRepository custom resource. Let me know if it's not clear.
NOTE: while QAing this (together with the most recent branches), I see that when upgrading an app, the dashboard is still requesting AppRepositories (a `REQUEST_REPOS` action is dispatched). It appears to be because the `SelectRepoForm` is used during upgrade, which calls `checkChart`. Thoughts @andresmgot ? Not a blocker for this PR, but I'd be keen to remove that requirement if we can.
Ref: #1110
> Remove no longer used code since #1151

- dashboard/package.json
- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/reducers/auth.test.ts
- dashboard/src/reducers/auth.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/AxiosInstance.test.ts
- dashboard/yarn.lock
Part 1 to fix #1162. This diff adds jsonwebtoken and updates the Auth to parse this and store the `defaultNamespace` in state when logging in.
Part 2 updates the header component/container to use this.
> Add defaultNamespace to auth state.

- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
> Fix root redirect when no default namespace is set

- docs/user/getting-started.md
Ref #1185 
2.12 is also a valid version but to be safe better recommend the latest version.
> Update Helm version in the getting started guide

- dashboard/package.json
- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.scss
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/shared/schema.test.ts
- dashboard/src/shared/schema.ts
- dashboard/yarn.lock
Ref #1182 
If the chart schema is present, validate it before submitting the chart:
> Validate values against the schema if exists

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
> Add schema validation for an upgrade if the schema exists

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/shared/schema.ts
> Basic parameter for hostname configuration

- .gitignore
- Makefile
- docs/user/manifests/openshift-tiller-with-apprepository-rbac.yaml
- docs/user/manifests/openshift-tiller-with-crd-rbac.yaml
- script/openshift-cluster.mk
Automating the local development installation of kubeapps on minishift (openshift version of minikube). Part 1.
> Initial WIP openshift example

- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/DeploymentForm/__snapshots__/DeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/components/UpgradeForm/__snapshots__/UpgradeForm.test.tsx.snap
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Config.test.ts
- dashboard/src/shared/Config.ts
> Remove basic form feature flag

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
Unify README to share sections with other Bitnami Charts
> Unify and refactor README

- chart/kubeapps/templates/apprepository-rbac.yaml
- integration/jest-puppeteer.config.js
- integration/jest.setup.js
- integration/package.json
- integration/use-cases/create-registry.js
- integration/use-cases/default-deployment.js
- integration/use-cases/missing-permissions.js
- script/e2e-test.sh
Closes #1209 
Add two new tests:
- Use a non-privileged user to create a release (that fails)
- Create a new repository
See inline comments.
> Additional end-to-end tests

- integration/jest.environment.js
- integration/package.json
- integration/use-cases/create-registry.js
- integration/use-cases/default-deployment.js
- integration/use-cases/missing-permissions.js
Ref #1209 
We are still seeing timeout issues. The global configuration appears not to be working.
> Move timeout setting per test

- docs/developer/basic-form-support.md
Docs update after #1257 and #1258
> Update developer docs for basic form

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/DeploymentFormBody/__snapshots__/DeploymentFormBody.test.tsx.snap
> Fix button margin

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepositories.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeapps/kubeapps/1272)
> Fix security context indentation. Fixes #1271

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepositories.yaml
- chart/kubeapps/values.yaml
Merge after: https://github.com/kubeapps/kubeapps/pull/1272
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeapps/kubeapps/1273)
> add support for nodeSelector on apprepository syncjob. Fixes #1255

- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/__snapshots__/DeploymentForm.test.tsx.snap
- dashboard/src/components/Footer/Footer.tsx
[trivial]
There was an error throwing a warning in the console so I fixed it. I have also added some automatic prettier changes.
> Fix warning and prettier

- chart/kubeapps/values.yaml
Include information for `cookieSecret` option of the auth proxy (including how to generate it).
As per https://kubernetes.slack.com/archives/C9D3TSUG4/p1574425334139300?thread_ts=1574335985.136900&cid=C9D3TSUG4
cc @lindhe
> Include usage information for the oauth2-proxy field 'cookieSecret'

- chart/kubeapps/templates/dashboard-config.yaml
- dashboard/public/config.json
- dashboard/src/actions/auth.test.tsx
- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/Config.ts
Mechanical search/replace to rename `loginURI` -> `oauthLoginURI` and `logoutURI` -> `oauthLogoutURI`.
As per https://github.com/kubeapps/kubeapps/pull/1315#discussion_r350187984
> Rename loginURI and logoutURI

- cmd/asset-syncer/delete.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
Define a generic interface that any database provider must provide for the asset-syncer:
```
Delete(repo): error
Sync(repo, url, auth): error
```
- ref #651
> Add generic interface

- .circleci/config.yml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/values.yaml
- script/chart_sync_utils.sh
- script/e2e-test.sh
Build and use the `asset-syncer` within the Kubeapps CI.
> Add the asset-syncer to the pipeline

- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
`Sync` method for the PostgreSQL driver of the `asset-syncer`. Still missing the tests and the icons fetch logic because I plan to refactor this method first (for the mongodb driver as well).
- ref #651
> Add sync method for postgresql

- pkg/auth/authgate.go
Moving forward, this should help us implement Helm 3 support (see #1309).
> Refactor token extraction

- docs/architecture/design-proposals/replacing-mongodb.md
This is a design proposal for https://github.com/kubeapps/kubeapps/issues/651
> MongoDB replacement proposal

- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/types.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
The goal of this PR is to move anything not related to the database out of the `Sync` method of the database so it can be reused for the different drivers.
Apart from that, I have moved the mongodb methods to the `mongoManager` struct.
- ref #651
> Refactor sync method

- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
Unit tests for the `Sync` method of the postgres manager. We cannot test a lot because this depends highly from the posgresql connection and response but we are adding some coverage. End-to-end tests will cover better this functionality.
- ref #651
> Unit tests for postgres sync

- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- chart/kubeapps/values.yaml
Adds the missing readiness/liveness checks for tiller proxy.
K8s can restart the pod when necessary :)
- fixes #1296 
I'm just adding this in passing since I'm currently adding some functionality in tiller-proxy in #1347
> Hook up the readiness and liveness checks for tiller proxy

- chart/kubeapps/values.yaml
Updates kubectl and oauth2-proxy images.
Tested locally with login via oauth2/dex.
> Update kubectl and oauth2 proxy images

- chart/kubeapps/templates/apprepository-deployment.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- cmd/apprepository-controller/main.go
I forgot to update the flags in the apprepository-controller after https://github.com/kubeapps/kubeapps/pull/1341 so this PR fixes that.
The go tests are failing because it's missing the changes in #1345 (and viceversa :upside_down_face:) 
- ref #651
> Add new flags to the apprepository-controller

- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
Follow up of https://github.com/kubeapps/kubeapps/pull/1339#issuecomment-561613522
This also fixes the golang tests for postgres.
> Use Postgres arguments

- chart/kubeapps/templates/assetsvc-deployment.yaml
- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/utils_test.go
- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main.go
- cmd/assetsvc/main_test.go
- cmd/assetsvc/mongodb_utils.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/utils.go
- go.sum
- pkg/dbutils/dbutils.go
- pkg/dbutils/mongodb_utils.go
- pkg/dbutils/postgresql_utils.go
Define the `assetManager` interface and move the database related methods to that interface. This enable us to start working on the same methods for postgresql.
- ref #651
> Refactor database methods for assetsvc

- cmd/kubeops/Dockerfile
_"That line can't be very important!"_ — me, 2019
> Copy CA certs to Kubeops container

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepositories-secret.yaml
The chart was omitting a needed `\n` for the authorizationHeader
- fixes #1391
> Fix authorizationHeader content

- cmd/assetsvc/handler.go
- cmd/assetsvc/main.go
- cmd/assetsvc/mongodb_utils.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
- cmd/assetsvc/utils.go
- pkg/dbutils/postgresql_utils.go
Database methods for PostgreSQL. Sorry in advance for the long PR! I was figuring out the implementation while developing them. Right now it's functional but there are several `TODO` comments in the code that I plan to work afterwards.
Requires #1394
> PostgreSQL methods

- cmd/assetsvc/handler.go
- cmd/assetsvc/main.go
- cmd/assetsvc/mongodb_utils.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
- cmd/assetsvc/utils.go
- go.mod
- go.sum
- pkg/dbutils/postgresql_utils.go
- pkg/dbutils/postgresql_utils_test.go
Methods to query one or several charts using PostgreSQL. Include tests for `postgresql_utils.go`
> Query methods for PostgreSQL

- pkg/agent/agent_test.go
Fixes flaky test in CI due to Helm's memory driver not providing consistent ordering.
Removed some dead code.
CI passes?
- fixes #
> Work around lack of consistent ordering for helm memory driver.

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- go.mod
- pkg/agent/agent.go
This PR implements `CreateRelease` using the Helm 3 API.
- Charts can be installed from the added Helm repos in Kubeapps.
- Validates `values.yaml` against schema files if present.
- Creating a release works, and it can be listed, but an error message is displayed because `GetRelease` does not exist yet.
- There are no tests yet (Help appreciated).
Based on discussions in #1309 (@lindhe)
Related PR for `ListReleases` in #1359  (@SimonAlling)
Don't forget to set `useHelm3` to `true` in `values.yaml` to see the changes.
> Add Helm 3 CreateRelease

- chart/kubeapps/README.md
Add docs of how to use PostgreSQL or MongoDB in the chart.
> Add database choice to chart README

- .circleci/config.yml
- script/e2e-test.sh
When testing the latest release (we do so when we release a new chart version), the goal of the job is to test that the bitnami images work with the new chart. Before this PR, we were testing the `kubeapps` images released for that chart. While those images contains the same code, the build process differ so we should test those bitnami images instead.
> Test bitnami images

- pkg/agent/agent.go
- pkg/agent/agent_test.go
Add support for listing all statuses when requesting them.
- ref #1056
> [helm3] List all statuses if required

- cmd/kubeops/internal/handler/dashboardcompat.go
- cmd/kubeops/internal/handler/dashboardcompat_test.go
- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/internal/handler/handler_test.go
The deletion time was missing in the response given by `GetRelease`. This is used to show a "Purge" button when viewing a deleted release:
The tests for `GetRelease` has not been merged yet so I will add it once that's ready.
cc/ @latiif @SimonAlling
> [helm3] Return deleted time if exists

- docs/user/manifests/kubeapps-local-dev-values.yaml
- script/deploy-dev.mk
Updates the `deploy-dev` make target, which sets up kubeapps on a kind cluster, to do so both with helm3 and for kubeapps running helm3.
Really just benefiting myself (currently using this env for all development)
I won't land this yet, but will keep it handy for helm3 work.
> Update deploy-dev make target to setup kubeapps with helm3

- cmd/kubeops/internal/handler/handler.go
See the removed TODOs. Just something I wanted to ensure happened before we release the Helm 3 support.
> Log error details rather than returning such details to user.

- dashboard/src/components/DeploymentFormBody/AdvancedDeploymentForm.tsx
Show a explanation note about comments in the advanced form:
Context: https://github.com/kubeapps/kubeapps/issues/1423#issuecomment-574224903
> Add note about comments in the advanced form

- docs/user/manifests/kubeapps-local-dev-values.yaml
- script/cluster-kind.mk
- script/deploy-dev.mk
Updates the kind development environment to use postgresql by default.
Also updated to support the latest `kind` version (0.7.0) while still retaining the separate kubeconfig for the env.
> Use postgres backend in dev environment.

- cmd/kubeops/internal/handler/handler_test.go
- pkg/agent/agent_test.go
Test new functionality introduced in #1421 
- Adds test for UpgradeRelease in `/pkg/agent`.
- Adds a separate test for `action="upgrade"` in `/cmd/kubeops/internal/handler/handler_test.go`. 
- Tests #1421.
- Dry testing in `handler_test.go` as per #1439.
Signed-off-by: Latiif <abdullatif.alshriaf@combitech.se>
cc: @SimonAlling  @lindhe
> [kubeops] Add testsfor UpgradeRelease

- integration/use-cases/upgrade.js
- script/e2e-test.sh
This test:
- Installs a chart using an old version.
- Checks that the application notifies that there is a new version available.
- Upgrades to that version.
It uses a new service account "edit" which has permissions to write resources only in its namespace (and don't have permissions to read/write apprepositories).
Requires the changes of https://github.com/kubeapps/kubeapps/pull/1472
> Upgrade end-to-end test

- README.md
- chart/kubeapps/README.md
- chart/kubeapps/values.yaml
- docs/architecture/overview.md
- docs/developer/kubeops.md
- docs/user/getting-started.md
- docs/user/securing-kubeapps.md
- script/release_notes.tpl
Update several files to reflect the latest status of Kubeapps (and Helm). This PR is better merged after the new release (1.8.0) is available for users.
> Update documentation for Kubeapps 1.8

- integration/use-cases/create-registry.js
Same as https://github.com/kubeapps/kubeapps/pull/1492 apparently that solution didn't work:
https://github.com/kubeapps/kubeapps/pull/1492#issuecomment-580754178
Again, trying with the double-click approach (if fails).
> Fix flaky test

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
Run `helm dependency update` with helm3.
`helm dependency build` command will work with helm3. If `helm dep up` is executed with helm2 and later on you execute `helm dep build` with helm 3 you get this error:
```
Error: Chart.lock is out of sync with Chart.yaml
```
> Update requirements using helm3

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
Update Nginx image since debian-9 is no longer maintained,
> Update nginx image

- cmd/asset-syncer/postgresql_db_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/assetsvc/postgres_db_test.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
- pkg/chart/models/chart.go
- pkg/dbutils/dbutilstest/dbutilstest.go
- pkg/dbutils/postgresql_db_test.go
- pkg/dbutils/postgresql_utils.go
Some background work so that the asset service can also be tested against pg.
Some comments inline.
> Add pg tests for assetsvc

- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/postgresql_db_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
- pkg/dbutils/postgresql_utils.go
Ref: #1521 
Updates the `removeMissingCharts` postgres functionality to remove from the repo (which is namespaced) only.
> Update removeMissingCharts to remove from a namespaced repo only.

- dashboard/package.json
- dashboard/src/components/ApplicationStatus/ApplicationStatus.scss
- dashboard/src/components/ApplicationStatus/ApplicationStatus.test.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.tsx
- dashboard/yarn.lock
From the design document at https://github.com/kubeapps/kubeapps/pull/1529
Add a pie chart for the application status showing the number of pods running for the different workloads of an application:
> Additional info for application status

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/components/InfoCard/InfoCard.scss
- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
- dashboard/src/containers/OperatorsListContainer/OperatorsListContainer.tsx
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Operator List view obtained checking the CRD `packagemanifests.packages.operators.coreos.com`:
The tags are the operator provider and the category.
Still needs to write more tests but sending this already to get an early review :)
- ref #1552
> Add operator list

- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
Include a link the configuration section for Operators:
- ref #1552
> Make the operator section navigable

- script/e2e-test.sh
Fixes master builds disabling the invalidateCache flag while testing the latest release:  https://circleci.com/gh/kubeapps/kubeapps/18448
> Avoid invalidate cache flag while testing the latest release

- script/e2e-test.sh
Fixes https://circleci.com/gh/kubeapps/kubeapps/18477?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> Fix missing var

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/components/ChartView/ChartReadme.scss
- dashboard/src/components/OperatorView/CapabilityLevel.scss
- dashboard/src/components/OperatorView/OperatorCapabilityLevel.test.tsx
- dashboard/src/components/OperatorView/OperatorCapabilityLevel.tsx
- dashboard/src/components/OperatorView/OperatorDescription.test.tsx
- dashboard/src/components/OperatorView/OperatorDescription.tsx
- dashboard/src/components/OperatorView/OperatorHeader.test.tsx
- dashboard/src/components/OperatorView/OperatorHeader.tsx
- dashboard/src/components/OperatorView/OperatorInstallation.tsx
- dashboard/src/components/OperatorView/OperatorView.test.tsx
- dashboard/src/components/OperatorView/OperatorView.tsx
- dashboard/src/components/OperatorView/__snapshots__/OperatorHeader.test.tsx.snap
- dashboard/src/components/OperatorView/__snapshots__/OperatorView.test.tsx.snap
- dashboard/src/components/OperatorView/index.tsx
- dashboard/src/containers/OperatorViewContainer/OperatorViewContainer.tsx
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Operator View. All the information can be extracted from the current definition of a `PackageManifest`:
- ref #1552
> Operator View

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main.go
Small cleanup to remove now redundant handler.
Ref: #1521
> Remove unnecessary handler

- dashboard/package.json
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/yarn.lock
Update dependencies in yarn.lock
> Update dashboard deps

- .circleci/config.yml
- chart/kubeapps/requirements.yaml
Update also `kubectl` and `kind` versions to fix builds in master. Apart from that I have modified the GKE builds to use Helm 3 and posgresql.
> Enable builds for GKE 1.15

- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/url.ts
Fix the operator list and the application list for operators when selecting "All Namespaces" in the namespace selector.
- ref #1552
> Show operators and instances in all namespaces

- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/CatalogItem.test.tsx.snap
> Replace chart/operator tag for an icon in the Catalog

- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
And point to GitHub issues:
- ref #1552
> Add alpha status notice for operators

- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
- dashboard/src/containers/OperatorsListContainer/OperatorsListContainer.tsx
- dashboard/src/reducers/operators.ts
Add a search bar for Operators (same approach than the Catalog):
- ref #1552
> Add search bar for operators

- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
Follow up of #1635 Same thing but with "Capability Levels" now.
> Add Capability filter

- dashboard/src/components/AppView/ResourceTable/ResourceItem/ServiceItem/ServiceItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ServiceItem/ServiceItem.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ServiceItem/__snapshots__/ServiceItem.test.tsx.snap
> Allow services with no ports defined

- pkg/kube/kube_handler.go
I forgot to remove this debug line.
> Remove debug print line

- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
It's no longer needed to use the version 7.8.10 for MongoDB
> Update chart requirements

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/ChartView/ChartReadme.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/containers/CatalogContainer/CatalogContainer.tsx
cc/ @absoludity I got this after doing some commit. I guess this is because you are skipping the pre-commit hook?
> Automatic code-style change

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoForm.test.tsx.snap
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/Secret.test.ts
- dashboard/src/shared/Secret.ts
Follow up of #1684
Add the subform to create docker credentials:
- ref #1522
> Allow to create docker registry credentials from the form

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
Update debian-10 Docker images including a fix for [CVE-2020-1967](https://security-tracker.debian.org/tracker/CVE-2020-1967)
> Update debian-10 Docker images including a fix for CVE-2020-1967

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoForm.test.tsx.snap
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/Secret.test.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/utils.ts
- pkg/agent/docker_secrets_postrenderer.go
- pkg/agent/docker_secrets_postrenderer_test.go
Fork of #1679 to include just the registry credentials selection (without the form to add new ones).
- ref #1522
> Select docker registry creds

- chart/kubeapps/values.yaml
- dashboard/public/config.json
- integration/use-cases/create-registry.js
Just in preparation for the next release.
> Repos per namespace, in preparation for next release

- cmd/apprepository-controller/controller.go
> rm useless err check

- go.sum
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Allow to update app repositories. Code is mostly the same than for creating an app repository. We also update auth secrets if they change.
- ref #1666
> Add API endpoint to update app repositories

- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoForm.test.tsx.snap
- docs/user/private-app-repository.md
Wondering if the UI should clearly state as much (and not allow imagePullSecrets to be configured)?
> Update docs to clearly state that the imagePullSecret feature is Helm3 only

- integration/use-cases/operator-deployment.js
- script/e2e-test.sh
- script/manifests/olm.yaml
Add end-to-end test for Operators. It requires to install OLM and an Operator (for the moment) in advance.
- ref #1708
> Add end-to-end test for Operators

- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
I believe that the message that explains global namespaces is not clear. People may think that selecting "All Namespaces" in the namespace selector would create a cluster resource rather than storing it in the Kubeapps namespace:
https://kubernetes.slack.com/archives/C9D3TSUG4/p1588170819044300
Suggestions?
> Elaborate message for global app repositories

- script/manifests/olm.yaml
The previous image is no longer available. Use the `latest` image until they release a new version.
https://github.com/kubeapps/kubeapps/pull/1718#issuecomment-625123423
> Use latest image for OLM

- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
Some people may try to look for a button to view all namespaces, this PR is to try to clarify that we are talking about the namespace selector in the header. cc/ @juan131
> Rephrase message for All Namespaces

- chart/kubeapps/values.yaml
- script/deploy-dev.mk
Follows on from #1718 . Fixes #1713
> Actually switch defaults for values.yaml to postgres.

- integration/use-cases/lib/utils.js
- integration/use-cases/operator-deployment.js
Avoid flaky test like: https://circleci.com/gh/kubeapps/kubeapps/22526?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- Some connection (like a logo) may be idle and cause a timeout so I removed the "networkidle" condition
- Even with that, it's possible for the reload to timeout due to a temporary issue, catch the error in that case.
- Increase the timeout in the `operator-deployment` test so we reduce the amount of reloads.
> Reload integration

- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
> Support newer YAML versions in manifests

- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Avoid using an incomplete apprepo to generate the associated secret.
Fixes #1658
Based on #1739
> Refactor creation of apprepo and secret

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Avoid just forwarding the response when running the App Repository validation.
Details at #1692
- fixes #1699
> Avoid HTTP error codes when running validation

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.test.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/containers/RollbackButtonContainer/RollbackButtonContainer.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
After doing the rollback, it's re-requesting the App but the parameters were switched and a 404 error is being showed now after running a rollback.
> Fix rollback bug

- docs/user/using-an-OIDC-provider.md
Just some missing info that I found while setting up an OIDC instance.
> Identify the callback url needed for configuring oidc IdP clients.

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
Update Nginx image to the latest version
- fixes #
> Bump Nginx Version

- dashboard/src/components/ChartView/ChartDeployButton.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/shared/url.ts
> Fix broken URL when selecting a version

- pkg/chart/chart.go
- pkg/http-handler/http-handler.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
> Don't ignore errors when creating clientset with AsUser helper.

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/SliderParam.test.tsx.snap
- docs/developer/basic-form-support.md
Fixes #1780
Closes #1788
- Feature Implemented
- Tests updated
- Docs updated
> Fixes #1780 (reviewed)

- chart/kubeapps/values.schema.json
After #1720, adapt our chart to the new syntax for hidden elements. (Note that this won't work until we release a new version).
> Fix hidden values in chart JSON schema

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/SliderParam.test.tsx.snap
- dashboard/src/components/Slider/Slider.tsx
- dashboard/src/shared/types.ts
- docs/developer/basic-form-support.md
- Feature #1743 implemented
- Tests updated
- Docs updated
Fixes #1743
> Feature request: Add step to slider params #1743

- docs/architecture/design-proposals/clarity-ui.md
Design doc for updating Kubeapps to use clarity.design.
Ref: #1354
> Design doc for Clarity UI

- dashboard/src/actions/apps.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- integration/use-cases/create-private-registry.js
- script/cluster-kind.mk
- script/e2e-test.sh
> 1815 ci update

- dashboard/src/components/AppView/AppControls/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls/AppControls.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/shared/url.ts
Follows on from #1826. Ref #1762.
> Update urls.app.apps.list to require cluster.

- dashboard/src/components/Header/Header.v2.test.tsx
- dashboard/src/components/Header/Header.v2.tsx
> Fix Header v2 compilation

- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/LoginForm/LoginForm.v2.scss
- dashboard/src/components/LoginForm/LoginForm.v2.test.tsx
- dashboard/src/components/LoginForm/LoginForm.v2.tsx
- dashboard/src/components/LoginForm/OauthLogin.tsx
- dashboard/src/components/LoginForm/TokenLogin.tsx
- dashboard/src/components/LoginForm/__snapshots__/LoginForm.v2.test.tsx.snap
- dashboard/src/components/LoginForm/index.ts
- dashboard/src/components/LoginForm/index.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts
Login page:
In the case OIDC is enabled:
- ref #1354 
The test and the component logic has been just adapted from the existing LoginForm component.
> Clarity Login form

- dashboard/src/components/Clarity/converter/reactWrapper.ts
- dashboard/src/components/LoadingWrapper/LoadingWrapper.v2.test.tsx
- dashboard/src/components/LoadingWrapper/LoadingWrapper.v2.tsx
- dashboard/src/components/LoadingWrapper/__snapshots__/LoadingWrapper.v2.test.tsx.snap
Update for the LoadingWrapper to use the Spinner based on Clarity UI.
- ref #1354
> LoadingWrapper Clarity Component

- dashboard/package.json
- dashboard/src/components/AppList/AppList.v2.scss
- dashboard/src/components/AppList/AppList.v2.test.tsx
- dashboard/src/components/AppList/AppList.v2.tsx
- dashboard/src/components/AppList/AppListGrid.tsx
- dashboard/src/components/AppList/AppListItem.v2.scss
- dashboard/src/components/AppList/AppListItem.v2.test.tsx
- dashboard/src/components/AppList/AppListItem.v2.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.test.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.v2.test.tsx.snap
- dashboard/src/components/AppList/index.tsx
- dashboard/src/containers/AppListContainer/AppListContainer.tsx
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/specs/aLoadingComponent.tsx
- dashboard/src/shared/url.ts
- dashboard/yarn.lock
Rest of components of the AppList view: 
- AppList
- AppListGrid
- AppListItem
- CustomResourceListItem
(The header button in the top-right corner is a bit misplaced, will fix in a different PR).
- ref #1354
> AppList v2

- .circleci/config.yml
Since the latest release doesn't include some of the changes already in master, some of the tests are not compatible. Disabling the tests for the moment. This fixes master.
> Disable scenario for testing the latest release

- chart/kubeapps/requirements.yaml
Fix master builds. See more details inline.
> Pin postgresql dep version

- dashboard/src/components/AppView/AccessURLTable/AccessURLItem/AccessURLServiceHelper.ts
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.v2.test.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.v2.tsx
- dashboard/src/components/AppView/AccessURLTable/__snapshots__/AccessURLTable.v2.test.tsx.snap
- dashboard/src/components/AppView/AccessURLTable/index.tsx
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/components/js/Table/Table.js
- dashboard/src/components/js/Table/Table.scss
- dashboard/src/components/js/Table/Table.test.js
- dashboard/src/components/js/Table/Table.types.js
- dashboard/src/components/js/Table/components/TableRow/TableRow.js
- dashboard/src/components/js/Table/components/TableRow/TableRow.test.js
- dashboard/src/components/js/Table/components/TableRow/index.js
- dashboard/src/components/js/Table/index.js
- dashboard/src/components/js/Tooltip/Tooltip.js
- dashboard/src/components/js/Tooltip/Tooltip.scss
- dashboard/src/components/js/Tooltip/Tooltip.test.js
- dashboard/src/components/js/Tooltip/index.js
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.tsx
Adaptation of the AccessURLTable:
- ref #1354
> AccessURLTable v2

- dashboard/src/components/AppView/ResourceTabs/ResourceTabs.test.tsx
- dashboard/src/components/AppView/ResourceTabs/ResourceTabs.tsx
- dashboard/src/components/AppView/ResourceTabs/index.tsx
- dashboard/src/components/Tabs/Tabs.scss
- dashboard/src/components/Tabs/Tabs.test.tsx
- dashboard/src/components/Tabs/Tabs.tsx
- dashboard/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- dashboard/src/components/Tabs/index.ts
Following up on #1872, use tabs to show the different resource types:
This PR also includes a generic "Tabs" type.
- ref #1354
> Resource Tabs

- dashboard/src/components/AppView/ResourceTable/ResourceData/DaemonSet.ts
- dashboard/src/components/AppView/ResourceTable/ResourceData/Deployment.ts
- dashboard/src/components/AppView/ResourceTable/ResourceData/OtherResource.ts
- dashboard/src/components/AppView/ResourceTable/ResourceData/Secret.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceData/Service.ts
- dashboard/src/components/AppView/ResourceTable/ResourceData/StatefulSet.ts
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretItemDatum.v2.scss
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretItemDatum.v2.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretItemDatum.v2.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/__snapshots__/SecretItemDatum.v2.test.tsx.snap
- dashboard/src/components/AppView/ResourceTable/ResourceTable.v2.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.v2.tsx
- dashboard/src/components/AppView/ResourceTabs/ResourceTabs.test.tsx
- dashboard/src/components/AppView/ResourceTabs/ResourceTabs.tsx
- dashboard/src/components/AppView/ResourceTabs/index.tsx
- dashboard/src/components/Tabs/Tabs.scss
- dashboard/src/components/Tabs/Tabs.test.tsx
- dashboard/src/components/Tabs/Tabs.tsx
- dashboard/src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
- dashboard/src/components/Tabs/index.ts
- dashboard/src/containers/ResourceTableContainer/ResourceTableContainer.ts
- dashboard/src/containers/ResourceTableContainer/index.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/ResourceKinds.ts
ResourceTable component for all the resources associated to an application:
This includes a big refactor of how this component works (due to the change of using the pre-built table and react hooks). I am not confident enough I will finish the UI changes this iteration so I am leaving the unit tests for later so we can have something to demo at the en of next week.
- ref #1354
> Resource Table v2

- dashboard/src/components/AppList/AppList.v2.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.v2.test.tsx.snap
- dashboard/src/components/AppView/AppView.v2.scss
- dashboard/src/components/AppView/AppView.v2.test.tsx
- dashboard/src/components/AppView/AppView.v2.tsx
- dashboard/src/components/AppView/index.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.v2.test.tsx.snap
- dashboard/src/components/Header/Header.v2.scss
- dashboard/src/components/Layout/Layout.v2.scss
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/shared/specs/mountWrapper.tsx
Application view gluing together all the previous components already reviewed:
There are some changes in generic CSS files, that's why other views like the Catalog or the AppList views are modified here a bit.
- ref #1354 
Note that the control buttons don't work yet. Will do that in future PRs.
> AppView v2

- dashboard/src/components/AppList/AppList.v2.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.v2.test.tsx.snap
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.v2.test.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.v2.tsx
- dashboard/src/components/AppView/AccessURLTable/__snapshots__/AccessURLTable.v2.test.tsx.snap
- dashboard/src/components/AppView/AccessURLTable/index.tsx
- dashboard/src/components/AppView/AppSecrets/AppSecrets.scss
- dashboard/src/components/AppView/AppSecrets/AppSecrets.test.tsx
- dashboard/src/components/AppView/AppSecrets/AppSecrets.tsx
- dashboard/src/components/AppView/AppSecrets/index.ts
- dashboard/src/components/AppView/AppView.v2.scss
- dashboard/src/components/AppView/AppView.v2.test.tsx
- dashboard/src/components/AppView/AppView.v2.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretItemDatum.v2.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/__snapshots__/SecretItemDatum.v2.test.tsx.snap
- dashboard/src/components/AppView/ResourceTable/ResourceTable.v2.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.v2.tsx
- dashboard/src/components/AppView/ResourceTabs/ResourceTabs.tsx
- dashboard/src/components/AppView/index.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.v2.scss
- dashboard/src/components/ApplicationStatus/ApplicationStatus.v2.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.v2.test.tsx.snap
- dashboard/src/components/Header/Header.v2.scss
- dashboard/src/components/Layout/Layout.v2.scss
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/shared/specs/mountWrapper.tsx
- dashboard/src/shared/utils.ts
The goal of this PR is to include a new component that shows the secrets of the application in a more prominent place, along with some style changes and internal to finish the "first" row of the application view. The goal of this first row is to try to show everything needed to access the repo: readiness, access URL and credentials:
- ref #1354
> AppSecrets section and first row completion

- CONTRIBUTING.md
So we can request/require contributions to be signed-off, knowing what they are signing-off on.
> Add DCO text to CONTRIBUTING.md

- dashboard/package.json
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.v2.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/LoginForm/LoginForm.v2.tsx
I noticed some eslint warnings when running the app locally. We were not taking into account eslint warnings in the build process, some fixes are useful.
> Adding eslint

- dashboard/src/components/ConfirmDialog/ConfirmDialog.v2.scss
- dashboard/src/components/ConfirmDialog/ConfirmDialog.v2.test.tsx
- dashboard/src/components/ConfirmDialog/ConfirmDialog.v2.tsx
- dashboard/src/components/ConfirmDialog/__snapshots__/ConfirmDialog.v2.test.tsx.snap
- dashboard/src/components/DeploymentForm/DeploymentForm.v2.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.v2.tsx
- dashboard/src/components/js/Modal/Modal.js
- dashboard/src/components/js/Modal/Modal.test.js
Confirm Dialog style that was missing in #1898 
- ref #1354
> Confirm dialog

- dashboard/src/components/AppUpgrade/AppUpgrade.v2.test.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.v2.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.v2.test.tsx.snap
- dashboard/src/components/AppUpgrade/index.tsx
- dashboard/src/components/AppView/AppView.v2.test.tsx
- dashboard/src/components/AppView/AppView.v2.tsx
- dashboard/src/components/ChartView/ChartHeader.v2.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.v2.tsx
- dashboard/src/components/SelectRepoForm/SelectRepoForm.scss
- dashboard/src/components/SelectRepoForm/SelectRepoForm.test.tsx
- dashboard/src/components/SelectRepoForm/SelectRepoForm.v2.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.tsx
- dashboard/src/components/UpgradeForm/__snapshots__/UpgradeForm.v2.test.tsx.snap
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.test.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
New upgrade flow:
Select repo form:
I am not that happy with the version selector field. It's quite hidden and in this flow is critical, will revisit later to make it more prominent.
- ref #1354 
This PR includes some unrelated fixes (adding the `cluster` param in some places that it was missing).
> App Upgrade v2

- dashboard/src/components/AppList/AppListItem.v2.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.tsx
- dashboard/src/components/InfoCard/InfoCard.v2.scss
Remove the icon from the applist cards so all of them have the same height. Also changed a bit the format of operator instances to match helm charts.
- ref #1907
> Minor review for AppList

- dashboard/src/components/AppView/AppControls/DeleteButton/DeleteButton.v2.test.tsx
- dashboard/src/components/AppView/AppControls/DeleteButton/DeleteButton.v2.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.v2.test.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.v2.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.v2.scss
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.v2.test.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.v2.tsx
- dashboard/src/components/AppView/AppView.v2.test.tsx
- dashboard/src/components/AppView/AppView.v2.tsx
- dashboard/src/components/ConfirmDialog/ConfirmDialog.v2.scss
- dashboard/src/components/ConfirmDialog/ConfirmDialog.v2.tsx
- dashboard/src/components/ConfirmDialog/__snapshots__/ConfirmDialog.v2.test.tsx.snap
Delete modal:
Rollback modal:
- ref #1354
> Rollback and delete buttons for AppView v2

- docs/developer/release-process.md
Include instructions for updating the related images when releasing Kubeapps.
Get latest images tested and released each time.
> Update the release process to include image updates.

- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/AppListGrid.tsx
- dashboard/src/components/AppList/CustomResourceListItem.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.test.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/Catalog/CatalogItem.test.tsx
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/CatalogItem.v2.tsx
- dashboard/src/components/Catalog/CatalogItems.test.tsx
- dashboard/src/components/Catalog/CatalogItems.tsx
- dashboard/src/components/Catalog/OperatorCatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.test.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.tsx
- dashboard/src/containers/OperatorInstanceCreateContainer/OperatorInstanceCreateContainer.tsx
- dashboard/src/containers/OperatorInstanceUpdateContainer/OperatorInstanceUpdateContainer.tsx
- dashboard/src/containers/OperatorInstanceViewContainer/OperatorInstanceViewContainer.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/shared/url.ts
Updates operator instance routes and adds relevant info when cluster switched from default.
- fixes #1894 
Follows #1931
> Update operator instance routes

- chart/kubeapps/requirements.lock
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
- docs/developer/release-process.md
Updates images and charts as per the [release process](https://github.com/kubeapps/kubeapps/blob/master/docs/developer/release-process.md) and updates the process doc to include frontend packages.
> Update images used for release.

- cmd/asset-syncer/utils.go
- cmd/assetsvc/postgresql_utils.go
- dashboard/src/components/Catalog/Catalog.v2.test.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/shared/types.ts
- pkg/chart/models/chart.go
Extend the `Chart` model in the backend to include the category of the chart and apply required changes in the dashboard to use those:
Note that chart and operator categories are used.
- fixes #1960
> Categories filter

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoControl.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoControl.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoDisabledControl.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.scss
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.tsx
- dashboard/src/shared/AppRepository.ts
Finish the AppRepoList view adding both global and namespaced repositories:
- ref #1354
> Split between global and namespaced repositories

- .circleci/config.yml
GKE 1.14 is no longer available. Fixes master.
> Add build for GKE 1.16

- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.test.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.tsx
- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/OperatorsNotSupported.tsx
- dashboard/src/components/OperatorNew/OperatorNew.test.tsx
- dashboard/src/components/OperatorNew/OperatorNew.tsx
- dashboard/src/components/OperatorView/OperatorView.test.tsx
- dashboard/src/components/OperatorView/OperatorView.tsx
- dashboard/src/containers/OperatorInstanceCreateContainer/OperatorInstanceCreateContainer.tsx
- dashboard/src/containers/OperatorInstanceUpdateContainer/OperatorInstanceUpdateContainer.tsx
- dashboard/src/containers/OperatorInstanceViewContainer/OperatorInstanceViewContainer.tsx
- dashboard/src/containers/OperatorNewContainer/OperatorNewContainer.tsx
- dashboard/src/containers/OperatorViewContainer/OperatorViewContainer.tsx
- dashboard/src/containers/OperatorsListContainer/OperatorsListContainer.tsx
Follows #1971 , this time all the operator components.
Ref: #1942
> Update operator components to use config.kubeappsCluster

- dashboard/public/config.json
- dashboard/src/components/OperatorList/OperatorList.v2.test.tsx
- dashboard/src/components/OperatorList/OperatorList.v2.tsx
- dashboard/src/components/OperatorNew/OperatorNew.tsx
- dashboard/src/components/OperatorNew/OperatorNew.v2.scss
- dashboard/src/components/OperatorNew/OperatorNew.v2.test.tsx
- dashboard/src/components/OperatorNew/OperatorNew.v2.tsx
- dashboard/src/components/OperatorNew/index.tsx
- dashboard/src/containers/OperatorNewContainer/OperatorNewContainer.tsx
> New Operator form v2

- pkg/kube/http_utils.go
- pkg/kube/http_utils_test.go
Just a follow-up commit that didn't make it into #1966 before it was merged.
> Default to the container env proxy vars if none set from apprepo.

- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.v2.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.v2.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.v2.test.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.v2.tsx
- dashboard/src/components/OperatorNew/OperatorNew.v2.test.tsx
- dashboard/src/components/OperatorNew/OperatorNew.v2.tsx
- dashboard/src/components/OperatorView/OperatorView.v2.test.tsx
- dashboard/src/components/OperatorView/OperatorView.v2.tsx
I didn't land #1974 immediately due to another issue and in the following day other call-sites for the changed URLs landed so that master was broken when I landed #1974
> Fix operator code landed between #1974 proposed and landed.

- chart/kubeapps/templates/kubeapps-frontend-service.yaml
Fixes frontend service port when using external proxy
- fixes #1996
> fix frontend service port when using external proxy

- dashboard/src/components/AppUpgrade/AppUpgrade.v2.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.v2.tsx
- dashboard/src/components/AppView/AppView.v2.test.tsx
- dashboard/src/components/AppView/AppView.v2.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.tsx
- dashboard/src/components/ConfirmDialog/ConfirmDialog.v2.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.v2.tsx
- dashboard/src/components/ErrorBoundary/ErrorBoundary.v2.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.v2.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.v2.tsx
- dashboard/src/components/OperatorList/OperatorList.v2.tsx
- dashboard/src/components/OperatorNew/OperatorNew.v2.tsx
- dashboard/src/components/OperatorView/OperatorView.v2.tsx
- dashboard/src/components/SelectRepoForm/SelectRepoForm.v2.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.tsx
Follow up of https://github.com/kubeapps/kubeapps/pull/1915#discussion_r473585646
`s/Found an error/An error occurred while/`
- ref #1907
> Rephrase Alert messages

- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.tsx
- dashboard/src/components/Layout/Layout.v2.scss
Small follow up of #2013. Since it's now possible to generate URL with filters, use it to link repositories in the AppRepositoryList:
- ref #1907
> Add links in the AppRepositories list

- dashboard/src/components/Header/ContextSelector.scss
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.v2.tsx
- dashboard/src/shared/specs/mountWrapper.tsx
Allow people to create and use new namespaces:
- ref #1907 
I refactored the `ContextSelector` component to avoid using props so we can eventually delete the container.
> Add form to create a new namespace

- dashboard/src/components/Layout/Layout.v2.scss
Before:
After:
Before:
After:
- ref #1907
> Fix some README style issues

- dashboard/src/components/OperatorList/OLMNotFound.v2.tsx
Remove the specific version we point in the OLMNotFound component to avoid having to maintain that version up to date or tell inaccurate instructions.
- ref #1907
> Remove version from OLM installation instructions

- dashboard/src/components/AppView/AppView.v2.tsx
- dashboard/src/components/AppView/ChartInfo/ChartInfo.v2.test.tsx
- dashboard/src/components/AppView/ChartInfo/ChartInfo.v2.tsx
- dashboard/src/components/AppView/ChartInfo/ChartUpdateInfo.tsx
The version and update info are currently separated so it's a bit confusing. Also, it's more difficult to notice if there are updates available. This is the current status:
In this PR I have moved all the version info to the same section and use an alert instead:
In the case there are no updates, is more subtle:
- ref #1907
> Refactor update info

- dashboard/src/components/DeploymentFormBody/Differential.scss
- dashboard/src/components/DeploymentFormBody/Differential.tsx
- dashboard/src/components/DeploymentFormBody/Tabs.scss
The style for the "Differential" tab was misplaced (in the `Tabs` component) so when I created the new components, that style was lost. This style is necessary for the Differential view to be properly rendered.
- ref #1907
> Apply Diff tab style

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.v2.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.v2.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.v2.test.tsx.snap
Calling `handleBasicFormParamChange` is expensive. This PR makes sure that it's only called when the user stop typing so the form is fluent.
- ref #1907
> Fix slow typing in basic form

- dashboard/src/components/ChartView/ChartHeader.v2.test.tsx
- dashboard/src/components/ChartView/ChartHeader.v2.tsx
- dashboard/src/components/ChartView/ChartVersionSelector.tsx
- dashboard/src/components/ChartView/ChartView.v2.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.v2.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.scss
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.tsx
The version selector is a bit difficult to notice, since this is important in the upgrade flow, I have also added a version selector in the main body of the form (as there were before):
- ref #1907
> Add a version selector in the upgrade form

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.v2.tsx
- dashboard/src/components/DeploymentFormBody/DifferentialTab.test.tsx
- dashboard/src/components/DeploymentFormBody/DifferentialTab.tsx
- dashboard/src/components/Layout/UISelector/Clarity.scss
- dashboard/src/components/Layout/UISelector/Clarity.tsx
- dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.v2.tsx
Highlight when there are new changes to review:
- ref #1907
> Add an icon when there are changes to review

- .circleci/config.yml
- chart/kubeapps/README.md
- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
- chart/kubeapps/templates/assetsvc-deployment.yaml
- chart/kubeapps/templates/db-secret-bootstrap.yaml
- chart/kubeapps/templates/db-secret-jobs-cleanup.yaml
- chart/kubeapps/values.yaml
Removes MongoDB as an option for the backend in the chart.
Subsequent PR will remove from the scripts and code.
Ref: #2039
> Remove MongoDB option from chart.

- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- script/e2e-test.sh
Since we are going to release a major version for the Kubeapps chart, keep PosgreSQL reference up to date.
- ref #2028
> Update PostgreSQL chart dependency

- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
- dashboard/src/components/SelectRepoForm/SelectRepoForm.test.tsx
- dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
- dashboard/src/reducers/apps.ts
- dashboard/src/reducers/auth.ts
- dashboard/src/reducers/charts.ts
- dashboard/src/reducers/config.ts
- dashboard/src/reducers/kube.ts
- dashboard/src/reducers/repos.ts
- dashboard/src/shared/specs/mountWrapper.tsx
Depends on #2050
Display global and namespaced repositories to select a repository source:
I have also refactored the component a bit to depend less from the container. 
- fixes #1987
- ref #2028
> Aggregate namespace repositories in SelectRepoForm

- docs/user/deploying-to-multiple-clusters.md
Updates the multi-cluster documentation to match the changes included as part of the solution to #1942 and #1943 .
While there, I've included some other debugging and common problems when configuring OIDC for k8s clusters based on early feedback.
View the updated doc at https://github.com/absoludity/kubeapps/blob/1942-docs-update/docs/user/deploying-to-multiple-clusters.md
> Update multi-cluster instructions with definitive list of clusters.

- chart/kubeapps/values.yaml
- dashboard/Dockerfile
- script/deploy-dev.mk
Updates images used within Kubeapps to latest security patches.
> Update images to latest to test before release.

- dashboard/src/components/AppView/AppSecrets/AppSecrets.scss
- dashboard/src/components/AppView/AppSecrets/AppSecrets.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretItemDatum.scss
- dashboard/src/components/ChartView/ChartHeader.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.tsx
- dashboard/src/components/Icon/Icon.test.tsx
- dashboard/src/components/Icon/Icon.tsx
- dashboard/src/components/InfoCard/InfoCard.test.tsx
- dashboard/src/components/InfoCard/InfoCard.tsx
- dashboard/src/components/InfoCard/__snapshots__/InfoCard.test.tsx.snap
- dashboard/src/components/OperatorSummary/OperatorSummary.tsx
- dashboard/src/components/OperatorView/OperatorHeader.test.tsx
- dashboard/src/components/PageHeader/PageHeader.tsx
While working on the documentation, I noticed a few bugs, fixing them here:
- The "App Secrets" section (in the AppView) was too big for some apps (Harbor) so I handled the overflow
- The values, in the basic form, for text fields were not being populated with the default data <-- This one is quite important.
- Some icons were not working (because it returned a 404 for example), showing the ugly broken image icon. I've created a component to handle that case.
- The OperatorSummary component was missing its CSS file.
- ref #2028
> Several bug fixes

- chart/kubeapps/README.md
> Remove docs related to tiller-proxy in chart readme.

- docs/user/deploying-to-multiple-clusters.md
> Remove no-longer applicable limitation and add link to TKG example config.

- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
> Force re-request of the chart version when upgrading

- .github/stale.yml
We usually want to keep track of feature requests, even if we don't have the resources to work on them at the moment.
> Avoid setting feature requests as stale

- docs/user/operators.md
The term "Operator instance" may be confusing because it may relate to operator itself or the managed resources that comes from it.
> Reword docs related to Operator instances

- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoControl.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoControl.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/shared/url.ts
- pkg/http-handler/http-handler.go
Fix the case in which "All Namespaces" is selected and the user list AppRepositories.
> List apprepos in all namespaces

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
Rather than just listing global ClusterServiceVersions, request those for all namespaces.
- fixes #2124
> List operator resources in all namespaces

- docs/architecture/design-proposals/OCI-registries.md
Design document detailing the desired approach for enabling OCI registries for Helm charts in Kubeapps. The document link should be available for everyone.
- ref #1358
> Design document for adding OCI registries

- docs/user/offline-installation.md
Minor improvements on the offline installation docs after having worked on a related issue.
The offline installation guide should be understood a little bit better (at least I hope so :P)
N/A
N/A
N/A
> Minor improvements in offline installation docs

- chart/kubeapps/crds/apprepository-crd.yaml
- chart/kubeapps/templates/apprepository-crd.yaml
- cmd/apprepository-controller/artifacts/examples/crd.yaml
Reverts kubeapps/kubeapps#2164
I will open an issue for following up on this change.
> Revert "Bump CRD from v1beta1 to v1 (k8s  1.16+)"

- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/components/Header/ClusterSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/Menu.test.tsx
- dashboard/src/components/Layout/Layout.scss
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
- dashboard/src/shared/Kube.test.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/specs/mountWrapper.tsx
- dashboard/src/shared/url.ts
Use the new endpoint (#2171) to check if the user has permissions to create a namespace and disable the button if not:
- ref #2018
> Check if the user has permissions to create namespaces

- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/Catalog/ChartCatalogItem.tsx
- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/ChartView/ChartDeployButton.tsx
- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.test.tsx
- dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/ChartViewContainer/ChartViewContainer.tsx
- dashboard/src/reducers/charts.test.ts
- dashboard/src/reducers/charts.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
- integration/use-cases/create-private-registry.js
After #2187, adapt all the components to be able to change the context from it. As explained there, most of the components didn't require any change because after a change in the namespace, the related resources get reloaded but there are some exceptions. I will explain those inline.
In the future we may introduce changes that break this behavior again.
- ref #2018
> Adapt components to change the namespace in the context

- .circleci/config.yml
- integration/.gitignore
- integration/manifests/executor.yaml
- integration/use-cases/create-private-registry.js
- integration/use-cases/create-registry.js
- integration/use-cases/lib/utils.js
- integration/use-cases/operator-deployment.js
- integration/use-cases/upgrade.js
- script/e2e-test.sh
The goal of this PR is to avoid, as much as possible, transient errors caused by flaky tests. The biggest issue is that these are not reproducible locally and only happens sometimes in the CI.
Most of this PR is adding retries/bigger timeouts (I didn't have the time to debug each of the issues).
The most troublesome test is the operator one. The OLM, apparently arbitrary misbehaves, so almost each of the actions is susceptible to fail. It will still fail from time to time after this PR (1/10 builds fails when running my tests).
In any case, the reliability should be increased with this PR since prior to this ~6/10 builds failed.
- fixes #2176 
Feel free to merge this PR if you want while I'm OOO.
I'll add some more comments inline.
FTR: I took notes of the errors I keep finding (as you …
> Increase reliability of e2e tests

- docs/architecture/design-proposals/OCI-registries.md
- docs/architecture/design-proposals/clarity-ui.md
- docs/architecture/design-proposals/multi-cluster-support.md
- docs/architecture/design-proposals/sso-without-oidc-api-server.md
- docs/developer/pinniped-proxy.md
After an internal migration, some of the docs were copied so the links here don't work anymore. Link to the new docs.
- fixes #2215
> Update doc links

- chart/kubeapps/Chart.lock
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
- dashboard/yarn.lock
- Update chart dependencies and images.
- ~~Update frontend deps.~~ (we need to do these more carefully as results in ts errors).
Follows the README instructions for manually updating the chart dependencies, default images used and frontend deps.
> Update chart deps and images.

- dashboard/yarn.lock
- go.mod
- go.sum
- pkg/kube/http_utils_test.go
Closes #2228
Updated NPM deps (yarn upgrade) and go deps (go get -u).
I had to fix a Go test, apart from that, smooth upgrade.
> Update yarn and go deps

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
Very minor fix of an unhandled rejection.
If this error is thrown, the app will show a friendly message.
N/A
N/A
- Change initially introduced in #2221 but removed from there to keep it as simple as possible.
> Fix unhandled rejection

- cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go
As explained in the design document, the option chosen to implement OCI registries requires a small modification of the AppRepository CRD to include the list of repositories.
- ref #2232
> Update CRD spec to include list of repositories

- cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go
Follow up of https://github.com/kubeapps/kubeapps/pull/2257#discussion_r560575419
> Rename repositories property in AppRepository CRD

- cmd/asset-syncer/postgresql_db_test.go
Fix a bunch of warnings vscode was reporting to me.
> Fix linter warnings

- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- cmd/asset-syncer/main.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
Follow up of #2260 Still no functional changes:
- Pass down the list of OCI repositories from the apprepository-controller to the asset-syncer
- Skeleton of the OCI repo interface in the asset-syncer
- ref #2232
> Add list of oci repositories as an argument

- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
I am creating this PR first for a couple of capabilities I need before I can pull and extract files from an OCI registry:
- First we need the list of tags to pull per app, I am storing that in the OCI registry info since we have that info already (obtained to get the registry checksum).
- When the chart is pulled, the content of the tarball is in a `bytes.Buffer`. Here I am adding the method that extract the files that we are interested in (metadata, readme, values and schema) from that buffer.
Will send the PR that actually pulls charts tomorrow.
- ref #2232
> Misc: Store OCI tag list and method to extract from tar buffer

- docs/user/getting-started.md
See #2292
See #2292
None.
- fixes #2292
> Create the service account in an explicit namespace

- cmd/asset-syncer/helm.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
Following up on #2295. This time adding authentication. It's just needed to set the authorization header in the "resolver".
- ref #2232
> Add authentication information when pulling OCI charts

- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
- pkg/helm/helm.go
Move helm code to its package, I will need it for `kubeops`. In particular, the piece that pulls a chart.
- ref #2232
> Move helm code to its package

- cmd/pinniped-proxy/Dockerfile
Just splitting out the Dockerfile changes from #2286 so that we can land them and see what Snyk says about the bitnami/minideb :)
> Split Dockerfile changes out from #2286

- .circleci/config.yml
- docs/user/getting-started.md
The PostgreSQL dependency now requires Helm >= 3.1.0
This fixes the CI.
> Bump Helm version

- dashboard/package.json
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BooleanParam.test.tsx.snap
- dashboard/yarn.lock
> Bumps react-switch from 5.0.1 to 6.0.0.

- cmd/kubeops/internal/handler/handler.go
- pkg/agent/agent_test.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/chart/fake/chart.go
- pkg/handlerutil/handlerutil.go
Follow up of #2310
I noticed that there was a bunch of code related to loading v2 charts but later on, only the v3 chart version was being taken into account so I cleaned it up.
- ref #2232
> Remove code related to charts v2

- dashboard/package.json
- dashboard/src/shared/Config.test.ts
- dashboard/src/shared/Config.ts
- docs/developer/dashboard.md
So this old code was used to select the namespace in which Kubeapps is running when using telepresence. It's not needed since this retrieved anyway from the dummy config file in `dashboard/public/config.json`.
No need to include in production code anything related to the dev environment.
> Remove unnecessary code

- dashboard/package.json
- dashboard/yarn.lock
This reverts commit e1c8c8be14840221e651eb13a66abf5ca5aad497.
more info at #2348
> Revert "Bump @clr/icons and @clr/ui in /dashboard (#2327)"

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
We need to add the registered icon to all the MongoDB references in our products
> Add registered icon to the MongoDB references

- docs/developer/release-process.md
Add a step in the release process for ensuring we check the open Snyk's PR-
The release process will have an additional step ensuring we don't introduce security issues.
N/A
- fixes #2237 
Feel free to add your comments/thoughts on it. This change is just to remember we should look at the Snyk's PR before releasing, but I'm glad to add more info or details if you want.
> Add step regarding security issues

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
Changing the namespace doesn't affect the `all namespaces` selection so the state should not be affected.
- fixes #2289
> Fix 'All Namespaces' button

- cmd/asset-syncer/utils.go
The order in which tags are received is not assured, making some golang test flaky.
Fixes https://app.circleci.com/pipelines/github/kubeapps/kubeapps/2039/workflows/569b60bb-b6a1-4da2-a6e9-51f44c502985/jobs/37138/parallel-runs/0/steps/0-103
> Order tags

- dashboard/public/openapi.yaml
This PR simply adds some updates in the AppRepository model (in the OAS document) after the OCI changes.
OAS document up to date :)
We should automatize this somehow... 
N/A
N/A
> Add new OCI properties to the API spec

- chart/kubeapps/templates/apprepositories.yaml
- chart/kubeapps/values.yaml
Add support for setting OCI registries as initialRepos in the chart.
- ref #2232
> Add support for setting OCI registries as initialRepos in the chart

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/types.ts
- pkg/kube/kube_handler.go
Frontend part of #2408.
Adding a button to skip TLS verification if needed.
- ref #2232
> Add skip TLS verification button

- dashboard/src/components/ApiDocs/ApiDocs.scss
- dashboard/src/components/ApiDocs/index.tsx
Remove these undesired margins and border:
Not many benefits, it just looks a bit better :P 
N/A
N/A
N/A
> Minor swagger-ui css tweaks

- dashboard/src/components/AppList/AppList.scss
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppView/AppControls/DeleteButton/DeleteButton.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.scss
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoRefreshAllButton.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/Menu.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.tsx
- dashboard/src/components/OperatorView/OperatorView.tsx
- dashboard/src/components/PageHeader/PageHeader.scss
- dashboard/src/components/PageHeader/PageHeader.tsx
- integration/use-cases/create-private-registry.js
From https://github.com/kubeapps/kubeapps/issues/2371#issuecomment-790615176
Fixes 1. 2. 4. and 11. from that comment:
Removed background color for the page header:
Fixed color of the icons of buttons (the property `inverse` is not needed):
Removed the `v` from the deployment form button:
AppRepo list buttons are now aligned:
I am getting some lint warnings related to how `React` is imported in some components (I guess due to some update):
So I am fixing them as I see them.
> Some minor fixes for Dark mode

- .circleci/config.yml
- integration/use-cases/create-private-registry.js
- integration/use-cases/create-registry.js
- integration/use-cases/operator-deployment.js
Follow up of #2527
Add more fixes to be able to run e2e tests with both the latest release and master.
This time I am modifying the CircleCI manifest to ensure that the latest release passes the test before merging.
Fixes master.
> More fixes for the compatibility of e2e tests

- chart/kubeapps/templates/kubeops-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/kubeops/Dockerfile
More info at #2288 
The timezone used to store apps info can be changed with an environment variable but it requires some extra files in the image.
cc/ @juan131 can you replicate this change in the Bitnami image?
- fixes #2288
> Allow to change kubeops TZ

- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.scss
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/components/AppView/AppSecrets/AppSecrets.scss
- dashboard/src/components/AppView/AppSecrets/AppSecrets.tsx
- dashboard/src/components/ConfirmDialog/ConfirmDialog.tsx
- dashboard/src/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.scss
- dashboard/src/components/SearchFilter/SearchFilter.scss
- dashboard/src/reducers/config.ts
Rest of the items missing from #2371:
- Fix the secret table height: 
- Fix the tooltip color:
- Fix the slider position:
- Delete modal:
- Search box:
- fixes #2371
> Several minor CSS fixes

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
- chart/kubeapps/templates/assetsvc-deployment.yaml
- chart/kubeapps/templates/db-secret-jobs-cleanup.yaml
Fixes #2409 
Allow to manually set the PostgreSQL password. For example: `--set postgresql.existingSecret=null --set postgresql.postgresqlPassword="foo"`
cc/ @Morriz
> Allow to manually set the PostgreSQL password

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/tests/test-assetsvc.yaml
- chart/kubeapps/templates/tests/test-dashboard.yaml
fixes #2552
adds missing securityContext to the tests
No more complaints when deploying those tests.
> fix: securityContext for tests

- dashboard/src/components/LoginForm/LoginForm.scss
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Config.ts
After the css changes, the login page has a couple of issues (described in #2572 ). This PR aims at solving both.
Login page will look better.
N/A
- fixes #2572
N/A
> Css login fix

- chart/kubeapps/README.md
Upgrade guide for the upcoming major chart version.
Related to #2590 and #2595.
- ref #2240
> Document upgrade process for chart 6.0.0

- .circleci/config.yml
- integration/jest.environment.js
- script/e2e-test.sh
This PR simply performs some minor refactor, extracting the hardcoded variables to CircleCI parameters. Furthermore, it names some of the steps so that the visualization in the CI dashboard is clearer at a glance.
Better CI visualization and DRY improvements.
N/A
- rel #2376
N/A
> Minor DRY changes in CI

- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
Fixed margin of the said button. Before:
After:
> Fix margin for apprepo form button

- script/e2e-test.sh
See https://github.com/kubeapps/kubeapps/pull/2801
> Revert temporary hotfix now that local chart matches 7.0.0

- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
Just addressing a comment on the previous PR at:
https://github.com/kubeapps/kubeapps/pull/3074#discussion_r662823041
Tests now are explicit (you can see exactly what details are used for input) while being DRY.
- fixes #2993
> Add makeChart test helper for explicit yet DRY tests.

- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
See #3076 for more info.
- fixes #3076
> Re-instate the userAgent config when fetching charts.

- .circleci/config.yml
- chart/kubeapps/templates/kubeappsapis/deployment.yaml
- docs/developer/manifests/values.kubeappsapis.yaml
- script/e2e-test.sh
~(PR not for the main branch yet, targeting branch: 3085-useNewAPI).~
This PR adds some changes in order to get the tests to work when testing code that depends on the new API (as #3164)
Tests should be passing again...
... however, these changes have been extracted from #3164 but this PR is not passing yet :(
- related #3165
~I'll keep this PR as a draft until I get my PR working~
> [kubeappsapis] Add kubeappsapis in CI

- chart/kubeapps/README.md
- docs/architecture/overview.md
- docs/step-by-step/kubeapps-on-tkg/introduction.md
- docs/step-by-step/kubeapps-on-tkg/step-1.md
- docs/step-by-step/kubeapps-on-tkg/step-2.md
- docs/step-by-step/kubeapps-on-tkg/step-4.md
While reading the guide I found a couple of errors and typos. This PR is to fix them
A better guide perhaps?
N/A
N/A
N/A
> Add minor fixes and correct typos in TKG guide

- README.md
> Fix typo pointed out on #3275.

- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppView/ChartInfo/ChartInfo.scss
- dashboard/src/components/AppView/ChartInfo/ChartInfo.tsx
- dashboard/src/components/OperatorSummary/OperatorSummary.tsx
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/schema.test.ts
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Please refer to https://github.com/kubeapps/kubeapps/issues/3165#issue-948121014 for further details 
This PR brings minor fixes before going deeper into the UI refactor:
- Fix wrong aria labels in the operators view
- Add a missing try-catch for error handling 
- Remove unused models in `types.ts`
- Remove unused URLs in `urls.ts`
Minor fixes before the actual revamp
N/A (if any, should already been caught at build time)
N/A
N/A
> [3/n] UI improvements - Minor removals and edits

- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- docs/user/manifests/kubeapps-local-dev-dex-values.yaml
- integration/use-cases/01-add-multicluster-deployment.js
- integration/use-cases/02-create-private-registry.js
- integration/use-cases/04-default-deployment.js
- integration/use-cases/07-upgrade.js
- integration/use-cases/08-rollback.js
> Check ci e2e tests with new UI

- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/update_test.go
- cmd/kubeops/internal/handler/handler_test.go
- integration/use-cases/07-upgrade.js
- pkg/chart/fake/chart.go
Adds the implementation for UpdateInstalledPackage for the Helm plugin, then refactors to DRY up similar code in Create/Update methods.
Can switch UI to use update from new API as well.
Haven't done an IRL test yet, but will do so before landing.
- ref: #3146
> Add UpdateInstalledPackage for Helm plugin.

- integration/use-cases/07-upgrade.js
Fixes CI by ensuring that delay 0.5s before checking the dom for a selected option.
CI test passes.
- fixes #
> Ensure DOM is updated before checking for selected version.

- cmd/kubeapps-apis/plugin_test/mock_plugin.go
- cmd/kubeapps-apis/server/packages.go
- cmd/kubeapps-apis/server/packages_test.go
Adds core implementations for Create, Update and Delete installed packages.
Dashboard can use the core client instead of the specific helm one (so we can test other plugins like flux).
- fixes #
> Add core implementations for Create, Update, Delete.

- chart/kubeapps/README.md
Really minor PR just updating the chart readme based on the latest version of our generator. 
Readme will be up do date.
N/A
N/A
N/A
> Run latest version of readme generator

- chart/kubeapps/templates/assetsvc/deployment.yaml
> fix resources for assetsvc

- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Adds implementation of GetAvailablePackageVersions for kapp-controller
Step 1 for displaying available pkg detail.
- Ref #3221
> Add implementation of GetAvailablePackageVersions for kapp-controller.

- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Adds an initial implementation for GetAvailablePackageDetail for the kapp-controller plugin.
Can now click on a tile to see (a somewhat sparse) available package detail:
It's sparse because there's no concept of a readme for the cavel package, so currently it's just the long description and support description.
- Ref #3221
Next is CreateInstalledPackage, which may also require fetching the config values (as part of getting the details) the way the tanzu cli does (need to find out what this does via kubectl cli/api).
> Add implementation for GetAvailablePackageDetail for kapp-controller.

- .circleci/config.yml
Follow-up of #3796, aiming at a second issue seen in the dashboard tests where we run out of memory.
Avoid out of memory issues when running dashboard tests (?)
- fixes #
> Set max old space size to a quarter of mem for 4 workers.

- CONTRIBUTING.md
- README.md
- chart/kubeapps/README.md
- chart/kubeapps/values.yaml
- docs/user/OIDC/OAuth2OIDC-debugging.md
- script/tpl/PR_external_chart_template.md
Since this README is copied to the bitnami/charts repo, links cannot be relative:
```console
$ markdown-link-check -r bitnami/kubeapps/README.md
FILE: kubeapps/README.md
[✓] https://circleci.com/gh/kubeapps/kubeapps/tree/master
[✓] https://circleci.com/gh/kubeapps/kubeapps/tree/master.svg?style=svg
[✓] https://kubeapps.com
[✓] https://github.com/helm/helm
[✓] https://marketplace.cloud.vmware.com
[✓] https://bitnami.com/application-catalog
[✓] https://operatorhub.io/
[✖] ./docs/user/using-an-OIDC-provider.md
[✖] ./docs/user/using-an-OIDC-provider-with-pinniped.md
[✖] ./docs/user/access-control.md
[✓] https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md
[✓] http://kubernetes.io
[✓] https://helm.sh
[✓] https://github.com/bitnami/charts/tree/master/bitnami/postgresql …
```
> Fix dead links in the Helm Chart README.md

- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Initial implementation of the `GetAvailablePackageVersions` operation
An initial and very limited Carvel support in Kubeapps
N/A
- related https://github.com/kubeapps/kubeapps/issues/3221
N/A
> Add 'GetAvailablePackageVersions' impl

- docs/developer/release-process.md
Minor fixes in `release-process.md` document.
Old Helm 2 reference and MD link broken.
Up-to-date release documentation
N/A
None
> Small fixes to release documentation

- docs/user/managing-carvel-packages.md
Just noticed while adding to the draft release notes, we had the resources and helm plugins twice in the carvel docs.
- fixes #
> Fix typo in Carvel docs

- dashboard/package.json
- dashboard/yarn.lock
When using other OS, a recurrent issue is how it handles the environment variables. This PR just adds the `cross-env` dev dependency for handling how the vars used in the scripts are passed to the OS.
Our package.json scripts will work in any OS
N/A
N/A
N/A
> Use `cross-env` for a better env var handling in package.json

- docs/user/operators.md
> Fix typo pointed out in 4269

- docs/user/OIDC/OAuth2OIDC-keycloak.md
added document about keycloak installation/configuration for OIDC support
> added keycloak doc

- .circleci/config.yml
- script/chart_sync.sh
- script/chart_sync_utils.sh
- script/chart_upstream_checker.sh
This PR adds an extra step in the chart sync CI script to also sync the chart's readme based upon the latest changes.
Readme in sync
N/A
- fixes https://github.com/kubeapps/kubeapps/issues/4371
Marking as a draft as I'm launching some debugging circleci instances to double-check it.
> Add readme genenator on each chart sync

- .circleci/config.yml
Just re-enables the upgrade test now that the backwards-incompatible chart change landed.
- fixes #
> Re-enable upgrade test now that 8.0.0 chart landed.

- cmd/apprepository-controller/cmd/root.go
- cmd/apprepository-controller/cmd/root_test.go
- cmd/apprepository-controller/server/server.go
See #4470 for a complete description.
Secrets and custom annotations/labels are set correctly.
- fixes #4470
> Initialise serveOpts after arg parsing and update test to verify.

- docs/user/getting-started.md
Apparently GH follows symlinks in your docs. We've had a number of reports for our old getting started being a 404 (from the old website, for eg.)
This should fix that.
Turns out the symlinks are only supported for a GH main README (afaict, can't find authoritatively, just doesn't work for the getting-started).
Updated now so that people following old links (eg. from kubeapps.com until we can get it updated) don't get a 404 but can follow through to the getting-started.
- fixes #
> Add getting-started.md at old location with link.

- docs/reference/developer/README.md
While writing the README for the carvel package of Kubeapps, the pattern there is to list the components of the package, so I linked to this doc but wanted to update it.
- fixes #
> Update the Kubeapps components to reflect the current reality.

- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
* implemented UpdatePackageRepository() in flux plugin
* added unit and integration tests
> 5th step for  Investigate and propose package repositories API with similar core interface to packages API. #3496 

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Proposal to standardize kubeapps issues by using templates for features and issues.
> Update issue templates for Kubeapps

- docs/reference/testing/end-to-end-tests.md
- integration/Dockerfile
- integration/manifests/executor.yaml
- integration/yarn.lock
This PR just performs a `yarn upgrade` for the integration image, rebuilds it and uses it in our CI.
Integration img up to date.
N/A
- related #4661
I've also updated the e2e docs; mainly fixing broken links after the docs refactor.
> Update integration image

- README.md
Signed-off-by: ndx robot <xiao.zhang@daocloud.io>
Getting started guide address is not available, corrected to correct connection address
- fixes #
> fix Getting started guide address

- MAINTAINERS.md
Update MAINTAINERS.md file to include @dlaloue-vmware.
Information updated.
None
- related to #4734
> Update maintainers to include @dlaloue-vmware

- .gitignore
Super quick PR to Git ignore folders/files generated by VScode and Intellij GoLand.
No additional files shown in git
> Ignore common IDEs files

- ADOPTERS.md
- site/content/docs/latest/tutorials/operators.md
Updated non-inclusive terminology identified in Kubeapps docs.
Improved documentation.
N/A
- related #3953 
Scan performed by using VMware [Inclusive Terminology Service](https://term-scan.esp.eng.vmware.com/its/scans?poll=23235). There are still some positive results in the scanning due official Bitnami chart (as keeps working in _master_ branch)
> Inclusive terms

- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
this change is an incremental update to add support for user-managed auth.
(final support is pending spec review and finalization)
> added first support for user managed auth

- site/config.yaml
- site/themes/template/assets/scss/_footer.scss
- site/themes/template/layouts/_default/baseof.html
- site/themes/template/layouts/partials/base-footer.html
Add OneTrust, GTM, legal links
Compliance, analytics
Added jQuery in order for OneTrust to work properly and adjusted footer styles to accommodate new legal links.
n/a
> Add OneTrust, GTM, legal links

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature-request.md
- .github/ISSUE_TEMPLATE/issue.md
- .github/ISSUE_TEMPLATE/support-request.md
- site/content/docs/latest/reference/developer/issue-triage-process.md
Update documentation and issue templates to update and standardize the issue creation, triage and prioritization processes.
Standard way to manage issues from maintainers. Information clear and updated for contributors.
Need for update the stale process.
> Update triage and prioritization processes

- ADOPTERS.md
Quick change to update the order in the adopters list after Otomi inclusion.
Consistency with our ADOPTERS.md file
None
> Update alphabetical order in the adopters list

- cmd/pinniped-proxy/src/pinniped.rs
I was investigating the simplest way to cache responses for our `TokenCredentialRequest`s that we send to pinniped and it turns out that Rust includes a [Hash trait](https://doc.rust-lang.org/std/hash/trait.Hash.html) which any struct can implement.
This PR just ensures that the `TokenCredentialRequest` object can be hashed correctly (via tests) so that we can use it as a key for the caching.
Enables me to use the `TokenCredentialRequest` as a cache key.
- ref #2875
> Add Hash trait to our TokenCredentialRequest for pinniped-proxy.

- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go
Signed-off-by: Akanksha Kumari [akankshakumari393@gmail.com](mailto:akankshakumari393@gmail.com)
This would fix the error message in `kubeapps-apis` service
This would give us the proper log message
NA
- fixes #4942
NA
> [Minor]Fix log trace message to have correct values for cluster and namespace

- LICENSE
- NOTICE
As per #4757, we are required to update the "legal" files to comply with our Open Source compliance team's guidelines. This PR is to add the generated files for our v2.4.6 release.
OSPO-compliant legal files, finally! 
N/A
- fixes #4757 
Marking as a draft since the actual files are still under review. Also, there are some ongoing questions I want to clarify before merging; but I wanted to send the PR asap so that others can make some comments and we have time to address them.
> Add generated files by the OSPO team

- CONTRIBUTING.md
This PR just fix a wrong link preventing our site to be deployed properly.
Site will get deployed again.
N/A
N/A
N/A
> Fix errata in contributing.md

- pkg/agent/agent_test.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/helm/index.go
- pkg/http-client/httpclient_test.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
- pkg/tarutil/tarutil_test.go
This PR is aimed at fixing those issues in the `pkg` component. Some of them has been fixed and other, just marked as `nolint`.
Once we fix every issue, we will be able to merge the PR and therefore detect any linter issue before merging a PR.
N/A
- related #3087
N/A
> Add gh linter - fix issues in pkg

- site/content/docs/latest/tutorials/using-an-OIDC-provider.md
Update the tutorial not only to comply doc style guidelines, but also making the tutorial easy to follow and more structured.
Better documentation
N/A
- related to #5024
> Update tutorial: Using an OAuth2/OIDC provider in Kubeapps

- chart/kubeapps/README.md
Quick PR that removes a tag breaking Netlify's process.
Netlify works
N/A
- related to #5258
> Removed tag breaking Netlify

- cmd/kubeapps-apis/buf.lock
- cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.gw.go
- cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.gw.go
- cmd/kubeapps-apis/gen/core/plugins/v1alpha1/plugins.pb.gw.go
- cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.gw.go
- cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.gw.go
- cmd/kubeapps-apis/gen/plugins/kapp_controller/packages/v1alpha1/kapp_controller.pb.gw.go
- cmd/kubeapps-apis/gen/plugins/resources/v1alpha1/resources.pb.gw.go
- dashboard/src/gen/google/api/http.ts
- dashboard/src/gen/google/protobuf/any.ts
- dashboard/src/gen/google/protobuf/descriptor.ts
- dashboard/src/gen/google/protobuf/struct.ts
- dashboard/src/gen/google/protobuf/wrappers.ts
- dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/packages.ts
- dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/repositories.ts
- dashboard/src/gen/kubeappsapis/core/plugins/v1alpha1/plugins.ts
- dashboard/src/gen/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.ts
- dashboard/src/gen/kubeappsapis/plugins/helm/packages/v1alpha1/helm.ts
- dashboard/src/gen/kubeappsapis/plugins/kapp_controller/packages/v1alpha1/kapp_controller.ts
- dashboard/src/gen/kubeappsapis/plugins/resources/v1alpha1/resources.ts
- dashboard/src/gen/protoc-gen-openapiv2/options/openapiv2.ts
This PR updates the code generated by `buf ` using the latest build.
Up-to-date generated code.
N/A
- related https://github.com/vmware-tanzu/kubeapps/issues/5293
N/A
> Update buf deps

- .circleci/config.yml
- script/e2e-test.sh
This PR fixes the problem described in #5416. It defines global environment variables for `KAPP_CONTROLLER_VERSION` and `CHART_MUSEUM_VERSION`, so those values are properly passed to the `e2e_tests.sh` script.
It fixes an issue that had been causing a big headache to our team due to a subtle bug in our CircleCI config.
None
- fixes #5416 
N/A
> Fix circleci pipeline

- cmd/apprepository-controller/cmd/root.go
- cmd/asset-syncer/cmd/root.go
- cmd/kubeapps-apis/cmd/root.go
###Changes to be committed:
``` 
modified:   cmd/apprepository-controller/cmd/root.go
modified:   cmd/asset-syncer/cmd/root.go
modified:   cmd/kubeapps-apis/cmd/root.go 
```
1. cmd/apprepository-controller/cmd/root.go
2. cmd/asset-syncer/cmd/root.go
3. cmd/kubeapps-apis/cmd/root.go
This Helped In The Removing Of YAML Config Files For Cobra Binaries
[user]
email = [hirdeymittal@gmail.com](mailto:hirdeymittal@gmail.com)
name = hirdey-1999
signingkey = 3B89C963E92E9EE143862550D210328360EE7B34
[commit]
gpgsign = true
[gpg]
program = gpg
> Removing YAML config files for Cobra commands

- .github/workflows/add-issues-to-project.yaml
- .github/workflows/codeql-reusable.yml
- .github/workflows/kubeapps-general.yaml
- .licenserc.yaml
- dashboard/public/browserconfig.xml
- site/themes/template/static/img/favicons/browserconfig.xml
This PR fixes some wrong license headers that contain the old `VMware, Inc.` copyright owner, no longer in use.
* License headers are consistent in all files through the repository. 
* License headers are correct for all the files in the project.
None
- fixes #5585 
None
> Fix license headers

- .github/actions/srp-source-provenance/action.yml
- .github/workflows/kubeapps-general.yaml
It seems that there is a bug in the current version of the GHA's `report_srp` job we've just merged, and for some reason, the SRP_CLI_VERSION is not being properly passed in the call to the `srp-source-provenance` action.
Fix the bug in the GHA's `report_srp` job, so it works as expected.
None
> Fix srp_report GHA's job

- .github/workflows/kubeapps-general.yaml
Undoing a small change unintentionally made to one file in https://github.com/vmware-tanzu/kubeapps/pull/5656
> fix an unintended change to a file done in my previous PR

- README.md
This commit removes the CircleCI badge from the README file of the repo.
The README file is up-to-date with the current CI configuration.
None.
- closes #4436
> Remove the CircleCI badge

- README.md
Signed-off-by: Pepe Baena <ppbaena@gmail.com>
Fix the link to the CodeQL Analysis action badge
The badge is properly displayed.
N/A
> FIx CodeQL Analysis badge

- .github/workflows/kubeapps-general.yaml
- script/lib/libcitools.sh
We recently rotated the secrets used by the GH actions, as well as the gpg key used by the kubeapps-bot account, but hadn't updated the fingerprint used.
- fixes #
> Update the fingerprint for the CI bot GPG key after updating

- cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json
- cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.go
- cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.go
- cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.go
- cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.go
- dashboard/src/gen/google/api/http.ts
- dashboard/src/gen/google/protobuf/any.ts
- dashboard/src/gen/google/protobuf/descriptor.ts
- dashboard/src/gen/google/protobuf/struct.ts
- dashboard/src/gen/google/protobuf/wrappers.ts
- dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/packages.ts
- dashboard/src/gen/kubeappsapis/core/packages/v1alpha1/repositories.ts
- dashboard/src/gen/kubeappsapis/core/plugins/v1alpha1/plugins.ts
- dashboard/src/gen/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.ts
- dashboard/src/gen/kubeappsapis/plugins/helm/packages/v1alpha1/helm.ts
- dashboard/src/gen/kubeappsapis/plugins/kapp_controller/packages/v1alpha1/kapp_controller.ts
- dashboard/src/gen/kubeappsapis/plugins/resources/v1alpha1/resources.ts
- dashboard/src/gen/protoc-gen-openapiv2/options/openapiv2.ts
- dashboard/src/shared/KubeappsGrpcClient.test.ts
Regenerate after updating to buf 1.12
- fixes #
> Buf generate after update.

- ADOPTERS.md
Signed-off-by: Pepe Baena <ppbaena@gmail.com>
Rename logo file to be displayed
Logo is displayed properly
N/A
> Rename OYO logo

- cmd/pinniped-proxy/Cargo.lock
- dashboard/src/gen/google/protobuf/struct.ts
- go.mod
- go.sum
- site/netlify.toml
Go, rust and website generator, as well as regen for grpc typescript stuff.
- fixes #
> Remaining updates for release

- go.mod
This is required for some internal scripts that audit dependencies.
- fixes #
> Add dynamic-resource-allocation to go.mod replacements.

- MAINTAINERS.md
- site/content/contributors/3-gfichtenholtz.md
- site/content/contributors/4-dlaloue.md
Update information about Maintainers both in the Kubeapps repository and the website.
Info up to date.
N/A
> Update Maintainers team

- cmd/pinniped-proxy/Cargo.lock
- cmd/pinniped-proxy/Cargo.toml
Allows the chrono library to avoid depending on an old time library.
- fixes #
> Remove dependency on old time 0.1 library.

- cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
While checking logs for other things, came across a debug message that got left in the code which was printing the service account token.
Removes sensitive data from logs.
- fixes #
> Remove service account token data from logs.

- cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_auth.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_resources.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go
- cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider.go
- cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider_test.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_filtering.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_test.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets_test.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go
- cmd/kubeapps-apis/server/server.go
Switches the resources plugin (only) to the new connect gRPC.
One down, 4 to go.
-ref #6013
One test, which was dependent on the implementation detail of the previous gRPC server, has been commented out. I want to revisit this before landing, to see whether I can create a similar double for the server, or remove that test.
> Switch resources plugin and update auth.

- cmd/kubeapps-apis/Dockerfile
Verify that latest grpc-health-probe version works.
Avoid scan error mentioned in #2628
- Ref #2628
Still need to ensure the Bitnami image is updated with the same.
> Test latest grpc-health-probe version.

- cmd/asset-syncer/server/utils.go
- cmd/asset-syncer/server/utils_test.go
This PR adds an initial OCI check for `CatalogAvailable` which currently just checks a VMware application catalog specific index. This will later be generalised to support other registries.
May provide a quick win for displaying a catalog for VAC registries. Next need to use this when validating an OCI registry in the UI, then use when syncing the registry.
- ref #6263
> Add OCI check for CatalogAvailable.

- cmd/asset-syncer/server/utils.go
- cmd/asset-syncer/server/utils_test.go
Part 3/3 for experimental support of VAC indexes.
Potentially quick win to display VAC OCI repos.
- ref #6263
Still need to test locally.
> Update the asset-syncer to fetch OCI catalog when present.

- dashboard/package.json
- dashboard/yarn.lock
Accidentally landed an upgrade which was failing CI.
> Reverting a bad dep upgrade.

- integration/package.json
- integration/yarn.lock
Reverts vmware-tanzu/kubeapps#6862
> Revert "Bump @playwright/test from 1.38.0 to 1.38.1 in /integration"

- cmd/asset-syncer/server/postgresql_utils_test.go
- cmd/asset-syncer/server/utils.go
- cmd/asset-syncer/server/utils_test.go
- cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_integration_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go
- cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
- cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils_test.go
- pkg/http-client/httpclient_test.go
- site/content/docs/latest/howto/OIDC/OAuth2OIDC-keycloak.md
Trivial PR just running an automated tool for fixing minor format issues.
No format issues.
N/A
N/A
N/A
> Run auto-formatter tool

- .github/workflows/gke_e2e_tests.yaml
Avoid piping the output of the script to investigate an error in CI.
N/A
N/A
N/A
N/A
> Display output of start-gke-env.sh

- .github/workflows/gke_e2e_tests.yaml
Fix CI script with a missing `"`.
N/A
N/A
N/A
N/A
> Fix wrong quotation mark in CI

- ADOPTERS.md
- site/content/docs/latest/img/adopters/aenix.svg
Hi, we utilize Kubeapps in combination with FluxCD as the dashboard for our free PaaS platform [Cozystack](https://cozystack.io/) to run virtual machines, Databases and Kubernetes-as-a-Service.
We'd like to share this information :)
> Add Ænix to the Adopters list

- script/chart_sync_utils.sh
This PR fixes the script for syncing the chart to the bitnami repo removing a not-always-true assumption.
The more generic approach is less prone to errors.
N/A
N/A
N/A
> Fix chart_sync_utils.sh

- .github/workflows/kubeapps-general.yaml
This reverts commit 3d84ad6aa6165bca8109bc5da37d81f387cfbb7b.
Reverts the previous bump of GitHub action docker/build-push-action (6 -> 5).
The CI works again.
- fixes #
> Revert "Bump docker/build-push-action from 5 to 6 (#7850)"

- dashboard/package.json
- dashboard/yarn.lock
Bump a bunch of javascript deps.
Dependencies are updated.
Unnoticed breaking changes.
- fixes #
> Update js deps

- MAINTAINERS.md
- site/content/contributors/1-cscazorla.md
- site/content/contributors/2-agamez.md
- site/themes/template/layouts/partials/home-contributors.html
This MR updates the https://kubeapps.dev website to keep it up-to-date and reflect the current reality of the project.
The website reflects the current status of the project in terms of maintenance.
NA
NA
NA
> Update kubeapps.dev website
