vmware-tanzu/kubeapps

docs/developer/using-makefiles.md, script/cluster-kind.mk, script/deploy-dev.mk
Starting setting up the environment for the OIDC auth mode is not a straightforward task for beginners. Despite there exists a bunch of scripts in a Makefile to do so, they are not documented at all.
This PR is to simply add some hints and comments on how to use these scripts.
Furthermore, it also updates the Makefile file itself, otherwise, I wasn't able to run it.
Newcomers developers will set up the OIDC env more easily.
The changes in the .mk scripts are not tested. It 'just works' in my machine. Any suggestion to improve them is welcomed.
- Related to https://github.com/kubeapps/kubeapps/issues/2177, but just because I needed to set up this OIDC env to write the docs.
N/A
=> Add documentation for the Makefile scripts

dashboard/src/components/PageHeader/PageHeader.scss
I noticed that some `<img` where not properly rendered when the `src`  is encoded in base64:
Change the `display` property fixes the issue (the rest of icons keep working as usual)
=> Fix CSS display for img-container

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/SelectRepoForm/SelectRepoForm.test.tsx, dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
Currently, adding the [bitnami](https://charts.bitnami.com/bitnami) and the [jfrog](https://repo.chartcenter.io) repos, and then trying to upgrade an app, results in the following behavior:
And the corresponding error in js console: `Encountered two children with the same key, 'kubeapps/jfrog'. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.` 
I guess it is due to an unintended side effect when concatenating
`AppRepository.list(currentCluster, namespace)` and `AppRepository.list(currentCluster, otherNamespace)` because they are global repos and they appear in both listings.
This PR filters out duplicated repos (duplicated= …
=> Filter out dups repos by UID

cmd/assetsvc/handler.go, cmd/assetsvc/handler_test.go, cmd/assetsvc/main.go, cmd/assetsvc/postgres_db_test.go, cmd/assetsvc/postgresql_utils.go, cmd/assetsvc/postgresql_utils_test.go, cmd/assetsvc/utils.go
Make uniqChartList function repo-scoped instead of being unscoped. 
Current behavior leads to this scenario:
1. Add bitnami repo (https://charts.bitnami.com/bitnami)
2. Go to bitnami charts -> there are plenty of charts, eg, "bitnami/wordpress"
3. Add jfrog repo (https://repo.chartcenter.io)
4. Go to bitnami charts -> only 4 charts, there is no longer a "bitnami/wordpress"
Adding a new repo with mirrored charts won't prevent the old repo to still have its charts.
With this PR, the whole Kubeapps catalog may have duplicated charts in different repositories.
Following-up the PR https://github.com/kubeapps/kubeapps/pull/2173#discussion_r531535059
The main point is that, from a UX perspective, the sudden disappearance of a number of charts in an old repo when adding a new one could be …
=> Change scope of uniqChartList from all to a single repo

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/service.rs
Adds a stub proxy server using the recommended libraries (crates) hyper and tokio.
The main crate introduced in this PR is hyper - "hyper is a fast and correct HTTP implementation written in and for Rust.". Hyper is itself is built on a lower-level crate, tokio: "A runtime for writing reliable network applications without compromising speed.", but it only features via a macro (see inline comments).
Follows on from #2193 
You can run the server with `cargo run` and curl the address to see the response as you'd expect.
- Ref #2181 
Before reading this PR, if you're interested, I'd recommend reading briefly about [Rust's error handling with the `Result` enum](https://doc.rust-lang.org/stable/book/ch09-02-recoverable-errors-with-result.html). Where Golang functions tend to return a tuple with …
=> Add stub proxy server.

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/https.rs, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/service.rs
Follows #2195
This PR adds an https module with functionality to extract and validate the k8s api server url from the HTTP headers. No new concepts I don't think, but shows some good examples of using `match` and testing.
- Ref #2181 
Might be a good spot, while reviewing, to read about [Enums and Pattern Matching](https://doc.rust-lang.org/book/ch06-00-enums.html)
=> Add https module with code to extract target server URL from header.

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/https.rs, cmd/pinniped-proxy/src/service.rs
Follows #2198 and adds functions to extract the api server CA cert from the request headers.
I'll follow this up with a change that doesn't require the CA cert in the request headers when targeting the default cluster api server (https://kubernetes.local), as per #2181 .
- fRef: #2181 
Two other changes here:
* adding the `handle_error` function in the service to handle errors with an appropriate HTTP response and use this to handle errors for the 3 `https::` functions so far.
* improve the logging, you can run with `RUST_LOG=debug` and curl the service to see details such as:
```
INFO  pinniped_proxy > Listening on http://127.0.0.1:3333
DEBUG hyper::proto::h1::io > read 122 bytes 
DEBUG hyper::proto::h1::io > parsed 4 headers 
DEBUG hyper::proto::h1::conn > incoming body is empty 
DEBUG …
```
=> Add functions to extract cert auth data from headers.

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/https.rs, cmd/pinniped-proxy/src/service.rs
Adds code to proxy the actual request, even though the credential exchange isn't yet implemented.
Follows #2199
- ref #2181
With this PR you can proxy to your running local k8s api server, all that's missing is the credential exchange.
```
$ curl http://127.0.0.1:3333/api/v1 -H "PINNIPED_PROXY_API_SERVER_URL: https://127.0.0.1:33613" -H "PINNIPED_PROXY_API_SERVER_CERT: $CA_DATA"
{
"kind": "Status",
"apiVersion": "v1",
"metadata": {
},
"status": "Failure",
"message": "forbidden: User \"system:anonymous\" cannot get path \"/api/v1\"",
"reason": "Forbidden",
"details": {
},
"code": 403
}
```
with the logs showing:
```
$ RUST_LOG=info cargo run
Compiling pinniped-proxy v0.1.0 (/home/michael/dev/kubeapps/cmd/pinniped-proxy)
Finished dev [unoptimized + debuginfo] target(s) in 26.50s
Running …
```
=> Add actual proxying (without credential exchange yet)

cmd/pinniped-proxy/src/cli.rs, cmd/pinniped-proxy/src/https.rs, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/service.rs
Follows #2206 and updates to load the default cert authority data for use when the request doesn't include this *and* the url is for the https://kubernetes.default url.
Less configuration for the single-cluster use-case.
- ref #2181 - one of the items identified there.
See inline comments.
=> Load default cert authority data for kubernetes.default

cmd/apprepository-controller/controller.go, cmd/apprepository-controller/controller_test.go
As explained at #1832, for namespaced repos, the cronjob used to sync it was not being deleted after deleting the apprepo.
I also found that the cleanup job for the database was not being created, more details inline.
- fixes #1832
The main method of the controller `syncHandler` is not being tested, and because of its length and complexity I don't have the time to create those tests now so I just tested this fix IRL.
=> Delete cronjob related to namespaced repos

cmd/assetsvc/handler.go, cmd/assetsvc/main.go, cmd/assetsvc/main_test.go, cmd/assetsvc/postgresql_utils.go, cmd/assetsvc/postgresql_utils_test.go, cmd/assetsvc/utils.go, pkg/chart/models/chart.go, pkg/dbutils/postgresql_utils.go, pkg/dbutils/postgresql_utils_test.go
Before this PR, the only way to retrieve the list of distinct chart categories was to fetch all charts and, then, manually retrieves these unique categories. This PR is to add an endpoint for doing so but at the server-side and leveraging from the DB.
The proposed response in this PR is the list of distinct categories (`name`) and the count of charts belonging to each category (`count`). An example is depicted below:
```
{"data":[{"name":"Analytics","count":10},{"name":"ApplicationServer","count":2},{"name":"CertificateAuthority","count":1},{"name":"CMS","count":5},{"name":"CRM","count":2},{"name":"Database","count":12},{"name":"DeveloperTools","count":7},{"name":"E-Commerce","count":3},{"name":"E-Learning","count":1},{"name":"Forum","count":2},{"name":"HumanResourceManagement","count":1}, …
```
=> Add a getChartCategories endpoint

pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
No functional changes, it just clears up some (but not all) confusion that I found here while preparing some related work.
Hopefully clearer that the field formally known as `svcClientset` on the `kubeHandler` is the clientset using the service account credentials for the cluster on which Kubeapps is running. Also reduces confusion of the same name being used as a field and method on the struct.
Also found an unhandled error.
None.
- Ref: #2181
=> Don't shadow method name with field name.

script/e2e-test.sh
The google stable chart repo is no longer valid. We need to install chartmuseum
during CI from its new location as per
https://github.com/helm/chartmuseum/pull/393
The current URL results in a 403 now.
CI works again?
=> Fix link to chartmuseum chart.

cmd/kubeops/main_test.go, cmd/pinniped-proxy/src/main.rs, go.sum, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go, pkg/kube/pinniped_proxy_roundtripper.go, pkg/kube/pinniped_proxy_roundtripper_test.go
When testing pinniped-proxy with Kubeapps, requests from the browser client to the Kubeapps frontend for the k8s API were successfully proxied via pinniped-proxy, hitting the k8s api server with generated certs which were auth'd by the api server successfully.
But what I hadn't counted on was the requests from the browser client to our Kubeapps frontend for the kubeops service, which creates its own `client-go` kubernetes client set for user requests. This PR ensures that these are also proxied via pinniped-proxy when configured for that cluster.
Kubeops can also successfully interact with the k8s api server of each cluster using pinniped.
~I still need to do the IRL (in real life) test to ensure this works as expected.~ Edit: finally found and fixed a number of small issues so that this …
=> Ensure Kubeops proxies user requests via pinniped proxy when configured.

docs/user/getting-started.md
While browsing the getting started for other reasons, I noticed it still
refers to Helm as an in-cluster requirement (from the tiller days).
Don't confuse users.
None.
=> Fix old reference to helm in cluster requirement.

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/apprepositories-secret.yaml
For namespaced repos we need to create two identical secrets containing
ca.crt and/or authorizationHeader. We need one in the namespace that the
app repository is scoped to and one in the kubeapps release namespace.
The name of the secret in the kubeapps release namespace is expected to
be of the format {{ .namespace }}-apprepo-{{ .name }} by the
apprepository controller.
Fixes #2233
=> Fix namespaced initial repos

cmd/assetsvc/postgres_db_test.go
`master` and other PRs are failing because of this go test:
```
--- FAIL: TestGetChartsWithFilters (0.17s)
--- FAIL: TestGetChartsWithFilters/returns_charts_from_different_repos_in_the_specific_namespace (0.06s)
postgres_db_test.go:509: mismatch (-want +got):
[]*models.Chart{
&{
- 		ID:   "repo-name-1/chart-1",
+ 		ID:   "repo-name-2/chart-1",
Name: "chart-1",
Repo: nil,
... // 10 identical fields
},
&{
- 		ID:   "repo-name-2/chart-1",
+ 		ID:   "repo-name-1/chart-1",
Name: "chart-1",
Repo: nil,
... // 10 identical fields
},
}
FAIL
FAIL	github.com/kubeapps/kubeapps/cmd/assetsvc	0.990s
FAIL
make: *** [Makefile:36: test-db] Error 1
Exited with code exit status 2
CircleCI received exit code 2
```
I guess this is caused by the update of the golang deps. Ensuring the order of the compared …
=> Fix flaky Go test

dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Param.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Subsection.test.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Subsection.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/Subsection.test.tsx.snap
This PR simply adds a new check when evaluating whether or not a form field should be rendered. If the current `getValue(appValues, path)` is undefined (that is, there is no actual value in the `values.yaml` file) it tries to obtain the value form the hidden property (via `param.hidden?.value`).
Users won't have to specify a value in `values.yaml` if there already exists a default value in `hidden.value` of the `values.schema.json`
N/A
- fixes #1913
N/A
=> Fix default value in forms when using hidden

cmd/apprepository-controller/Dockerfile, cmd/asset-syncer/Dockerfile, cmd/assetsvc/Dockerfile, cmd/kubeops/Dockerfile, cmd/pinniped-proxy/Dockerfile
When running Kubeapps on a TMC cluster with TMC's default settings all our services errored with:
```
Warning  Failed     1s (x5 over 29s)  kubelet, ip-10-0-1-198.eu-west-1.compute.internal  Error: container has runAsNonRoot and image will run as root
```
If CI doesn't find any side effects, it means Kubeapps can run in security contexts requiring non-root containers without any extra config.
See what CI says, otherwise none.
=> Ensure containers run as as non-root.

cmd/assetsvc/handler.go, cmd/assetsvc/handler_test.go, cmd/assetsvc/postgresql_utils.go, cmd/assetsvc/postgresql_utils_test.go, cmd/assetsvc/utils.go
`getAllChartCategories` method was not using the `ChartQuery` object to receive the information.. Also, this PR allow using both `?repo` and  `?repos` for backwards compatibility.
Retrieving all distinct categories will work even if we choose a particular repo (o list of repos).
N/A
N/A
- Change initially introduced in https://github.com/kubeapps/kubeapps/pull/2221 but removed from there to keep it as simple as possible.
=> Use ChartQuery in getChartCategories

dashboard/src/components/AlertGroup/AlertGroup.test.tsx, dashboard/src/components/AlertGroup/AlertGroup.tsx, dashboard/src/components/AlertGroup/index.tsx, dashboard/src/components/Header/Header.test.tsx, dashboard/src/components/Header/Header.tsx, dashboard/src/components/Layout/Layout.scss, dashboard/src/components/Layout/Layout.test.tsx, dashboard/src/components/Layout/Layout.tsx, dashboard/src/reducers/kube.test.ts, dashboard/src/reducers/kube.ts, dashboard/src/shared/types.ts
Follow up of #2234
At the moment, if a request to resolve API kinds fails, we fallback to the default set with a silent error. With this PR, we show a closable warning to inform about the issue:
Now it's possible to use closable errors :)
=> Support for closable errors. Add kind-resolution error as closable

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.tsx, dashboard/src/components/SelectRepoForm/SelectRepoForm.test.tsx, dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
Follow up of https://github.com/kubeapps/kubeapps/pull/2245#discussion_r557286054
When `fetchRepos` is called for more than one namespace (any namespace + global namespace), the secrets from the global namespace are not needed so they should not be fetched. That's the current behavior but this PR ensures that, making it a boolean the parameter to fetch global repos or not.
=> Refactor fetchRepos action

dashboard/src/actions/charts.test.tsx, dashboard/src/actions/charts.ts, dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/containers/CatalogContainer/CatalogContainer.tsx, dashboard/src/reducers/charts.test.ts, dashboard/src/reducers/charts.ts, dashboard/src/shared/Chart.test.ts, dashboard/src/shared/Chart.ts, dashboard/src/shared/types.ts, dashboard/src/shared/url.ts
This PR is to introduce the `page` and `size` params (defaulted to `1`, `0`, that is, no pagination whatsoever). The functionality is the very same as the parent branch of this PR.
Not many... just intended for easing the endless scrolling feature.
N/A
This PR depends on https://github.com/kubeapps/kubeapps/pull/2249 to be merged.
- Change initially introduced in https://github.com/kubeapps/kubeapps/pull/2221 but removed from there to keep it as simple as possible.
=> Add pagination params 

dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/containers/CatalogContainer/CatalogContainer.tsx
This PR uses the `repos` property, which already exists in the global state, and adds the component state variable `currentRepo` for tracking the selected repos (used in the /chart request)  
The logic to getting all the repositories will no longer require iterate over the whole list of charts; instead, repos will be retrieved from the state.
N/A
This PR depends on https://github.com/kubeapps/kubeapps/pull/2249 to be merged.
- Change initially introduced in https://github.com/kubeapps/kubeapps/pull/2221 but removed from there to keep it as simple as possible.
=> Use repos from state in catalog

dashboard/src/components/OperatorList/OperatorList.scss, dashboard/src/components/OperatorList/OperatorList.tsx
This PR simply introduces a small bottom padding to the Operator catalog, so the UI remains more or less consistent with the general chart catalog.
Operator catalog will no longer be like:
... to be like:
N/A
N/A
N/A
=> Add small padding bottom to the OperatorList

dashboard/src/components/Catalog/Catalog.tsx
After the changes in #2249, some minor bugs are popping up. This PR is just to force the clear when the text input has been deleted.
The current (master) status is:
Note that "Clear all" and `?Search=` remains despite the user input has been deleted.
Users won't be shown a "clear all" even if they already cleared the input, that is:
N/A (I hope so)
N/A
Sometimes I'm noticing a sync problem between the text at the search filter (the `?Search=xxx` value) and the text input content.  Perhaps we can look into this other issue in another PR.
=> Clear search filter when deleting text

cmd/apprepository-controller/controller.go, cmd/apprepository-controller/controller_test.go, cmd/asset-syncer/main.go, cmd/asset-syncer/sync.go, cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go, pkg/chart/models/chart.go
This PR doesn't include any functional change, two changes have been included:
- The AppRepository `type` is now passed as an argument to the asset-syncer (but currently it's being ignored)
- Methods depending on the `type` has been moved to an interface (`Repo`) so I can implement those for the OCI repository type in the next PR.
- ref #2232
=> Refactor: Move asset-syncer methods to an interface

dashboard/src/components/Layout/Layout.tsx
Warning messages generated by the `AlertGroup` wrongly include a  `$`. This PR is to get rid of this char.
Browsers will save some computation time by not rendering the `$`, I guess :stuck_out_tongue: 
N/A
N/A
N/A
=> Remove the '$' character from the error message

pkg/agent/agent.go, pkg/agent/agent_test.go, pkg/agent/httpConfigForCluster.go
While testing and demoing Kubeapps on a non-oidc cluster using pinniped, I've found that although helm releases are fetched correctly, I was not able to create a new release (deploy an app). Instead I'd get the cryptic message: Release "..." failed and has been uninstalled: unable to build kubernetes objects from release manifest: unknown
I assumed the issue was in pinniped-proxy, so began debugging there only to find that certain requests were hitting pinniped-proxy without the `Authorization` header with the bearer token. Confused, I then looked to kubeops where we create the requests via the helm API. After a lot of hunting around, the issue was pinpointed in that *something* in the internals of `genericclioptions.ConfigFlags.ToRestConfig()` was stripping off the bearer token if the …
=> Helm with pinniped

dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/components/ApplicationStatus/ApplicationStatus.tsx, dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx, dashboard/src/reducers/kube.test.ts, dashboard/src/reducers/kube.ts, dashboard/src/shared/types.ts
In Firefox, there is an issue that a warning is thrown when opening a websocket: https://github.com/socketio/socket.io/issues/2016
This causes Kubeapps to fallback to the periodic polling mechanism but it's still receiving events from the websocket. It's also losing the reference to the "timer" that needs to be cleaned when the component is unmounted.
This PR includes two fixes:
- If the websocket receives an event, remove the timer so the fallback method is not executed.
- The timer is stored in the Kube state, identified uniquely by the resource is polling so it's not possible to create two timers for the same resource.
- fixes #2258
=> Fix websocket behavior in Firefox

cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go
Add the method to get the "checksum" of an OCI registry. To achieve this, the method retrieves the list of tags for each repository (app) and calculates the checksum of the aggregated list.
For large registries, a request will be made per repository which might bloat the registry API.
- ref #2232
=> Implement checksum method for OCI registries

dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/components/OperatorList/OperatorList.test.tsx, dashboard/src/components/OperatorList/OperatorList.tsx
Following up https://github.com/kubeapps/kubeapps/pull/2221#issuecomment-760943588 and https://github.com/kubeapps/kubeapps/pull/2264#pullrequestreview-575212694.
This PR is to workaround this bug by simply change the default character for splitting and joining, the comma `,`, to another less frequent but also meaningful, the pipe `|`.
Filters values having a comma as part of their names won't break the UI anymore: 
I don't think so, but I'm not fully aware whether or not this "comma"-split way to generate the URL is being used anywhere else. 
N/A
N/A
=> Change comma by pipe to concat filters in the catalog

chart/kubeapps/templates/kubeapps-frontend-config.yaml, cmd/kubeops/main.go, cmd/kubeops/main_test.go, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
This PR has two small changes which I found necessary while testing a setup of multiple clusters without OIDC configuration (but using pinniped instead).
The first is just a typo in the frontend config which resulted in the api server URL not being set for the requests to a configured second cluster.
The second was that in Kubeops we were attempting to send the certificate authority data for a second cluster unencoded.
With these changes we can now use pinniped in a multi-cluster scenario.
Not aware of any.
- Ref: #2181
I noticed while testing this that the context selector does not seem to be updating the current cluster after changing context. I'll check separately whether this is related or unrelated. (I had to manually update the URL after changing the context).
=> pinniped api server cert must be encoded when sent as header.

dashboard/src/components/Header/ContextSelector.test.tsx, dashboard/src/components/Header/ContextSelector.tsx, dashboard/src/shared/specs/mountWrapper.tsx
While testing the multicluster setup with pinniped, I noticed that when selecting a different cluster, the current cluster didn't appear to change. See comment on #2281.
Looking more closely here using the redux debugger, I could see that SET_NAMESPACES was called when changing context which correctly updated `currentCluster` in the state, but it was immediately followed by a LOCATION_CHANGE which set it back to its previous value.
Checking the code, it appeared to be related to a change in #2187 where we'd updated the location when changing context, directly after calling `setNamespace`, but had done so without using the new cluster in the location.
You can change clusters again :)
Not aware of any.
- Ref #2018, Ref #2181
=> Fix context selector when changing clusters.

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/pinniped.rs, cmd/pinniped-proxy/src/service.rs
Up until now, if pinniped-proxy received a response from pinniped identifying that it could not exchange credentials (such as "authentication failed") it would return a 500.
This PR updates to recognise a successful request to pinniped that doesn't contain credentials and returns some context of a specific error so it can be handled differently in the service.
We don't return 500 internal server errors for errors that aren't internal server errors.
The user just sees a 401 request with a limited message.
An error such as this is a configuration error (ie. the user does not have access yet, or the jwt authenticator has the incorrect audience (this is how I tested it)), so checking logs is required to solve.
We should update the oidc debugging faq with pinniped specific steps once we …
=> Handle pinniped authentication errors as unauthorized.

chart/kubeapps/templates/kubeapps-frontend-config.yaml, chart/kubeapps/templates/kubeops-deployment.yaml
Without this change the pinniped-proxy-url used by kubeops was relying on a default value (kubeapps namespace).
This updates the location for pinniped-proxy in both the kubeops and frontend deployments, based on existing values.
Pinniped-proxy will work when using a namespace other than kubeapps for the kubeapps deployment.
None.
- Ref #2181
=> Create pinnipedProxyURL based on existing params.

cmd/asset-syncer/helm.go, cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go
After testing the code related to OCI registries IRL, I noticed the three issues fixed here (the first one is the bigger):
- An OCI endpoint can contain any kind of artifact (docker images or helm charts). We need to filter only the Helm charts, if not it will fail trying to pull a docker image as a chart. For simplicity, I have moved the methods related to the OCI API to an interface (`ociAPICli`).
- If a chart contained several READMEs, the last one read was the one stored (e.g. `apache/vhosts/README.md`). Fixed to only take into account files in the root directory.
- For "large" text files (e.g. Jenkins README), `tarReader.Read` lost a bunch of bytes at the end, filling those with "0"s (TBH, not sure why). Using `ioutil.ReadAll` fixes the issue.
- ref #2232
=> Several fixes to the pull process

chart/kubeapps/templates/kubeapps-frontend-config.yaml, cmd/kubeops/main.go, dashboard/src/shared/App.test.ts, dashboard/src/shared/App.ts, dashboard/src/shared/url.ts, pkg/http-handler/http-handler.go
This PR is just to delete a bunch of old endpoints that are no longer used by any part of the code.
We finally will: 1) get rid of the non-cluster aware docs; 2) replace the reference to tiller by kubeops; 3) remove the old non-cluster aware `/kube/` proxypass.
Can't think of any, but I'm opening this draft PR to see if CI complains
- fixes #2298
Related to  #2291. If this PR becomes merged, `tiller-deploy` should be also renamed there.
=> Delete unused API endpoints

dashboard/src/actions/apps.test.tsx, dashboard/src/actions/apps.ts
Fix an unhandled rejection that shouldn't really occur. While developing the UI the URLs are pointing to `/kubeops/` and not to `/tiller-proxy/`. There is a temporary inconsistency just when telepresencing just the UI pod.
However, it always good to remove these rejections :)
Avoid annoying rejection when developing the UI until we release the next version.
N/A
N/A
N/A
=> Fix unhandled rejection in actions/apps

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/https.rs, cmd/pinniped-proxy/src/pinniped.rs
This PR updates the dependencies of pinniped-proxy as I was previously using a differing version of kube-runtime and kube-derive, which can cause compilation issues (as seen on #2286 .
Updated libs, compiles without issue.
None known.
=> Update pinniped-proxy deps to latest kube and k8s-openapi

cmd/asset-syncer/utils_test.go, cmd/kubeops/internal/handler/handler.go, pkg/agent/agent_test.go, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/chart/fake/chart.go, pkg/handlerutil/handlerutil.go, pkg/helm/fake/helm.go, pkg/helm/test/utils.go
Follow up of #2311
Now it's time to implement the actual interface for the OCI case. 
As explained in a `TODO`, using a CA cert won't work here. The only alternative with ORAS is to use an `insecure` flag but I didn't included that (yet?).
- ref #2232
=> OCI GetChart

pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
Adding the endpoint to enable validation for OCI registries. Rather than just doing a request to validate the registry, we are doing a request per repository (app) to validate that there are no typos there (we could not validate just the registry anyway, because the root path of the API `https://repo/v2` is protected, even for public repos, at least for Harbor).
- ref #2232
=> Enable validation for OCI appRepos

chart/kubeapps/templates/kubeapps-frontend-config.yaml
Small issue I noticed when putting a demo env together: although we'd changed the individual cluster option for enabling a specific cluster to use pinniped from `exchangeCredentials` to `enable` and updated kubeops accordingly, it'd been left here in the template with the old name.
Don't need to set both `.enable` and `exchangeCredentials` in the cluster config for a specific cluster to demo it.
None.
=> Use .enable rather than .exchangeCredentials

chart/kubeapps/templates/dashboard-config.yaml, chart/kubeapps/values.yaml
Autoconvert from yaml to json for easing the process of writing a custom locale
Users will write yaml instead of json
N/A
- related #2346 
N/A
=> Use yaml to define customLocale

chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
When testing the translation feature in an OIDC scenario, requests to the custom style and locale were 403-blocked. This PR just add both files to the skip flags of the authProxy.
Custom styles and locales can be used in the OIDC login page
N/A
- related #2346 
N/A
=> Add custom_style and custom_locale to the skip-auth

dashboard/src/actions/charts.test.tsx, dashboard/src/actions/charts.ts, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
A couple of fixes I noticed when testing the OCI repo sync (on top of #2336):
- When loading a chart, use the latest version available (using semver).
- When not using a scheme in the repo form (`http://` or `https://`), assume https://. This is fairly common when using OCI registries.
- ref #2232
=> Some OCI repo form fixes

dashboard/src/actions/charts.test.tsx, dashboard/src/actions/charts.ts, dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx, dashboard/src/shared/AppRepository.ts, dashboard/src/shared/types.ts
Enable the usage of OCI registries for AppRepositories: 
Note that using a CA cert is not supported as explained here: https://github.com/kubeapps/kubeapps/pull/2323#issuecomment-775029689
- ref #2232
=> Allow to create OCI apprepos

dashboard/src/components/LoginForm/LoginForm.scss
It seems that `display: contents` doesn't play well with Safari. This PR fixes it:
- fixes #2375
=> Fix login button for Safari

cmd/kubeops/internal/handler/handler.go, cmd/kubeops/main.go
Currently deploying to an additional cluster fails due to a recent change (see [comment](https://github.com/kubeapps/kubeapps/pull/2310/files#r574249840)) which switched from fetching an AppRepository only ever from the Kubeapps cluster to instead trying to fetch the AppRepository from the *current* cluster.
You can once again deploy to other clusters.
Not as a result of this, but we currently don't test deploying to other clusters in CI. We should (#2367).
=> fix deploy other clusters

cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go
Similar to #2373 but this time for getting tags. As mentioned in that issue, checking tag per tag is a bit slow (since it requires an API request per tag) so doing it in parallel improves a lot the total time took.
From the test run, I got a 10x faster sync in the part of the sync that checks the tags.
In total (this PR plus the previous one), my test sync went from ~25 to 4 minutes.
- ref #2232
=> Request tags in parallel

cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go, pkg/chart/chart_test.go, pkg/helm/helm.go
Right now, there is a mechanism to download files (tarballs) in parallel for the Helm repository case but not for OCI charts. This PR implements this.
The sync process is quite faster (the pulling process is now 5x faster in the test I've done).
- ref #2232 
I noticed that the process of getting the list of tags is almost as slow as the process of pulling charts so I will do another PR to query that in parallel as well.
=> Pull charts in parallel

dashboard/src/components/Catalog/Catalog.scss
This PR just forces the vertical scrollbar to appear to prevent it to blink while fetching filtered and paginated charts in the catalog.
The issue is caused by:
```jsx
{!hasFinishedFetching && !isFetching && (
<div className="scrollHandler" ref={observeBorder} />
)}
```
This `scrollHandler` has an overflow of about 50% vertical viewport to allow scrolling down to fetch more when in a natural way.
I've also tried hiding (`visitbility: hidden`) instead of not rendering it, but the interactionObserver API doesn't trigger as expected (no UI shaking, but tons of messed up HTTP requests...)
Since the scroll is, now, an inherent feature of the catalog, a possible workaround is just to force the scrollbar to always appear.
The bug described in #2290 won't happen anymore if we always display the …
=> Display scrollbar in the catalog to prevent blinking

cmd/apprepository-controller/controller.go, cmd/apprepository-controller/controller_test.go, cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go, cmd/asset-syncer/main.go, cmd/asset-syncer/sync.go, cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go, pkg/chart/chart.go, pkg/kube/http_utils.go, pkg/kube/http_utils_test.go
Allow to use HTTPS for Helm repositories/registries but skip the TLS verification for self-signed certificates.
Since the `Resolver` is now using a custom HTTP client, we can additionally use a custom CA
- ref #2232
As an extra, the `netClient` variable is no longer global but part of the repository `struct`.
Reviewing per commit may be easier.
=> Allow to skip TLS verification and use a custom CA

.circleci/config.yml, chart/kubeapps/Chart.yaml
At the moment, `master` builds are broken because we have changed some routes (https://github.com/kubeapps/kubeapps/pull/2300). The last version `v2.1.0` uses `tiller-proxy` URLs while the current NGINX config in the latest chart configures `kubeops`. We have two options: either add backward-compatible config and routes or disable the "latest release" builds knowing that **we cannot release a new version of the chart until we release a new version of Kubeapps**.
I am going for the second option since we plan to release a new version soon anyway. Note that we are only testing the combination of the current chart + the latest release when releasing a new chart version. Because of that, I am reverting the change at #2359 for the version bump.
Fix master
Block chart releases
=> Revert last chart version bump

cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go
When using an OCI repository, there two options:
1. Use the registry URL with the repo and the app name without the repository (e.g. `registry: docker.io/bitnami, app: wordpress`).
2. Use the registry URL without the repo and include that in the app name (e.g. `registry: docker.io, app: bitnami/wordpress`).
The second was not working because the app was stored with `/` while the request to the asset service the name is URL-encoded.
- ref #2232
=> Encode OCI repository names before storing them

chart/kubeapps/templates/_helpers.tpl, chart/kubeapps/templates/kubeapps-frontend-config.yaml, chart/kubeapps/values.yaml
More context in Slack can be found [here](https://kubernetes.slack.com/archives/C9D3TSUG4/p1612546656047300?thread_ts=1612465715.011500&cid=C9D3TSUG4).
In order to use kubeapps with our API gateway (authenticating proxy), I need to be able to configure an optional k8s API URL _path_ (in addition to the base service URL).
This way I can write an ingress rule that matches that path, and set the base k8s service URL to my ingress service. Voila - kubeapps sits behind our API gateway, like all our other upstream services!
One additional change is needed: In the kubeops NGINX locations (i.e. those that proxy via `proxy_pass {{ include "kubeapps.frontend-config.proxy_pass" . -}};`), I need to be able to set an additional proxy header so as to include an `Authorization: Bearer some-token` that …
=> Allow apiServiceURLs to include subpath in NGINX location

.circleci/config.yml, cmd/pinniped-proxy/Dockerfile, cmd/pinniped-proxy/src/pinniped.rs, docs/developer/release-process.md
Cleans up the Dockerfile used to build pinniped-proxy, updating to use bitnami/minideb for the runtime base.
Also adds the testing and building of pinniped-proxy to circleci, but does not depend on it for any other images/tests.
Start building the pinniped-proxy image.
I'll check with @carrodher about landing this and whether we need to wait for equivalent config in the bitnami pipeline.
- fixes #2181
@andresmgot You mentioned recently that the build image might be an issue since it's not part of the bitnami catalog, but I'm not sure how that's different to the golang images which use a dockerhub image for building - ah, unless during the bitnami release it's switched for a specific bitnami go image in that case?
=> Update pinniped-proxy runtime to bitnami/minideb. Add to circleci

chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
The devel Dockerfile doesn't specify an entrypoint (similar to all Kubeapps devel Dockerfiles) so our deployment worked fine, but since the bitnami Dockerfile for pinniped-proxy *does* define an ENTRYPOINT, our deployment effectively tried to do `./pinniped-proxy pinniped-proxy`.
This change ensures that our deployment specifies the command (which is therefore used instead of the entrypoint).
Our deployment works with the bitnami pinniped-proxy image.
None.
=> Use command for pinniped-proxy to overwrite entrypoint.

docs/user/using-an-OIDC-provider-with-pinniped.md, docs/user/using-an-OIDC-provider.md
Include documentation for configuring Kubeapps with pininped for OIDC authentication.
People have more info about configuring Kubeapps with OIDC on clusters without the API server being configured for OIDC.
You can [view the rendered change](https://github.com/absoludity/kubeapps/blob/document-pinniped-proxy/docs/user/using-an-OIDC-provider-with-pinniped.md).
=> Add documentation for OIDC with pinniped.

chart/kubeapps/templates/kubeapps-frontend-deployment.yaml, cmd/pinniped-proxy/Dockerfile
Yesterday I saw that we needed to explicitly specify the command for pinniped-proxy deployment rather than just using args, as the [bitnami image](https://github.com/bitnami/bitnami-docker-kubeapps-pinniped-proxy/blob/2.2.0-debian-10-r0/2/debian-10/Dockerfile) specifies an entrypoint.
What I failed to notice is that the bitnami image is not putting the executable in the root directory, but rather is relying on the path.
This change updates the chart deployment config to similarly rely on the path to find the executable. This change is required for the release (sorry).
The second change to our devel dockerfile just matches the bitnami Dockerfile in terms of the executable and is not required for the release (ie. we don't need new images).
Our devel Dockerfile is more inline with the …
=> Don't use absolute ref to pinniped-proxy command in container.

cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go, pkg/chart/chart_test.go, pkg/helm/fake/helm.go
I introduced a bug after https://github.com/kubeapps/kubeapps/pull/2373
The variable for the chart versions was scoped to goroutine so only the first one was stored (causing the app to just store the first version received of the chart).
Will need to release a patch version after this :/
=> Fix behavior for multiple chart versions for OCI registries

dashboard/src/actions/operators.ts, dashboard/src/components/AppList/AppListGrid.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/shared/types.ts
If an Operator doesn't contain CRDs, the dashboard fails with: `cannot read owned of undefined`. Adapted the typescript definition to avoid this issue.
=> Fix for Operators without owned CRDs

chart/kubeapps/values.yaml
Verified locally that oidc setup works fine with the new version.
I've not updated the chart versions since #2436 hasn't yet landed which also updates the chart version. If you land this first it will be included, otherwise I'll add an update before landing?
Use the current oauth2-proxy with update support.
=> Update oauth2-proxy version to 7.x

dashboard/src/components/ApiDocs/ApiDocs.scss, dashboard/src/components/AppView/AppSecrets/AppSecrets.scss, dashboard/src/components/Header/ContextSelector.scss, dashboard/src/components/Header/Menu.scss, dashboard/src/components/Header/Menu.tsx, dashboard/src/components/Layout/Layout.scss, dashboard/src/components/PageHeader/PageHeader.scss, dashboard/src/index.scss
_Depends on #2450_ 
This PR introduces some tweaks for the dark mode (rendered when loading the dark clr theme), mainly converts some svg to white for improving the contrast.
It also fixes an issue with the scrollbars in the secret view and a wrong color in a cds-icon.
It adds these changes:
N/A
- fixes #2462 
-  related #2372
-  related #2371 
N/A
=> Minor css fixes and tweaks for the dark mode

dashboard/src/actions/charts.test.tsx, dashboard/src/actions/charts.ts, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/reducers/charts.test.ts, dashboard/src/reducers/charts.ts
This PR aims at solving one of the issues detected in https://github.com/kubeapps/kubeapps/issues/2484#issuecomment-788658490. Currently, the pagination is trying to increase the page regardless of the status code.
In this PR we stop requesting more pages if an error is detected. However, solely adding that has a severe impact on the UX: if request happens to fail, all the previously requested items will be discarded and the only way to retry is by performing a hard reload (f5).
Wherefore this PR also adds a mechanism to trigger: i) an increase of the requested page; 2) clearing the current error.
A live example is depicted below:
This approach just assumes there is a problem on a given page and we force to request the next one. As a result, the failing page will remain unrequested. 
- …
=> Avoid endless page requesting if when failing requests + manual retry

chart/kubeapps/Chart.lock, chart/kubeapps/Chart.yaml, chart/kubeapps/README.md, chart/kubeapps/crds/apprepository-crd.yaml, chart/kubeapps/templates/NOTES.txt, chart/kubeapps/templates/_helpers.tpl, chart/kubeapps/templates/apprepository-deployment.yaml, chart/kubeapps/templates/apprepository-jobs-cleanup-rbac.yaml, chart/kubeapps/templates/apprepository-jobs-cleanup.yaml, chart/kubeapps/templates/apprepository-jobs-postupgrade-rbac.yaml, chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml, chart/kubeapps/templates/apprepository-rbac.yaml, chart/kubeapps/templates/assetsvc-deployment.yaml, chart/kubeapps/templates/assetsvc-service.yaml, chart/kubeapps/templates/dashboard-deployment.yaml, chart/kubeapps/templates/db-secret-cleanup-rbac.yaml, chart/kubeapps/templates/db-secret-jobs-cleanup.yaml, chart/kubeapps/templates/ingress.yaml, chart/kubeapps/templates/kubeapps-frontend-deployment.yaml, chart/kubeapps/templates/kubeapps-frontend-service.yaml, chart/kubeapps/templates/kubeops-deployment.yaml, chart/kubeapps/templates/kubeops-rbac.yaml, chart/kubeapps/templates/tests/test-assetsvc.yaml, chart/kubeapps/templates/tests/test-dashboard.yaml, chart/kubeapps/templates/tls-secrets.yaml, chart/kubeapps/values.yaml
Signed-off-by: juan131 <juanariza@vmware.com>
This PR adapts the Kubeapps chart to use the `bitnami/common` library so several common macros are reused. This is important to standardize this chart with the rest of the Bitnami Catalog.
On the other hand, it ensures the `apiVersion` of several objects (e.g. Ingress, RBAC, CRDs, etc.) is compatible with different K8s versions.
- Standardization
- Compatibility with multiple K8s versions.
None
N/A
None
=> [chart] Use bitnami/common function + provide compatibilty with different K8s versions

integration/use-cases/create-private-registry.js
The current test `create-private-registry` is failing when used against the latest release of kubeapps (2.2) (https://app.circleci.com/pipelines/github/kubeapps/kubeapps/2334/workflows/1ee87892-79a9-42c5-8105-11e765540321/jobs/39920) due to the latest changes in the AppRepo form. This PR adapts the test so it can be used against master (or 2.3) and 2.2.
Fixes master
We'd need to remember to remove the workaround (try/catch) once we release 2.3.
=> Adapt e2e test selectors to both versions of kubeapps

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/_helpers.tpl
Looks like the result of merging both the common chart dependency together with the oauth2 sensitive data PR #2436
As a result, templating when using oauth proxy fails:
```
helm template chart/kubeapps --set authProxy.enabled=true
Error: template: kubeapps/templates/_helpers.tpl:143:12: executing "kubeapps.oauth2_proxy-secret.name" at <{{template "kubeapps.fullname" .}}>: template "kubeapps.fullname" not defined
```
=> Fix dangling reference to old template helper.

chart/kubeapps/templates/kubeapps-frontend-deployment.yaml, chart/kubeapps/values.yaml, cmd/pinniped-proxy/src/pinniped.rs, docs/user/using-an-OIDC-provider-with-pinniped.md
This PR adds support for Pinniped 0.6.0 (but with a **not-backward-compatible** change). It means Pinniped-proxy will only work in >=0.6.0.
Apart from some very minor refactor, there are two main changes:
1. API calls to `authentication.concierge....` and `login.concierge....` will be global instead of namespaced (this is the breaking change).
2. Shamefully ugly workaround consisting of duplicating code for supporting another API group rather than `pinniped.dev`. Specifically, this PR adds support for the one that will be used in Tanzu Mission Control.
1.  Pinniped >= 0.6.0 will be supported.
2.  Pinniped-proxy can be used in TMC.
Dropping support for Pinniped < 0.6.0
- fixes #2426 
There is another PR aimed at solving the problem more generically …
=> Make pinniped-proxy compatible with 0.6.0 and TMC

chart/kubeapps/templates/dashboard-config.yaml, chart/kubeapps/templates/dashboard-deployment.yaml, chart/kubeapps/values.yaml, dashboard/package.json, dashboard/src/RemoteComponent.js, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/CustomFormParam.test.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/CustomFormParam.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Param.tsx, dashboard/src/remote-component.config.js, dashboard/src/shared/types.ts, dashboard/yarn.lock, docs/developer/basic-form-support.md, docs/developer/custom-form-component-support.md, docs/developer/examples/CustomComponent.js, docs/developer/examples/CustomComponent.jsx, docs/developer/examples/CustomComponent.min.js
Signed-off-by: Anthony Rizzo <36711320+aanthonyrizzo@users.noreply.github.com>
This PR adds the ability to load custom form components from a separate js file by passing the render param and the the handleChange func.
- Allow devs to build custom UI components (radios for example)
- Allow devs to consume external APIs inside of components for rendering logic/validation
- Unfortunately the external components have to be loaded via a separate js file (im imagining this is a js bundle). As you will see I decided to use a pvc to mount the file into the dashboard nginx so that when pods are deleted the js file is remounted. 
Fixes #2352 
Example:
Instead of rendering a dropdown it rendered 'Hello world!' from a js bundle file
=> feat(form): Add custom form component integration

dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/CustomFormParam.test.tsx
Since one of the latest PR was being developed at the same point as we were migrating to eslit, there is a minor issue preventing our CI to work.
This PR simply tweaks a little bit the failing file, a test using window.location.
No CI errors.
N/A
N/A
N/A
=> Fix test to work with the latest eslint rules

chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
This simple PR just adds the manifest.json to the `skip-auth-regex` .
A 403 warning will not be thrown in the login page.
N/A
N/A
N/A
=> Add the static manifest.json to the auth-proxy skip-auth-regex

cmd/pinniped-proxy/src/service.rs
As per the discussion in https://github.com/kubeapps/kubeapps/issues/2328#issuecomment-803984871, this PR simply adds an explicit 5xx-error when proxying a websocket connection attempt (aka 101 HTTP status code).
The polling fallback mechanism now will be triggered.
An error msg will be thrown in the js console.
- rel #2328
N/A
=> Fail when proxing ws in pinniped proxy

chart/kubeapps/README.md, chart/kubeapps/templates/kubeops-deployment.yaml, chart/kubeapps/values.yaml, cmd/kubeops/internal/handler/handler.go, cmd/kubeops/main.go, pkg/http-handler/http-handler.go, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
Run namespace checks in parallel (the check that verifies if a user can access a namespace). Also, if the user has permissions to list namespaces, this check is skipped.
I did the following tests to verify the new performance:
1. 200 namespaces, without this PR: 39s
~~2. 200 namespaces, 20 parallel workers (the new default): 8.6s~~
2. 200 namespaces, 10 QPS, 15 Burst requests: 19.8s
3. 200 namespaces, 100 QPS, 200 Burst requests: 0.5s
Using too many workers might saturate the k8s API.
- fixes #2506
cc/ @mecampbellsoup
=> Parallelize namespace-check requests

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/apprepository-deployment.yaml, chart/kubeapps/templates/assetsvc-deployment.yaml, chart/kubeapps/templates/dashboard-deployment.yaml, chart/kubeapps/templates/kubeapps-frontend-deployment.yaml, chart/kubeapps/templates/kubeops-deployment.yaml, chart/kubeapps/values.yaml
The reason I want this supported is so that I can add these deployments
to my service mesh. Most service mesh decide on which deployments/pods
should be part of the mesh using annotations. I would like to be able to
control this via the Helm chart.
Service meshes can also allow you to add a whole namespace to the
service mesh. The reason this doesn't work well is that the sync jobs
created by kubeapps will never complete if they have a sidecar
container, which is what's done to add a pod to a service mesh.
This only adds support for adding annotations to the deployments, not
the pods created by those deployments. If we want to support that as
well, we could add another field called podAnnotations to each of these
components.
I also changed how the labels were added to the deployments, …
=> Add ability to set annotations to each individual deployment

chart/kubeapps/templates/apprepository-rbac.yaml
Found an error in the controller logs when refreshing a repository (probably because I am running in Kubernetes 1.20):
```
E0326 07:34:40.891173       1 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"bitnami.166fd426ace6b979", GenerateName:"", Namespace:"kubeapps", SelfLink:"", UID:"", ResourceVersion:"22447", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, …
```
=> Update apprepository-controller RBAC role

chart/kubeapps/values.yaml
This PRs simply performs an upgrade of the external image versions that Kubeapps uses, particularly:
[bitnami/nginx](https://github.com/bitnami/bitnami-docker-nginx)
[bitnami/kubectl](https://github.com/bitnami/bitnami-docker-kubectl)
[bitnami/oauth2-proxy](https://github.com/bitnami/bitnami-docker-oauth2-proxy)
Since the oauth2proxy has been bumped up to 7.1.0, it includes the changes required by #2118 to be solved.
Furthermore, these latest versions of nginx/kubectl will include as well the latest release of the openssl dep.
N/A
- closes #2118
If you may prefer, we can just update the oauth2proxy version for addressing the #2118 issue and leave the other unchanged.
=> Update image versions

.circleci/config.yml, integration/use-cases/create-registry.js, integration/use-cases/operator-deployment.js
This PRs aims at providing a DRYer approach to define common env vars in the CI environment.
It, hopefully, prevents from having this kind of errors (kubectl not being downloaded due to a missing `$KUBECTL_VERSION`
```bash
circleci@3ee4bb67d105:~/project$ cat /usr/local/bin/kubectl
<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: kubernetes-release/release//bin/linux/amd64/kubectl</Details></Error>circleci@3ee4bb67d105:~/project$ 
```
Some vars may not be strictly necessary in some steps, but not a big deal at all.
- related #2376
N/A
=> Use common environment variables in CI

chart/kubeapps/Chart.yaml, script/chart_sync_utils.sh
This PRs adds the `pinniped-proxy` image in the list of imgs to be replaced in the official Bitnami chart (see https://github.com/kubeapps/kubeapps/blob/master/script/chart_sync_utils.sh).
Pinniped-proxy will be available (I mean, the official Bitnami image, not our kubeapps one) as part of the Bitnami chart.
N/A
N/A
Since this process is being carried out from our CI system, we should pass this list as an envar, so that we only need to define it once. However, it should be another PR (and once we finish the CI updates).
=> Add pinniped-proxy to the official chart

pkg/agent/docker_secrets_postrenderer.go, pkg/agent/docker_secrets_postrenderer_test.go
Fixes #2634
When converting the key `imagePullSecrets`, the object type is `map[interface{}]interface{}` rather than `map[string]interface{}` (even if the object is `- name: foo`).
I'm using the raw YAML in the tests to be able to reproduce the issue.
=> imagePullSecrets: Fix type conversion

.circleci/config.yml
According to the GKE news (https://cloud.google.com/kubernetes-engine/docs/release-notes#no-channel), we must update the GKE versions used in CI from 1.15->1.17 and 1.16->1.18
Note that we are using the _stable_ and _regular_ environmetns.
We will test kubeapps on state-of-the-art cluster versions.
Minor issues in the CI? Let's see what it says...
- fixes #2646
We must now revisit other issues regarding API versions: https://github.com/kubeapps/kubeapps/issues/2169
Note the changes are being tested in the [test-changes-ci](https://github.com/kubeapps/kubeapps/tree/test-changes-ci) branch.
=> Update the GKE versions used in CI

integration/use-cases/02-create-private-registry.js, integration/use-cases/lib/utils.js, script/e2e-test.sh
This PR simply removes a leftover line that is preventing the test to work in master.
Since we are using this shell expansion: `  "${multiclusterFlags[@]+"${multiclusterFlags[@]}"}" `
we are evaluating the array `multiclusterFlags[@]` prior to the actual expansion, so there is no need of initializing the var beforehand. 
See the actual test: https://app.circleci.com/pipelines/github/kubeapps/kubeapps/2682/workflows/b6c780e5-78c6-4eb9-847b-dbbde4ba4fc1
=> Minor CI fix

dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
Follow up of https://github.com/kubeapps/kubeapps/pull/2650#discussion_r608603878
Rather than hiding the Docker Credentials section in the AppRepo form (which can be confusing), disable it with a hint:
=> Disable (rather than hiding) the Docker Credentials section

cmd/apprepository-controller/controller.go, cmd/apprepository-controller/controller_test.go, cmd/asset-syncer/sync.go, dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/shared/AppRepository.ts, dashboard/src/shared/url.ts, pkg/chart/chart_test.go, pkg/kube/http_utils.go, pkg/kube/http_utils_test.go, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
When testing #2638 and #2650 in real live, I noticed several issues that are fixed in this PR:
- The asset-syncer needs to be adapted for the case in which a `.dockerconfigjson` is passed
- When validating a repository that has a `.dockerconfigjson` linked, it's necessary to specify its namespace (before, the kubeapps namespace was being used)
- When accessing a secret `.Data`, this data is already converted from base64 (there is no need to do it again).
- The docker credentials secret was not being properly copied to the `kubeapps` namespace for the sync job to use it.
=> Several fixes to reuse docker reg creds

cmd/asset-syncer/postgresql_db_test.go, cmd/asset-syncer/postgresql_utils.go, cmd/asset-syncer/postgresql_utils_test.go, cmd/asset-syncer/sync.go, cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go, go.mod, pkg/dbutils/postgresql_utils_test.go
This is a workaround for the second item at #2425. The goal is to reduce the amount of time that takes for an OCI repository to be available through the UI since the user submits it. Ideally, chart versions should be introduced one by one in the database, first starting with the latest version of each chart. Since that'd require to change the database schema (and I don't have time for that this week), I propose to do a shallow sync of the repository (only adding the latest version of each chart), store that in the database and then do a full sync (including all versions).
Saves a considerable amount of time for the user. In this example, a user of this repository of 55 applications, can start using the repository after 4 min (for a total sync of 10 min):
```
time="2021-04-13T11:49:37Z" …
```
=> Run a shallow sync the first time a repository is processed

dashboard/package.json, dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx, dashboard/src/components/DeploymentForm/DeploymentForm.tsx, dashboard/src/moniker-native.d.ts, dashboard/yarn.lock
After some users reported some inappropriate names being generated by our generator (Moniker), I performed a quick review of replacement alternatives. Even if some of them have dictionaries with appropriate words, there is still a chance of having an unlikely bad combination.
After an internal discussion, we decided to drop the autogeneration feature, as also Helm 3 did. 
No more unfortunate combinations of autogenerated release names.
Users will no longer have an autogenerated name, so they will have to come up with one.
- fixes #2570
- fixes #2649
We have the frontend validation:
As well as the backend one:
=> Remove name auto-generation of release names

cmd/asset-syncer/postgresql_db_test.go, cmd/asset-syncer/postgresql_utils.go, cmd/asset-syncer/postgresql_utils_test.go, cmd/asset-syncer/sync.go, cmd/asset-syncer/utils.go, integration/use-cases/01-add-multicluster-deployment.js, integration/use-cases/04-default-deployment.js, integration/use-cases/05-missing-permissions.js, integration/use-cases/07-upgrade.js, integration/use-cases/lib/utils.js
Context at https://github.com/kubeapps/kubeapps/pull/2677#discussion_r612942869
So I tried to handle the error when getting the latest checksum but when running the e2e tests, a new error appeared:
```
time="2021-04-15T09:08:58Z" level=fatal msg="pq: relation \"repos\" does not exist"
```
Rather than adding another exception, I left the code as it was before (ignoring the error). In any case, that operation (checking the last checksum) is not critical for the rest of the process.
[EDIT]
Seems that the CI was misbehaving yesterday? #2680 was also merged with a green but the e2e tests require some adaptation to type down the name of the releases. Fixed that as well here.
Fixes master
I merged it because I saw a green in #2677 but it seems that I clicked in the interval before the e2e tests …
=> Ignore errors when syncing and fix e2e tests

integration/use-cases/lib/utils.js
As some CI checks are still failing, it seems that changing the default `.wait` strategy could benefit the reliability of the tests. 
This PRs should reduce the amount of  `Execution context was destroyed, most likely because of a navigation.` we receive.
N/A
N/A
N/A
=> Improve wait strategy during ci login

docs/user/using-an-OIDC-provider-with-pinniped.md, script/deploy-dev-for-pinniped.mk
This PR brings two main changes: i) adds a section in the docs on how to install kubeapps with OIDC using the pinniped impersonation proxy; ii) changes the Pinniped download endpoints to match their official docs (and defaults to `latest` instead of sticking to a certain version)
Users will be able to (know how to) install Kubeapps in managed clusters.
N/A
- fixes #2691
Currently, there is an open issue (https://github.com/kubeapps/kubeapps/issues/2692) that prevents users from using Kubeapps if using this guide in a single-cluster environment.
=> Docs: installing kubeapps with OIDC using the pinniped impersonation proxy

dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.test.tsx, dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.tsx
Well... it seems the rollback form was broken and the unit test was not covering the `<select>` change, so we supposed everything was working fine when we (I, indeed) changed the form/modal to the new cds one.
Rollback now will work again
N/A
- fixes #2697
N/A
=> Fix rollback html event handling

chart/kubeapps/templates/kubeops-deployment.yaml, chart/kubeapps/values.yaml, cmd/kubeops/internal/handler/handler.go, cmd/kubeops/main.go, pkg/http-handler/http-handler.go, pkg/http-handler/http-handler_test.go, pkg/kube/fake.go, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
Signed-off-by: Marcin Gucki <mgucki@coreweave.com>
This change refers to #2506 and allows passing namespaces in the header. The name of the header field and its value are defined by 2 environment variable:
- `KUBEAPPS_NAMESPACE_HEADER` - the name of the header field, e.g. `X-Consumer-Groups`
- `KUBEAPPS_NAMESPACE_PATTERN` - defines regular expression with the single matching group for the namespace name, e.g. `namespace:([\w-]+)`
For 2 namespaces, the header may look like this: `X-Consumer-Groups: namespace:ns1, namespace:ns2`.
It prevents looping over all namespaces in the cluster.
We have too many namespaces and even with parallel workers it takes too long and the number of namespaces is still growing.
The additional header will be injected by our API gateway. This way Kubeapps will …
=> Add namespaces filtering in header

cmd/apprepository-controller/main.go
Just noticed some inconsistency in the name being documented and the actual var. Fixed that and noted the feature gate requirement.
=> Update docstring for the ttl-lifetime-afterfinished-job

cmd/kubeops/internal/handler/handler.go, dashboard/src/shared/url.ts, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/http-handler/http-handler.go, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
As per the discussion in https://github.com/kubeapps/kubeapps/issues/2692#issuecomment-822940480, this PR allows using the inCluster configuration if no clusters have been configured.
Specifically, it will allow configurations like this one, when we prevent users from deploying apps in the cluster in which Kubeapps has been installed on.
```yaml
clusters:
- name: target-cluster
apiServiceURL: url
isKubeappsCluster: false
```
This PR now simply brings three changes (+ tests)
- Make `GetAppRepoAndRelatedSecrets` use the asSVC if `isKubeappsCluster && (nonUIKubeappsCluster || isGlobalAppRepository) `. 
- Make `NewClusterConfig` use the `inCluster` config if the cluster is empty.
- Make `getSvcClientsetForCluster` use the asSVC approach if the cluster is empty.
Furthermore, as a result of the …
=> Assume inCluster config when no cluster is passed 

integration/use-cases/02-create-private-registry.js
Add try/catch to prevent CI to fail in master when testing the latest released version (which does not have the UI change)
CI will work on master
N/A
N/A
This change should be reverted once we got the new release since it's no longer necessary.
=> Add try/catch in CI test to check the latest released version

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.tsx, dashboard/src/reducers/repos.test.ts, dashboard/src/reducers/repos.ts, dashboard/src/shared/Secret.ts, dashboard/src/shared/url.ts
We were requesting all the secrets in a namespace when listing the app repositories. This was for later on, being able to render secrets associated to a repo or to select some docker registry credentials. This PR changes that:
- The request is now done only when rendering the new/edit repo form.
- We are listing only docker registry secrets
- We are getting just the secret associated to a repository (when editing it).
- fixes #1686 
If you request some changes, I will eventually come back to this and address your comments :)
=> Limit secret requests when listing app repositories

script/chart_sync_utils.sh
Minor curl fix in the replaceImage script to pass properly the token so that we won't rate-limited
Not that much... just avoiding getting rate-limited if you're debugging the script
N/A
N/A
I gues we are gonna remove this script soon, so it will be just an ethereal ephemeral change :P
=> Minor curl fix in the replaceImage script

.circleci/config.yml, README.md, chart/kubeapps/README.md, docs/developer/ci.md
This PR removes the sync_chart job in our CI and clarifies that the we are using the bitnami chart as the official one. 
The chart will no longer be pushed to the bitnami/repo, we are now in charge of sending the PR to the repo once we detect changes in the chart.
We have to come up with a way to systematically update the chart, if not, some inconsistencies may appear.
- fixes #2704
I've commented the code instead of removing it in case we later go ahead with this idea: https://github.com/kubeapps/kubeapps/issues/2704#issuecomment-829080612
=> Disable sync_chart

docs/user/using-an-OIDC-provider-with-pinniped.md
As pointed out offline by the Pinniped folks, we should use the `CredentialIssuer` in our docs (instead of referring users to svc and secrets directly).
Docs will no longer be coupled to a given `svc` and `secret` names and they will be more Pinniped-compliant.
N/A
N/A
N/A
=> Use the credentialissuer in the pinniped docs

dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.test.tsx, dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.tsx
The value was being set to `currentRevision -1`  and later being updated with the value of the `onChange` event. If the user wouldn't change the selected option, the event wouldn't trigger and, therefore, the revision value was totally wrong.
This PR checks the user input and relies on the react hooks to manage the lifecycle.
Rollbacks with a single revision will work again.
N/A
- fixes #2760
N/A
=> Fix rollback form

docs/user/using-an-OIDC-provider-with-pinniped.md
Fixing a wrong link in the oidc debug docs.
The link will point to somewhere :P 
I can't think of a more harmless PR than this one.
N/A
N/A
=> Fix wrong link in docs

.circleci/config.yml, docs/developer/ci.md, docs/developer/release-process.md, script/PR_external_chart_template.md, script/PR_internal_chart_template.md, script/chart_sync.sh, script/chart_sync_utils.sh, script/chart_upstream_checker.sh, script/create_release.sh, script/release_utils.sh
This PR brings an automated way to fetch changes from the Bitnami chart and, analouglsy, send our changes back to them,
All the process is being done through pull requests; however, push access is still needed just to avoid creating our own bitnami/chart fork.
The synchronization process will be full-duplex automatic :)
The process assumes a linear series of events: for instance, multiple ongoing PRs are not supported.
So, what is expected is:
- Perfect sync
- Push to master: no new chart version
- Bitnami update some images
- Push to master: pull changes from bitnami (via PR)
- New PR: kubeapps accepts it
- Push to master: no new chart version
- Kubeapps perform some changes in the chart
- Kubeapps release: push changes to bitnami (via PR)
- Bitnami accepts the PR
- Kubeapps got released …
=> Automatic chart syncing in CI

.github/dependabot.yml, docs/developer/release-process.md
This PR updates the current dependabot config to also upgrade our integration deps periodically. The release process docs have also been updated accordingly
The bot will send PRs for the integration dependencies as well. We no longer will get notified about security issues in these deps (though they are not part of the kubeapps code itself).
Please note the integration image is *not* being created automatically. According to our release process, this image might be updated when releasing a new kubeapps version. **Direct consequence:** the current code in the main branch won't match the actual code in the image container image.
Alternatives:
A) We just assume the integration image won't match the declared dependencies in the main branch. They eventually sync once we release a new Kubeapps …
=> Add integration dependabot

script/chart_sync_utils.sh
Minor CI hotfix to check if the remote branch exists prior to perform a `git push`. 
Builds in master will no longer fail if we:
1. Have an open PR bumping the chart version
2. Push any commit to master
N/A
N/A
N/A
=> Check if remote branch already exists to prevents git push failures

.dockerignore, cmd/apprepository-controller/Dockerfile, cmd/assetsvc/Dockerfile, cmd/kubeops/Dockerfile, cmd/pinniped-proxy/.dockerignore, cmd/pinniped-proxy/Dockerfile
Noticed while adding a Dockerfile that we were still referring to the experimental (unversioned) docker frontend even though the buildkit support (for which it was added) graduated into 1.2.
Stay on a stable API.
Let's see what CI says.
=> Update dockerfile frontend to 1.2, buildkit support graduated from experimental

chart/kubeapps/templates/_helpers.tpl, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeappsapis/rbac.yaml, chart/kubeapps/templates/kubeappsapis/service.yaml, chart/kubeapps/templates/kubeappsapis/serviceaccount.yaml, chart/kubeapps/values.yaml, cmd/kubeapps-apis/Dockerfile, docs/developer/manifests/values.dev.yaml, docs/user/manifests/kubeapps-local-dev-values.yaml
Follows #2805. Adds the chart templating to deploy the kubeapps-apis service behind a feature flag.
Note that the local dev env is currently broken due to the upstream Kubeapps chart changes which we synced. I'll deal with that in a separate PR, but with this current change I'm able to deploy Kubeapps, port-forward the service, then curl it with:
```
curl http://localhost:8080/core/plugins/v1alpha1/configured-plugins
{"plugins":["foobar.package.v1"]}
```
Easier testing and further development of the kubeapps-apis service.
None that I see.
- Ref: #2773
I've not updated the main values.yaml with all the options so as to avoid the auto-documentation of those in the upstream published chart when we merge. Instead, I've put them in a `docs/developer/manifests/values.dev.yaml` that I'll include …
=> Add dev-only deployment of kubeapps-apis

script/chart_sync_utils.sh
Follow up of https://github.com/kubeapps/kubeapps/pull/2802. This PR slightly changes the condition used in the `if` statement. It wasn't able to recognize if the branch doesn't exist.
We will get new chart PRs again
N/A
N/A
=> Fix CI: check existing remote branch condition

chart/kubeapps/templates/kubeappsapis/rbac.yaml, cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/Makefile, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, docs/developer/manifests/values.dev.yaml, script/deploy-dev.mk
Adds the implementation for the kapp_controller plugin's GetAvailablePackages endpoint.
While port-forwarding to the kubeapps-apis service with
```
kubectl -n kubeapps port-forward svc/kubeapps-internal-kubeappsapis 8080:8080
```
http endpoint responds with:
```
curl -s http://localhost:8080/kapp_controller/packages/v1alpha1 | jq .
{
"packages": [
{
"name": "app1.example.com",
"version": "0.11.3",
"iconUrl": "",
"repository": null
},
{
"name": "app2.example.com",
"version": "3.11.3",
"iconUrl": "",
"repository": null
},
```
while with grpcurl:
```
grpcurl -plaintext localhost:8080 kubeappsapis.plugins.kapp_controller.packages.v1alpha1.PackagesService.GetAvailablePackages
{
"packages": [
{
"name": "app1.example.com",
"version": "0.11.3"
},
{
"name": "app2.example.com",
"version": "3.11.3" …
```
=> Add implementation for kapp-controller GetAvailablePackages.

.circleci/config.yml, script/chart_sync_utils.sh, script/chart_upstream_checker.sh
This PR tries to solve a lack of permission issue since the default ssh key loaded is not valid for the forked repository.
At the same time, I've extracted the ssh-related params to CI variables, as passing manually the values is so error-prone
Syncing charts working... hopefully
N/A
N/A
An alternative is to define "labeled" host like:
```
Host github-as-kubeappsbot
HostName github.com
User git
IdentityFile ~/.ssh/id_rsa.xxxxx
IdentitiesOnly yes
```
But since we just need permission for pushing, it's clearer to just pass the key explicitly
=> Pass additional ssh key to the script. Extracted ssh values to global ci vars

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Establish a pattern for testing with the dynamic k8s client in plugin code.
We'll have a pattern to follow and improve on when adding further code.
N/A
- Ref #2849
=> Example of unit-testing with dynamic client.

docs/step-by-step/kubeapps-on-tkg/step-2.md, docs/user/using-an-OIDC-provider.md
For long time, we have been relying on the oidc autodiscovery feature, which is great. However, there are scenarios where it is not possible -the CSP case- . So, this PR is to stop recommending using  `--insecure-oidc-skip-issuer-verification` in favor of a manual configuration, as follows:
```yaml
- --skip-oidc-discovery=true
- --oidc-issuer-url=https://gaz.csp-vidm-prod.com
- --login-url=https://console.cloud.vmware.com/csp/gateway/discovery
- --redeem-url=https://console.cloud.vmware.com/csp/gateway/am/api/auth/token
- --oidc-jwks-url=https://console.cloud.vmware.com/csp/gateway/am/api/auth/token-public-key?format=jwks
```
Instead of:
```yaml
- --insecure-oidc-skip-issuer-verification=true
- --oidc-issuer-url=hhttps://console.cloud.vmware.com/csp/gateway/am/api
```
No more "insecure" …
=> Replace insecure-oidc flag with the manual oidc config

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/_helpers.tpl, chart/kubeapps/templates/frontend/configmap.yaml
This PR simply adds (if the feature flag is enabled) the current kubeapps-apis behind the nginx reverse proxy. This way, we can pass through the authentication token as in the rest of the services.
Besides paving the way for #2851, it also allows using the API without any port-forwarding. 
Note that -currently- it uses a privileged SA to list everything, but it is not a production-ready thing and we soon change are changing it to use the user's credentials, it's not a big deal.
N/A
I hope to be sending the auth PR soon :S
=> Add kubeappsapis behind nginx

script/libtest.sh
This PR tries to fix the current `k8s_wait_for_deployment` function behavior used in CI. When the status is `Terminating` it just exits without considering the timeout. In a previous attempt, we added an additional fallback attempt, but it seems it's not enough.
Example: see how it's terminating, after 10 grace seconds it tries to get the status and finally it errors (with just 2 deployments left).
```console
TEST SUITE: None
INFO  ==> Waiting for Kubeapps components to be ready (local chart)...
INFO  ==> Rollout exit code: '1'
INFO  ==> Retrying after 10s...
NAME                                                             READY   STATUS        RESTARTS   AGE
kubeapps-ci-65bbf5db54-j27zv                                     2/2     Terminating   0          21s …
```
=> Improve k8s_wait_for_deployment

.circleci/config.yml, script/chart-template-test.sh, script/libtest.sh
Follow up of #2950. After analyzing the root cause (besides the lack of enough time to terminate/create the pod), it was a silly issue with the template (I always forget Helm doesn't have lazy evaluation...). The problem is that our CI was unable to catch this error since Helm 3.1 wasn't returning any information or errors.  
This PR performs two changes: a) minor change in the logic introduced in #2950 (silly typo in the counter variable name...); b) installing a new helm version (latest stable) available at `helm-stable` just for performing an additional `helm template` check to avoid these errors. 
N/A
N/A
Example of the former bug being caught: https://app.circleci.com/pipelines/github/antgamdia/kubeapps/590/workflows/ee637b9f-8426-4db2-b87c-78eb1ef184d5/jobs/4006
=> Fix Helm template CI check

dashboard/src/actions/namespace.test.tsx, dashboard/src/actions/namespace.ts
We had an unhandled null in the `fetchNamespaces` action; this PR simply adds a check to display the proper error message back to the user
No more "cannot read property .map from undefined"  ugly errors : )
N/A
- fixes #2956
N/A
=> Fix a null pointer in fetchNamespaces

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeappsapis/service.yaml
Just a follow-up from a [discussion on a previous PR](https://github.com/kubeapps/kubeapps/pull/2819#discussion_r634193991).
It is clear from the k8s config that the port is used for both http and grpc.
=> Update port name for kubeapps-apis to be clear it includes both grpc and http.

.github/dependabot.yml
This PR simply distributes the dependabot checks in 1-hour intervals so that the CI doesn't get exhausted.
(The default behavior is to check everything at 05:00 UTC)
Ci will handle the eventual PRs better
N/A
N/A
For the record, the first check begins at 10am (AUS)/ 2am (ES, dst)
=> Distribute dependabot checks

chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeappsapis/service.yaml
I didn't check the label change with a deploy, can't use underscores.
I'm testing this in a deploy now and won't land it unless it works (since we don't have CI testing kubeappsapis yet).
Can deploy in dev again.
None (assuming it works as advertised).
=> Fix non-alpha label for port

cmd/kubeapps-apis/Dockerfile
This PR adds the `buf lint` command in the Dockerfile. To do so, it installs the `buf` binary and then install the go deps, this way, we have fetched all the required deps before running the `lint` command.
We will detect errors at build time (and, therefore, the CI will eject if a build error is thrown)
N/A
- fixes #3016
N/A
=> [kubeapps-apis] Add buf lint in dockerfile

cmd/assetsvc/handler.go, cmd/assetsvc/handler_test.go, cmd/assetsvc/main.go, cmd/assetsvc/postgres_db_test.go, cmd/assetsvc/postgresql_utils.go, cmd/assetsvc/postgresql_utils_test.go, cmd/assetsvc/utils.go
Potential prequel for #3022, so that the plugin can just export the required manager and functions from the existing code.
Just does:
-  Public interface `assetManager` -> `AssetManager` (interface is just because we transition from mongo and supported both implementations for a while).
-  Public NewPGManager
-  Public PostgresAssetManager. (woops, I'll add a commit with this in a bit).
-  Public methods on the postgres asset manager
Let's Antonio focus on 3022
?
- Ref #2993
=> Update the postgresql asset manager to be publicly exported.

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/server/plugins.go, cmd/kubeapps-apis/server/plugins_test.go
As per discussion on #3022, we originally tried the typed client for interacting with packaging CRs but hit the issue that we'd need the same version of client-go used by those packaging systems, which leads to dependency hell. So we switched to use a dynamic client for the plugins.
That said, now that certain plugins also need to interact with the core k8s api resources, a typed client(set) would also be useful (and nicer to work with) for interacting with those core resources.
This PR updates so that plugins are provided with both - a type clientset and a dynamic clientset.
Plugins don't need to use unstructured objects when interacting with the core k8s resources.
None (assuming the client works IRL, which we'll test in a subsequent PR that uses the typed client for the direct helm …
=> Add typed client to plugin client getter.

.circleci/config.yml
This PR simply disables the GKE testing each time we push to master. Instead, it will only run when tagging a new release.
No more (so frequent) CI errors.
Code takes more time to be tested in GKE, but with the multicluster env in Kind we are spinning up, I think is enough. 
N/A
N/A
=> Remove GKE on master in CI

cmd/apprepository-controller/controller.go, cmd/apprepository-controller/controller_test.go, cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go, cmd/asset-syncer/main.go, cmd/asset-syncer/utils.go, cmd/asset-syncer/utils_test.go, dashboard/public/openapi.yaml, dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx, dashboard/src/shared/AppRepository.ts, dashboard/src/shared/types.ts, pkg/kube/kube_handler.go
This PR adds a similar change as the Helm folks did in https://github.com/helm/helm/commit/179f90151d5ecb4aa3d35ada35e82b5c1e791752
Now, the credentials will be passed to an external URL if: 1) a user adds `pass-credentials` to the repo OR 2) the domain in the chart index.yaml file matches the icon/tarball domain.
Not passing credentials to external domains (such as icons and tarballs)
If users don't explicitly decide to allow passing the credentials, in scenarios when the index.yaml URL doesn't match the icon/tarball URL domain, the credentials won't be passed through anymore.
- fixes #2136
More testing is required, I feel the mock clients we use here are not enough to make sure we are doing it right.
=> Improve credentials handling when fetching repo resources

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/pinniped.rs
upgraded kube crate from version 0.55.0 to 0.57.0.
refactored code for backward incompatible changes
upgraded to new version to use dynamic kube objects
none
issue #2695: Allow configuring pinniped-proxy with per-cluster namespace and suffix
=> bumped kube version

integration/use-cases/08-rollback.js, script/e2e-test.sh
In the rollback test, we were performing the rollback action prior to check if the app was fully deployed. It caused some inconsistencies; especially, the rollback dialog showed "loading, please wait". Wherefore the expected text never appeared.
This PR is for checking the app is fully deployed and the rollback dialog is loaded before checking the revision version.
Every time the tests passed... it was like planet conjunction :P
The CI (should) pass again.
N/A
N/A
N/A
=> CI - Fix rollback test

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
Adds and tests pagination for direct helm plugin's GetAvailablePackageSummaries request.
- Ref #2993
=> Add pagination for direct-helm get summaries.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/proto/kubeappsapis/core/packages/v1alpha1/packages.proto, cmd/kubeapps-apis/proto/kubeappsapis/plugins/helm/packages/v1alpha1/helm.proto
Adds the implementation for GetAvailablePackageVersions for the direct helm plugin.
IRL example:
```
$ grpcurl -plaintext -d '{"available_package_ref": {"context": {"namespace": "kubeapps"}, "identifier": "bitnami/apache"}}' localhost:8080 kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.GetAvailablePackageVersions
{
"packageAppVersions": [
{
"pkgVersion": "8.5.7",
"appVersion": "2.4.48"
},
{
"pkgVersion": "8.5.6",
"appVersion": "2.4.48"
},
{
"pkgVersion": "8.5.5",
"appVersion": "2.4.48"
},
{
"pkgVersion": "8.4.2",
"appVersion": "2.4.46"
},
{
"pkgVersion": "8.4.1",
"appVersion": "2.4.46"
},
{
"pkgVersion": "8.4.0",
"appVersion": "2.4.46"
},
{
"pkgVersion": "8.3.2",
"appVersion": "2.4.46"
},
{
"pkgVersion": "8.3.1",
"appVersion": "2.4.46"
},
{
"pkgVersion": "8.3.0", …
```
=> Add GetAvailablePackageVersions implementation for direct-helm

.github/stale.yml, docs/developer/issue-triage-process.md
Update the stale bot to increase the frequency of issues marked as stale to 15 days (the standard Kubeapps iteration cycle). The issue triage documentation is also updated to be aligned to these changes.
These changes will contribute to keep a cleaner board without outdated issues. It is also the goal to foster Kubeapps maintainers and contributors to provide more frequent feedback/confirmation to open issues.
Increase the revision of issues marked as stale.
- fixes #3088 
N/A
=> Update stale bot frequency

Makefile, dashboard/src/components/Header/Menu.tsx
This simple PR just:
1) Rename `bitnami` by `vmware`.
2) Add `pinniped-proxy` and `kubeapps-apis` to the makefile target.
N/A
N/A
N/A
N/A
=> Minor rename and makefile edit

.circleci/config.yml
Due to the changes in https://cloud.google.com/kubernetes-engine/docs/release-notes, the 1.17 version is not supported and it's making our CI (for releasing) fail.
This PR is updating it to 1.18 and 1.19
N/A
N/A
N/A
N/A
=> Update CI GKE versions to 18 and 19

CONTRIBUTING.md
Since we say in the CONTRIBUTING.md guidelines that we require DCO sign-off on all commits, I've added the DCO bot to check PRs.
This update just has a little extra info to help when people find they need to do sign-off retrospectively, as well as ensuring it's in all commits for the project if they want.
Avoid frustration with DCO sign-off.
None that I can see.
=> A little extra help since we're requiring signed-off commits

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/server/plugins.go, cmd/kubeapps-apis/server/plugins_test.go
Originally we passed plugins a client getter that return a dynamic
client. We then found that the helm plugin additionally needs a typed
client, so updated the client getter to return both. For work that I'm
currently doing instantiating a helm API action configuration, I also
need the plugin to have access to a genericclioptions.RESTClientGetter.
Rather than updating the existing client getter to return yet another
type, and given that it's a single line to create a client from the rest
config, I'm instead updating so that plugins are initialised with an
initialized rest.Config getter so that they can create any client they
need while still not needing to know any details of the config (eg.
pinniped setup or similar).
I can continue with the helm work, using the config to create a …
=> Update so plugins are passed a rest.Config getter rather than a client getter

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
Adds the implementation for GetInstalledPackageSummaries for the Helm plugin.
I'll do a follow-up PR that adds the LatestPkgVersion field as well.
IRL test:
```
grpcurl -plaintext -d '{"context": {"namespace": "kubeapps"}}' localhost:8080 kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.GetInstalledPackageSummaries
{
"installedPackagesSummaries": [
{
"context": {
"namespace": "kubeapps"
},
"identifier": "chartmuseum"
},
"name": "chartmuseum",
"pkgVersionReference": {
"version": "2.14.2"
},
"currentPkgVersion": "2.14.2",
"iconUrl": "https://raw.githubusercontent.com/helm/chartmuseum/master/logo2.png",
"pkgDisplayName": "chartmuseum",
"shortDescription": "Host your own Helm Chart Repository"
},
{
"context": {
"namespace": …
```
=> Add implementation for GetInstalledPackageSummaries.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
Although we'd added AvailablePackageSummary.Name to the messages (after
switching to use an Identifier in the reference), we hadn't yet populated
it.
Related to discussion at https://github.com/kubeapps/kubeapps/issues/3165#issuecomment-883812172
=> Populate AvailablePackageSummary.Name

dashboard/src/components/Header/ContextSelector.test.tsx, dashboard/src/components/Header/ContextSelector.tsx
Adds a condition to enable or disable change context button based on current clusters and namespaces.
Improves user experience by not allowing to switch context while no namespace is selected.
None.
Fixes #2723.
https://user-images.githubusercontent.com/43246350/126552562-ffbe026f-b57c-406d-acde-6c8708d8ed44.mp4
Still working to implement a test.
=> Enable or disable change context button based on clusters and namespaces

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
```
grpcurl -plaintext localhost:8080 kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.GetInstalledPackageSummaries
...
{
"context": {
"namespace": "default"
},
"identifier": "test-apache"
},
"name": "test-apache",
"pkgVersionReference": {
"version": "8.5.8"
},
"currentPkgVersion": "8.5.8",
"iconUrl": "https://bitnami.com/assets/stacks/apache/img/apache-stack-220x234.png",
"pkgDisplayName": "apache",
"shortDescription": "Chart for Apache HTTP Server",
"latestPkgVersion": "8.5.9"
}
```
Includes the latest package version, so that the UI can present when upgrades are available.
- Ref #3146
=> Include the latest package version in the installed pkg summaries.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
Antonio recently landed changes for more consistent naming, and I landed my PR which added new tests using the old names and didn't merge the latest changes on master before landing. So the code itself was updated correctly, but the new tests that I wrote kept the incorrect naming.
CI passing again on master.
None
I'll rubber-stamp this one to get CI passing again.
=> Fix merge of my PR which wasn't updated after renames

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeappsapis/rbac.yaml, cmd/kubeapps-apis/Dockerfile, docs/developer/manifests/values.kubeappsapis.yaml, script/deploy-dev.mk
I noticed that currently we were always loading all plugins with no option to enable individual ones.
Given that we're planning to release initially with only the helm plugin enabled, this change updates to allow enabling specific plugins, defaulting to the helm one.
I've also updated the dependencies in the Chart.yaml, so that we don't accidentally update the upstream chart with the redis dependency.
Finally, I've set the replicaCount for redis in dev to zero (similar to what we do for postgres). Let me know if this is an issue Greg.
Upstream changes to our chart (whether by us or the content team) should include only the helm plugin for now.
None
I'll annotate in line for anything I missed here.
=> Update to enable individual plugins for apis server

chart/kubeapps/templates/kubeappsapis/deployment.yaml, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
As Greg pointed out, the existing code was using what appear to be no-longer-used fields on the model.
This PR updates to request the chart files from the DB and use those instead.
I'll follow-up with a PR to remove the code which is no longer being used.
IRL:
```
grpcurl -plaintext -d '{"available_package_ref": {"context": {"namespace": "kubeapps"},"identifier": "bitnami/wordpress"}}' localhost:8080 kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.GetAvailablePackageDetail
{
"availablePackageDetail": {
"availablePackageRef": {
"context": {
"namespace": "kubeapps"
},
"identifier": "bitnami/wordpress",
"plugin": {
"name": "helm.packages",
"version": "v1alpha1"
}
},
"name": "wordpress",
"pkgVersion": "11.1.5",
"appVersion": "5.7.2",
"iconUrl": …
```
=> Add chart files to response for AvailablePackageDetail

chart/kubeapps/templates/frontend/deployment.yaml
We noticed there were some missing files under the `--skip-auth-regex` flag. This issue should be preventing the dark mode to work properly in unauthenticated calls. 
` .... GET - "/clr-ui-dark.min.css" HTTP/1.1 "....  403 .....`
No more 403 errors before authenticated.
N/A
N/A
N/A
=> Add missing files under "skip-auth-regex"

chart/kubeapps/README.md, chart/kubeapps/templates/dashboard/configmap.yaml, chart/kubeapps/values.yaml, dashboard/public/config.json, dashboard/src/actions/config.ts
Signed-off-by: Anthony Rizzo <36711320+aanthonyrizzo@users.noreply.github.com>
This PR adds the ability to overwrite the initial default theme for Kubeapps via a config value.
Allows for more control for theming and UX
If this value is set. Anytime a user reloads or refreshes, the theme is changed back to the default value, even if the user sets a different one. We can potentially add another value to local storage called `user_theme`, which is set by the theme toggle switch. And add logic there so if that value is present, ignore the config.theme value.
Fixes #3176
=> feat(dashboard): Add default theme value

dashboard/src/actions/config.test.tsx, dashboard/src/actions/config.ts, dashboard/src/components/HeadManager/HeadManager.tsx, dashboard/src/components/Header/Menu.test.tsx, dashboard/src/components/Header/Menu.tsx, dashboard/src/reducers/config.ts, dashboard/src/shared/Config.test.ts, dashboard/src/shared/Config.ts
After #3205 and #3191, we noticed we were overriding the theme config. It was the result of small improvements towards the dark mode and bug fixes along the way.
This PR is the first step at having a clearer logic on which theme preference takes precedence over another.
Currently: `user (via toggle)>system (via values.yaml)>browser (via browser config)>fallback (hardcoded light theme)`
It (should) paves the way to create other config parameters like "allowChangingTheme" or similar.
I've checked and I don't foresee any error... but UI can always fail OSI L8 actors are involved :P 
- fixes #3176
I've used the changes from #3191 as my base branch, all the credits should go for @aanthonyrizzo. I'm thinking of merging that PR and then this one? cc @absoludity 
Here is a demo: …
=> Improve theme switcher mechanism

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
Dimitri pointed out that the check on these seemed odd (why check ChartVersions at all?).
There's actually no need for checking whether chart.Maintainers is nil or not since nil is the zero value for arrays, a range of it results in nothing to iterate.
The existing tests in TestIsValidChart demo this already (examples with nil maintainers).
I'm not yet sure about sharing code between plugins, so for now haven't dealt with that (but more than happy if you want to have a go Dimitri).
Removes confusing code :)
None.
=> Remove unnecessary and incorrect check on maintainers.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
I had a test failure on a [CI run for another branch which failed](https://app.circleci.com/pipelines/github/kubeapps/kubeapps/3783/workflows/802eef40-a668-4f0a-a15a-5ebd95b07d10/jobs/54013) with:
```
--- FAIL: TestGetAvailablePackageSummaries (0.00s)
--- FAIL: TestGetAvailablePackageSummaries/it_returns_the_proper_chart_categories (0.00s)
server_test.go:855: mismatch (-want +got):
&v1alpha1.GetAvailablePackageSummariesResponse{
... // 3 ignored fields
AvailablePackageSummaries: {&{AvailablePackageRef: &{Context: &{Namespace: "my-ns"}, Identifier: "repo-1/chart-1", Plugin: &{Name: "helm.packages", Version: "v1alpha1"}}, Name: "chart-1", LatestPkgVersion: "3.0.0", LatestAppVersion: "1.2.6", ...}, &{AvailablePackageRef: &{Context: …
```
=> Fix test which depended on map key order.

integration/jest.environment.js, integration/use-cases/02-create-private-registry.js, integration/use-cases/03-create-registry.js, integration/use-cases/06-operator-deployment.js, integration/use-cases/07-upgrade.js, integration/use-cases/lib/utils.js
Also ensure a screenshot is created when logging in so the directory is
non-empty.
While trying to find out why CI isn't saving screenshots as artifacts anymore, I checked a build from a few months ago, and there I see the following in the Uploading Artifacts step log:
```
Uploading /home/circleci/project/integration/reports to integration/reports
Uploading /home/circleci/project/integration/reports/.notempty: SKIPPED, file is empty
Uploading /home/circleci/project/integration/reports/screenshots/upgrades-an-application.png (20 kB): DONE
```
whereas today, we see only the first two lines, implying that circle ci thinks there's nothing to upload.
This PR just adds some logging so we can test whether the directory we think we're writing to …
=> Add some logging when creating a screenshot.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
This PR removes the FilterOptions when returning all the distinct categories in a namespace, as per https://github.com/kubeapps/kubeapps/pull/3210#issuecomment-889540304
Fetching the charts will also fetch the categories (no duplicated requests) [in the new API]
N/A
N/A
N/A
=> [kubeappsapis] Ignore FilterOptions for the namespace categories

docs/user/getting-started.md
Updates "Getting Started" docs retrieve token example to use `--namespace default` flag. 
When creating a serviceaccount in previous section, it's also done with `--namespace default` flag in case user is not in the `default` namespace context. By adding the namespace flag, users in different context can copy and paste the shell example otherwise they'll receive this error:
```shell
» kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token                                                                                                          
Error from server (NotFound): serviceaccounts "kubeapps-operator" not found
```
n/a
=> docs: add namespace flag for retrieve token example

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, script/deploy-dev.mk
Adds implementation for GetInstalledPackageDetail.
The response includes the release values, notes and a ref to the available package for further details about the available package:
```
$ grpcurl -plaintext localhost:8080 kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.GetInstalledPackageSummaries                                                                                               {
"installedPackageSummaries": [
...
{
"context": {
"namespace": "default"
},
"identifier": "test-apache"
},
"name": "test-apache",
"pkgVersionReference": {
"version": "8.5.8"
},
"currentPkgVersion": "8.5.8",
"currentAppVersion": "2.4.48",
"iconUrl": "https://bitnami.com/assets/stacks/apache/img/apache-stack-220x234.png",
"pkgDisplayName": "apache", …
```
=> Add GetInstalledPackageDetail implementation.

.circleci/config.yml, docs/user/manifests/kubeapps-local-dev-dex-values.yaml, integration/use-cases/lib/utils.js, script/deploy-dev.mk
I updated my local kind installation (to v0.11.1, so supporting k8s 1.21) only to find that it breaks the dev env.
The reason is a change in 1.21 which results in the version of dex we were using crash-looping.
Since we were using the deprecated (and no longer updated) stable repo for dex, I updated to the current dex chart repo and got things working with the latest version of that chart instead.
Dev environment works with k8s 1.21.
Updated dex version (only visible difference is that it now lets the user choose to grant the email scope).
None that I can think of.
=> Update to support k8s 1.21 requiring dex update.

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/server/plugins.go, cmd/kubeapps-apis/server/plugins_test.go
Updates the KubernetesConfigGetter function alias to accept the cluster as an arg.
It uses this to return a config for the specified cluster, but defaults to the current behaviour of the cluster on which Kubeapps is running.
Tests that the correct config is created depending on the clusterConfig.
This is step 1 in being able to match the existing cluster support but with the new APIs server (for Helm).
- Ref #3278
The following PR will add support for the Helm plugin to reply sanely for requests to other clusters, while leaving the other plugins using the default behaviour for now.
=> Update server.KubernetesConfigGetter to support cluster arg

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go, cmd/kubeapps-apis/server/plugins.go
This PR updates the GRPC registration function for plugins so that it receives the clusters configuration. This enables plugins to make decisions based on the clusters configuration, which is required for the Helm plugin as it behaves slightly differently for the cluster on which Kubeapps is installed.
Even though the Helm plugin only requires the kubeapps cluster name, I've passed the complete config for generality... perhaps we should just pass the kubeapps cluster name for now (though that makes assumptions about other plugins later needs).
It then updates the Helm plugin so that:
* Requests for packages available in a namespace of other clusters only ever returns the global available packages (ie. those from the kubeapps namespace on the kubeapps cluster), and
* Requests for installed …
=> Support multi-cluster with helm plugin

cmd/kubeops/internal/handler/handler.go
The Create operation was fixed in a previous commit to allow creation of apps on a remote cluster from a global repository.
The fix was not applied to the Upgrade operation and as such upgrading an app deployed on a remote cluster was failing.
The change is applying the same fix made for Create onto Upgrade as well.
Upgrade of remote applications will not be possible.
none
Issue 3213
N/A
=> replicated fix previously made for create to upgrade as well

chart/kubeapps/templates/dashboard/configmap.yaml, chart/kubeapps/values.yaml, dashboard/public/config.json, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/CustomFormParam.test.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/CustomFormParam.tsx, dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx, dashboard/src/reducers/cluster.test.ts, dashboard/src/reducers/config.ts, dashboard/src/shared/Auth.test.ts, dashboard/src/shared/Config.ts, docs/developer/custom-form-component-support.md
This PR adds the ability for developers to load their custom components from a remote URL as an alternative to loading from the configmap. This is an optional value that can be set for the custom components feature. If the value is not set the `<CustomComponent />` will be pulled from the `custom_components.js` file.
- No longer worry about 1 MiB max configmap size
- Allows for easier version control of the form components (should that be needed)
- Bundle will have to be served from a remote host and will be the responsibility of the developer
=> feat(form): Allow remote loading for form components

dashboard/src/actions/apps.ts, dashboard/src/shared/Chart.ts
The change is to fix upgrade of apps when the charts does not provide an app version (optional field).
One change is to ensure that "undefined" is not sent as a filter value when querying the list of matching charts.
The other change is to remove the app version as a condition to render the AppUpgrade component.
Upgrade of apps with charts with no app version is now possible.
none
- fixes  #3253
This is the simplest change. The UI will most likely change once the new APIs are integrated.
=> fix upgrade for charts where the optional app version not specified

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
A small follow-on from the mechanical change in #3290 , populating the `InstalledPackageDetail.latestVersion`
In real life test:
```
$ grpcurl -plaintext -d '{"installed_package_ref": {"context": {"namespace": "default"}, "identifier": "test-apache"}}' localhost:8080  kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.GetInstalledPackageDetail
{
"installedPackageDetail": {
"context": {
"namespace": "default"
},
"identifier": "test-apache"
},
"pkgVersionReference": {
"version": "8.5.4"
},
"name": "test-apache",
"currentVersion": {
"pkgVersion": "8.5.4",
"appVersion": "2.4.46"
},
"valuesApplied": ...,
"status": {
"ready": true,
"reason": "STATUS_REASON_INSTALLED",
"userReason": "deployed"
}, …
```
=> Populate the `InstalledPackageDetail.LatestVersion` field.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
Signed-off-by: Antonio Gamez Diaz <agamez@vmware.com>
This PR simply fix a bug induced by a wrong order of the parameters in a function. 
I will be able to continue doing the UI revamp :P 
N/A
N/A
I'll rubber-stamp this PR as it is a trivial change.
=> [kubeappsapis] Fix wrong param order in a function

dashboard/tsconfig.json
`eslint` is using ES2020, but tsconfig was still in ES6. This PR is to make both versions match.
No ES versions mismatches.
Don't foresee any, but let CI confirm.
N/A
N/A
=> Match ES version in ts and eslint config

docs/user/manifests/kubeapps-local-dev-values.yaml
Tried to setup a dev env and it was not working because the ingress-nginx controller was claiming that the kubeaps ingress was invalid.
Turned out to be related to the update to use 1.0.0 of the ingress-nginx controller in our dev env, which requires the class to be set for the ingress to pass validation.
Dev env works again.
- fixes #
=> Fix development ingress to be valid with ingress-nginx 1.0.0

dashboard/src/shared/App.ts, dashboard/src/shared/Chart.ts, dashboard/src/shared/KubeappsGrpcClient.ts
One of the most difficult (yet satisfying to find the solution) bugs I've debugged in a long time :P
Our CI for the release was failing only for tests on GKE, but it turned out to be just because the GKE tests are the only ones which use token authentication.
Reproducing the issue locally was tricky at first, because it seemed to go away if you refresh the page (which explained some of the screenshots taken on CI which had errors at first, but passed on refresh).
The issue turned out to be that we were initializing the grpc clients when the app loads. Since there is no auth token present in local storage when the app loads and you're unauthenticated, the clients do not have any authentication metadata. If you re-load after authenticating, no issue. If you're configured with OIDC, this …
=> Don't cache clients that are created (without auth) when app loads.

dashboard/src/components/AppList/AppListItem.test.tsx, dashboard/src/components/AppList/AppListItem.tsx, dashboard/src/components/AppView/ChartInfo/ChartInfo.test.tsx, dashboard/src/components/AppView/ChartInfo/ChartUpdateInfo.tsx
As per the [Helm docs for the Chart.yaml](https://helm.sh/docs/topics/charts/#the-chartyaml-file), the appVersion field is not required to be semver at all.
I wonder whether we should assume this for package version as well. For Helm it's safe, but we can't base our decisions on Helm. Furthermore, it's already enough that the backend has indicated that the latest version is different to the current version, so I can't see why we need the semver check here in the frontend even for the package version.
Let me know and I'll update to remove it there also.
- fixes #3347
=> Fixes #3347 by not assuming semver for app version.

script/chart_sync_utils.sh
I assumed I already sent this PR, but while pruning my branches it seems I didn't.
This PR fixes an unnoticed rename we should perform to be able to push local chart changes to bitnami/charts again.
No more manual workarounds (last time I had to ssh into the circleci machine to trigger the PR :P )
N/A
N/A
N/A
=> Add a rename for auto chart sync

cmd/kubeops/internal/handler/handler.go, pkg/chart/chart.go, pkg/chart/chart_test.go
This is a spin-off change for supporting CreateInstalledPackage via the new kubeapps apis. I don't want the new kubeapps-apis to need to deal with the `kube.handler` abstraction, since our plugins don't even see the user token, nor should they need to know about them.
The RegistrySecretsPerDomain function depends on less code.
None known.
- ref #3146
=> Update chart.RegistrySecretsPerDomain to depend on kube clientset only.

dashboard/package.json, dashboard/src/components/AppList/AppListItem.test.tsx, dashboard/src/components/AppList/AppListItem.tsx, dashboard/src/components/AppView/ChartInfo/ChartInfo.test.tsx, dashboard/src/components/AppView/ChartInfo/ChartUpdateInfo.tsx, dashboard/yarn.lock
Follow-up PR from #3348. This PR is removing the `semver` for checking package updates. We should not assume every package is being semantically versionated
We will support any pkg versionning.
From now on, it is the backend package plugin that is currently in charge of returning the latest version.
N/A
N/A
=> Avoid using semver for check pkg updates

dashboard/src/shared/url.ts
Updates the kubeappsapis URL in the dashboard to be relative like all other endpoints.
See the related #3368  for details (and the related slack conversation). Herve found that if you use a subpath, then requests are not sent to the backend apis server. This can itself be reproduced in the local dev env with the diff on the issue repro steps, and is fixed by the one-line change here (to use a relative URL path).
Whether or not there is still an issue in Herve's environment once the paths are corrected in the dashboard remains to be seen.
Kubeapps can be deployed on a subpath again.
None that I can see.
- ref #3368
=> Ensure relative path is used for kubeappsapis so any subpath is included.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/create_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
Adds implementation for `CreateInstalledPackage` for the helm plugin.
```
$ grpcurl -plaintext -d '{"available_package_ref": {"context": {"namespace": "kubeapps"},"identifier": "bitnami/apache"}, "target_context": {"namespace": "default"}, "name": "apache-via-api"}' localhost:8080 kubeappsapis.plugins.helm.packages.v1alpha1.HelmPackagesService.CreateInstalledPackage
{
"context": {
"cluster": "default",
"namespace": "default"
},
"identifier": "apache-via-api",
"plugin": {
"name": "helm.packages",
"version": "v1alpha1"
}
}
}
$ k -n default get po
NAME                              READY   STATUS    RESTARTS   AGE
apache-via-api-6dbc85b48b-cdd56   0/1     Running   0          11s
```
One more piece we can switch over with the current helm support.
None that I'm aware …
=> Kubeapps-APIs implementation of helm create installed pkg 

cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
Ensures that the user-agent is set when fetching the chart from the bitnami repository with with something that can be used to query access logs for all requests from the kubeapps-apis server or from specific plugins or specific versions and builds of specific plugins.
As an example, after building the image with:
```bash
$ IMAGE_TAG=dev4 VERSION=test-version-from-env make kubeapps/kubeapps-apis
```
and loading and running, I see the following in the logs when creating a new installed package:
```
I0908 03:50:27.512904       1 server.go:841] +helm CreateInstalledPackage fetching chart "bitnami/
apache" with user-agent "kubeapps-apis/plugins/helm.packages/v1alpha1/test-version-from-env"
I0908 03:50:28.960310       1 plugins.go:114] +core GetConfiguredPlugins
I0908 03:50:38.960270       1 …
```
=> Add plugin-specific user-agent to kubeapps-apis helm plugin

.circleci/config.yml
After sketching up some diagrams, I noticed our CI has some steps wich aren't defined in the `requires` section. 
Example:
Not a real benefit, actually, but the dependencies that semantically makes sense are now defined as part of the CI config.
N/A
N/A
It seems to me that we have to do something with the `GKE_1_XX_zzzzzz` steps. The tests there were also flaky during the past release.
I'm thinking about having a named commit that makes CirlceCI trigger this workflow, something like "prerelease" or "prepare release". This way, we can safely execute the GKE test... without tagging a commit (an action that  automatically triggers the bitnami pipeline)
=> Add missing dependencies for CI steps

chart/kubeapps/Chart.lock, chart/kubeapps/templates/apprepository/apprepositories-secret.yaml, chart/kubeapps/templates/apprepository/apprepositories.yaml, chart/kubeapps/values.yaml
This PR adds the ability to specify the credentials to connect to a repository, e.g.:
```bash
helm install kubeapps bitnami/kubeapps -n kubeapps --create-namespace \
--set apprepository.initialRepos[0].name=local \
--set apprepository.initialRepos[0].url=http://localhost \
--set apprepository.initialRepos[0].basicAuth.user=<user> \
--set apprepository.initialRepos[0].basicAuth.password=<password>
```
=> Chart: add support for basic authentication on initial apprepositories

chart/kubeapps/README.md, chart/kubeapps/templates/ingress.yaml
This PR adds the changes proposed by @Mauraza at https://github.com/kubeapps/kubeapps/issues/3366#issuecomment-914392309 to fix the issue when rendering the Helm template.
Our chart will work again :P
N/A
- fixes #3366
We should commit these changes to the upstream chart repo as well.
=> Fix non-rendering chart if using `extraHost` or `extraPaths`

dashboard/src/components/LoadingWrapper/LoadingWrapper.scss, dashboard/src/components/LoadingWrapper/LoadingWrapper.tsx
While using Kubeapps I noticed a minor issue in dark mode when rolling back an application, but it resulted to be an issue with the LoadingWrapper text, which wasn't getting the proper css color variable.
Proper text color: 
N/A
N/A
N/A
=> Fix text color issue in dark mode

chart/kubeapps/templates/_helpers.tpl
Minor PR adding kubeappapis image to a couple of missing places in the chart.
If using pullsecrets for our chart images, they will also work for the kubeappsapis img
N/A
N/A
N/A
=> Add kubeappsapis img to the imagePullSecrets dict

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/server/packages.go
Follow-up PR based on https://github.com/kubeapps/kubeapps/pull/3376#discussion_r706962795
Less verbosity for just building a log msg
N/A
N/A
N/A
=> Use getters to avoid verbose nil checking

chart/kubeapps/templates/apprepository/deployment.yaml
This PR is just to pass the asset-syncer job image as an ENV var.
Kubeapps is closer to being built as a Carvel pkg.
N/A
- fixes #3401
If accepted, then sync with the Content team to check if any further changes are required in their internal tooling.
=> Pass asset-syncer img as an ENV var

integration/use-cases/07-upgrade.js
Same purpose as https://github.com/kubeapps/kubeapps/pull/3432, but relying on selectors and pseudoselectors instead. 
Triggering the CI to see if it works, if not, I'll debug in circleci cia ssh
The CI test will no longer depend upon a fixed set of versions, but instead, it will get the `latest` and `latest - 1` to perform the upgrade.
It will mask issues like #3339, but we'd better go with this approach so that our CI doesn't get stuck in a permanent failure.
- related #3339
- closes #3432
N/A
=> Use dynamic current and latest versions in test

cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/cmd/root.go, cmd/kubeapps-apis/cmd/root_test.go, cmd/kubeapps-apis/server/server.go
This PR adds the `--version` command to `kubeaps-apis`
Our binaries will properly display their version
N/A
- related #3429
```
DOCKER_BUILDKIT=1 docker build -t kubeapps/kubeapps-apis:dev --build-arg "VERSION=$(git rev-parse HEAD)" -f cmd/kubeapps-apis/Dockerfile .
docker run  docker.io/kubeapps/kubeapps-apis:dev ./kubeapps-apis --version
```
=> Add versions - kubeappsapis

cmd/kubeops/Dockerfile, cmd/kubeops/cmd/root.go, cmd/kubeops/cmd/root_test.go, cmd/kubeops/main.go, cmd/kubeops/server/server.go
This PR adds the `--version` command to `kubeops`
Besides, it also adapts the code to the latest cobra boilerplate, so that all of our binaries are similar.
Our binaries will properly display their version
N/A
- related #3429
Testing with:
```
DOCKER_BUILDKIT=1 docker build -t kubeapps/kubeops:dev --build-arg "VERSION=$(git rev-parse HEAD)" -f cmd/kubeops/Dockerfile .
docker run  docker.io/kubeapps/kubeops:dev ./kubeops --version
```
=> Add versions - kubeops

cmd/assetsvc/Dockerfile, cmd/assetsvc/cmd/root.go, cmd/assetsvc/main.go, cmd/assetsvc/pkg/utils/postgres_db_test.go, cmd/assetsvc/pkg/utils/postgresql_utils.go, cmd/assetsvc/pkg/utils/postgresql_utils_test.go, cmd/assetsvc/pkg/utils/utils.go, cmd/assetsvc/server/handler.go, cmd/assetsvc/server/handler_test.go, cmd/assetsvc/server/server.go, cmd/assetsvc/server/server_test.go
This PR adds the `--version` command to `assetsvc`
Our binaries will properly display their version
N/A
- related #3429
```
DOCKER_BUILDKIT=1 docker build -t kubeapps/assetsvc:dev --build-arg "VERSION=$(git rev-parse HEAD)" -f cmd/assetsvc/Dockerfile .
docker run  docker.io/kubeapps/assetsvc:dev ./assetsvc --version
```
=>  Add versions - assetsvc

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/Dockerfile, cmd/pinniped-proxy/build.rs, cmd/pinniped-proxy/src/cli.rs, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/pinniped.rs
This PR adds the `--version` command to `pinniped-proxy`
Our binaries will properly display their version
N/A
- related #3429
I have been also exploring [vergen](https://docs.rs/vergen/5.1.15/vergen/index.html), but it gives us much more build/git/etc env information than we need.
```
IMAGE_TAG=dev make kubeapps/pinniped-proxy && docker run  docker.io/kubeapps/pinniped-proxy:dev   --version
```
=> Add versions - pinniped-proxy

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/delete_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
Adds implementation for DeleteInstalledPackage.
Can switch UI to use this.
None (though haven't done in-real-life test yet).
- fixes #3146
Thanks Antonio for the upgrade of helm at some point, we can now use `errors.Is` (I'd wanted that a while back).
=> Implement delete installed package.

chart/kubeapps/templates/apprepository/apprepositories.yaml, chart/kubeapps/values.yaml
Allow filter rules to specified when creating Application Repositories from Helm.
=> Allow filter rules to be set on App Repositories

integration/use-cases/02-create-private-registry.js
Seeing failures often for this test right at the end and am keen to understand what's going on when it fails.
Just adding a retry and refresh so it captures a screenshot when failing more than anything.
We'll know more about the failure.
None.
- fixes #
=> Add retry and refresh for screenshot on 02-create-private-registry.

integration/use-cases/01-add-multicluster-deployment.js, integration/use-cases/04-default-deployment.js, integration/use-cases/05-missing-permissions.js, integration/use-cases/07-upgrade.js, integration/use-cases/lib/utils.js
Saw the following failure in CI:
We should not be relying on random names to avoid conflict between the tests. Updates to use a release name based on the running test. I've left the random suffix so that if we ever have the same tests running concurrently in the same cluster for different Kubeapps versions, we won't immediately fail.
CI won't fail due to name clashes.
None.
- fixes #
=> Don't rely on randomness for test names.

chart/kubeapps/values.yaml, docs/user/using-an-OIDC-provider-with-pinniped.md
This minor PR just documents the `pinnipedConfig: true` values under the `clusters` section in our chart and removes a no longer useful warning about the required pinniped version.
Better docs
N/A
N/A
N/A
=> Document pinnipedConfig in values.yaml. Minor fix in Pinniped docs

chart/kubeapps/Chart.yaml, chart/kubeapps/values.schema.json, chart/kubeapps/values.yaml, dashboard/public/openapi.yaml
This PR simply scales down the replicas back to 0 for the `assetsvc` but it does not remove it. This way, current users still will be able to ` --set assetsvc.replicas=1` if desired. Also, this PR removes the API docs for this service.
I still have to manually check (again) there is anything calling this svc, but the UI does not have any reference, as far as I can tell.
- fixes #3509
N/A
=> Deprecate assetsvc

integration/use-cases/01-add-multicluster-deployment.js, integration/use-cases/02-create-private-registry.js, integration/use-cases/04-default-deployment.js, integration/use-cases/07-upgrade.js, integration/use-cases/08-rollback.js, script/e2e-test.sh
This PR is intended to mitigate https://github.com/kubeapps/kubeapps/issues/3339 by replacing the chart `chart` with `prefix-chart`. This way, we will get a valid chart from the bitnami repo (as we were doing), but it cannot be retrieved by looking up the bitnami catalog (since `prefix-chart` does not exist anywhere except for our chartmusseum instance).
Also, it changes the description to ensure we are selecting the mutated chart.
Besides, instead of using the "bitnami" repo, this PR also installs a "bitnami" repo, but points to the local chartmusseum (which holds the mutated charts).
I really hope this PR would fix the CI issues we're having, as well as protect us from further upstream changes...
Perhaps the e2e tests will have to be modified. Let's see what our beloved CI has to say …
=> Mutate chart name when pushing to charmusseum

dashboard/src/components/AppUpgrade/AppUpgrade.tsx, dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx, dashboard/src/components/UpgradeForm/UpgradeForm.tsx
This PR addresses (what I think is a bug) regarding the fetching of Packages when upgrading.
When navigating to the upgrade form for deployments that are installed in the `"default"` cluster. The upgrade form fails to fetch the applicable package details if it is looking in the wrong cluster.
When fetching the package details, we use the cluster that is defined in the `AvailablePackageDetail` property when fetching the package. This should lead to correct fetching behavior.
Global packages that are installed in the `""` cluster but are deployed in the `"default"` can now be upgraded.
I don't believe there are any.
I did not create an issue since I was experimenting w/ solutions locally and seemed to have solved it.
I believe this is a relatively impactful bug that is present in …
=> fix(upgrade): Fetch package from its installed cluster

dashboard/package.json, dashboard/yarn.lock
As part of the analysis done in https://github.com/kubeapps/kubeapps/issues/3480, this PR is to remove the `fstream` dependency as it appears to be old and unused in our current code.
Quick manual tests do not result in a failure, so let's double-check it while triggering the CI.
No more old/unused UI deps to maintain.
Perhaps it is being used by react-scripts and we haven't noticed? Unlikely but plausible, let's see what our CI thinks.
- related #3480
I'm creating a single PR for each change so that we can know with certainty which dep is failing.
=> Remove `fstream` UI dependency

dashboard/package.json, dashboard/src/setupTests.ts
As part of the analysis done in https://github.com/kubeapps/kubeapps/issues/3480, this PR is to remove the `raf` dependency as it appears to be old and unused in our current code.
Quick manual tests do not result in a failure, so let's double-check it while triggering the CI.
No more old/unused UI deps to maintain.
Perhaps it is being used by react-scripts and we haven't noticed? Unlikely but plausible, let's see what our CI thinks.
- related #3480
I'm creating a single PR for each change so that we can know with certainty which dep is failing.
=> Remove `raf` UI dependency

dashboard/package.json, dashboard/src/index.scss, dashboard/yarn.lock
As part of the analysis done in https://github.com/kubeapps/kubeapps/issues/3480, this PR is to replace the `normalize` dependency as it appears to be old and clarity moved to `modern-normalize`
Quick manual tests do not result in a failure, so let's double-check it while triggering the CI.
No more old/unused UI deps to maintain.
Perhaps it is being used by react-scripts and we haven't noticed? Unlikely but plausible, let's see what our CI thinks.
- related #3480
I'm creating a single PR for each change so that we can know with certainty which dep is failing.
=> Replace `normalize` with `modern-normalize` UI dependency

chart/kubeapps/README.md, dashboard/package.json
Minor PR replacing an old reference to the Helm stable repo with the Bitnami Application Catalog.
Up to date docs.
N/A, but CI will complain anyway :(
N/A
N/A
=> Replace helm stable with BAC in chart readme

script/e2e-test.sh
This minor PR just adds a missing rolebinding (granting read on apprepositories) to the CI SA token we use as "edit-token".
CI will work in GKE (well, not only GKE, but any CI workflow not using the OIDC login)
None, but I wonder if this change is also required for some users. Not sure, but I'll drop a line in the release notes, just in case.
N/A
Rubber-stamping as it has been tested at https://app.circleci.com/pipelines/github/kubeapps/kubeapps/4497/workflows/17a5635f-fcfc-48f6-a3ec-5da8bc778b65
=> Add missing rolebinding for the CI user

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go
This will be the first in a list of PRs required to use the flux plugin from the UI (I'll add and link an issue to track them).
Running the Kubeapps UX with the fluxv2 plugin enabled results in:
This is because currently the plugin handles the case where the `request.Context.Cluster == ""` (ie. cluster isn't specified) only, in which case it correctly defaults to the cluster on which Kubeapps is installed. Since the UI will not know which requests plugins can handle (ie. which plugins support requests for different clusters etc.), it will always set the full context and rely on the plugin to respond with unimplemented or a valid response accordingly.
With this change, the response correctly comes back as empty rather than unimplemented (before I've added any flux `HelmRepositories`): …
=> Enable UX to request fluxv2 available packages

script/chart_sync_utils.sh
As expected, after the changes in https://github.com/kubeapps/kubeapps/pull/3676, there were some minor issues. In this case, a wrong variable.
Master builds will pass again
N/A
N/A
N/A
=> Fix errata in CI config

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/create_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/update_test.go, pkg/chart/chart.go, pkg/chart/chart_test.go
As outlined in https://github.com/kubeapps/kubeapps/issues/3567#issuecomment-954311431, this PR addresses another proposal to mitigate the effect of some memory peeks. In particular, this PR aims at solving https://github.com/kubeapps/kubeapps/issues/2363.
We simply pass the tarball URL (which we retrieve beforehand from cache), so we skip the expensive fetchRepo calls.
Even if the memory peaks can still occur, they won't be caused by our code, so to speak. The deploy/update chart actions are expensive in that they required some ulterior validation performed in the Helm/k8s code. About 50 MB or so, meaning 2-3 concurrent actions in a 256MB system. 
I'd really like to have removed the expensive code, but it is still used in Kubeops (just in the create/update actions). However, since it is …
=> Pass the tarball file in the `getChart` function to avoid re-fetching the repo

dashboard/src/actions/apps.test.tsx, dashboard/src/actions/apps.ts
There were two small issues stopping the display if installed apps when using the flux plugin:
1. We currently dispatch a request to fetch the manifest for a helm deployment, which needs replacing. For now I've just disabled this request unless it's for the helm plugin, allowing the UI to display basic info about a flux installed app.
The flux plugin returns apps without the cluster set in the context.
2. The flux plugin returns an empty "cluster" in the context, regardless of the request, which leaves the dashboard unable to create the URL. I've worked around this for now by initializing the context.cluster when fetching apps based on the request. But if @gfichtenholt is OK with it, it'd be cleaner for the flux endpoints to populate the cluster (it already has the info both in the …
=> Ensure cluster is set when listing and fetching apps.

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, script/makefiles/deploy-dev.mk
This PR just updates the (very) outdated kapp-controller plugin to match the current carvel k8s API.
The nice thing is that since the Kubeapps dashboard is using the aggregated API, running Kubeapps with both helm and carvel plugins:
```diff
--- a/docs/user/manifests/kubeapps-local-dev-values.yaml
+++ b/docs/user/manifests/kubeapps-local-dev-values.yaml
@@ -15,6 +15,11 @@ postgresql:
existingSecret: postgresql-db
kubeappsapis:
replicaCount: 1
+  enabledPlugins:
+    - helm
+    - kapp-controller
+  image:
+    tag: dev5
ingress:
enabled: true
hostname: localhost
```
enables viewing a combined catalog:
Carvel plugin works (only get available packages, and even that is missing data).
None.
- Ref #3221
cc @migmartri 
I'll follow-up with …
=> Update kapp-controller plugin to current version.

chart/kubeapps/values.yaml, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/integration_utils_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_integration_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go, docs/user/manifests/kubeapps-local-dev-redis-tiny-values.yaml, script/makefiles/deploy-dev.mk
This is mostly an incremental PR which isn't meant to address any big issue, but more specifically
1) adds an integration test for scenarios where redis cache is limited in size, has to evict entries in order to make room for new ones and flux plug-in functions as expected . This took a bit of an effort to make work
2) add a checksum comparison for repos before performing expensive operation of indexing 
3) tidy up/fix a few minor issues in unit tests
=> flux plugin: add integration test for low memory env and check repo checksum before indexing

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
- Basic meta, but need to refactor.
- Switch to use PackageMetadata as available package.
Carvel's kapp-controller changed their API quite significantly since we'd last looked at this plugin.
This PR switches to use the `PackageMetadata` as the "AvailablePackage", as it is the data which is common across versions, and the Package CR as the specific version.
It then adds the remaining metadata so that carvel and helm packages display side-by side without differences as shown:
Note: it looks like something is incorrect in the UI with the icon being much smaller, but it's just because of the SVG icon in the carvel test package, which has a size much bigger than the actual content, so in its original format looks like:
We can browser available packages with the kapp-controller plugin enabled. …
=> kapp-controller plugin metadata

docs/user/using-an-OIDC-provider-with-pinniped.md
Just two cases of `enable` that I missed, in the documentation for pinniped-proxy setup.
Just noticed while pointing someone else at the docs.
When we do the next release, people will use the consistent key rather than the deprecated key..
Until we release, people need to use the old key (the new release will support both for now).
For this reason, I'll not land this change until we release.
- Ref #3590
=> Two documentation uses of `enable` that I missed in #3590

dashboard/public/openapi.yaml, dashboard/src/components/ApiDocs/ApiDocs.scss
This PR just addresses two minor bugs: a CSS color issue (in the light theme, text inputs color and background were the same) and a wrong path preventing users from using the swagger-ui API client in the new KubeappsAPI.
API docs section won't have those bugs.
N/A
N/A
N/A
=> Minor fix in api docs

.circleci/config.yml, docs/user/operators.md
When installing the OLM for testing the icons I noticed there is a newer version of the OLM, so this PR is to update our default version to this one.
Using (and testing in CI) the latest OLM version
N/A
N/A
N/A
=> Bump default OLM version up

dashboard/src/components/AppUpgrade/AppUpgrade.tsx, dashboard/src/components/DeploymentForm/DeploymentForm.tsx, dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
We had a card in our board regarding a "/" not being properly handled at some point. Unfortunately, I wasn't able to fully remember what this was about, so I'll remove it and open a proper issue next time I face it. 
However, I did find a couple of missing URLDecode calls preventing some loading messages to render properly, wherefore this PR.
No more "foo%2Fbar" loading msgs.
N/A
N/A
N/A
=> Add missing URLEncode in some mgs

cmd/kubeapps-apis/cmd/root.go, cmd/kubeapps-apis/cmd/root_test.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins_test.go, cmd/kubeapps-apis/core/serveopts.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/utils.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/server/packages.go, cmd/kubeapps-apis/server/packages_test.go, cmd/kubeapps-apis/server/server.go
Untangles the core packaging and plugin implementations.
Untangles the core plugin implementation from the core packages. I needed to update the core plugin in small ways for the resources work, but would have been making the situation worse, so decided to move the core plugin implementation now rather than adding the the tech-debt.
The main change is that the core plugin implementation no longer knows anything about the core packages API. Where the core plugin used to check registered plugins to see if they implement the core packaging API, it now instead provides an exported function: `GetPluginsSatisfyingInterface`, which is called by the main executable after registering the plugins to get a slice of plugins that satisfy the core …
=> Move the core plugin implementation into a versioned module.

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_test.go, cmd/kubeapps-apis/server/server.go
Small follow-up to #3750, this time moving the core packages implementation into a versioned module.
As expected, this change was pretty trivial and just worked after the previous PR.
See #3750 .
- fixes #3329 (this completes that issue)
- ref #3403
=> Move core packages to versioned module.

cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go
Adds and tests an initial implementation for the GetResources call of the resources plugin.
It'll be followed by further PRs to:
* Filter by the requested resource refs,
* Enable watching for further changes of the requested resource refs
* Replace the use of UnsafeGuessKindToResource.
Enables requesting resources for an installed package.
IRL example:
```
grpcurl -plaintext -d '{"installed_package_ref": {"context": {"cluster": "default", "namespace": "default"}, "plugin": {"name": "helm.packages", "version": "v1alpha1"}, "identifier": "default-kafka-from-flux"}, "watch": true }' -H "Authorization: $token" localhost:8080 kubeappsapis.plugins.resources.v1alpha1.ResourcesService.GetResources{  "resourceRef": {    "apiVersion": "v1", …
```
=> Add initial GetResources implementation.

cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go
Following on from #3756 , this PR adds and tests the functionality to:
* Ensure only requested refs are returned (ie. filter by the requested refs)
* Ensure only requested refs belonging to installed pkg are returned.
We don't return unnecessary resources.
We don't expose arbitrary resources in the installed package namespace.
- ref #3403
=> Ensure only requested refs are returned.

cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go
Adds support for watching resources for changes.
As noted in the comments, I tried to unit-test the watch requests but am failing to trigger the watch events when using the fake client. But the IRL test works fine.
Can begin the implementation to watch many resources from the dashboard with a single request.
- ref #3403
When testing IRL, I notice that there are several responses (for the same resource) sent initially. I plan to check the type of the event and see if we can get it to a single response initially. Subsequent responses (when I manually update the resource being watched) are just one per change, as expected.
=> Add support for watching resources via GetResources.

cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go
Who would have thought converting from the GroupVersionKind of a yaml resource to the GroupVersionResource required by the API server would be so arduous?!
This PR replaces the unsafe conversion that was used temporarily, instead initializing a RESTMapper from the APIserver (using the service account) at startup and switching to use that at run-time for the conversion.
Follows on from #3767 
We don't depend on known-to-be-unsafe code.
- Ref #3403
=> Replace the unsafe gvk to gvr conversion with restmapper.

dashboard/src/components/AppView/CustomAppView/CustomAppView.test.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/CustomFormParam.test.tsx
Updates the tests related to the remote component so that they don't try to fetch external resources during tests.
CI was failing on master consistently with:
```
Summary of all failing tests
FAIL  src/components/InfoCard/InfoCard.test.tsx
● Test suite failed to run
ENOMEM: not enough memory, read
at Runtime.readFile (node_modules/jest-runtime/build/index.js:1987:21)
at Object.<anonymous> (node_modules/domutils/lib/index.js:16:14)
FAIL  src/components/AppView/AppControls/DeleteButton/DeleteButton.test.tsx
● Test suite failed to run
ENOMEM: not enough memory, read
at Runtime.readFile (node_modules/jest-runtime/build/index.js:1987:21)
at Object.<anonymous> (node_modules/lodash/_castPath.js:4:16)
FAIL …
```
=> Don't fire external network requests during test.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/getresources_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
While removing code from the dashboard in #3794, I found that the dashboard was handling some extra cases of `List` resources that had not been included in the helm plugin's GetInstalledPackageResourceRefs.
This PR addresses those and I'll rebase 3794 on this.
Avoid a regression when switching to the api server endpoint.
- ref #3779
=> Support for list resources in GetInstalledPackageResourceRefs

.circleci/config.yml
Still seeing some dashboard test runs on CI failing when workers get close to 1Gb (see [details in comment](https://github.com/kubeapps/kubeapps/pull/3797#issuecomment-976041955)). Forgot that we probably need to leave some memory for other processes, so updating to cause GC when a worker has 512Mb old mem.
Hopefully more stable CI.
- fixes #
=> CI dashboard tests should garbage-collect earlier.

dashboard/package.json
A number of times I've had test_dashboard failing on CI with output like:
```
#!/bin/bash -eo pipefail
yarn --cwd=dashboard run lint
yarn run v1.22.15
$ npm-run-all lint-css-check eslint-check
$ stylelint --config ./.stylelintrc.json 'src/**/*.scss'
$ eslint --config ./.eslintrc.json 'src/**/*.{js,ts,tsx}' --quiet --max-warnings=0
=============
WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.
You may find that it works just fine, or you may not.
SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0
YOUR TYPESCRIPT VERSION: 4.5.2
Please only submit bug reports when using the officially supported version.
=============
ESLint found too many warnings (maximum: 0). …
```
=> Show a lint error when there is one in CI.

dashboard/src/actions/apps.test.tsx, dashboard/src/actions/apps.ts, dashboard/src/actions/kube.test.tsx, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx, dashboard/src/containers/helpers/index.test.ts, dashboard/src/reducers/apps.ts, dashboard/src/reducers/kube.test.ts, dashboard/src/shared/App.ts, dashboard/src/shared/ResourceRef.test.ts, dashboard/src/shared/ResourceRef.ts, dashboard/src/shared/types.ts
This change updates the dashboard so that fetching the list of resource references for an installed package is no longer based on parsing the helm manifest, but instead a call to the apis server.
Other plugins can provide the installed package references for an installed app.
- ref #3779
While removing some of the dashboard code here, I noticed two cases that the backend may not yet support, so need to update that in the helm plugin.
=> Update dashboard to fetch resource refs via API.

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Initial implementation of the `GetPackageRepositories` operation
An initial and very limited Carvel support in Kubeapps
N/A
- related https://github.com/kubeapps/kubeapps/issues/3221
N/A
=> Add 'GetPackageRepositories' impl

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go
This PR just adds support for the GetInstalledPackageResourceRefs call to the fluxv2 plugin.
The code is the same as that in the helm plugin (longer term we may want to have some shared functionality between the helm and fluxv2 plugins given they both work with flux).
I had to update the tests to work in the same way as the flux model.
I haven't done the in-real-life test (but will do), but this should ensure that we can now view the details of an installed package (and it will watch/track the resources)
Installed package details for flux can be viewed correctly.
- ref #3779
=> Adds support for the GetInstalledPackageResourceRefs grpc call for fluxv2

dashboard/.eslintrc.json, dashboard/src/components/ErrorBoundary/ErrorBoundary.test.tsx, dashboard/src/registerServiceWorker.ts
Minor PR adding just an eslint warning if the committed code includes unnoticed `console.log`. I thought it was enabled by default, but some previous updates in the eslint config must have disabled it.
I won't commit again (or at least, our CI won't let it pass) code with console.log eventually useful for debugging a unit test :P
N/A
N/A
I'd say it was marked (in the past) as an `error`, which prevented eventual console statements when developing, Now it is a warning, we should be able to run `yarn start` without any issues.
=> Add eslint warning if console.log are left

chart/kubeapps/Chart.yaml, chart/kubeapps/README.md, chart/kubeapps/templates/frontend/configmap.yaml, chart/kubeapps/templates/kubeops/deployment.yaml, chart/kubeapps/templates/kubeops/rbac.yaml, chart/kubeapps/templates/kubeops/service.yaml, chart/kubeapps/templates/kubeops/serviceaccount.yaml, chart/kubeapps/values.yaml, dashboard/src/shared/App.ts, dashboard/src/shared/url.ts
Now that the dashboard is using the helm plugin for all helm-related functionality, we have no need for the connection to the kubeops service.
This PR just removes the two small references which are unused afaict.
With this, I believe we can indeed remove the kubeops (and already assetsvc) services? Not sure if we want to do that as part of this release. We'd have to update the internal content team tests I assume. What do you think Antonio?
I've additionally removed the config from the frontend so that no requests are forwarded to the kubeops or assetsvc services to see if anything breaks.
Less moving parts :)
None here, but if we remove the kubeops/assetsvc from the code and chart, we'll need to update the content teams tests or …
=> Remove last remaining connection to kubeops from dashboard.

cmd/asset-syncer/server/utils_test.go, go.mod, go.sum, pkg/chart/chart_test.go, pkg/helm/index_test.go, pkg/tarutil/tarutil_test.go
I assumed the dependabot error (below) was somethig transient, but it is not. It is due to an old dep causing some problems when auto-upgrading deps. Therefore, this PR is to replace it with the one we have been extensibily using (the other one is from the Monocular times).
Dependabot will be able, hopefully, to keep our go deps up to date... and I will be sleep happy knowing everything is smoothly being upgraded :P
N/A
N/A
N/A
=> Use the same assert library to avoid extra deps

chart/kubeapps/Chart.yaml, chart/kubeapps/values.yaml, cmd/apprepository-controller/server/controller.go, cmd/apprepository-controller/server/controller_test.go
Just fixes two small issues I noticed while investigating #3818.
The logs of the app-repository controller are currently just:
```
W1125 09:05:48.815213       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1125 22:06:10.357233       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1125 22:14:02.224164       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W1125 22:20:29.230197       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
```
and the functionality behind the `invalidateCache` feature flag …
=> Remove unused feature flag. Remove use of batch/v1beta1

cmd/apprepository-controller/server/controller.go, cmd/apprepository-controller/server/controller_test.go, script/e2e-test.sh
This PR aims at fixing some issues found when preparing the release, namely: 1) enabling kubeops via --set flag (only needed now we added this new param and it is not available in the current-1 chart version yet), 2) reverting the change in the cronjob API.
Kubeapps will continue to [work in k8s 1.20](https://app.circleci.com/pipelines/github/kubeapps/kubeapps/5106/workflows/78c1abb8-7a40-442f-9927-6c1c1c74b224/jobs/65517)
N/A
N/A
The issues found arise two questions to me:
1) Should we start using the same approach for selecting the API group version as we did in the past (you know, the fix Michael did when removing the unsafe lookup function) to spin up the cronjobs?
2) Should we clearly state in the project readme the current supported k8s versions?  And, what's more, perhaps also …
=> Revert change in crobjob API. Add kubeops.enabled in CI

integration/use-cases/08-rollback.js, script/e2e-test.sh
Updates the CI deployment to use two replicas for the kubeapps-apis service.
We've been experiencing intermittent issues with the last e2e test, `08-rollback.js`, lately that appear to be getting more frequent.
I first added the same retries as Antonio had done in #3866 so that I could continue debugging, and found that the first screenshot (first failure) shows an error:
while the second and third retries are just reloading the same page (though note that the update to the replicas is lost, so it shows 1 again) without error:
So an error is occurring, but then the retry is simply re-loading the page (without re-clicking on the deploy), which works fine, but is a different state to that expected. 
I then retried the e2e test with SSH …
=> Use two replicas for Kubeapps-apis service in CI

cmd/asset-syncer/server/testdata/helm-index-spaces.yaml, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go
This PR allows to sync and store in DB charts that contain spaces in name. End user will then be allowed to reach to the package details page, and when deploying, the error thrown by Helm will be shown.
Applied only to Helm repos, not to OCI.
Kubeapps is transparent with regards to charts containing spaces in name. Those charts are synced and stored properly, and end user can navigate to package details now. However Helm installation will still fail due to its restrictions. [See here](https://github.com/kubeapps/kubeapps/issues/3758#issuecomment-981748752)
Packages that can not be installed are listed.
This fix applies only to spaces in name: should we do the same exercise for other special characters? Helm only allows …
=> Allow to sync and store charts with spaces in name (#3758)

dashboard/package.json, integration/manifests/executor.yaml, integration/package.json, integration/yarn.lock
As part of the release process, we ought to update the integration image with the latest changes (just bumping up deps), so this PR is to perform this change.
I've pushed upstream so that the CI gets the changes.
Perhaps new versions bring more CI stability? 
Perhaps new versions bring more CI **in**stability? 
N/A
N/A
=> Update integration image

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/getresourcerefs_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go
While testing the Dashboard using the new resources plugin to watch k8s resources, I found a few issues in the plugin itself.
The main one being that the watch request was not limited to a particular resource but rather all gvr's in the namespace. Only noticed because I had two deployments in the default namespace with different replicas and was seeing the wrong number of pods in the UI.
Other small changes which I'll comment on inline.
Dashboard UX won't get confused when displaying k8s resources for an installed package (when I update to use the resources plugin in a following PR).
- Ref #3779
=> Watch specific resources rather than list of all gvrs.

dashboard/.eslintrc.json, dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx, dashboard/src/reducers/kube.test.ts, dashboard/src/reducers/kube.ts, dashboard/src/setupTests.ts, dashboard/src/shared/Kube.ts, dashboard/src/shared/KubeappsGrpcClient.ts, dashboard/src/shared/ResourceRef.ts, dashboard/src/shared/types.ts
This PR adds the new required actions (and handling of those actions in the reducer) for interacting with the new resources plugin to get and watch resources.
This allows a single request to the resources plugin to watch many resources. The streaming rpc call uses [server-side events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events) rather than web sockets, with the grpc-web client using rxjs observables which makes the implementation quite tidy.
This PR doesn't change the AppView yet, so the only benefit is preparation for the next PR where the AppView will be updated to use the new action.
- Ref #3779
=> Add actions for getting resources from resources plugin.

dashboard/src/components/Header/Header.scss, dashboard/src/components/PageHeader/PageHeader.scss, dashboard/src/components/PageHeader/PageHeader.tsx
Since I'm working on the deployment/upgrade views, I couldn't resist fixing something that really annoys me: a wrong overflow when reducing the size of the window:sweat_smile: 
I also removed some <ul> bullets, but happy to revert back if you like them.
Before:
After:
Better UI?
N/A
N/A
N/A
=> Fix css overflow issues

dashboard/src/components/DeploymentForm/DeploymentForm.tsx, dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.scss, dashboard/src/components/PackageHeader/PackageHeader.test.tsx, dashboard/src/components/PackageHeader/PackageHeader.tsx, dashboard/src/components/PackageHeader/PackageVersionSelector.tsx, dashboard/src/components/UpgradeForm/UpgradeForm.scss, dashboard/src/components/UpgradeForm/UpgradeForm.tsx, integration/use-cases/02-create-private-registry.js
As part of the slow and continuous (?) process to migrate our UI to use the new Clarity CDS core components, I've moved the pkg version selects to the new ones. 
Before:
After:
We will be able to add more components (like the ServiceAccount selector) without mixing `clr` and `cds` components.
Also, the `cds` component looks much better, it has a responsive layout already built-in, so less thing to worry about.
N/A
N/A
I don't know if there is an actual reason for keeping two package version selectors... what do you think about removing the one in the header (just for the upgrade view, I mean). If you agree, I'll do it in a separate PR (perhaps it has some e2e tests implications and I want to land this one soon for the service account selector thing)
=> Use cds-select in the deployment/upgrade views

chart/kubeapps/Chart.yaml, chart/kubeapps/values.yaml, dashboard/src/components/AppView/AccessURLTable/AccessURLTable.test.tsx, dashboard/src/components/AppView/AppSecrets/AppSecrets.test.tsx, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/components/AppView/ResourceTable/ResourceTable.test.tsx, dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.ts, dashboard/src/containers/helpers/index.test.ts, dashboard/src/containers/helpers/index.ts, dashboard/src/shared/utils.ts
Switches the AppView to use the new `getResources` action (using the resources plugin), with minimal changes to other code.
Checking the application detail for the Kubeapps app now only shows a single request for api server's `getResources` rather than 16 or so watch requests directly to the k8s api server:
And creating a new installation watches for updates so that the UI gets updated when pods are ready:
* Single request for watching all resources.
* No longer hitting the k8s API server to do so
* Can now remove *lots* of code and simplify other code.
See what CI says.
- ref #3779
There will be a few PRs to follow removing lots of code, extracting the current `ResourceRef` model and all its dependencies, removing the request for all …
=> Switch AppView to use new getResources.

dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/components/AppView/AccessURLTable/AccessURLTable.test.tsx, dashboard/src/components/AppView/AppSecrets/AppSecrets.test.tsx, dashboard/src/components/AppView/ResourceTable/ResourceTable.test.tsx, dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx, dashboard/src/containers/helpers/index.test.ts, dashboard/src/containers/helpers/index.ts, dashboard/src/reducers/kube.test.ts, dashboard/src/reducers/kube.ts, dashboard/src/shared/Kube.test.ts, dashboard/src/shared/Kube.ts, dashboard/src/shared/ResourceRef.test.ts, dashboard/src/shared/ResourceRef.ts, dashboard/src/shared/types.ts
Following on from the other #3779 PRs, this PR removes more now-unused code (after switching to the new resources plugin endpoint) and simplifies the `keyForResourceRef` helper now that it is used solely with our protobuf-generated resourceref.
- ref #3779
=> Remove watchResource and associated code.

dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
Fixes the problem of "Install Repo" button being fired multiple times.
Repo installation process is not triggered more than once.
N/A
- fixes #3678
Makes use of [React's useRef](https://reactjs.org/docs/hooks-reference.html#useref)
=> Fix install repo firing twice (#3678)

dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/reducers/kube.test.ts, dashboard/src/reducers/kube.ts
Rather than watching all resources for an installed package (as Kubeapps has done for quite some time), this PR updates so that we only watch the resources which are updated in the UX and just fetch the rest once only when the AppView is mounted.
Viewing Kubeapps, for example, now results in only 13 watches on the k8s API server (from the plugin), rather than ~40.
- fixes #3779
=> Only watch resources that are updated in UX.

cmd/kubeapps-apis/server/server.go
Kubeapps-api is using "httpGet probe" for livenessProbe & readinessProbe every 10secs.
values.yaml
```
livenessProbe:
enabled: true
httpGet:
path: /core/plugins/v1alpha1/configured-plugins
port: 50051
initialDelaySeconds: 60
periodSeconds: 10
readinessProbe:
enabled: true
httpGet:
path: /core/plugins/v1alpha1/configured-plugins
port: 50051
initialDelaySeconds: 0
periodSeconds: 10
```
This is causing noisy logs of probe endpoint
`/kubeappsapis.core.plugins.v1alpha1.PluginsService/GetConfiguredPlugins`
as mentioned in PR#[3780](https://github.com/kubeapps/kubeapps/pull/3780)
Solution:
Option-1:
We can probably use "GRPC Health Checking Protocol" as mentioned in  [health-checking-grpc-servers-on-kubernetes](https://kubernetes.io/blog/2018/10/01/health-checking-grpc-servers-on-kubernetes/) …
=> suppress noisy logs

cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_test.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
Follows on from #3905 , adding the implementation of those namespace GRPC methods of the resource plugin.
The next PR will be for the dashboard and can remove the calls to the K8s API server for the namespace functionality.
- ref #3896
=> Add implementation for Namespace related GRPC methods in resources plugin

cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_test.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, dashboard/src/actions/namespace.test.tsx, dashboard/src/actions/namespace.ts, dashboard/src/components/Header/ContextSelector.test.tsx, dashboard/src/components/Header/ContextSelector.tsx, dashboard/src/reducers/cluster.test.ts, dashboard/src/reducers/cluster.ts, dashboard/src/shared/Namespace.ts
Updates the dashboard to use the resources plugin to check if a namespace exists (rather than the more generic getNamespace which was hitting the k8s API server directly from the dashboard).
Also updates the `Namespace.create` shared helper to use the resources client.
See #3896 
- ref #3896
=> Switch dashboard to use checkNamespaceExists.

dashboard/src/shared/AppRepository.test.ts, dashboard/src/shared/AppRepository.ts
This PR fixes a problem with updating an app repository with filters.
Repo filter data is now processed correctly both in backend and frontend.
App repository filters are no longer gone after repo data update.
N/A
- fixes #3447
I have added a test file for `AppRepository` given that none was existing.
=> App repository update form fix for filters (#3447)

dashboard/src/shared/Kube.test.ts, dashboard/src/shared/Kube.ts
This PR prevents FE from placing can-i requests with malformed URLs that otherwise end up in 404 or 405 HTTP errors.
Thought that it was more correct formally not placing the requests instead of returning `200 OK` with body `authorized: no`. Reason being that the URL was incorrect, and not the parameters.
Less useless requests from browser to backend for can-i checks.
N/A
- fixes #2719
=> Fix for malformed can-i URL (#2719)

dashboard/src/actions/operators.test.tsx, dashboard/src/actions/operators.ts, dashboard/src/components/AppList/AppList.test.tsx, dashboard/src/components/AppList/AppListGrid.tsx, dashboard/src/components/AppList/CustomResourceListItem.tsx
Fix for operators resources showing repeated times (as many as namespaces existing in cluster) when listing installed items with "Show apps in all namespaces" marked in Dashboard.
Also added the label with namespace to cards.
Issue affects only the Dashboard/FE.
Realistic view of what operators resources are installed on each namespace.
N/A
- fixes #3574
=> Fix repeated operator resources shown in dashboard (#3574)

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
This PR simply adds a polling mechanism (interval/timeouts are harcoded, but could be split out into separate params if required) before sending OK when creating an installed package.
Since the App CR has to be created by kapp automatically before something can be considered as "installed", this active wait will ensure the App is present in the cluster; that is, no more UI errors after accessing to the installed view.
Can't think of; I mean, if the App CR is not created... that means something is wrong, so we better catch this error when executing the creation operation.
- fixes #3852
I want to DRY the tests up. Now we have the whole test suite and know what we need, we can refactor it and reduce the number of lines for creating the data. But it should be a follow-up PR (I've added it as …
=> Check App CR creation when CreateInstalledPackage

cmd/asset-syncer/server/testdata/helm-index-spaces.yaml, cmd/asset-syncer/server/utils_test.go
Extension of tests introduced in #3758 to cover characters other than space in chart names, although Helm specifies that `chart names must contain only lower case letters and numbers. Words may be separated with dashes (-)`. See [Helm general conventions](https://helm.sh/docs/chart_best_practices/conventions/#chart-names).
Therefore, the special characters tested in this PR won't have effect for Helm, as it will fail if chart contains them. Maybe for systems other than Helm is useful.
Bit more test coverage for special characters encoding on chart names
N/A
- fixes #3758
Maybe we should limit the possible characters available for package names.
=> Added some more cases to the tests for chars encoding (#3758)

script/makefiles/cluster-kind.mk
This PR brings a small adjustment for the Makefile in order to use the right cluster name when accessing the Kind node.
Kind creates nodes in Docker based on the `--name` parameter.
```
kind create cluster \
[...]
--name ${CLUSTER_NAME} \
[...]
```
So when accessing those nodes, the corresponding name from variable is now used.
Previously the key+cert files were being retrieved from a hardcoded Kind node name. Now it is in line with the cluster name.
N/A
None
=> Set variable for Kind cluster name in makefile

cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets_test.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
Following on from #3914, this PR adds the implementations for `CreateSecret` and `GetSecretNames`.
Can now update the dashboard to use the new endpoints rather than hitting the k8s API server.
- Ref #3896
=> Add implementation for resources secret endpoints

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/shared/Secret.test.ts, dashboard/src/shared/Secret.ts
Switches the `Secret.createDockerRegistrySecret` helper from using the k8s API directly to using the resources plugin.
Tested IRL to ensure both the dashboard change and the backend grpc function work together as expected (which they do).
* No longer receive the secret data over the network when creating a secret,
* One less call-site using the k8s API
- ref #3896 
Next up is switching the dashboard's `Secret.list` to use the plugin's `GetSecretNames` which will be trickier, as it also involves updating the dashboard to no longer require the secret data for the UX interaction.
=> Switch dashboard's createDockerRegistrySecret to use resources API.

pkg/http-handler/http-handler.go, pkg/http-handler/http-handler_test.go, pkg/kube/fake.go
This PR primarily adds an endpoint to the current kubeops backend handler to get an app repository, importantly, that includes the related auth header/ca.crt secret in the response. The dashboard currently relies on fetching app repo secrets directly from the k8s API server, which we want to remove. This is an initial work-around to avoid requiring a generic get secret endpoint (see #3922 for discussion of options).
While there, I've fixed the `returnK8sError` helper which was logging incorrect and hence confusing information.
It'll enable the followup PR which updates the dashboard to no longer fetch secrets via the k8s API.
- Ref #3922
=> Add GetAppRepository to kubeops backend

dashboard/package.json, dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx, dashboard/src/components/Config/AppRepoList/AppRepoControl.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.tsx, dashboard/src/reducers/repos.test.ts, dashboard/src/reducers/repos.ts, dashboard/src/shared/AppRepository.ts, dashboard/src/shared/url.ts, dashboard/yarn.lock
Following on from #4027, this PR updates the AppRepoForm component so that it no longer receives a related secret as a prop (from the redux state?), but rather fetches the secret when mounting and uses the local component state.
The new endpoint for fetching a secret for a repo's secret is used (rather than the k8s API), and it avoids the need to update the redux state when a repo is updated (since we always fetch the secret when loading the form). Also avoids storing all repo secrets in the redux state (and removes the related actions/reducers).
- ref #3922 
As always, testing the combination of an async react hook (useEffect) turned out to be painful to realise, but got there after a lot of head scratching.
I still need to test this IRL locally before landing (once CI passes etc.)
=> Remove repo secrets from redux state, fetch on mount

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils_test.go
This PR is aimed at providing a set of initial values for users when installing/upgrading a Carvel package. Particularly, in this PR:
* The raw schema is passed through the wire (for the custom form, if ever implemented - see https://github.com/kubeapps/kubeapps/issues/3853#issuecomment-1004746080)
* The default values are calculated as follows: if a `.Default` property exists, use it; otherwise, fall back to each data type default value (eg., `""` or `0`)
* Several tests have been written since I noticed the `server_utils_test` wasn't being tested. 
Users will get more information about the values that a package requires, being a similar UX as in other pkg formats (Helm).
Some problems arise:
* I've noticed some schemas (from our usual Carvel repos) have problems when performing the yaml …
=> Set the `ValuesSchema` and `DefaultValues` in Carvel pkgs

dashboard/src/components/PackageHeader/PackageHeader.tsx, dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx, dashboard/src/components/UpgradeForm/UpgradeForm.tsx
In this PR, we add an attribute to conditionally render the version selector in the header, so that we can choose where we should render it.
No duplicated version selectors. In the picture, install vs upgrade views:
If the CI fails, we should also add some fixes there.
- fixes https://github.com/kubeapps/kubeapps/issues/3890
(it's my first PR of 2022 :P)
=> Disable the version selector when upgrading pkgs

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx, dashboard/src/reducers/repos.test.ts, dashboard/src/reducers/repos.ts, dashboard/src/shared/Secret.test.ts, dashboard/src/shared/Secret.ts, dashboard/src/shared/url.ts
This PR follows on from #4028, updating the AppRepoForm so that it fetches the image pull secret *names* only (from the resources API), rather than fetching (and storing in global state) the image pull secrets for a namespace. Also updated, while there, to no longer use global state for these, but rather just local state on the form.
It also does some cleaning up, so that `shared/Secret.ts` no longer has any references to the k8s API, as well as removing the urls from `shared/urls` etc.
Tested IRL.
Kubeapps no longer hits the k8s API for secrets, nor does it expose any method for fetching secrets generally.
- ref #3896
=> No more secret requests to K8s API

cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, dashboard/src/components/LoginForm/LoginForm.test.tsx, dashboard/src/components/LoginForm/LoginForm.tsx, dashboard/src/shared/Auth.test.ts, dashboard/src/shared/Auth.ts, dashboard/src/shared/KubeappsGrpcClient.test.ts, dashboard/src/shared/KubeappsGrpcClient.ts
Part one of removing `shared/Auth`'s use of the k8s API server, this PR updates the `validateToken` check, used when Kubeapps is configured with token authentication, so that it hits the resources API (`checkNamespace`), rather than hitting the k8s API server directly.
To do so, I had to correct the error handling in the resources plugin to differentiate between 401s and 403s (and will later follow up as per the TODO there).
I also fixed an issue where the dashboard was checking cookie auth based only on the loginURL being set, which it is by default anyway (which resulted in an extra error being displayed when token login failed).
One more action no longer hitting k8s API.
- Ref #3896
=> Update dashboard's validateToken not to use k8s api server.

dashboard/src/shared/Auth.test.ts, dashboard/src/shared/Auth.ts
Follows on from #4043, this time updating the cookie-based authentication so that it no longer uses a request to the k8s API server to determine the authentication status.
I'd originally planned to remove axios from `shared/Auth` (with the `isAnonymous` and `is403FromAuthProxy` functions), but then found they are still used in `shared/AxiosInstance` which is still used by the operator support (which will continue for now to query the k8s API directly).
As with the previous PR the pain here was testing IRL locally the various possibilities to find the best solution.
Hopefully no more requests to the k8s api server, outside of the operator support (though I'll do a proper audit and test tomorrow).
- ref #3896
=> Update cookie auth check to no longer use axios/k8s api server

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils_test.go, dashboard/src/components/UpgradeForm/UpgradeForm.tsx
Follow-up PR of #4023. 
After giving a try to the repo that the TCE folks so kindly created (https://github.com/vmware-tanzu/community-edition/pull/2775#issuecomment-1006784759)), I noticed it still failed in Kubeapps. The unmarshaller was returning an error even if the `addtionalProperties` prop was properly being set (according to the JSONSchema Spec). 
I guess it has something to do with the `JSONSchemaPropsOrBool` (from k8s) field it tries to unmarshall to, but I don't know the root cause yet.
Anyway, it gets sorted out when using another `yaml` dependency, which in case of failures, it seems to be using the default value in `JSONSchemaPropsOrBool` (which is `true`).
This PR replaces this yaml dep and updates the test cases accordingly.
Kubeapps will be able to set default values for …
=> Use another yaml dep to unmarshall the schema

cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
I just took a brief look at this issue after you mentioned @antgamdia it in the standup:
- The [ResourceRef message](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/proto/kubeappsapis/core/packages/v1alpha1/packages.proto#L924-L928) already explicitly supports references for resources that are in other namespaces than the installed package context.
- The tests for the [resources plugin already have a case for this](https://github.com/kubeapps/kubeapps/blob/master/cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go#L318).
but, that said, I wasn't able (yet) to test the streaming requests and as it turns out, it was using the installed package context namespace, rather than that of the resource.
This one-liner …
=> Fix namespace when watching (rather than getting) resources.

.circleci/config.yml, chart/kubeapps/templates/frontend/configmap.yaml, dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/components/Layout/Layout.test.tsx, dashboard/src/components/Layout/Layout.tsx, script/e2e-test.sh
Follows on from both the work on #3896 as well as @castelblanque 's work in the recent #4051 . Since the latter isn't yet landed, I've targeted a branch that I created which is just an updated master with Rafa's changes. I'll retarget to master once Rafa's PR lands. (Edit: done)
This PR updates the frontend config so that it no longer proxies to the k8s API server, unless operators are enabled.
It also updates ci so that the operator switch (and hence whether Kubeapps proxies to the k8s api server) can be configured via the env. I set it to disable operators and the k8s api proxying to [verify that it passed](https://circleci.com/gh/kubeapps/kubeapps/70321?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) …
=> Test running without k8s api proxying.

dashboard/src/actions/apps.ts, dashboard/src/components/AppList/AppList.tsx, dashboard/src/components/ErrorAlert/ErrorAlert.scss, dashboard/src/components/ErrorAlert/ErrorAlert.test.tsx, dashboard/src/components/ErrorAlert/ErrorAlert.tsx, dashboard/src/components/ErrorAlert/index.tsx, dashboard/src/components/RpcErrorMessage/RpcErrorMessage.scss, dashboard/src/components/RpcErrorMessage/RpcErrorMessage.test.tsx, dashboard/src/components/RpcErrorMessage/RpcErrorMessage.tsx, dashboard/src/components/RpcErrorMessage/index.tsx, dashboard/src/shared/RpcError.test.ts, dashboard/src/shared/RpcError.ts, dashboard/src/shared/types.ts
Introduces a React `ErrorAlert` component aimed at improving readability of UI errors and that could replace existing `<Alert>` usages. 
It is able to turn this kind of UI error:
into this:
It can detect RPC errors and show them indented while not affecting existing plain text errors.
The change also allows to specify a stack of errors when creating a custom error (or an extension of it).
Better error readability on UI
None that I can think of.
=> Error alert component

dashboard/public/openapi.yaml
Simply removes the links and info about the proxied k8s API since we
1) no longer do this in the default setup, and 
2) don't want to do this long term even with operators.
We no longer advertise something which isn't available by default, nor something that we want to remove long term.
- ref #3896
=> Remove proxied K8s API from our openapi.yaml

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
This trivial PR addresses a failure in a test case due to a wrong test assert introduced in a merged PR.
CI will pass again
N/A
N/A
I'll rubber-stamp this PR as soon as it passes in CI
=> Fix failing test after previous PR merge

cmd/apprepository-controller/cmd/root.go, cmd/apprepository-controller/cmd/root_test.go, cmd/apprepository-controller/server/controller_test.go, cmd/apprepository-controller/server/server.go
This PR simply addresses an intentional leftover in  #4101 as it is an actual change in the code.
However, as far as I'm concerned, this param is not being used in our chart or ci scripts.
I've used `--apiserver` as the param name, but happy to change it to any other better alternative you think of.
The param name won't point to an outdated name in kubernetes (`master` nodes were renamed to `control plane` long time ago).
Unnoticed uses of this param elsewhere? 
- rel #4075 
N/A
=> Rename `MasterURL` to `APIServerURL`

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils_test.go
Since Carvel packages do not have any `readme` field, we decided to build one on our own. In the initial implementation, we simply populated a markdown template regardless of the existence (or not) of the given fields.
Also, some arrays and date types weren't being considered.
This PR is to slightly improve the look n' feel of the installation page
Better readme.
N/A
- related #3849
Before:
After:
=> Improve readme builder for carvel pkgs

.circleci/config.yml, cmd/pinniped-proxy/Dockerfile
As part of the circleci [image deprecations](https://circleci.com/docs/2.0/circleci-images/), this PR is simply to update the container images used for running the steps.
We'll continue to have image upgrades (`circleci/xxxx` images were deprecated in 2021)
Let's see if the CI think otherwise
N/A
N/A
=> Update circleci imgs to the latest ones

cmd/pinniped-proxy/Cargo.toml, docs/developer/release-process.md
This trivial PR just extracts the version used in the `k8s-openapi` dependency apart into a Cargo feature. This way any piece of code depending on `pinniped-proxy` can modify the target k8s platform simply compiling it with a `feature`.
Defaulting to the same value it has.
Pinniped-proxy will be simpler to configure when used as a dependency.
N/A
N/A
I've added also a note in the release docs talking about then kubernetes-related deps.
=> Allow changing the k8s target version in Cargo

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go
As per the discussion in https://github.com/kubeapps/kubeapps/pull/4074#discussion_r794704956, this PR simply reverts back some annotations that were wrongly added in a previous PR.
We will follow the recommnetarions made by the carvel team.
N/A
N/A
N/A
=> Remove wrongly added annotations in carvel plugin

cmd/apprepository-controller/cmd/root.go, cmd/asset-syncer/cmd/root.go, cmd/assetsvc/cmd/root.go, cmd/kubeapps-apis/Makefile, cmd/kubeapps-apis/cmd/root.go, cmd/kubeops/cmd/root.go, pkg/agent/httpConfigForCluster.go
This PR extends https://github.com/kubeapps/kubeapps/pull/4176 in 1) performing some dep renames in the kubeapps-apis cmd with the latest changes introduced some weeks before (default verbosity and homedir); 2) extending those changes to the rest of cobra applications (asset-syncer, kubeops, etc...)
Uniform command-line applications in Kubeapps.
N/A
- rel #3848
N/A
=> Use the same cmd args in every cmd-based application

pkg/agent/docker_secrets_postrenderer.go, pkg/agent/docker_secrets_postrenderer_test.go
This PR simply updates a piece of code using the yaml version 2 instead of v3. Since it has some breaking changes, it is a separate PR.
Avoid multiple dependency versions in our codebase.
Some additional and unnoticed breaking changes? Let's see what the CI thinks.
- rel #3848
This is one of the few places we are using the go yaml library instead of the k8s one. In this piece of code, we don't have any typed model to marshal from/to, so I guess that's the reason.
However, I wonder about this decision, I mean, why not rely on a PodSpec since it is a well-established k8s API (corev1)?
Happy to discuss it offline in our standup, though.
=> Migrate from go yaml.v2 to yaml.v3

cmd/asset-syncer/server/utils.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go, pkg/chart/chart.go, pkg/helm/index.go
This PR just replaces `ghodss/yaml` with Kubernetes fork of the same library, `sigs.k8s.io/yaml`, as it was the most used along our codebase.
Reduce same-purpose deps.
I don't know we are ever relying on a very specific feature of the original dep whose behavior differs from the k8s-fork one. I can't think of it, but let's our CI decide.
- rel #3848
N/A
=> Migrate from ghodss/yaml to sigs.k8s.io/yaml

cmd/apprepository-controller/cmd/root.go, cmd/apprepository-controller/server/controller.go, cmd/asset-syncer/cmd/root.go, cmd/asset-syncer/server/utils.go, cmd/assetsvc/cmd/root.go, cmd/assetsvc/server/handler.go, cmd/kubeapps-apis/cmd/root.go, cmd/kubeops/cmd/root.go, cmd/kubeops/internal/handler/handler.go, pkg/agent/agent.go, pkg/agent/docker_secrets_postrenderer.go, pkg/chart/chart.go, pkg/helm/helm.go, pkg/http-handler/http-handler.go, pkg/kube/kube_handler.go
This PR continues the effort started some time ago in unifying the logging libraries. We opted for `klog`, the one used in Kubernetes. Some minor changes have been introduced in order to adapt the log operations to the ones available in klog (no `WithParams` or `WithError` are available here).
Reduce same-purpose deps. It also simplifies the task of moving to structured logging as we were asked in the past.
N/A
- rel #3848
N/A
=> Replace `logrus` by `klog`

dashboard/src/actions/apps.ts, dashboard/src/components/AppList/AppList.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/components/ErrorAlert/ErrorAlert.test.tsx, dashboard/src/components/ErrorAlert/ErrorAlert.tsx
Initially was just to update the error displayed in the AppView to use the `ErrorAlert` component, but the `ErrorAlert` component didn't currently support child elements like the old one did, which the AppView uses. So after chatting with Rafa, I've updated that component to take the error as a prop allowing the children to be normal react nodes.
Before:
After:
Clicking on the "Try again" does what it always did, re-issuing the request and rendering the view when it succeeds.
- fixes #4190 
- Ref #3695
=> Update error in AppView to use ErrorAlert.

integration/tests/utils/kubeapps-login.js
This PR fixes the login in E2E when using Bearer token.
It is the mechanism used for testing in GKE and therefore important for releasing Kubeapps.
Bearer token login is working now
N/A
- Fix on top of functionality delivered for #2898
=> Fix bearer token login on E2E tests (#2898)

dashboard/src/actions/apps.test.tsx, dashboard/src/actions/apps.ts, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/reducers/apps.test.ts, dashboard/src/reducers/apps.ts, dashboard/src/shared/types.ts
Separates out the action for fetching resource refs for an installed application.
When the resource refs were first added to the `SelectedApp` state, I think Antonio and I both agreed that it didn't belong there (in the `CustomInstalledPackageDetail` which was temporarily created to accommodate the helm version field), but at the time I wasn't keen to refactor it.
Now we have an unrelated issue that for flux (and carvel), the call to fetch the resource refs fails with a 404 initially (within 1 second of creating the installed package) because the underlying reconciliation creates the helm (for flux) release very soon after creating the installed package, but not immediately.
I'm going to create an issue for the plugin backend so that the …
=> Separate action for requesting resource refs.

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go
After merging #4068, I've noticed there was an error every time you installed a package. This is because right after a successful install, you get redirected to the details view, meaning that every expected resource is supposed to be available.
We had that problem in the past (we needed the `App` CR to be created, something that happens a few seconds after creating the `PackageInstall`). However, now we are watching the generated resources, we need to query a `ConfigMap` to get the App ID (something generated by `kapp-ctrl` ); therefore, we need to wait until the CM is created. The thorny thing here is it takes up to 30s.
This PR just follows the similar approach we did for querying  the existence of an`App`, but I'm open to any other suggestions you may have.
No ugly error when the user …
=> Wait until CM is created when installing a carvel pkg

.circleci/config.yml, integration/tests/main/01-missing-permissions.spec.js, integration/tests/main/09-user-positive-installation.spec.js, integration/tests/utils/kubeapps-login.js
This PR adds a positive test-case to use the more limited user `kubeapps-user` (deploy & delete).
It also adds a new negative test for that user trying to deploy from a repo with secrets to which user does not have access.
We are better covering the "limited" user deploy/undeploy actions in CI.
N/A
- fixes #4081
=> Default user positive and negative test for deploying

docs/developer/end-to-end-tests.md, integration/playwright.config.js
This PR doesn't fix any failing tests (see Rafa's #4243 for that), but rather solves an issue of the disappearing local screenshots and videos.
In the end, it was simply that the 1.0.0 image had the html reporter enabled and set to write to the *same* directory as the test reports. Turns out the reporter *overwrites* the directory. So the screenshots and videos were being written and saved, then at the end the html report was generated and overwrote the directory.
This doesn't happen by default, because the [default output directory used for automatic screenshots etc. is `test-results`](https://playwright.dev/docs/test-configuration#automatic-screenshots) and the [default output for the html reporter is …
=> CI: Don't overwrite `/app/reports` directory with html reporter.

dashboard/src/shared/InstalledPackage.test.ts, dashboard/src/shared/InstalledPackage.ts
I was getting ready to update the `GetInstalledPackageResourceRefs` shared util, went to write a test for the existing code, but found that the existing tests for that module were mocking the actual function being tested, rather than mocking the underlying client so that we can verify that the client is called with the arguments.
This PR just updates those tests so that we are not mocking the actual functions that we're testing (guess we did this when rushing to switch to the new grpc client). The tests aren't particularly valuable here, since the util is just calling the client with the same args, but the test for GetInstalledPackageResourceRefs will be extended to be more useful in the following PR (where I'll add retries).
Only …
=> Update tests for installed package to test call to client.

docs/user/getting-started.md
Adding instructions on how to get the token if using Powershell (the typical console in recent Windows versions)
Windows users will have an easy way to get the token.
N/A
N/A
=> Add powershell instructions

dashboard/src/components/Catalog/PackageCatalogItem.tsx
This simple PR just adds the same workaround to get the repository for those packages coming from the flux plugin.
Until we came up with a better solution, I think it solves the short-term problem for some users.
Repo will be displayed in pkgs from Fluxv2
It's just a short-term solution, but so was the Helm one as well.
- fixes #4231
=> Add same workaround to show repo in flux

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/_helpers.tpl
While I was enabling/disabling plugins in my local env, I've spent some time wondering what was wrong in my setup... it turned to be just a typo in the plugin name :facepalm: 
This PR adds some validation to the plugin names we are using, at least, for the mistakes I use to make :P
Feel free to suggest more.
No "OSI layer 8"-derived problems, haha
N/A
N/A
```bash
kubeapps: kubeappsapis.enabledPlugins 
You enter "flux", perhaps you meant "fluxv2"?
kubeapps: kubeappsapis.enabledPlugins 
You enter "kapp_controller", perhaps you meant "kapp-controller"?
kubeapps: kubeappsapis.enabledPlugins 
If you enable the "fluxv2" plugin, you must also set redis.enabled=true
```
=> Add initial tpl validation for plugins

dashboard/src/shared/InstalledPackage.test.ts, dashboard/src/shared/InstalledPackage.ts
See #4213 for description of the problem.
This change just ensures that the call will retry a number of times, backing off exponentially. For Flux it only needs to be a second, but carvel has other needs.
Error no longer shown when first deploying flux package.
- Ref #4213 
- Ref #3695
=> Call GetInstalledPackageResourceRefs with exp backoff.

chart/kubeapps/Chart.lock, chart/kubeapps/Chart.yaml, chart/kubeapps/templates/_helpers.tpl
Currently it's possible to configure the kubeapps apis service with both the fluxv2 and helm plugins running. This is not something we are able to support right now, since it would enable interacting with the helm releases directly when they are being managed by flux (as well as confusingly display apps twice).
I've used the new chart validation that @antgamdia added recently, since it's nice to catch the configuration issue *before* doing the deployment.
We don't allow a configuration which we don't intend to support.
- ref #3695 
Next up, removing the need to enable redis (and removing postgres when helm plugin is not used? - possibly, depends on effects, may need to also remove assetsvc, apprepo controller etc.).
=> Ensure only one of helm or fluxv2 plugins are configured.

integration/tests/main/01-missing-permissions.spec.js
Fixes the E2E test number 01 that is failing in GKE but not on Kind.
Test should not fail now in GKE.
Hopefully none
=> Fix for test 01 aimed at GKE

dashboard/src/actions/installedpackages.test.tsx, dashboard/src/actions/installedpackages.ts, dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/reducers/installedpackages.ts
Fixes an issue whereby a package installs successfully but the upgrade/delete buttons remain disabled.
With this change, we refresh the package status whenever a bunch of resources are processed.
When using Flux plugin to install a package, the buttons enable once the package is reconciled.
- ref #3695
=> Trigger fetch of package status after resources are updated.

dashboard/src/components/LoginForm/LoginForm.test.tsx, dashboard/src/components/LoginForm/LoginForm.tsx
This PR just allows passing a `?token=xxxxxx` in the token login view so that we can bypass manually entering a value.
No human interaction for accessing Kubeapps with a token, if desired.
N/A
N/A
x
=> Autologin if a token is passed as queryParam

chart/kubeapps/templates/_helpers.tpl, cmd/kubeapps-apis/Dockerfile
Small follow-up to #4264 that updates the location that kubeapps-apis plugins are located (to match the Bitnami containers).
@castelblanque If you do want this change, just be sure to merge it first (as it's currently targeting #4264 and so will be merged into there, but if that PR is merged first to main, this will be automatically updated by GH to target main and may need rebasing, depending).
Consistency. Nice to explicitly identify packaging plugins.
- ref #3695
=> Update to use the same plugin directories that bitnami Dockerfile uses.

.circleci/config.yml, docs/developer/release-process.md
As per the instructions received by CircleCI (https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration), we should migrate to Ubuntu 20.04. This was one of the changes performed at https://github.com/kubeapps/kubeapps/pull/4170, but it didn't get merged finally.
We will use a non-deprecated way to define the machine image used by the CircleCI
Perhaps a problem with some deps? Let's see what the CI thinks.
N/A
N/A
=> Use an up-to-date circleci machine

docs/developer/release-process.md
Due to our recent problems with the release, this PR just adds another step to ensure we double-check our new dockerfiles against the latest release's ones. 
We (hopefully) won't forget this step anymore when releasing.
Still manual and therefore error-prone, but... nothing more we can do :S
N/A
N/A
=> Add step in the release docs

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/_helpers.tpl, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/values.yaml, cmd/kubeapps-apis/Dockerfile, docs/user/managing-carvel-packages.md
@batiati If approved, feel free to land this and include in the release if you want.
This PR has two related changes:
1. Create a user-centric `packaging` option in the values for specifying whether Kubeapps should run with helm, flux or carvel packaging. Defaulting to helm of course.
2. Uses these new boolean values to control whether the Redis chart dependency is installed, so that we no longer need to manually specify `redis.enabled` (removed that from the chart, since it's no longer used in the chart dependency condition).
```
➜  kubeapps git:(3695-dont-require-explicit-enable-redis-2) ✗ git --no-pager diff docs/user/manifests/kubeapps-local-dev-values.yaml
➜  kubeapps git:(3695-dont-require-explicit-enable-redis-2) ✗ make …
```
=> Enable specifying plugins that determine chart dependencies.

chart/kubeapps/Chart.yaml, chart/kubeapps/templates/NOTES.txt, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeappsapis/rbac_fluxv2.yaml
I broke the Flux deployment in my recent commit because I focused on the enabling of the correct plugins and installation of the chart dependency, but didn't check it running IRL.
Turns out we had two places in the chart still referring to the old `redis.enabled`.
This fixes that,  and I just verified IRL that with this I can deploy flux locally :)
I'll update the upstream PR later (just going AFK).
- fixes #
=> Fix Flux deployment for local dev env.

chart/kubeapps/Chart.yaml
CI step **_Run the check_upstream_chart script_** is failing due to
`Current chart version (7.8.0-dev6) is less than the chart external version (7.8.0)`.
This PR tries to tackle that problem by bumping up the development chart version to `7.8.1-dev1`.
Chart versions should be correct between Bitnami and Kubeapps devel charts.
Hopefully none until versions are changed again in either side.
[Current Kubeapps devel chart version](https://github.com/kubeapps/kubeapps/blob/main/chart/kubeapps/Chart.yaml#L36)
[Bitnami Kubeapps chart version](https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/Chart.yaml#L36)
[Example of failing CI run](https://app.circleci.com/pipelines/github/kubeapps/kubeapps/6216/workflows/6587f4eb-3ec1-42 …
=> Update devel chart version to be higher than Bitnami's

docs/developer/release-process.md
Added a new step in the release process documentation to check that the new chart is available in the Bitnami repo.
We don't publish by mistake a new release until the chart is publicly available.
N/A
=> Add step to release process for checking Bitnami repo is up to date

dashboard/src/components/AppList/AppListItem.test.tsx, dashboard/src/components/AppList/AppListItem.tsx
The status displayed in the application list was using the plugin-specific `status.userReason` field, resulting in the following when displaying both flux and carvel packages together:
rather than the `status.reason` field which is consistent across plugins, which results in:
We avoid formatting issues with the plugin specific user reason on the tiles. Get standard status's across plugins for apps.
Changes the default from "deployed" to "installed". We could put a condition in there, but it seems appropriate to use `installed` (given our generic packaging wording) so left it. Let me know.
- ref #3695
=> Ensure consistent status in tile for different plugins.

dashboard/src/components/Catalog/Catalog.tsx
Just adds an extra paragraph to the empty catalog display page, linking directly to our docs:
A user has more information about where to go if they see an empty catalog.
- ref #3695 
I was originally planning to check which plugins are configured and just show info related to that plugin, but it looks to be more work than it is worth given that we're currently investing in the app repository API (which will be aggregated etc. and replace the current AppRepository handling).
I had also planned to link to specific documentation for flux and carvel, but given the current doc restructuring that @ppbaena is working on, I instead just pointed to the root of the docs.
=> Update empty catalog message to include docs for flux/carvel

dashboard/src/components/AppList/AppListItem.tsx, dashboard/src/components/AppView/PackageInfo/PackageInfo.test.tsx, dashboard/src/components/AppView/PackageInfo/PackageInfo.tsx, dashboard/src/shared/utils.ts
Currently we haven't included the installed package status on the detail page at all (only on the list page, as a tag). For Helm this wasn't a problem, as we only ever got to the detail page if the helm chart was installed, but for Flux (and others) the semantics are slightly different: The `HelmRelease` is created, but the helm chart may not be installed.
This happens most obviously when the service account chosen for the install doesn't have the required perms. The install details page shows zero information about the state of the install.
With this change, we update to display the status (`installed`, `pending`, etc.), and for the case where the status isn't `installed`, we also display the user reason:
In the above example, the user …
=> Include installed pkg status and user reason on app detail.

dashboard/src/actions/installedpackages.test.tsx, dashboard/src/actions/installedpackages.ts, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/reducers/installedpackages.ts, dashboard/src/shared/InstalledPackage.test.ts, dashboard/src/shared/InstalledPackage.ts, dashboard/src/shared/types.ts
This PR updates the AppView so it handles the fetching of the resource references directly (rather than dispatching and going through redux) so that it can decide itself when to poll and importantly, can abort the polling when the component is unmounted.
This fixes a couple of issues that I found recently while testing deploying a flux package with a service account that doesn't have the required RBAC:
1. The existing code would retry the request up to 4 times, then display the not found error. This was find for the case where we expect the resources to exist in a short time-frame, but not for the case where they will never exist until RBAC is updated (see #4337 ),
2. The existing code would continue to retry the request even when you navigated away from the app view. This was because …
=> Continue to poll for resource references when not found

script/chart_sync_utils.sh
Probably after the update of the images used in CircleCI, I don't know, but the sync chart from bitnami step stopped working.  This PR just changes the way the ssh key is passed back to git: before, we were setting the local git config, which was working nicely, but now this same info is passed through an env var.
CI step will work again
N/A
N/A
Tested while accessing via ssh to the circle ci machine with a successful output: https://github.com/kubeapps/kubeapps/pull/4348
=> Use env var instead of git config for setting the ssh key

dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx, dashboard/src/components/UpgradeForm/UpgradeForm.tsx
This PR fixes a small UI bug for the upgrade cases in which there were no installation applied values. This is mainly happening with the Carvel plugin.
When trying to render the `UpgradeForm`, there was an error due to the impossibility to convert a null/empty string to json.
Upgrade view now renders and no error is shown.
N/A
- fixes #4352
=> Allowing empty values applied when upgrading installation

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go
See #4345 
No issues syncing public repos on services that send 401 for requests with empty auth header.
None
- fixes #4345
=> Don't send empty Auth header when syncing repos.

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
See #4328 for description of the visible problem.
In the code, AFAICT, within the Carvel plugin, there was no difference in functionality for an empty state vs an incorrect state. So if no repo was setup, an error was returned as per #4328 in the same way that the error was returned if a carvel package metadata did not have a corresponding package (version).
This change separates errors from an empty result, returning a specific Internal error when it happens, but not returning an error for an empty catalog.
Users can see the empty catalog view with links to documentation for setting up repositories etc.
- fixes #4328 
Since I needed a channel to gather any errors, it seemed convenient to use that channel for synchronization rather than …
=> Enable an empty response from carvel.GetAvailablePackageSummaries

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
This change is a refactor only. It updates to:
1. Move the functionality of the go-routine into a typed function returning both the available pkg summary and error,
2. Update so that the go-routine communicates via the channel, sending the available pkg summary and error, rather than writing to shared memory.
As a result, we no longer need to worry about `nil` entries in a separate slice etc.
Note:
- I've also include the index in the channel message, just so the current order is maintained.
- I've added a test for fetching a non-initial page of results (as when I refactored I knew I'd broken it at first, but tests passed).
Main benefit is that we're preferring communication via channels (and using that channel for syncing results) …
=> Avoid writing to shared memory in go-routine.

docs/user/managing-carvel-packages.md
While testing yesterday I'd added the TCE carvel repo as per the docs, but noticed I still had an empty catalog. Turned out to be because the TCE `packagerepository` was created in the `default` namespace, so the packages were only visible in the catalog when I switched context to the default namespace.
Avoid confusion when trying out the carvel support.
- fixes #
=> Carvel docs to specify namespace for repository.

cmd/kubeapps-apis/Makefile, cmd/kubeapps-apis/tools/tools.go, docs/developer/kubeapps-apis.md, go.mod, go.sum
Switches to use the extracted `cobra-cli` command since it is being removed from the `github.com/spf13/cobra` module (xref https://github.com/spf13/cobra/issues/1597)
Makefile and docs will continue to be accurate after https://github.com/spf13/cobra/issues/1597 is completed
-
xref https://github.com/spf13/cobra/issues/1597
=> Switch to standalone cobra-cli dependency

cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/main.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go
This is a prequel to #4370 . It doesn't make any functional change, but just pulls out the arguments to the dynamically loaded grpc registration function into a struct defined in the one place. This makes it easier moving forward for us to modify it when needed in the one place. Please see #4370 for an example where we ensure plugins have access to QPS and Burst options without having to change other plugins necessarily.
Easier to modify grpc registration args in the future.
- ref #4329 
I again hit an import naming issue here, because some plugins import both the generated plugins/v1alpha1 as well as our implementation module for plugins/v1alpha1. So  @antgamdia , I looked up your earlier #4176 where you'd put some thought into this and …
=> Replace args with struct for grpc registration.

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
See the [comment on the related issue](https://github.com/kubeapps/kubeapps/issues/4099#issuecomment-1057687768) for the background investigation.
This PR reduces the response time for the GetAvailablePackageSummaries RPC call of the Carvel plugin with the TCE repository (12 package metas, 18 packages) from over 5s to around 280-500ms on my local computer, without changing the functionality (~~although I've left a TODO related to one assumption which may not be correct, but it's an easy update if the assumption is false~~ Edit: I've now removed this assumption).
Timing with TCE repo after updating without assumption of version order:
```
I0304 01:28:41.068310       1 server.go:59] OK 603.570424ms /kubeappsapis.core.packages.v1alpha1.PackagesService/GetAvailablePackageSummaries
...
I0304 …
```
=> Reduce Carvel response times for GetAvailablePackageSummaries

cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
This is the same PR as at approved PR #4370 which was closed accidentally but automatically because I landed the branch it targeted.
Sets reasonable QPS and Burst for the client config used only in the discovery of the REST API (by the RESTMapper).
Before this change, registering the resources plugin took around 8 seconds due to client throttling:
```
I0302 00:40:47.539843       1 plugins.go:137] Successfully registered plugin "/plugins/fluxv2-packages/fluxv2-packages-v1alpha1-plugin.so"
I0302 00:40:48.318594       1 request.go:597] Waited for 109.310691ms due to client-side throttling,
not priority and fairness, request: GET:https://10.96.0.1:443/apis/networking.k8s.io/v1beta1
...
I0302 00:40:56.919228       1 request.go:665] Waited for 8.611529015s due to client-side throttling,
not …
```
=> Set QPS/Burst for resources RESTMapper client

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils_test.go
Fixes a test issue I noticed the other day, but wasn't sure then the best way to fix it.
The test was giving a false positive: the test appears to check that the versions are returned in the order of earliest to latest, when I knew that that wasn't the case (since code was grabbing the [0] version as the latest).
Turns out the reason it was passing was because we'd asked it to ignore all hidden fields of the struct that we were comparing - `pkgSemver` - which includes the `.version` field that we're wanting to check. So it effectively accepted any `pkgSemver` instances in the slice, it just had to be the correct length.
The update is to instead allow checking of unexported fields, but ignore the `.pkg` field that this test wasn't …
=> Fix TestGetPkgVersionsMap

docs/user/operators.md
Changed Operators documentation to mention that are disabled by default and how to enable them.
User `Sven` pointed out [in Slack](https://kubernetes.slack.com/archives/C9D3TSUG4/p1646883765921509) that operators menu had disappeared and I noticed there was no mention about it in documentation, apart from v2.4.3 release notes.
=> Add operators disabled default in documentation

.github/workflows/ci-custodian-rules.yaml
Restrict the execution of Custodian rule github action to the `kubeapps/kubeapps` repo only.
When forking Kubeapps repo, there will be no failing runs for the Github action.
=> Add repo restriction to Github action

.github/dependabot.yml
As we continue to add new github actions to the project, we need to keep them (the images) up to date; therefore, this PR is to add a dependabot step looking at these new deps.
GHA up to date.
N/A
N/A
N/A
=> Add dependabot to github actions

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
While helping @cmoulliard debug an issue he was seeing running Kubeapps with carvel support and the TAP 1.0.2 repo, we noticed that the repo itself appears to have invalid data (missing metadata for some packages). Running this locally myself, I would see the error in the UI:
> An error occurred while fetching the catalog: Invalid GetAvailablePackageSummaries response from the plugin kapp_controller.packages: rpc error: code = Internal desc = unexpected order for kapp-controller packages, expected "cnrs.tanzu.vmware.com", found "cert-manager.tanzu.vmware.com".
This is because our kapp-controller plugin was asserting that there was always one `PackageMetadata` for any package's `refName`. It turns out that sometimes invalid repositories …
=> kapp-controller plugin handles missing metadata.

dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/shared/specs/mountWrapper.tsx
See #4539 for the problem.
The fix is to remove the now incorrect assumption in the Catalog component that the kubeapps namespace is the global repos namespace.
CI passes (on GKE - haven't looked yet why this is only relevant for that env, but assume the global repos dir is set to kubeapps for the others).
- fixes #4539
Confirmed locally in CI env that this change results in the repo filter being present:
=> Don't assume kubeapps namespace is the global repos one.

script/e2e-test.sh
After fixing one issue related to the GKE environment in #4539, the prerelease CI failed again on the same tests but with a different error:
It turns out that since our CI tests were recently updated to include a private repo (no pull secrets, just repo access) in the global repos namespace, the edit service account didn't have access to read secrets in the global repos namespace.
This PR just explicitly adds this RBAC for CI, but I've left a couple of TODOs because we should clean up the CI RBAC and eventually (when it's no longer possible to use the `kubeapps` namespace for global repos) enable authenticated users to read secrets in the global repos namespace (only).
- fixes #
=> Enable CI edit user to view secrets in global repos namespace.

.circleci/config.yml, script/chart_sync.sh
CI error: /script/chart_sync.sh: line 38: README_GENERATOR_REPO: unbound variable
The release job failed with: /script/chart_sync.sh: line 38: README_GENERATOR_REPO: unbound variable
- fixes #
=> Fix the unbound env var README_GENERATOR_REPO

.circleci/config.yml, script/chart_sync.sh
Since upstream now run the readme generator as an action when PR is
created.
- fixes #
@antgamdia This PR reverts the fix I did in #4548 to ensure the env var for the readme generator repo was bound, since the run with that change successfully ran the readme generator, but then `commitAndSendExternalPR` failed with "Wrong repo path. You should provide the root of the repository", as though after the readme generator ran, the chart.yaml wasn't in the expected place.
Although I've not verified the above, I also realised that for the upstream PR against bitnami/charts, we actually don't need to run the readme generator, as it's now run automatically as an action for each PR. So this just removes that step. I'm not confident that it'll fix …
=> Remove readme-generator call for upstream PR

cmd/asset-syncer/cmd/root.go, cmd/asset-syncer/cmd/root_test.go, cmd/asset-syncer/server/utils.go, cmd/kubeops/cmd/root.go, cmd/kubeops/cmd/root_test.go
Following on from the fix for 4470, it looks like with #3449 we may have also broke the userAgent setting for kubeops and the asset-syncer.
This PR updates the tests to actually verify that the userAgent is set and fixes accordingly.
- fixes #
=> Update asset-syncer and kubeops to ensure userAgent set correctly.

.github/workflows/add-issues-to-project.yaml, .github/workflows/ci-custodian-rules.yaml, .github/workflows/custodian-rules/remove-unattached-disks.yaml
This PR simply adds a new GitHub action, extracted from [here](https://github.com/github/feedback/discussions/5378#discussioncomment-2137318), that automatically adds new issues to the board.
I've already set the proper environment variables in the GitHub repo.
Since we moved to the new projects (beta) boards, we need to add new issues there, so a change was required anyway. Besides, the current gh action we had, wasn't working at all (see https://github.com/vmware-tanzu/kubeapps/actions/runs/2114620529)
N/A
N/A
Added copyright headers that were missing.
=> Auto add issues to the new project board

.github/workflows/ci-custodian-rules.yaml
I've noticed the custodian job is failing since we transferred the repo to the `vmware-tanzu` organization. This PR is to change the hardcoded value with the correct one.
Jobs will continue to work again
N/A
N/A
@castelblanque , I wonder why we set `if: github.repository == 'vmware-tanzu/kubeapps'` instead of `if: github.repository == '$GITHUB_REPOSITORY'` or even removing this check. Perhaps there's a reason, but I don't recall it now haha.
=> Fix custodian job

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, script/makefiles/deploy-dev.mk
- Solution that works with the exception of across namespaces.
- Adapt solution to cater for requests across namespaces.
I thought this was going to be similar to #4378 but although a similar approach can be taken, the solution is quite different, due to the iteration of package installs (rather than metadata).
It also ended up substantially more complicated for two reasons that I've highlighted in the code with a comment.
Response times are approximately 1/6th for fetching installed package summaries (tested locally with 10 installed packages).
- fixes #4542
=> Fix timeout for Carvel installed package summaries

cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Updates the `GetInstalledPackageResourceRefs()` call so that it will not wait indefinitely (or until a timeout) for the kapp config map to have been created.
Instead, the code now returns a NotFound error immediately, which is already handled by the dashboard code with an explanatory comment at:
https://github.com/vmware-tanzu/kubeapps/blob/06774a4476219b6e031b5b2fb436f1c12a8048bd/dashboard/src/components/AppView/AppView.tsx#L180-L187
We neither wait for a timeout, nor do we switch to an error after the timeout, fixing case 2 of #4614 .
- fixes #4614
I'll now check the case 1 situation, which may be harder (optimizing the response when all the data is there). EDIT: Nothing to do there, even for a kubeapps carvel install, …
=> Return NotFound immediately when kapp configmap not found.

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_integration_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/integration_utils_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_integration_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_integration_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go
Documented behavior in the spec (under GetPackageRepositoryDetail 
https://docs.google.com/document/d/1z03msZRGsRvcRaom-yrvEwIWcEfNy6fSA5Zg28gjYvA/edit#heading=h.ou8mya83exsw and UpdatePackageRepository https://docs.google.com/document/d/1z03msZRGsRvcRaom-yrvEwIWcEfNy6fSA5Zg28gjYvA/edit#heading=h.gd8t5sfz32li) as per agreement with team
Implemented according to spec in the flux plugin
=> hide sensitive data for GetPackageRepoDetail and UpdatePackageRepository with kubeapps managed secrets

docs/howto/OIDC/OAuth2OIDC-VMware-cloud-services.md, docs/howto/OIDC/OAuth2OIDC-azure-active-directory.md, docs/howto/OIDC/OAuth2OIDC-debugging.md, docs/howto/OIDC/OAuth2OIDC-keycloak.md, docs/howto/OIDC/OAuth2OIDC-oauth2-proxy.md, docs/tutorials/kubeapps-on-tkg/step-2.md
I've noticed we left unchanged some of our docs during the chart standardization. Specifically, with respect to this change:
>- `authProxy.additionalFlags` renamed as `authProxy.extraFlags`
This PR is to update our docs to to use `extraFlags` instead of `additionalFlags`.
Our docs will be up to date and will be consistent with our current chart values.
N/A
N/A
There is still another file using `additionalFlags`, but it is the chart readme, so we better change it upstream, so that the change get published sooner.
=> Rename `additionalFlags` to `extraFlags`

.circleci/config.yml, cmd/apprepository-controller/Dockerfile, cmd/asset-syncer/Dockerfile, cmd/asset-syncer/server/postgresql_db_test.go, cmd/assetsvc/Dockerfile, cmd/assetsvc/pkg/utils/postgres_db_test.go, cmd/kubeapps-apis/Dockerfile, cmd/kubeops/Dockerfile, cmd/pinniped-proxy/Dockerfile, dashboard/Dockerfile, docs/reference/developer/release-process.md, script/e2e-test.sh
As part of the release process, this PR is to update several dependencies used in our CI; from the versions of the images we use to the default Kubernetes version.
The referenced versions in our CI will be up to date.
N/A (let's the CI speak itself :P)
- related#4661
I've updated the release process docs as it included several broken links.
=> Update CI vars

dashboard/src/actions/availablepackages.test.tsx, dashboard/src/actions/availablepackages.ts, dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/components/Catalog/CatalogItems.test.tsx, dashboard/src/components/Catalog/CatalogItems.tsx, dashboard/src/components/PackageHeader/PackageView.test.tsx, dashboard/src/reducers/availablepackages.test.ts, dashboard/src/reducers/availablepackages.ts, dashboard/src/shared/PackagesService.test.ts, dashboard/src/shared/PackagesService.ts, dashboard/src/shared/types.ts
This is the first step towards fixing #3399 . When we initially updated the dashboard to use the new UX, we'd encoded knowledge of the pagination token in the frontend, which we really need to avoid. The plugin should simply be able to set the `NextPageToken` in the response and the client sends that back with the next request.
The main change is to remove the `page` (int) state and replace it with the token verbatim which is returned by the API. There was one existing point where we need to track which page number to avoid jitter (? not sure, didn't verify, just maintained the same behaviour) so the page state is still counted within the catalog view but not used for anything other than calculating `isFirstPage` for the CatalogItems component.
I'd like to encode more info into the next …
=> Remove knowledge of pagination internals from UX/Client

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_test.go
Updates the core packages plugin so that if only a single plugin is used, it will pass through the pagination options and return the next page token of the plugin.
This small change (on top of #4654) will allow me to start updating the individual plugins without affecting the combined behaviour for now.
I can continue by next updating the helm plugin from a page number to an item number.
- ref #3399
=> Use pagination options with plugin when only one plugin configured.

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
See #3399 for the background. This PR follows #4659 which updated the Helm plugin to use an item offset rather than a page offset, and makes the same change for the kapp_controller plugin (which just works seamlessly now that the Dashboard UX client does not introspect the page token at all).
Checked in real life:
2 down, 1 to go (Flux). This will enable to core plugin to interleave paginated results from plugins.
- Ref #3399
=> Update Carvel plugin to use an item offset rather than page offset.

cmd/kubeapps-apis/cmd/root_test.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, pkg/kube/kube_handler_test.go, pkg/kube/kube_utils_test.go
Since I am temporarily running a Windows system, I've noticed that some of our tests are not ready to run there (asserting non-existing error messages, dealing with files and env vars, etc...), so, even we decrease the test coverage when running tests on windows, at least, we won't get consistently failing tests anymore.
We will be able to run our test suite on Windows without false positives.
Less coverage on Windows.
N/A
N/A
=> Skip some tests when running on Windows

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/pkg/paginate/paginate.go, cmd/kubeapps-apis/plugins/pkg/paginate/paginate_test.go
Follows on from #4678 with the similar change for the flux plugin.
Verified it works in real life:
The existing unit tests for pagination still pass because they use a pageSize of 1, so that an itemOffset is the same as a pageOffset.
Haven't checked @gfichtenholt 's integration tests. Might give them a spin after lunch and see (but they shouldn't be affected unless they're introspecting the page token).
~~Hmm, also didn't update the repo endpoints which I assume use the same/similar pagination. Marking this as a draft until I've done that~~ Checked, they don't use pagination.
Now I can do the core pagination :)
- ref #3399
=> Update flux plugin to use item offset rather than page offset.

cmd/asset-syncer/server/sync.go, cmd/asset-syncer/server/utils.go
just print logs if helm repo empty instead throws error
sync job will come to a Compelte state instead of error, it's more user-friendly
- fixes #4611
=> logs if helm repo empty instead throws error

dashboard/.eslintrc.json, dashboard/tsconfig.json
This PR just increases the ecmascript version we are transpiling to from ES2020 to ES2022 (to be officially released in June)
Some interesting features have been added since 2020. For instance, the `replaceAll` function or the logical assignments operators (like `??=`). More info below:
https://dev.to/naimlatifi5/ecmascript-2021-es12-new-features-2l67
https://dev.to/faithfulojebiyi/new-features-in-ecmascript-2021-with-code-examples-302h
N/A
- related #4661
N/A
=> Bump ECMAScript version up to 13

cmd/apprepository-controller/Dockerfile, cmd/asset-syncer/Dockerfile, cmd/assetsvc/Dockerfile, cmd/kubeapps-apis/Dockerfile, cmd/kubeops/Dockerfile
Trivial PR upgrading the go versions of our dev container images.
Go 1.18.2 includes security fixes to the syscall package. Not sure it is relevant for us, but it's good to keep our imgs up to date.
N/A
- related #4661 
N/A
=> Update go versions

dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/reducers/availablepackages.test.ts, dashboard/src/reducers/availablepackages.ts
This change is to fix an issue that I've identified as part of #4694, where we have a tension between global redux state and local state.
The issue is that:
- We currently use global redux state, so if you navigate to the catalog and then navigate away, the state of the catalog is retained (items, last token etc.)
- When you navigate back to the catalog, an initial request goes off to fetch the available package summaries, followed by another effect to reset the state
Two possible approaches:
1. Update the reset effect so that it is only run when a dependency changes (not on the initial render) - this is what's done here, but it means we'd also need to reset the state separately when the namespace is changed outside of the component (may …
=> Don't reset catalog on first render.

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_fan_in.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_test.go, cmd/kubeapps-apis/plugin_test/mock_plugin.go, cmd/kubeapps-apis/plugins/pkg/paginate/paginate.go
Updates the core plugin's GetAvailablePackageSummaries so that it outputs ordered results from multiple configured plugins.
It does this by deferring to a new helper function `fanInAvailablePackageSummaries()`. See inline comments for details.
Example of paginated responses coming back with combined, ordered results of Helm and Carvel packages:
We can paginate aggregated results on the core packages `GetAvailablePackageSummaries` end point. 
Currently two issues I need to fix:
1. ~~Currently, it returns the combined results correctly for the first 70 results (helm + carvel), until, it seems, when it hits a streak where the whole page is from one plugin only, it then does not include the other plugins offset in the result, so that plugin …
=> Enable fan-in of results for summaries from plugins.

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_fan_in.go, dashboard/src/shared/InstalledPackage.ts
Follows on from #4694 , applying the same functionality to the core `GetInstalledPackageSummaries` handler.
~~It does not yet work, because the dashboard client is currently assuming knowledge of the pagination token, so I need to do a separate PR for the dashboard to remove that assumption for `GetInstalledPackageSummaries`, as I did earlier for the available packages in the dashboard (hence being a draft).~~ EDIT: it ended up only requiring a 2-line change to the dashboard so I've just included it in this PR.
Works to display correlated installed package summaries:
Core pagination for multiple plugins will display installed packages in order efficiently.
- ref #3399 
I did play a little with generics at first but couldn't yet see a …
=> Updates core installed pkg summary handler for pagination.

ROADMAP.md
Update roadmap.md file to include Kubeapps epics planned for FY23-Q2 (May-Jul 2022)
This should serve as a reference point for Kubeapps users and contributors to understand where the project is heading, and help determine if a contribution could be conflicting with a longer term plan.
None
- related #4734
=> Update Kubeapps roadmap for FY23-Q2

dashboard/src/components/AppList/AppListItem.test.tsx, dashboard/src/components/AppList/AppListItem.tsx
Simple PR just adding the plugin name to the installed package summaries view as we were doing for the catalog view.
More consistent view with the catalog.
N/A
- fixes #4727
Perhaps worth adding a test case? I'll look into it tomorrow.
=> Add plugin name to the cards in the installed pkgs view

cmd/kubeapps-apis/docs/kubeapps-apis.swagger.json, cmd/kubeapps-apis/proto/kubeappsapis/apidocs/v1alpha1/apidocs.proto, dashboard/package.json, dashboard/public/index.html, dashboard/src/components/AppView/AppNotes/AppNotes.tsx, dashboard/src/components/Layout/Layout.scss, dashboard/yarn.lock
In https://github.com/vmware-tanzu/kubeapps/pull/4143 we added markdown rendering to the app notes, but it resulted in a wrong hanling of the break-lines, as @dud225 described at https://github.com/vmware-tanzu/kubeapps/issues/4395.
In https://github.com/remarkjs/react-markdown/issues/278#issuecomment-971909964 I saw using `remark-breaks` could make the trick for us. Therefore, this PR is just removing the old way to handle the word wrapping using css and replacing it instead with this remark plugin.
Better handling of the break-lines.
N/A
- fixes #4395
See [my comment ](https://github.com/vmware-tanzu/kubeapps/issues/4395#issuecomment-1134804347) with examples and pics.
_Squeezing some typo-fxing in here :P_
=> Use `remark-breaks` instead of a css `pre-wrap`

script/makefiles/cluster-kind.mk, site/content/docs/latest/tutorials/getting-started.md, site/themes/template/layouts/partials/use-cases.html
With 1.24, token secrets are not created automatically for a service account. Updated our getting started to create the secret with the required annotation to be populated with a valid token, and update the instructions to just get that token (more simple anyway).
Verified this works both with k8s 1.24 and 1.21 .
Avoid confusion with token auth moving forward as more people use 1.24
- fixes #4763
=> Update the token-auth example for getting-started.

cmd/apprepository-controller/server/controller.go, cmd/apprepository-controller/server/controller_test.go
This PR addresses #4061 by truncating (+hashing) a cronjob name up to its 52-chars limit. The rationale has been:
Our cronjob's names have: 1) a fixed part `apprepo--cleanup--` and `apprepo--sync-`; 2) a namespace name; 3) a job name.
Whereas we don't want to change anything from 1), 2) and 3) can, on their own, have up to 63 characters. So, in theory, until now, we can exceed the 126 characters... far distant from the 52-chars limit.
So, in this PR I'm truncating both 2) and 3), but, in order to avoid name collisions, a hashing function is applied if possible. After having a look at some hashing functions producing short checksums, two main options were `fletcher` and `adler` in their 32-bit version. Having compared the chances of a collision [1] and given they both produces similar …
=> Truncate cronjobs' names

dashboard/craco.config.js, dashboard/package.json, dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx, dashboard/src/components/LoadingWrapper/LoadingWrapper.test.tsx, dashboard/src/components/js/Card/components/CardImage/CardImage.test.js, dashboard/yarn.lock
Today, I performed a `yarn install` to update my local deps with the latest dependabot updates. However, I got an error related to webpack 4 not being able to parse some new(ish) JS features like nullish coalescing or optional chaining. The offending dependency was the latest version of `yaml` dependency that we recently updated.
Instead of work around this issue, I decided to invest some time to look into #4018.
This PR updates to CRA >=5 adding the usual workaround I mentioned in the aforementioned issue: adding the polyfills manually.
However, instead of adding them independently, I've added `node-polyfill-webpack-plugin`, which should add the required ones more transparently.
The webpack tweak is performed using `craco` a tool to inject some webpack configuration without ejecting the …
=> Update to CRA 5

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/repositories.go, dashboard/src/actions/namespace.test.tsx, dashboard/src/components/AppList/AppList.test.tsx, dashboard/src/components/AppList/AppList.tsx, dashboard/src/components/AppView/CustomAppView/CustomAppView.test.tsx, dashboard/src/components/Catalog/CatalogItems.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx, dashboard/src/components/Config/AppRepoList/AppRepoList.tsx, dashboard/src/shared/KubeappsGrpcClient.test.ts, dashboard/src/shared/KubeappsGrpcClient.ts, dashboard/src/shared/utils.ts
As part of the work required for #4764, this prequel PR adds minor stuff that I can easily have taken apart from my ongoing changes. Namely:
- Related to the Repos UI:
- Add more information to the core API logs 
- Add more str cases in getPluginPackageName 
- Add repos api clients to KubeappsGrpcClient 
- Minor unrelated improvements
- Handle uncaught `canI` rejections 
- Remove "as unknown" in some types 
- Return 0 if equals in a sort function 
Subsequent PRs will have less code to review :P
N/A
- related #4764
The changes are pretty unrelated to the actual repos API things, as they are mainly improvements on other parts of the code.
=> Add minor improvements prior to the repos UI

integration/tests/operators/06-operator-deployment.spec.js
Simply set global deployment timeout for test when deploying an operator.
Reasoning behind is that e2e tests where randomly failing due to operator not yet ready when the test continued after the waiting timeout.
Did 10 runs on CircleCI that can be checked [here](https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps?branch=4832-operators-e2e-tests&filter=all). None of those failed.
E2E test should not fail, at least not that often.
E2E may take a little more time, but due to operators being deployed actually.
- fixes #4832
=> New deployment timeout for Operators

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/pinniped.rs, script/makefiles/deploy-dev-for-pinniped.mk, site/content/docs/latest/reference/developer/pinniped-proxy.md
Just a fly-by while getting setup with pinniped-proxy locally again, this PR does 3 things:
* Updates to use the latest pinniped version (0.17.0) in our dev environment
* Updates the dev environment targets to allow creating a single-cluster environment
* Simplifies the `identity_for_exchange` now that the underlying `native_tls::Identity` supports creating an identity cert directly from an x509.
Simpler code, easier dev env.
- ref #2875
Although I've tested in real life, I'm keen to see if it's trivial to add a unit test for this also, so leaving in draft until I've tried.
=> [pinniped-proxy] Create identity cert directly from x509.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
New repositories API adds field `interval` when adding/updating a repo.
It is not possible to map that field to any field in the existing CR `AppRepository`, and `syncJobPodTemplate` is not used anymore.
This PR adds a check for the Helm plugin to return error when `interval` has been specified.
Interval data posted to the API will not be swallowed and will produce an error.
N/A
None
=> Add check for interval in Helm Repository API

script/e2e-test.sh
I came across this `helm test ...` command in the CI script and, as far as I am concerned, we removed the helm tests a long time ago. This PR is to remove this piece of code performing an extra helm test.
Less unused code
N/A 
N/A
If I'm mistaken and this piece of code is indeed useful, I'm happy to close the PR :P
=> Remove helm test in CI

dashboard/src/components/Layout/Layout.scss
As reported by @dud225, we were adding an extra margin in the installation notes box. This PR is to remove it.
> _(installation notes)_ to be absolutely perfect 
😛 
N/A
- related #4395
Before:
After:
=> Remove unnecesary extra margin-top

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/expired_value_cache.rs, cmd/pinniped-proxy/src/main.rs
Adds an implementation of the [cached trait](https://docs.rs/cached/latest/cached/trait.Cached.html) that allows a cached value to determine if it has expired or not. If it has expired when fetched from the cache, it is removed.
We can use this for caching the pinniped `ClusterCredential` rather than fetching it for every user request.
- ref #2875
=> Add expired value cache.

site/content/docs/latest/reference/developer/release-process.md
Yesterday I wrongly merged #4911 with a typo (double brackets) in an md file. This was preventing the website from being rendered. I assumed it was a transient error... sorry, my bad 😅 
Netlify checks will work again
N/A
N/A
N/A
=> Fix typo in md

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/cli.rs, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/tls_config.rs
After playing around with different options, this appears to be the simplest way to add tls support to pinniped-proxy without breaking the existing non-tls setup.
I'm leaving this as a draft until I figure out how TLS on the related service will interact with this. After that, it should just be updating the api server to be able to trust the cert, then the related chart changes.
- fixes #
=> Add TLS support to the pinniped-proxy directly.

chart/kubeapps/README.md, chart/kubeapps/templates/frontend/deployment.yaml, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeops/deployment.yaml, chart/kubeapps/values.yaml, site/content/docs/latest/howto/OIDC/using-an-OIDC-provider-with-pinniped.md
Following on from #4958, this PR updates the kubeapps chart to:
- supply the pinniped-proxy service with the tls cert and key, when the secret is specified
- supply the clients of pinniped-proxy (kubeappsapis, and currently still kubeops) with the related CA cert.
The pinniped-proxy service can run as a TLS web service, when configured so.
- ref #2268
=> Update chart to support TLS for pinniped-proxy

cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go
This bugfix tackles the issue of `GetAvailablePackageVersions` in Helm direct plugin not returning the correct versions list when the input versions are not ordered.
We had all input values in our tests correctly sorted, which might not be the case on runtime.
[See here.](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go#L31)
Solution done here is to sort versions first thing in [PackageAppVersionsSummary](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go#L57).
Versions returned by `GetAvailablePackageVersions` should be correct now.
Solution modifies `pkgutils.PackageAppVersionsSummary` function, which applies to Flux …
=> Add fix for Helm charts versions ordering

cmd/kubeops/cmd/root.go
When triggering the release, we noticed some failures in the "upgrade chart" test case due to some assetsvc-related params being still used. We decided to postpone the removal until de v2.4.6 was out.
This PR is simply removing this unused cmd argument.
No more assetsvc-related code.
N/A
- related #4936
CI will fail unless Bitnami releases the new chart version :S
=> Remove temporary cmd arg for assetsvc

chart/kubeapps/Chart.yaml, script/chart-template-test.sh
I wasn't aware that Helm allows setting the minimum k8s version until people from Content team just told me. In our case, we are relying on certain resource versions (especially, cronjobs `v1` instead of `v1beta`, see #3846) and, when we update them, we are not backward compatible. 
We will be clear about the version we do support.
Users won't be able to install Kubeapps on unsupported versions, which might be not ok in some cases (people working on old k8s versions not using those old resource versions, for instance, just using the flux or carvel plugin instead of the helm one).
N/A
Happy to close the PR if we don't really like the outcome as described above.
=> Specifiy the mininum k8s version in the chart

cmd/apprepository-controller/artifacts/examples/crd.yaml, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/reducers/kube.ts, pkg/agent/docker_secrets_postrenderer.go, site/content/docs/latest/howto/OIDC/OAuth2OIDC-oauth2-proxy.md, site/content/docs/latest/reference/proposals/authentication-and-authorization.md
During the release process, I've noticed we have some old kubernetes resources versions out there. This PR is just to use the proper resource versions as per the current Kubernetes version 1.22.
We won't have any outdated (and potentially unsupported) group resource version in our examples and docs.
N/A
N/A
N/A
=> Use k8s stable versions as per v1.22

cmd/kubeops/Dockerfile, cmd/kubeops/internal/handler/handler.go, cmd/kubeops/internal/httphandler/http-handler.go, cmd/kubeops/internal/response/response.go, cmd/kubeops/server/server.go
After reporting #4810 , I've added the linter just in the `kubeops` code . 
The building is gonna fail now, but if we start fixing the issues, we will be, eventually, able to merge this PR.
Prevent new `gosec` issues.
N/A
- related #4810 
N/A
=> Add gosec to kubeops

cmd/apprepository-controller/Dockerfile, cmd/apprepository-controller/server/controller.go
After reporting #4810 , I've added the linter just in the `apprepository-controller` code . 
The building is gonna fail now, but if we start fixing the issues, we will be, eventually, able to merge this PR.
Prevent new `gosec` issues.
N/A
- related #4810 
N/A
=> Add gosec to apprepository-controller

cmd/asset-syncer/Dockerfile, cmd/asset-syncer/server/postgresql_utils.go
After reporting #4810 , I've added the linter just in the `asset-syncer` code . 
The building is gonna fail now, but if we start fixing the issues, we will be, eventually, able to merge this PR.
Prevent new `gosec` issues.
N/A
- related #4810 
N/A
=> Add gosec to asset-syncer

dashboard/src/shared/Config.ts, dashboard/src/shared/I18n.ts, dashboard/src/shared/Kube.ts, dashboard/src/shared/Namespace.ts, dashboard/src/shared/url.ts
This PR performs a quick review on the UI calls to kubeops. As this component will be deprecated soon, we should start migrating those calls to the kubeapps-apis component.
The PR just adds a comment on those calls to be migrated, as well as centralizes some sparse URLs into the `url.ts` file.
Knowing what to migrate will be easier.
N/A
- related https://github.com/vmware-tanzu/kubeapps/issues/4785
N/A
=> Mark old kubeops calls to be migrated to the resources API

pkg/chart/chart.go, pkg/http-client/httpclient.go, pkg/tarutil/tarutil.go
Trivial PR just removing some references to Tiller in the code. It is just a reminiscence of the Helm 2 times and it is no longer used since many releases ago.
No more references to old parts of Kubeapps.
N/A
- related #4785 
N/A
=> Remove refs to tiller in the code

cmd/apprepository-controller/Dockerfile, cmd/asset-syncer/Dockerfile, cmd/kubeapps-apis/Dockerfile, cmd/kubeops/Dockerfile, pkg/dbutils/dbutilstest/pgtest/pgtest.go, pkg/helm/index.go, pkg/http-client/httpclient.go, pkg/kube/kube_handler.go, pkg/kube/kube_utils.go, pkg/tarutil/tarutil.go
After reporting #4810 , I've added the linter just in the `pkg` code . 
The building is gonna fail now, but if we start fixing the issues, we will be, eventually, able to merge this PR.
Prevent new `gosec` issues.
N/A
- fixes #4810 
Draft as it requires the rest of PRs to be merged.
=> Fix rest of gosec issues under `pkg`

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
I've noticed the Helm plugin is not setting the `status.ready` field. As it defaults to `false`, the UI shows misleading information to the users. This PR sets it to `true`, but ideally, we would want actually to query the status of the repo sync.
No more misleading "not ready" info to the users.
A failed sync job will still be marked as "ready" when it is not. However, this is the initial behavior and there is another (old) issue tracking it: #153. 
- related https://github.com/vmware-tanzu/kubeapps/issues/4764
This is just a workaround, but we should be able to query, somehow, the status of an AppRepository job's execution.
=> Add status helm repos API

site/content/docs/latest/reference/developer/style-guide.md
Add writing style guidelines to follow for the Kubeapps documentation
Make Kubeapps documentation clearer, more homogeneous and simple for contributors and users.
Guidelines to follow in Kubeapps documentation, so a revision of Kubeapps documentation is necessary.
- fixes #5019
=> Add guidelines for documentation style

dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx, dashboard/src/reducers/repos.ts, dashboard/src/shared/PackageRepositoriesService.ts, dashboard/src/shared/types.ts
This PR performs the same renames done at https://github.com/vmware-tanzu/kubeapps/pull/5046, but in the new repos API's code.
Consistent naming
N/A
- fixes #5016
N/A
=> Rename the repos API's custom detail name field - 2

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx, dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoButton.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoButton.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoList.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx, dashboard/src/components/SelectRepoForm/SelectRepoForm.test.tsx, dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx, dashboard/src/reducers/repos.test.ts, dashboard/src/reducers/repos.ts
This PR removes several no longer used fields from the PkgRepo state as well as some unused actions from its reducer.
Less unused code!
N/A
- fixes #5061
From
```js
{
addingRepo: false,
errors: {},
form: {
name: "",
namespace: "",
show: false,
url: "",
},
isFetching: false,
isFetchingElem: {
repositories: false,
secrets: false,
},
validating: false,
repo: {} as PackageRepositoryDetail,
repos: [] as PackageRepositorySummary[],
imagePullSecrets: [],
};
```
to
```js
initialState = {
errors: {},
isFetching: false,
repo: {} as PackageRepositoryDetail,
repos: [] as PackageRepositorySummary[],
};
```
Also, after this cleanup, the isFetching property is used to prevent the form from being sent multiple times:
=> Clean up unused vars from the pkgRepo state

cmd/apprepository-controller/Dockerfile, cmd/apprepository-controller/cmd/root_test.go, cmd/asset-syncer/Dockerfile, cmd/asset-syncer/cmd/root_test.go, cmd/asset-syncer/server/postgresql_db_test.go, cmd/asset-syncer/server/sync.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeops/Dockerfile, cmd/kubeops/cmd/root_test.go, cmd/kubeops/internal/response/response_test.go
This PR is aimed at fixing those issues in the `kubeops`, `asset-syncer`and `apprepo-ctrl` components. Some of them has been fixed and other, just marked as `nolint`.
Once we fix every issue, we will be able to merge the PR and therefore detect any linter issue before merging a PR.
N/A
- related #3087
N/A
=> Add gh linter - fix issues in kubeops, asset-syncer and apprepo-ctrl

site/netlify.toml
Netlify builds often fail because there is no new content added to the website. It compares the cached version with the PR's (to main) content and given there are no changes, no deploy action is performed. Adding an ignore clause to netlify.toml file to prevent this situation, so builds only proceed when changes in the base directory (/site).
- Save some building cycles for netlify.
- Avoid the "failed" badge for netlify on top of our readme.
N/A
- fixes #4878
=> Add ignore clause to netlify builds

dashboard/src/reducers/availablepackages.test.ts, dashboard/src/reducers/availablepackages.ts
Since the API (after pagination) is returning the categories for the current chunk of pkg repos, replacing the whole `categories: xxxxx` leads to end up with an incomplete set of categories, as reported in the issue.
This PR aggregates the categories like we are doing for the packages.
Categories won't get overridden on each chunk.
N/A
- fixes #5066
~Draft as I have to write a test to prevent regressions.~
=> Avoid overriding categories on each chunk

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/docker_reg_v2_repo_lister.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo.go, go.mod, go.sum
Uptake oras.land/oras-go/v2 v2.0.0-rc.1 which fixes https://github.com/oras-project/oras-go/issues/196
=> flux OCI support part 5

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/globals_vars_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, dashboard/src/actions/repos.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx, dashboard/src/shared/PackageRepositoriesService.test.ts, dashboard/src/shared/PackageRepositoriesService.ts, dashboard/src/shared/types.ts
This PR simply performs a consistent rename from `customDetails` (note the final `s`) to `customDetail` (as defined in the proto file).
Today, the custom details weren't being processed simply due to this extra `s`.
N/A
- related #4764 
N/A
=> Rename to `customDetail`

site/content/docs/latest/howto/private-app-repository.md
After an internal conversation, we noticed we haven't documented how to run our apprepo sync behind a proxy. This PR is to document that (regardless of any future action we should carry out for ensuring the feature parity in the new Repos API).
Users will have a piece of documentation on how to run sync jobs behind a proxy.
N/A
- fixes #5005
N/A
=> Add docs about running repo syncs behind a proxy

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/globals_vars_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, pkg/chart/chart_test.go, pkg/http-client/httpclient_test.go, pkg/kube/kube_utils_test.go
This PR addresses the Bearer authentication in the two plugins supporting it (Helm and Carvel) and makes the implementation "prefix-safe". Regardless of what the API client send (either `Bearer foo` or `foo`) the prefix will be trimmed out and the secret's content will become `Bearer foo`.
The UI will be able to send the bearer token regardless of the plugin's implementation.
N/A
- fixes #5028
I haven't changed anything related to the terminology as, in supporting both (prefixed/non-prefixed) the "token" can actually be the token and not the whole header. Anyway, happy to rename if you still think so.
Edit: squeezing some golang-ci-lint-related code; the tool (used in the gh action) got updated and new checks were being triggered. Ignoring them as it is just code used for testing.
=> Make repos' bearer auth prefix-safe

.circleci/config.yml, Makefile, integration/.gitignore, script/e2e-test.sh, site/content/docs/latest/reference/developer/release-process.md
While working on the e2e tests I noticed we had a hardcoded CharMuseum version, this PR is extracting the version into a separate variable so that we can properly update it.
CM cersion management will be aligned with the rest of the CI component's
N/A
- fixes #5118
N/A
=> Make ChartMuseum CI version configurable

integration/playwright.config.js
E2E tests output in CI shows a red error message saying
```
Configuration Error: HTML reporter output folder clashes with the tests output folder:
html reporter folder: /app/reports-html
test results folder: /app/reports
HTML reporter will clear its output directory prior to being generated, which will lead to the artifact loss.
```
This might be due to some path pattern usage that Playwright does.
Both paths have been made different with this PR.
E2E CI tests not display the red message about wrong report path anymore.
N/A
N/A
=> Fixed E2E tests reporting output

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/globals_vars_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go
This PR adds the handling of global secrets that affects to namespaced package repositories with secrets related.
Asset-syncer spings up the sync jobs **in the global namespace** and therefore it is requiring every namespace repo's secret to be copied to that location. Otherwise, private repos won't sync. 
This management wasn't implemented yet in the new package repos API logic.
This wasn't, and isn't the best solution (cloning secrets into the global ns) but for now we have followed the same approach as in the old implementation.
Repos controller can find now the secret for namespaced repositories in the global namespace.
Maybe some edge cases not yet detected where repository controller needs the global secret? Can't think of …
=> Added Helm global secret for namespaced repos

site/content/docs/latest/reference/developer/issue-triage-process.md
Update issue triage documentation to add a new label for multi-cluster support.
Accurate categorization by using GitHub labels.
Maintainability of labels.
=> Update triage document to add component/multi-cluster label

.circleci/config.yml
This trivial PR just adds the docker registry credentials when pulling the images used in the CircleCI runners.
Avoid rate limits, maybe?
N/A
- fixes #2985
After and before:
=> Add credentials when pulling img in CI

site/content/docs/latest/howto/syncing-apprepository-webhook.md, site/content/docs/latest/tutorials/getting-started.md, site/content/docs/latest/tutorials/kubeapps-on-tce/02-TCE-unmanaged-cluster.md, site/themes/template/layouts/partials/use-cases.html
This commit simplifies some of the instructions to run kubeapps locally.
Signed-off-by: Jesús Miguel Benito Calzada <beni0888@hotmail.com>
Removes a redundant/overwritten parameter in a CLI command. 
Makes the instructions clearer.
=> Simplify instructions in getting-started.md

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_utils_test.go
As stated in https://github.com/vmware-tanzu/kubeapps/issues/5165, we were not filtering by repos in the carvel plugin. This PR is merely to implement it and handle the scenario of an empty result.
The filter by repo will actually work in backend (so no unnecessary data will be sent over the wire when requesting pkg from a repo).
N/A
- fixes #5168
N/A
=>  Add filtering by repos in carvel pkgs

dashboard/.gitignore, dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
Trivial PR that fixes issue in the multicluster mode that was showing buttons for managing repos when on additional clusters. This actions are not valid in that scenario.
Those buttons are not appearing anymore in additional clusters.
Users will not get the repository creation dialog on additional clusters -a feature not available in Kubeapps so far- and thus will not get an error when trying to create a repo.
N/A
=> Fixed repo mgmt buttons showing in additional clusters

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/globals_vars_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go
With the introduction of #5140, the secret for namespaced repos was being copied to the global namespace, which is incorrect.
The right one is the **kubeapps** namespace. Both are equal by default, but when `apprepository.globalReposNamespaceSuffix` is specified, syncer job runs in kubeapps namespace, and secrets are being created in the global namespace. This leads the syncer job creation to fail with error: `Error: secret "test-apprepo-example-repo" not found`.
This PR changes logic when creating and updating package repos so that secrets are copied to the `kubeapps` namespace if repo wasn't created in that namespace. In this way, we make sure that asset syncer has the secret available.
Namespaced repos can be synced correctly …
=> [Helm plugin] Changed repo secrets copied now to Kubeapps namespace

dashboard/public/openapi.yaml
In a previous API docs update, we wrongly removed the `/apis` prefix, which is added by the nginx for accessing the kubeapps-apis service. This PR is adding the prefix back as well as marking as deprecated some kubeops endpoints that will be deleted in upcoming releases. 
Users will be able to use the API from the UI.
N/A
- fixes #5166
=> Fix api docs prefix

integration/tests/main/03-create-private-package-repository.spec.js, integration/tests/main/10-deploy-package-with-private-image.spec.js
In previous PRs we have been extensively working on the new repos API and UI. However, the integration wasn't fully working due to several blocking issues.
This PR is to re-enable some commented-out test cases we had disabled.
Once passing, we should be able to start creating the PR against `main`, as, in theory, it wouldn't break the current UX.
If they don't work, we might discover additional issues we have to fix 😝 
- fixes #4876
N/A
=> Add pending e2e tests for the repos UI

script/install-local-registry.sh, script/makefiles/deploy-dev-for-pinniped.mk
Added some improvements (e.g. variable checks) to a E2E script and the Pinniped makefile of the project.
More robust scripts in the project, and usable from local command line too.
N/A
=> Small improvements in scripting

dashboard/src/actions/availablepackages.test.tsx, dashboard/src/actions/availablepackages.ts, dashboard/src/components/Catalog/Catalog.test.tsx, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/reducers/availablepackages.test.ts
- Even if we implement the other mitigations, there are still some edge cases where the state remains inconsistent. For instance, when selecting a repo filter, scrolling down (to trigger pagination), or selecting another repo filter (to unmount the component)... would lead to a request made to the API when the app is in an `isFetching=true` state.
- The proposed solution is twofold:
- Absorb small race conditions with a dummy wait: this will prevent most of the errors to appear, because it will simply retry the request in 1 or 2 seconds. It requires storing a local copy (component's state) of the `isFetching` global state var.
- Return an error if a "request_packages" request arrives at the state reducer while in an `isFetching=true` state. The UI will simply show a "try again" button, …
=> Debounce isFetching in the catalog ui

chart/kubeapps/README.md, chart/kubeapps/templates/frontend/deployment.yaml, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeops/deployment.yaml, chart/kubeapps/values.yaml, site/content/docs/latest/howto/OIDC/using-an-OIDC-provider-with-pinniped.md
Renames a couple of chart values regarding TLS for Pinniped proxy.
```
pinnipedProxy.TLSSecret --> pinnipedProxy.tls.existingSecret
pinnipedProxy.CACert    --> pinnipedProxy.tls.caCertificate
```
Kubeapps chart is in line with TLS parameters used by Bitnami.
N/A
- fixes #5191
=> Rename Pinniped Proxy TLS values in chart

script/makefiles/deploy-dev-for-pinniped.mk
Trivial PR fixing the instructions to deploy/undeploy Pinniped that exist in the makefile.
Based on input from [this Pinniped issue.](https://github.com/vmware-tanzu/pinniped/issues/1251#issuecomment-1210935999)
Pinniped can be correctly deployed and undeployed using Makefile.
N/A
- related #5189
=> Fixed Pinniped makefile instructions

dashboard/src/actions/installedpackages.test.tsx, dashboard/src/actions/installedpackages.ts
This PR adds a check before getting the installed pkg status: "if there is not an active subscription, skip the process". This way, when unmounting components, like when we are deleting a package (we get redirected to the apps view), the fetch won't happen. 
If the app had been deleted, the fetch would have failed, showing an unpleasant error back to the user. 
N/A
- fixes #5205
N/A
=> Skip re-fetching deleted installedPkgs status

.circleci/config.yml, integration/tests/operators/06-operator-deployment.spec.js
It seems a new operator has been added and we are installing this new one instead of the expected one. See screenshot:
The new operator is indeed failing, therefore, the test case is failing too.
```
install failed: deployment ack-prometheusservice-controller not ready before timeout: deployment "ack-prometheusservice-controller" exceeded its progress deadline
```
We need to make the selector more specific so that we really select the one we are expecting.
CI will pass again.
N/A
- fixes #5225 
N/A
=> Fix olm test case

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Catalog/Catalog.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx, dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx, dashboard/src/shared/utils.test.ts, dashboard/src/shared/utils.ts
Since the OCI support in Flux was something in progress, we didn't allow adding OCI repos in the past release. As we are implementing this support, the UI should also support it.
In this PR I'm also squeezing a fix for a regression we've had: Flux repos couldn't be created as they need to be global. This was broken in the https://github.com/vmware-tanzu/kubeapps/pull/5203 hotfix.
Besides, this PR fixes several minor problems, namely:
- Rename to `setInterval` to `setSyncInterval` since there is a js function called setInterval and the IDE was triggering some warnings.
- Avoid re-auto-selecting storage type if the user already has selected one.
- Avoid overriding the scheme (`https://`, `oci://`, etc) with the default one except for the helm plugin. It was causing some issues with the Flux …
=> Changes to support OCI with flux in the UI

integration/tests/operators/06-operator-deployment.spec.js
I've noticed a random failure in the operator-relate CI test: it starts typing before the view is fully rendered. See below:
This PR is just to add a wait for the proper selector to become visible before starting typing.
More CI reliability.
N/A
- related #5227 
N/A
=> CI - wait until "operators" appears before typing

script/chart-museum.sh, script/e2e-test.sh
This PR changes the E2E execution logic to install first chart museum and then Kubeapps. Before, Kubeapps was being installed before. It could be rare, but in some situations, ChartMuseum could not be ready for Kubeapps.
After the refactoring done in #5143 it has been easier to implement this change, for example the namespace was already the right one, `chart-museum`.
Right installation order of E2E elements.
N/A
- fixes #4430
=> Changed order of installing ChartMuseum in E2E tests

dashboard/src/actions/repos.test.tsx, dashboard/src/actions/repos.ts, dashboard/src/components/Config/PkgRepoList/PkgRepoButton.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx, dashboard/src/shared/PackageRepositoriesService.test.ts, dashboard/src/shared/PackageRepositoriesService.ts, dashboard/src/shared/types.ts, dashboard/src/shared/utils.ts
Adding an explicit scope for selecting whether the repo should be namespace or global + some info messages to the user.
Adding a global repo will no longer require switching the context, which wasn't something trivial to figure out as a user.
N/A
- fixes #2995 
Squeezing two changes:
- Disable the description field if using carvel repos (as it currently errors if any is passed)
- Fix some <label> tags to comply with a11y recommendations.
=> Add explicit scope to the new repo form

dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx
A quick follow-up PR of #5240 just for disabling the field when editing a repo.
The rest of the changes are just trivial: using `includes` instead of chaining `||`  when possible and avoid using the `?.` operator if the field is not optional.
N/A
- related #5121 
N/A
=> Disable scope field when editing a repo

Makefile
This PR adds support for specifying the target CPU architecture for the docker images through a parameter in the call to the corresponding make target. This PR doesn't modify the CI, it just adds support for building the docker images for different platforms through `Make`.
Docker images can be built for different CPU architectures (others than AMD64), so developers using computers with those architectures can take advantage of it.
N/A
- Helps fix #5208 
N/A
=> Add support for setting target architecture for images

integration/tests/carvel/04-default-deployment.spec.js
Trivial PR trying to fix the error appearing with E2E test 04 for Carvel.
It is the typical error on E2E CI that fails from time to time, but I noticed that the frequency has been increasing lately.
CI pipelines should pass successfully more often.
That this PR does not really fix the issue.
- fixes #5267
=> Fix for E2E Carvel test 04 selectOption

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/common/utils.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/global_vars_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/common/plugin.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/test_util_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/pkg/agent/agent_test.go, pkg/chart/chart.go, pkg/chart/chart_test.go, pkg/helm/index_test.go, pkg/http-client/httpclient.go, pkg/http-client/httpclient_test.go, pkg/kube/kube_handler.go, pkg/kube/kube_handler_test.go
The latest golangci-lint version warned us about a deprecation in go: the `io/ioutils`  modules have been moved to `io` and `os` packages. This PR is removing this dependency in favor of each `io` and `os` functions.
No deprecated code in our codebase.
N/A (some fn signatures might have changed, I'll perform the requires changes as well)
-  related https://github.com/vmware-tanzu/kubeapps/pull/5290 (in fact, this PR has to be merged first, otherwise the linter will fail)
N/A
=> Remove io/ioutils imports

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/pinniped.rs
I've noticed the pinniped-proxy deps were out of sync in some PRs, therefore I'm just running `cargo update` once every dep has been updated.
Besides, it defaults the k8s API to 1.24, as subsequent PRs will also update the corresponding go deps.
Up to date rust deps.
N/A
- related https://github.com/vmware-tanzu/kubeapps/pull/5278
- related https://github.com/vmware-tanzu/kubeapps/issues/5293
N/A
=> Run cargo update

site/content/docs/latest/tutorials/kubeapps-on-tce/01-TCE-cluster-preparation.md, site/content/docs/latest/tutorials/kubeapps-on-tce/02-TCE-managed-cluster.md, site/content/docs/latest/tutorials/kubeapps-on-tce/02-TCE-unmanaged-cluster.md, site/content/docs/latest/tutorials/kubeapps-on-tce/03-preparing-kubeapps-deployment.md, site/content/docs/latest/tutorials/kubeapps-on-tce/04-deploying-kubeapps.md, site/content/docs/latest/tutorials/kubeapps-on-tce/05-Managing-applications.md, site/content/docs/latest/tutorials/kubeapps-on-tce/README.md, site/content/docs/latest/tutorials/kubeapps-on-tce/introduction.md
Update Kubeapps on TCE tutorial to comply with style guides.
Documentation updated and standardize according to Kubeapps style guides based on Kubernetes style guides
N/A
- related to #5024
An index at the end of each section have been added to ease the navigation across sections.
=> 5024 doc/update kubeapps on tce tutorial

script/chart-museum.sh, script/e2e-test.sh
CI E2E runs are constantly failing due to problems with the `port-forward` done in the chart-museum part.
Whenever a chart is needed to be pushed to chart-museum, there is a port-forward done to the service.
That solution is weak and error prone, this PR removes that and adds an ingress setup for Chart museum so that there is no port-forward used anymore.
Ingress is only used from the scripts to push charts. From the E2E tests, the same internal service locator is used (`http://chartmuseum.${CHARTMUSEUM_NS}.svc.cluster.local:8080/`).
It should bring more reliability.
N/A
N/A
=> Fix for CI: adding chart museum ingress

script/e2e-test.sh, script/install-local-registry.sh, script/local-docker-registry.sh
After #5337 was merged I realised that there was another port-forward failing in CI. The one used to push a sample image to the local Docker registry.
This PR removes this port-forward and substitutes it with an Ingress, just like #5337.
Bring more reliability to CI E2E tests execution.
N/A
- related #5337
=> E2E tests: Add Docker registry ingress to avoid port-forward

CONTRIBUTING.md
Adds the requirement for contributors to sign (with GPG) and sign off the Git commits of contributors.
After some PRs were already created by contributors, we realized that commits were not signed, which is a requirement now for Kubeapps Git repo.
Less confusion for contributors when making contributions.
N/A
- related #5335
=> Updated Contributing doc to reflect the requirement for signed commits

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_resources.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider.go, cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider_test.go
This PR adds a new logic for obtaining the clients for K8s APIs. It resides in the `/pkg` package, but it is only applied to the Helm plugin by now.
It should speed up the response times for Helm plugin: a lot when using Pinniped, not so much without Pinniped.
Problem solved here was found to be the root cause for #4919.
In the business logic of Helm plugin (at least), usually only one type of client is required per scenario (e.g. the typed client when retrieving available packages summary).
When using the old client getter, all types of clients were being retrieved due to [the invocation of `clientGetterHelper`](https://github.com/vmware-tanzu/kubeapps/blob/cf858134a3b67e9f6ee2c53ce7b5071407b3ff7a/cmd/kubeapps-apis/plugins/pkg/cl …
=> New K8s clients provider for Helm plugin

cmd/pinniped-proxy/src/main.rs, site/content/docs/latest/reference/developer/pinniped-proxy.md
Adds timestamp to logs in Pinniped proxy. Uses the same format than Kubeapps-apis.
Before:
```
INFO  pinniped_proxy::service > GET https://kubernetes.default/apis/kubeapps.com/v1alpha1/apprepositories 200 OK
```
After:
```
2022-09-21T09:49:16.567145 [INFO] - GET https://kubernetes.default/apis/kubeapps.com/v1alpha1/apprepositories 200 OK
```
Logs have the timestamp info
N/A
- related to #4919
=> Add timestamp to Pinniped proxy logs

dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx, dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx, dashboard/src/components/OperatorInstanceFormBody/OperatorAdvancedDeploymentForm/OperatorAdvancedDeploymentForm.test.tsx, dashboard/src/components/OperatorInstanceFormBody/OperatorAdvancedDeploymentForm/OperatorAdvancedDeploymentForm.tsx, dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.test.tsx, dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.tsx, dashboard/src/components/OperatorInstanceUpdateForm/OperatorInstanceUpdateForm.test.tsx, dashboard/src/shared/schema.ts, dashboard/src/shared/utils.ts
Before start adding deep changes to the deployment form, this PR is extracting those views related to operators (which will get refactored once we encapsulate the operators as a plugin) and aligning the views to the new "in-line diff editor". 
Therefore, the old (and pretty unmaintained) `Differential` component, has been removed in these views (but they have not in the non-operators ones for now).
Also, adding a couple of minor changes in the utility functions.
The non-operator-related views can be now safely modified in subsequent PRs.
N/A
- required by #4396
I'll be stacking more PRs on top of this one.
=> New deployment forms: changes in operator-related views

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, script/e2e-test.sh
Kapp controller has introduced a [new suffix for apps identifier since v0.39.0](https://github.com/vmware-tanzu/carvel-kapp-controller/blob/v0.39.0/pkg/deploy/factory.go#L46).
In our CircleCI we were actually using and old version of Kapp Controller (v0.32.0) due to some problem in passing variables to `e2e-test.sh`.
We discovered that changes done in #4767 were not being correctly tested in E2E. That PR adds a fix for handling the app identifier suffix in Kapp Controller versions >0.47, with a fallback to previous versions (using suffix `-ctrl`). E2E was only testing the fallback scenario. Suffix used was [`.apps.k14s.io`](https://github.com/vmware-tanzu/carvel-kapp/blob/develop/pkg/kapp/app/recorded_app.go#L28). Actual suffix for `ConfigMap` used by Carvel has suffix `.app`.
This PR …
=> Fix for Kapp app suffix

dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx, dashboard/src/reducers/repos.ts, dashboard/src/shared/PackageRepositoriesService.ts, dashboard/src/shared/types.ts
This PR implements #5378. Adds to the package repositories management UI the possibility to select an auth provider for the so called auto-login.
It only works for Flux plugin and OCI repositories, and it is added as another authentication method available.
Following the backend logic that swallows an update on this field (`customDetails.provider`), the update in the UI is disabled. Although I incline more towards throwing an error from backend in those cases, it hasn't been implemented like that, so I tried to mitigate from UI.
The backend/API part implemented in #5368 is finally available through UI.
There is a bit of a mix in the concepts of `spec.provider` and actual authentication. In theory, according to Flux documentation: …
=> Add Flux auth provider option to UI

.github/workflows/kubeapps.yaml
Currently, we have a bug in the job `push_dev_images` from GitHub Actions workflow, that fails for two reasons:
* The env var `IMAGES_TO_PUSH` redefined at the job level is not taking the right value.
* The path used to load the images previously generated, uploaded and downloaded, is wrong.
The job `push_dev_images` will work as it is expected to do.
Nothing.
=> Fix the job push_dev_images from GHA workflow

.github/workflows/kubeapps.yaml
With this change, the GH Actions workflow will be triggered on pushes to the main branch, as right now it's only being triggered on PRs and pushes to the `migrate-ci` branch (the one used for its development).
The workflow will be triggered when it should be.
Nothing.
=> Run GHA pipeline on pushes to main branch

.github/workflows/kubeapps.yaml
Currently, both GHA and CircleCI workflows (aka. pipelines), are running in parallel and configured to generate the development docker images using the same suffix `-ci` to avoid polluting the canonical images repository. However, this leads us to a situation where both pipelines overlap when it comes to pushing the images to Dockerhub, and cannot make sure which was the pipeline that generated each published image (it will depend on which finishes last).
We can clearly identify which workflow generated what image and avoid overlap by having the images generated by both repositories publicly available in Dockerhub, under different suffixes.
Nothing, as we're in the development phase of the GHA workflow, it should have any negative consequences in case we break anything on it.
- related to …
=> Change IMG_MODIFIER suffix for the GHA workflow

.github/workflows/kubeapps.yaml
This PR fixes some errors in the `push_images` job from the `Kubeapps general workflow` in GH Actions.
The `push_images` job works as expected and images are uploaded to Docker Hub upon commits to the main branch.
None.
=> Fix push_images job from GH Actions workflow

site/content/docs/latest/howto/access-control.md
Update the How-to guide to standardize with rest of guides and follow style guidelines.
Documentation updated
N/A
- related to #5024
=> Update access control how-to guide

dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTable.tsx, dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTableHelpers.ts
This PR adds a workaround while the TabStack table bug is being fixed (adding the `filterFromLeafRows` should be enough to get what we want). We just mark a row as "passing" if it matches the search query (existing behavior) OR it has a child that matches the query (workaround)
Users will be able to search by any nested value in the table.
I was a little reluctant to add this workaround for the performance implications I was foreseeing... but I have tested IRL and it is performing pretty well (see gif below), so I decided to to ahead.
- fixes #5437
(unedited speed)
=> Search table nested params

.circleci/config.yml
Gcloud CLI operations in CI were throwing warning like this in console:
```bash
WARNING: the gcp auth plugin is deprecated in v1.22+, unavailable in v1.25+; use gcloud instead.
To learn more, consult https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```
and an action request (in CI step `Start GKE environment`):
```bash
CRITICAL: ACTION REQUIRED: gke-gcloud-auth-plugin, which is needed for continued use of kubectl, was not found or is not executable. Install gke-gcloud-auth-plugin for use with kubectl by following https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
```
With this PR, we are now using the new auth plugin.
Related messages are now gone.
[CI pipeline run on GKE with the new …
=> [CI,GKE] Use `gke-gcloud-auth-plugin` for `kubectl` auth

.github/workflows/kubeapps.yaml
The changes in this PR aim to fix [the error](https://github.com/vmware-tanzu/kubeapps/actions/runs/3243474129/jobs/5318724841#step:10:60) raised in the `local_e2e_tests` job of the GitHub Actions "kubeapps general workflow", where it's failing because it's trying to docker-load a non-image artifact.
The `local_e2e_tests` job of the GHA workflow should no longer fail for the reason mentioned above.
None
* Error: https://github.com/vmware-tanzu/kubeapps/actions/runs/3243474129/jobs/5318724841#step:10:60
=> Skip non-image files when loading docker images in local_e2e_tests

.github/workflows/kubeapps.yaml
According to [a recent GitHub post](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/), `set-output` and `save-state` commands have been deprecated and corresponding environment files should be used instead.
* Remove the use of deprecated GitHub Actions' commands and follow best practices. 
* The pipeline is more secure.
None.
* [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
* [https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#environment-files](https://docs.githu …
=> Use GitHub Actions' environment file for steps' outputs

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/OCI_TERMINOLOGY.md, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/harbor_api_v2_repo_lister.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/gcloud-setup.md, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/harbor-create-project.json, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/testdata/harbor-create-robot-account.json, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/testdata/cert/ca-config.json
This PR aims at solving the issue reported by CodeQl (see https://github.com/vmware-tanzu/kubeapps/security/code-scanning/29).
No more CodeQL open issues
N/A
- fixes https://github.com/vmware-tanzu/kubeapps/security/code-scanning/29
Run prettier as well.
=> Fix codeql issue

dashboard/src/components/Config/PkgRepoList/PkgRepoControl.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoControl.tsx
This PR fixes a problem in the package repositories deletion action. When the user didn't have enough permissions to delete the repo (or any other error at deletion), the error message was shown flashing and disappearing.
This was confusing: user was seeing an error for a fraction of a second, and the repository not deleted.
The user now can see the error message, after the confirmation popup is automatically closed:
Repos are now re-fetched only when there is no error in the deletion action.
User is able to see the actual error message and repos are not unnecessarily re-fetched.
N/A
- fixes #4220
=> [Dashboard] Fix for error flashing when deleting repo

dashboard/src/actions/repos.ts, dashboard/src/components/Config/PkgRepoList/PkgRepoList.tsx
This PR adds the list of global repos when context is set to a cluster other than the default one.
List is set on read only mode.
Same UI warning message is kept, as it still describes correctly the situation.
Targeted at the case stated in #2717, users that do not have access to the main/default cluster where Kubeapps is installed.
- Users in non-default cluster can see the list of global repositories, at least in read-only mode.
N/A
- fixes #2717
=> Repos global list on additional clusters

script/makefiles/site.mk, site/content/docs/latest/reference/developer/release-process.md, site/netlify.toml
It's been a long time since we don't update the website's engine version; mainly because it wasn't documented in our guidelines.
This PR is updating Hugo to the latest version, as well as adding the instructions on how to do it for future reference.
We will benefit from the latest changes in Hugo, for instance, in v100 they finally supported shortcodes in the main template (we had to add some hacky workarounds bc of it) and support for previewing 404 error pages.
N/A  (this hugo dependency is not being reported to OSM, as it is not part of the actual Kubeapps build)
- fixes #  TBD ( I will create an issue soon)
N/A
=> Update Hugo version

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, script/makefiles/deploy-dev.mk, site/content/docs/latest/tutorials/managing-carvel-packages.md
I was keen to see exactly what was required to use the Carvel plugin with the existing multicluster support. It turns out, nothing (maybe @antgamdia already checked this and got it working a while ago? Not sure). The only changes I needed were:
* Updating the version of kapp-controller that we run in the cluster (since v0.35 was still requiring secrets attached to service-accounts, which stopped with k8s 1.24, and updated in kapp-controller with v0.37, but I've tested with the latest which works).
* Adding a makefile target to add kapp-controller to the second dev cluster
* Fixing an issue in our carvel docs for creating the reconciliation service account.
With those changes, I can deploy kubeapps on the main cluster, with the patched …
=> Small changes to check Carvel multicluster support.

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/cli.rs, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/tests/cli_tests.rs, cmd/pinniped-proxy/tests/cmd/help.trycmd
Replaces `structopt` with `clap`
Removes dependencies on now unmaintained packages
- fixes #5357
=> [pinniped-proxy] Update from structopt to clapv4. Fixes #5357

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
Trivial PR removing unneeded checks for provided context cluster.
Cluster is not strictly required, as it will fall back to the Kubeapps cluster if not specified. See [code in charge here](https://github.com/vmware-tanzu/kubeapps/blob/main/cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go#L328-L330).
Otherwise, an error like this was returned:
```bash
ERROR:
Code: InvalidArgument
Message: Invalid GetPackageRepositorySummaries response from the plugin helm.packages: rpc error: code = InvalidArgument desc = no valid context provided
```
Specify cluster context for operations in Helm plugin is not required.
N/A
N/A
=> [Helm plugin] Remove unnecessary context check

chart/kubeapps/Chart.yaml, chart/kubeapps/README.md, chart/kubeapps/templates/dashboard/configmap.yaml, chart/kubeapps/templates/dashboard/deployment.yaml, chart/kubeapps/templates/dashboard/service.yaml, chart/kubeapps/templates/frontend/configmap.yaml, chart/kubeapps/values.yaml
Adds a chart value to enable/disabled the setup of the Kubeapps Dashboard.
Defaults to enabled, as is now.
When disabled, Kubeapps is deployed in a kind of "API mode" where requests to e.g. `https://<INGRESS_HOST>/apis/*` can still be done.
Possible to deploy a headless Kubeapps
N/A
- N/A
This will be useful when deploying workloads for multicluster, or for scenarios where UI is not needed.
=> Add flag for disabling dashboard

site/content/docs/latest/tutorials/using-an-OIDC-provider.md
Update the how-to guide to comply with stylish guidelines.
Standard documentation
N/A
- related to #5024
=> Update OIDC with pinniped guide to comply with style guidelines

dashboard/src/shared/yamlUtils.ts
While working on #5436, I noticed some errors during the YAML parsing; well not errors, but unexpected (for me) values being returned by the `genIn` method. In collections, the returned thing is not a js object, but a custom data type from the YAML library. 
This PR is just to convert collections (YAML sequences and YAML maps) back to plain js objects (even if the function says `toJSON()` 😅 
We will be able to use arrays and object fields in the form.
N/A
- fixes #5519
> **Note**
> This PR is part of a series of PRs aimed at closing [this milestone](https://github.com/vmware-tanzu/kubeapps/milestone/27). I have split the changes to ease the review process, but as there are many interrelated changes, the tests will be performed in a separate PR (on top of the branch containing all the …
=> Yaml decoding fix

dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/ArrayParam.tsx, dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/BooleanParam.tsx, dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/Params/TextParam.tsx, dashboard/src/components/DeploymentForm/DeploymentFormBody/BasicDeploymentForm/TabularSchemaEditorTable/TabularSchemaEditorTableRenderer.tsx, dashboard/src/shared/utils.ts
In #5436 we mentioned that several fields were still pending, namely
-  1st level: object (at least, as array of tuples <string, any> for defining each property.
-  Array level:  enum, arrays, objects
WRT the top-level objects, it is not an actual problem: if they have `properties`, they will get rendered as any other nested param more. It is only the case when it lacks the `properties` fields that we need to handle.
- Solution: allow any serialized object like `{"foo": 1234}` and add more validation messages.
WRT the array-level properties:
- Solution for enum: use the same approach as in the top-level enum.
- Solution for arrays and objects: use the same approach as in the top-level objects: render a text field but enforce validation.
Additionally, the array now enforces `maxItems` and …
=> Add remaining schema renderers

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/pinniped.rs, script/makefiles/deploy-dev-for-pinniped.mk, site/content/docs/latest/howto/OIDC/using-an-OIDC-provider-with-pinniped.md, site/content/docs/latest/reference/developer/pinniped-proxy.md
This PR is the result of the investigation described on #5407 , the end result of which is a single line removal, though I've left some other changes that were helpful during debugging (logging related).
Pinniped-proxy is faster when hit with lots of simultaneous requests.
NOTE: Leaving in draft as although the requests are serviced more quickly in pinniped-proxy, it's still taking 5s for the kubeapps-apis to respond. Investigating why...
None.
- fixes #5407
After
```
2022-10-20T02:22:19.383560 [TRACE] - registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-10-20T02:22:19.383685 [INFO] - Listening on http://0.0.0.0:3333
2022-10-20T02:22:37.624364 [TRACE] - registering event source with poller: …
```
=> Remove sync_writes optino for pinniped-proxy cred cache.

cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, pkg/kube/cluster_config.go, pkg/kube/cluster_config_test.go
Adapted version of the outdated PR #4591. After removing kubeops, there has been a refactor of places changes by the old PR.
It fixes the scenario in which the cluster where Kubeapps is installed is not part of the configured list of clusters.
For example:
```yaml
clusters:
- name: second-cluster
domain: ...
apiServiceURL: ....
certificateAuthorityData: ...
serviceToken: eyJhbGciOiJS...
```
For doing so, it uses a token to reference the Kubeapps cluster: `-`.
Also empty string `''` is accepted as cluster reference, for allowing payloads in which there is no cluster specified in context.
Therefore, if a cluster string is empty or `-`, backend logic assumes that the Kubeapps cluster will be used.
User can work in a multicluster …
=> Add explicit token for Kubeapps cluster reference

site/themes/template/layouts/_default/baseof.html, site/themes/template/layouts/_default/search.html, site/themes/template/static/js/main.js
This PR is a hotfix for a bug introduced at #5579: the searchbox init code was moved to a `static` folder, which is unable to retrieve the values from the site params. Therefore, the API key is  literally `.Site.Params.docs_search_api_key` instead of the replaced value.
Also, squeezing a minor fix to prevent `Kubeapps Kubeapps ...`  to appear in the descriptions.
Search will work again
N/A
N/A
N/A
=> Fix website search issue

dashboard/src/components/DeploymentForm/DeploymentFormBody/DeploymentFormBody.tsx
This PR solves a bug found during a manual test prior to the release: when selecting a different version, the `isLoaded` flag was preventing a proper execution of the useEffect flow. The flag has been replaced with `isLoading`, which just avoid re-renders when an expensive operation is running (like parsing the schema).
Users upgrading package will see the deployed values (correct) instead of the pkg defaults (incorrect). 
In those cases, the component will re-render twice, but that's not a big deal (no expensive backend calls, the table is now performing well, etc).
- fixes #5603
=> Remove "isLoaded" flag from deployment form

.github/workflows/kubeapps-general.yaml
This PR increases the timeout for the `operator` group of the `local_e2e_tests` job of the `kubeapps-general.yml` workflow.
Prevent flaky tests due to timeouts.
N/A
N/A
=> Increase timeout for local_e2e_tests(opeartor) to avoid flaky tests

.github/workflows/kubeapps-full-integration.yaml, .github/workflows/kubeapps-main.yaml, .github/workflows/kubeapps-release.yml
This PR renames the `main` job in GHA workflows to `CI`.
We get a shorter and (IMHO) more intuitive name for the job that calls the `kubeapps-general` workflow from several top-level workflows.
None
N/A
=> Rename GHA's `main` job to `CI`

.github/workflows/kubeapps-main.yaml, .github/workflows/kubeapps-release.yml
With these changes we achieve the following:
- Do not trigger the `Kubeapps Main Pipeline` workflow for every push, only for pushes to the master branch.
- Use a different concurrency group for the `Release Pipeline`, so a later workflow triggered from a push to the main branch won't cancel the release pipeline.
- Do not trigger the `Kubeapps Main Pipeline` workflow on tags creation. We trigger the release pipeline for this event and don't want a second pipeline running on the same version of the code, that could interfere with the former (eg. canceling the release pipeline because they both run in the same concurrency group).
- Less number of pipelines triggered, and the triggered ones are more meaningful.
- A more resilient release flow.
- The main pipeline isn't triggered until a PR is …
=> Adjust concurrency in gha workflow

README.md
This PR adds several status badges to the README.md file for some of the GitHub Action's workflows (main, release and codeql).
The latest status of the GitHub actions workflows is shown in the README.md file.
N/A
N/A
=> Add status badges for GHA's workflows

.github/workflows/kubeapps-full-integration.yaml
Run the GitHub Action's `Full Integration Pipeline` on schedule. We usually run this pipeline manually only when we are going to release a new version of Kubeapps, and from time to time it turns out that it fails. 
With this change, we get a much shorter feedback loop, so we can act on the errors more proactively.
An increase in cloud costs due to the fact of running the tests more frequently. Is that a problem?
N/A
=> Run GHA's Full Integration Pipeline on schedule

integration/tests/flux/04-default-deployment.spec.js
The Flux e2e test is currently failing while selecting version `6.2.0` of the `podInfo` package to install. After taking a look at the recorded video, it seems that it could be possible that the desired version is no longer available, so switching to an existing one (eg. `6.2.3`) could do the trick.
* The `Flux` e2e test no longer fails.
* Are we pointing to version `6.2.0` for some reason??
N/A
* [Failing pipeline](https://app.circleci.com/pipelines/github/vmware-tanzu/kubeapps/9552/workflows/ece12186-b3c9-4825-92bd-9107447178ab/jobs/105445/steps)
* [Recorded Video](https://circleci-tasks-prod.s3.us-east-1.amazonaws.com/storage/artifacts/c6a54f6f-b4e8-4579-a155-e68a2f7bc16f/09eb0742-3780-4289-960f-7e5f5552069e/0/integration/reports/t …
=> Fix flux e2e test

.github/workflows/kubeapps-general.yaml, .github/workflows/kubeapps-release.yml
We need a way of being able to test the new release workflow in GHA. So far, it's only triggered on new tags following the pattern `v[0-9]+.[0-9]+.[0-9]+`, so we cannot trigger it unless a new release tag is created. To allow testing without generating new release tags, we have added a new condition that triggers the workflow when new tags following the pattern `tests-*` are created.
The release workflow can be triggered and tested without the need of creating new release tags.
If we don't control the kind of tag that triggered the workflow, and deactivate the `DEV_MODE` for the `kubeapps-main` workflow, we could generate an actual release on the Bitnami side upon the creation of new `test-*` tags.
N/A
=> Trigger GHA release workflow on tags following `test-*` pattern

.github/actions/srp-source-provenance/action.yml, .github/workflows/kubeapps-general.yaml
This PR adds the required SRP source provenance report to the GHA pipeline. Currently, the report is being done in the CircleCI pipeline, but as part of the migration to GHA, we need to implement it there. For this report to work, we need to register a new SRP UID for GHA, which will be something like `uid.mtd.provenance_2_5.fragment(obj_uid=uid.obj.build.github(instance='github.com',namespace='vmware-tanzu/kubeapps',...),version='')`. An [issue](https://servicedesk.eng.vmware.com/servicedesk/customer/portal/12/INTSVC-54793) has been created in the Jira Service Desk for this task, and we will maintain this PR as a draft until that request is fulfilled. 
* Report SRP source provenance from GHA pipeline.
* GHA pipeline is complete and …
=> Add SRP source provenance report

.licenserc.yaml, .yamllint.yml, Makefile, script/linters/golang-linter.sh, script/linters/license-linter.sh, script/linters/yaml-linter.sh
Currently, we have several linters running in our GHA pipeline, but we do not have an easy way of running those linters locally. This PR adds a new target to the makefile that allows executing those linters locally, so we can easily run them as git hooks or whatever.
We are able to execute the linters locally.
None
- related to #5628
=> Add makefile lint target

.github/workflows/kubeapps-general.yaml
We have a bug in the recently added `report_srp` job in the GHA pipeline. In this job, we are using a custom action defined in the Kubeapps repository without calling the `checkout` action before, so the runner is not able to find the custom action.
GHA's `srp_report` job works as expected.
None
=> Call chekout action before using srp-source-provenance

.github/actions/srp-source-provenance/action.yml
This PR fixes a typo in the call to `srp provenance source` command in the GHA's `srp-source-provenance` action.
A typo in the call to a command is removed, so it should work as expected now.
None.
=> Fix typo in srp command

.github/actions/srp-source-provenance/action.yml
Even though the `report_srp` job of the GHA's pipeline is working properly, it's showing a warning due to the use of a deprecated argument in the call to the `srp` tool. Here we replace that argument by the new recommended one.
We get rid of a deprecated argument in the call to the `srp` CLI tool and remove the risk of a future failure when updating to a new version that no longer supports the deprecated argument.
None
* https://github.com/vmware-tanzu/kubeapps/actions/runs/3485334417/jobs/5830985505#step:3:701
=> Update deprecated parameter in the call to srp tool

chart/kubeapps/templates/frontend/deployment.yaml, cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml, cmd/pinniped-proxy/src/cache.rs, cmd/pinniped-proxy/src/https.rs, cmd/pinniped-proxy/src/main.rs, cmd/pinniped-proxy/src/pinniped.rs, cmd/pinniped-proxy/src/service.rs
Follows on from #5518, this time replacing the `cached` package with a custom credential cache.
After further digging, I found that one cause of the slow handling of 50 concurrent requests going through the pinniped-proxy was that:
- We were caching a function with an async/await signature which means that even the cached version must have that signature as well - which means a blocking i/o call (which switches the task), and
- The `Cached` trait specifies that even a `cache_get` operation mutates the cache (in our case, just for statistics of hits/misses), which, as a result, requires acquiring a *write* lock to the cache to read a cached value.
For more details, please see the [discussion with the `Cached` …
=> Switch cache to custom without write-lock for reads.

.github/workflows/kubeapps-general.yaml
This commit adds just some minor improvements to the GHA's kubeapps-general workflow. The changes consist mainly of applying more restrictive bash options (`set -eu`) so the scripts fail out loud when a required env var is not defined and finish their execution when an intermediate command returns a non-zero code.
We follow shell script's best practices to try to avoid subtle bugs.
More restrictive bash options could result in breaking some currently running scripts, or even lead us to discover some unnoticed misbehaviors.
None
=> Add some minor improvements in the GHA's kubeapps-general pipeline

.github/workflows/kubeapps-release.yml
This commit fixes the regex that triggers the release pipeline for "testing releases" (tags following the pattern `test-vX.Y.Z`).
We can test the release pipeline without triggering a real release.
None.
=> Fix wrong regex for testing the release in GHA

.github/workflows/kubeapps-general.yaml
This commit fixes the GHA's Release Pipeline. Currently, the workflow is not working properly because the `sync_chart_from_bitnami` only runs when the pipeline is triggered from the main branch, and it should run when it's triggered from a version tag also.
The GHA's Release Pipeline works as expected.
None
=> Fix GHA's release workflow

.github/workflows/kubeapps-general.yaml, .github/workflows/kubeapps-release.yml, script/create_release.sh
This commit aims to simplify the logic in the GHA's Kubeapps General workflow. Currently, we have some logic that checks if the pipeline has been triggered by a tag pushed to the repo, and if it is, we run some jobs: push_images, sync_charts, release, etc. As we already have a top-level workflow `kubeapps-release.yml` that internally uses the general workflow, and only runs when a tag following the release pattern is pushed to the repo, we can just introduce an input parameter in the general workflow that controls whether those jobs should be run or not, instead of relying on the logic residing in the general pipeline.
GHA's workflows `kubeapps-general.yaml` and `kubeapps-release.yml` are simpler to understand and maintain.
None.
- …
=> Simplify release-related logic in GHA's kubeapps general pipeline

cmd/asset-syncer/server/postgresql_utils_test.go, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, pkg/chart/models/chart.go
It confuses me every time I deal with the Values field in different parts of the code, since it's not user values at all, but the chart's default values file. Hopefully this will make it clearer.
Simple refactor, changing the name. Nothing to review here (though VSCode's refactoring did create an extra file that I deleted, let's see what the automated tests do).
- fixes #
=> Simple rename.

site/content/docs/latest/tutorials/using-an-OIDC-provider.md
While chatting about [OIDC configuration](https://github.com/vmware-tanzu/kubeapps/issues/5671#issuecomment-1324168711) with @RGPosadas I was looking through the docs and found that it reads currently as if you should use Pinniped either way.
This change just clears that up a bit, I hope, so that people use the cluster's own OIDC support when they can, and pinniped when they can't.
- ref #5671
=> Improve wording to avoid implying pinniped is used either way.

script/e2e-test.sh, site/netlify.toml
This PR aims to fix the failing full integration pipeline (which we need to pass for release).
Also updates Hugo version (based on instructions in the release-process.md.
Recent runs (from the past 6 days) of the [full integration pipeline](https://github.com/vmware-tanzu/kubeapps/actions/workflows/kubeapps-full-integration.yaml) have been failing. Looking for the differences, I could see that:
- `chart-museum.sh` was failing to upload our custom apache chart to the chartmuseum instance, because...
- `LOAD_BALANCER_IP` was set to `172.18.0.2`, which is the `DEX_IP`, whereas it should be set to the load balancer IP address (which has been created correctly), as it is in the last passing run. It's not doing this because...
- The code that …
=> Finish switching from GKE_BRANCH to GKE_VERSION (from #5730)

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo.go, pkg/chart/models/chart.go, pkg/tarutil/tarutil.go, pkg/tarutil/tarutil_test.go
While working on the next part of #5692 and noticed that the OCI code seemed to be repeating similar functionality that exists already in a re-usable lib. This PR just updates to use the existing code, which required a little refactoring as OCI tarballs don't have a root directory like the chart ones do.
Less code.
- ref #5692
=> Refactor OCI file extraction to use existing tarutils.

cmd/asset-syncer/server/postgresql_db_test.go, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go, pkg/chart/models/chart.go
Updates the asset-syncer to fetch additional values files from a chart package and updates the helm plugin in kubeapps-apis to populate the `AvailablePackageDetail` with the additional values files when present.
The dashboard can now be updated to use or display these when present.
- ref #5692
=> Update asset-syncer to populate additional default files.

.yamllint.yml, dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx, dashboard/src/components/DeploymentForm/DeploymentForm.tsx, dashboard/src/reducers/availablepackages.test.ts, dashboard/src/reducers/availablepackages.ts, integration/charts/simplechart-customvalues/.helmignore, integration/charts/simplechart-customvalues/Chart.yaml, integration/charts/simplechart-customvalues/templates/_helpers.tpl, integration/charts/simplechart-customvalues/templates/deployment.yaml, integration/charts/simplechart-customvalues/templates/service.yaml, integration/charts/simplechart-customvalues/templates/tests/test-connection.yaml, integration/charts/simplechart-customvalues/values-custom.yaml, integration/charts/simplechart-customvalues/values.yaml, script/chart-museum.sh
This change uses the new support for custom default values files so that:
- if a single custom default values file is found in the chart, it is presented to the user so that authors can control the default values presented to users.
Note that, since it is just an overlay over the charts `values.yaml`, it can be used both to present a simpler selection of options to users, or to present a different set of default values.
Fulfills use-case 1 of #5692 .
- ref #5692 
Using the [custom default values in the simplechart](https://github.com/vmware-tanzu/kubeapps/blob/5692-dashboard/integration/charts/simplechart-customvalues/values-custom.yaml), before the user makes any changes, they are presented with those values (only):
Any changes made are …
=> Default to a custom default values if exactly one provided.

.yamllint.yml, dashboard/src/actions/availablepackages.ts, dashboard/src/components/DeploymentForm/DeploymentFormBody/DeploymentFormBody.tsx, dashboard/src/reducers/availablepackages.test.ts, dashboard/src/reducers/availablepackages.ts, integration/charts/simplechart-multicustomvalues/.helmignore, integration/charts/simplechart-multicustomvalues/Chart.yaml, integration/charts/simplechart-multicustomvalues/templates/_helpers.tpl, integration/charts/simplechart-multicustomvalues/templates/deployment.yaml, integration/charts/simplechart-multicustomvalues/templates/service.yaml, integration/charts/simplechart-multicustomvalues/templates/tests/test-connection.yaml, integration/charts/simplechart-multicustomvalues/values-scenario-a.yaml, integration/charts/simplechart-multicustomvalues/values-scenario-b.yaml, integration/charts/simplechart-multicustomvalues/values.yaml
Adds an example chart (which can later be used in CI) and the background state work to support switching the selected default values for charts that support it.
Next PR can focus on the UI work.
- Ref #5692
=> Initial state for handling multiple defaults.

cmd/asset-syncer/server/utils_test.go, dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx, dashboard/src/components/DeploymentForm/DeploymentForm.tsx, dashboard/src/components/DeploymentForm/DeploymentFormBody/DeploymentFormBody.tsx, pkg/tarutil/tarutil.go, pkg/tarutil/tarutil_test.go
This PR adds a default values selector to the DeploymentForm which is only displayed if a package has multiple additional values file in the package. For packages with multiple additional values files, the deploy initially uses the package values.yaml, but the form explains why the selector is available:
If the user selects a different default values file, the form is updated with that files content, ready for editing:
And finally, if the user edits the fields, the diff is against the selected default, as expected:
Also fixes issue to enable hyphens in custom values files (hard to find bug found while testing this PR).
- fixes #5692 
Tomorrow (actually, Friday), I will verify the behaviour for installed packages being upgraded.
=> Add default value selector

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
A user is getting an error in the UX showing "Unable to retrieve chart: sql: no rows in result set" but no corresponding error in the backend. Checking, I found that we don't actually log the error, other than the request log showing the internal error without details:
```
I0119 19:05:27.529184       1 server.go:314] Requesting chart 'repo/kubeapps%2Fnginx' (latest version) in ns 'default'
I0119 19:05:27.530935       1 server.go:375] Requesting chart 'repo/kubeapps%2Fnginx' (latest version) in ns 'default'
I0119 19:05:27.535286       1 server.go:62] Internal 88.857512ms /kubeappsapis.core.packages.v1alpha1.PackagesService/GetAvailablePackageDetail
I0119 19:05:27.536622       1 server.go:62] Internal 90.361477ms …
```
=> Add more explicit error logging when fetching detail.

dashboard/src/components/AppView/AppView.tsx
Signed-off-by: Vaibhav Mittal <53215737+mittalvaibhav1@users.noreply.github.com>
Fix the incorrect formatting of the installation values on the Kubeapps UI
- Cleaner UI 😀 
- None as far as ik
- fixes #5894
=> [Bug] Parse the yaml before dumping it back to string

cmd/pinniped-proxy/src/pinniped.rs
Fixes #5912 by including the k8s server url in the cache key.
Fixes an issue that was causing logouts when switching clusters.
- fixes #5912
=> Update the cache used by pinniped proxy to include the k8s api server url.

cmd/kubeapps-apis/plugins/pkg/resources/namespaces.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_filtering.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server_test.go, pkg/kube/cluster_config.go, site/content/docs/latest/reference/manifests/kubeapps-local-dev-users-rbac.yaml
The main change here is to ensure that the request for namespaces uses the *user* client first, then the service account client. For a detailed analysis of the issue it is fixing, see my [comment on 5755](https://github.com/vmware-tanzu/kubeapps/issues/5755#issuecomment-1406172791)
While there, I have tried to clarify the code a little, so that it is clearer when the user client is being used (it now matches the comments again).
I also fixed an RBAC issue in the dev environment (so that `kubeapps-user@example.com` is permitted to access, in addition to `oidc:kubeapps-user@example.com`, since the former is what pinniped uses).
Back to expected behavior when authenticated as a non-privileged user with or without a service account token configured in Kubeapps' clusters configuration.
- fixes …
=> Ensure user client with service account backup when fetching namespaces.

.github/workflows/kubeapps-general.yaml, script/lib/libcitools.sh
I used this PR to debug why the installation of the GPG key was failing. The process I used was:
1. list the files written to disk in the `installGPGKeys` command (`ls -al /tmp/*.key`) which showed that they had the incorrect size,
2. print out the `head -n1` of each (which is just the `-----BEGIN PGP PRIVATE KEY BLOCK-----`) (had to also base64 it to avoid it being correctly redacted as it should).
This showed clearly that, since I updated the secrets, the GPG data was in fact not being written to disk. After some experimenting, and reading the [GH documentation for secrets in actions](https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow) I realised that the issue could be because …
=> Add test action to reproduce issue in normal PR.

site/content/docs/latest/reference/developer/release-process.md
Just a note to ensure we're ready if we upgrade with interdependent components.
- fixes #
=> Include note in release process about chart publishing per image.

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, pkg/helm/index.go, pkg/helm/index_test.go, pkg/helm/testdata/valid-index-harbor-unified.yaml
In #3863 a change was made to ensure that we unescape spaces in the chart name before syncing data to the database, which unintentionally stopped Kubeapps from being able to retrieve charts that include a slash `/` in the chart name (as is the case when using a unified repository with Harbor). It was [noted on the PR as a possibility](https://github.com/vmware-tanzu/kubeapps/pull/3863#pullrequestreview-819141298), but at the time, we didn't have non-OCI helm chart names with slashes that we were aware of, so we didn't follow it up.
A unified Harbor Helm repo can be used with Kubeapps.
Haven't checked if the chart will display with the escaped slash or not, but still better to be able to display it rather than error.
- fixes #5897
=> Leave slash in chart name encoded. Fixes #5897

pkg/kube/cluster_config.go, pkg/kube/cluster_config_test.go
After some testing of the previous PR, we found the issue is actually that kubeapps assumes the cluster on which Kubeapps is installed will never have an APIServiceURL set in the configuration (since it can be accessed via the in-cluster configuration at https://kubernetes.default).
As it turns out, some users need to set the APIServiceURL of the cluster on which Kubeapps is installed because they use a proxy in front of the API server for authentication purposes, so it's important that Kubeapps also use this.
- fixes #5999
=> Ensure that clusters' apiServiceURL is honored for kubeapps cluster.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go
In [#5339 we inadvertently switched](https://github.com/vmware-tanzu/kubeapps/pull/5339/files#diff-da1b1406426f28c45f4b63a5ae7547e9c29747e118bf70df6a4694d575710f94R104) from an [assignment](https://go.dev/ref/spec#Assignment_statements) to a [short variable declaration](https://go.dev/ref/spec#Short_variable_declarations):
```diff
-		pluginConfig, err = common.ParsePluginConfig(pluginConfigPath)
+		pluginConfig, err := common.ParsePluginConfig(pluginConfigPath)
```
which meant that, in context, a *new* `pluginConfig` var was created in that scope, so that the actual `pluginConfig` var from the outside scope remained empty.
Plugin config works again for the Helm plugin.
- fixes #6020 
I spent some time trying to write a test for this, but I could either extract the 5 lines to a separate …
=> Ensure loaded plugin config is saved to helm server.

cmd/apprepository-controller/cmd/root.go, cmd/apprepository-controller/server/controller.go, cmd/apprepository-controller/server/controller_test.go, cmd/apprepository-controller/server/server.go
This PR adds an optional boolean flag that for the apprepository controller, `--v1-beta1-cron-jobs`, which can be set to ensure that the app repository controller creates and watches the older v1beta1 cronjobs.
Note that, although enabling this functionality to help with #6021 , we won't be removing the restriction in the Chart.yaml for > k8s 1.21, so to install the chart on a cluster prior to 1.21 you'll need to manually comment out that line in the Chart.yaml (this just ensures we don't go back and start supporting older k8s versions officially).
To use the flag, you can add the following to your values.yaml:
```yaml
apprepository:
extraFlags:
- "--v1-beta1-cron-jobs"
```
People who need to can choose to install Kubeapps explicitly on 1.20 .
- fixes #6021 
@mecampbellsoup Can you please …
=> Add optional flag to use v1beta1 CronJob (pre 1.21)

dashboard/src/shared/KubeappsGrpcClient.ts
After some debugging, issue was simply missing the `Bearer ` when setting the token auth. CI didn't pick it up since only the full integration tests use token auth now.
Token auth works again (only broken in the dev version currently, not released).
- fixes #6112
=> Ensure bearer token formatted correctly for token auth.

script/makefiles/deploy-dev.mk
While using the normal Makefile target to setup a dev env, I noticed it would fail because the postgresql db secret was missing the `password` data field. Not sure if the chart updated recently to include validation of the data even though we don't use it, but I've taken the opportunity to remove the `postgres-postgres-password` entry (don't remember why we ended up with that) and replace it with the missing `password` entry.
Dev environment setup works.
- fixes #
=> Update secret names for the postgresql secret.

cmd/kubeapps-apis/Dockerfile
Gives permission for the running process to write the k8s discovery cache when kubeapps-apis first communicates with the k8s api server.
This doesn't appear to affect users, but may be contributing to memory usage and potentially restarts.
Before this change, after deploying an app, the following would appear in the kubeapps-apis logs:
```
I0322 23:20:57.965475       1 cached_discovery.go:93] failed to write cache to /.kube/cache/discovery/10.96.0.1_443/batch/v1/serverresources.json due to mkdir /.kube: permission denied
I0322 23:20:57.965483       1 cached_discovery.go:93] failed to write cache to /.kube/cache/discovery/10.96.0.1_443/autoscaling/v2/serverresources.json due to mkdir /.kube: permission denied
I0322 23:20:57.965485       1 cached_discovery.go:93] failed to write cache to …
```
=> Ensure discovery cache can be written by client-go in the kubeappsapis service

.github/workflows/kubeapps-general.yaml, chart/kubeapps/templates/kubeappsapis/deployment.yaml, cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins_test.go, cmd/kubeapps-apis/server/server.go, go.mod, go.sum
This is split out from the investigation done in #6097 and will be followed by a bunch more switching other services and plugins away from the improbable-eng gRPC backend (see #6013)
This PR sets a clear example of switching one of the gRPC servers, the core plugin service, away from the improbable-eng server to the connect gRPC server. The switch of the server is trivial, the difficulty was in getting our kubeapps-apis service working correctly with a combination of improbable and connect gRPC servers. As a side-effect, I updated the liveness and readiness checks to use a grpc request (since we no longer have the gateway endpoint for the core plugin service).
Initially I'd tried using the existing server as the default and routing certain routes for transitioned servers to the new …
=> Switch the core plugin gRPC service to connect gRPC.

.github/workflows/kubeapps-general.yaml, cmd/kubeapps-apis/server/server.go
Just verifying that we actually don't need to lose the gRPC Gateway functionality (of the ReST-ish API translation to gRPC).
In the end, all that was required was to update the gateway args so that it points to the *new* gRPC connect service, and then it just continues to work (I'd thought it was dependent on a piece that we'd be removing, but it's not).
Local example check:
```
curl http://localhost:50051/core/plugins/v1alpha1/configured-plugins
{"plugins":[{"name":"helm.packages", "version":"v1alpha1"}, {"name":"resources", "version":"v1alpha1"}]}
```
I assume I'll be able to hook it up similarly when using other plugin services with auth.
We keep the OpenAPI gateway API :)
None
- Ref #6013
=> Verify that gateway ReST-ish API can still be used!

cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins_test.go, cmd/kubeapps-apis/core/serveopts.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider.go, cmd/kubeapps-apis/plugins/pkg/helm/helmaction_configgetter.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
This PR does some background prep, updating the config getter signature to include the http headers (which the connect gRPC uses).
Following PRs just have changes for actual plugins.
- ref #6013
=> Update to pass http Header as well as context for authz.

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_fan_in.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_test.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go, cmd/kubeapps-apis/server/server.go
This PR switches the core packages API to be using the connect gRPC for gRPC and gRPC-Web. The authz token is then set in the context when calling the (currently untransitioned) plugin implementations.
Step 2 of 4 done.
- ref #6013
=> Switch core packages to use connect.

cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/core/plugins/v1alpha1/plugins_test.go, cmd/kubeapps-apis/core/serveopts.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/release_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_auth.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/test_util_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_resources.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider.go, cmd/kubeapps-apis/plugins/pkg/clientgetter/clients_provider_test.go, cmd/kubeapps-apis/plugins/pkg/helm/helmaction_configgetter.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_filtering.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go
We no longer need to be passing the context down and around for authorization, as headers are used now.
This PR isn't complete - I've got a bunch of TODOs that I need to followup.
- ref #6013
=> Remove unnecessary context for authz

cmd/kubeapps-apis/core/plugins/v1alpha1/plugins.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/main.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/server.go, dashboard/src/actions/installedpackages.test.tsx, dashboard/src/actions/installedpackages.ts, dashboard/src/actions/kube.test.tsx, dashboard/src/actions/kube.tsx, dashboard/src/components/AppView/AppView.test.tsx, dashboard/src/components/AppView/AppView.tsx, dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx, dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx, dashboard/src/reducers/kube.test.ts, dashboard/src/reducers/kube.ts, dashboard/src/shared/types.ts
Removes the last redundant pieces of functionality after the switch to connect gRPC-Web. In particular:
- Switches the resources plugin to use the connect gRPC client rather than the non-connect one, so that the header auth can be used, which meant
- Remove the last use of auth in the go context and supporting function
-  Remove the `subscriptions` state in the dashboard, which was related to the non-connect gRPC-Web implementation that subscribed to events rather than using async/await.
- Remove redundant `closeRequestResources` action.
Completes the work for 6013
- fixes #6013
=> Switch resources plugin to use connect core packages client and other clean-ups.

cmd/pinniped-proxy/Cargo.lock, dashboard/package.json, dashboard/yarn.lock
Just remaining dep updates for 2.7.0 release.
=> Rust and Javascript deps.

.github/workflows/kubeapps-general.yaml
In the previous PR I changed the minor version of the GH CLI correctly, but failed to change the patch version, resulting in a release that does not exist:
https://github.com/vmware-tanzu/kubeapps/pull/6209/files#diff-5b6cd7ed775959abb6c5484c9dabb475d5bb5c55850de016832356722ec3f7f8R40-R41
Full-integration pipeline can download the GH CLI.
=> Fix version for Github CLI

.github/actions/srp-source-provenance/action.yml
has moved from /linux/ to /linux-amd64/
Not clear to me why we were on the old 0.2 version, but the [0.2 version has a `/linux/` directory](https://vmwaresaas.jfrog.io/ui/native/srp-tools/srpcli/0.2.20220825211752-571e676-57/) while the [0.7 version has arch-specific directories](https://vmwaresaas.jfrog.io/ui/native/srp-tools/srpcli/0.7.2-20230418081227-67dbd9c-113).
=> At some point between the 0.2 release and the 0.7 the linux binary

script/chart_sync_utils.sh
See #6220 for a description.
We can release.
We'll need to manually update the auto-generated PR for the upstream change with the correct images.
- ref #6220
=> Workaround for non-existent GH repo tags.

script/chart_sync_utils.sh
After getting a couple of dev chart auto-created PRs like #6236, which are doing nothing except setting our development images from `latest` (which they should be in the dev chart) to a fixed version, I realised that in #6221 I'd actually updated the incorrect part of the script.
This PR fixes that, by ensuring that we don't refer to `tag` in `replaceImage_latestToProduction` since we don't have the production values of the tag currently (until we update to use the dockerhub API as per #6220) - this was the intended change of the previous PR - and reverts the unintended change that updated `replaceImage_productionToLatest` so that we again expect `latest` for our own images in the dev chart.
We're no longer bothered by noop PRs such as #6236 .
- fixes #
=> Revert and fix so that latest tag is used in dev chart PRs.

cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go, script/makefiles/deploy-dev.mk
When Kubeapps was encountering Helm charts with non-semver versions, rather than just returning the versions as they are, we were implicitly converting them to the closest semver. This resulted in Kubeapps then not being able to upgrade to a different version once an app with a non-semver version was installed.
See #6099 for more detail.
If people choose to use non-semver versions, we don't block them from upgrading.
We were previously ignoring errors when creating semver versions whereas with this PR we now simply return all the versions as they were provided. This may change some untested behavior, though unlikely.
- fixes #6099 
Also fixes an accidental change to our dev environment Makefile (I'd accidentally committed a change in #6209 that had our dev environment installing the …
=> GetAvailablePackageVersions returns non-semver versions unchanged

Makefile, cmd/oci-catalog/Cargo.toml, cmd/oci-catalog/Dockerfile, cmd/oci-catalog/src/main.rs
Creating the Dockerfile for the stubbed service now so that we can start the process for getting an official image in the bitnami pipeline.
I'll have another attempt at a static build for a scratch image before making the request.
We can communicate a working Dockerfile for the official Bitnami image to be based on.
- ref #6263
```
$ IMAGE_TAG=dev1 make kubeapps/oci-catalog
...
$ docker run -p 50051:50051 docker.io/kubeapps/oci-catalog:dev1 
```
then in a separate terminal
```
$  grpcurl -proto ./proto/ocicatalog.proto -d '{"repository": {"registry": "registry-1.docker.io"}}' -plaintext "127.0.0.1:50051" ocicatalog.OCICatalog.ListTagsForRepository
{
"name": "tag-0"
}
{
"name": "tag-1"
}
{
"name": "tag-2"
}
{
"name": "tag-3"
}
{
"name": "tag-4"
}
{
"name": "tag-5"
}
{
"name": "tag-6"
}
{ …
```
=> Initial Dockerfile for OCI catalog.

cmd/oci-catalog/Cargo.lock, cmd/oci-catalog/Cargo.toml, cmd/oci-catalog/build.rs, cmd/oci-catalog/src/cli.rs, cmd/oci-catalog/src/main.rs, cmd/oci-catalog/src/providers/dockerhub.rs, cmd/oci-catalog/src/providers/mod.rs
Adds basic command options (`--help`, `--port`, `--version`).
Splits code out to enable multiple providers later.
- ref #6263 
```
$ RUST_LOG=info cargo run -- --port 9876 
Finished dev [unoptimized + debuginfo] target(s) in 0.37s
Running `target/debug/oci-catalog --port 9876`
[2023-06-09T04:31:05Z INFO  oci_catalog] listening for gRPC requests at 0.0.0.0:9876
```
=> Restructure to enable multiple providers. Add basic command options.

cmd/oci-catalog/Cargo.lock, cmd/oci-catalog/Cargo.toml, cmd/oci-catalog/proto/ocicatalog.proto, cmd/oci-catalog/src/providers/dockerhub.rs
Adds implementation of send_repositories for the dockerhub implementation, replacing the stub.
Actual results (see below).
- ref #6263 
Logs for request show two separate requests to hub.docker:
```
RUST_LOG=debug cargo run
Finished dev [unoptimized + debuginfo] target(s) in 0.52s
Running `target/debug/oci-catalog`
[2023-06-13T01:54:29Z INFO  oci_catalog] listening for gRPC requests at 0.0.0.0:50001
[2023-06-13T01:54:33Z DEBUG oci_catalog::providers::dockerhub] requesting: https://hub.docker.com/v2/namespaces/bitnamicharts/repositories/?page_size=100&ordering=name&content_types=helm
[2023-06-13T01:54:33Z DEBUG reqwest::connect] starting new connection: https://hub.docker.com/
[2023-06-13T01:54:35Z DEBUG oci_catalog::providers::dockerhub] requesting: …
```
=> Replace stub request with real (non-authed) dockerhub request.

cmd/oci-catalog/proto/ocicatalog.proto, cmd/oci-catalog/src/main.rs, cmd/oci-catalog/src/providers/dockerhub.rs, cmd/oci-catalog/src/providers/mod.rs
After improving the error handling, this PR adds a strategy pattern for enabling the provider to be chosen based on the request.
Other providers can be added easily.
- ref #6263
=> [OCI-Catalog] Improve error handling. Add provider strategy.

cmd/kubeapps-apis/plugins/pkg/connecterror/connecterror.go, cmd/kubeapps-apis/plugins/pkg/connecterror/connecterror_test.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_test.go
When we switched to connect-grpc, we continued sending standard gRPC error codes from Kubeapps-APIs, and without more information, the [connect-gRPC machinery was converting these to code unknown](https://connect.build/docs/go/errors/#working-with-errors).
When we check that a user has authenticated successfully by getting the default namespace after the login dance, either an OK or a forbidden means the request was authenticated, unauthenticated means it was not. But instead the error was coming back with an unknown code and so Kubeapps was not recognising this as authenticated. This was affecting logins for users who do not have permission to get the default namespace (see #6269 for the workaround).
I reproduced this locally (though with token auth) and so before this change, the gRPC …
=> Switch CheckNamespaceExist to return a connect error as expected by client

cmd/kubeapps-apis/plugins/pkg/connecterror/connecterror.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/namespaces_test.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets.go, cmd/kubeapps-apis/plugins/resources/v1alpha1/secrets_test.go
Follows on from #6319, cleaning up the resources plugin so that it uses the connect error.
- ref #6269
PRs will follow for the helm and flux plugins, before removing the original status error code.
=> Switch resources plugin over to connect error.

cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/chart_cache.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/chart.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/create_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/delete_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_resources.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/rollback_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go
Continuing switch from status.Error to connect.Error. See #6269 for more info.
- ref #6269
=> Switch helm plugin to use connect error (part 1/2)

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/getresourcerefs_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_auth.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/update_test.go
This is the rest of the updates removing the old status errors from the Helm plugin.
- ref #6269
=> Finish switching the helm plugin to connect error (2/2)

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Doesn't complete but does most of the kapp-controller switch to the connect error with tests passing.
- fixes #6269
=> Convert carvel plugin to connect errors pt 1/2

cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_packages.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_ctrl_repositories.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_adapters.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_data_resources.go, cmd/kubeapps-apis/plugins/kapp_controller/packages/v1alpha1/server_test.go
Finishes the switch of the kapp-controller plugin over to use the connect errors. Next up, flux.
- ref #6269
=> Switch the remaining kapp-controller errors to connect.

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go
This PR updates the OCI app registry validation so that an empty list of repositories is allowed if a catalog is available. 
Step 2 of 3 in experiment to support VAC index.
- ref #6263
=> Update OCI validation allowing empty repo list if catalog available.

.github/dependabot.yml
Just ensures we're not blocking further non-security dep updates when we stall on some manual dep updates.
Less blocking of further dependabot PRs.
=> Update the pull-request limit to 10, matching the defualt for security issues.

cmd/asset-syncer/server/utils.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx
Two small fixes required when testing the VAC catalog for an OCI registry:
1. Ensure the UX no longer requires the filter field
2. Ensure in the backend the repositories are set before the CheckSum is calculated.
With this change, Kubeapps displays the full catalog from a VAC-published OCI registry.
- ref #6263
=> Small fixes for IRL test of VAC catalog index.

dashboard/package.json
Ensures that the `craco build` step has enough heap space. I can reproduce the issue that CI sees by reducing the heap space and re-running:
```
% yarn build
yarn run v1.22.19
warning ../../package.json: No license field
$ npm-run-all build-css compile-lang build-js
warning ../../package.json: No license field
$ sass src/ --no-source-map && yarn run copy-clr
warning ../../package.json: No license field
$ shx cp ./node_modules/@clr/ui/clr-ui-dark.min.css public/clr-ui-dark.min.css && shx cp node_modules/@clr/ui/clr-ui.min.css public/clr-ui.min.css && shx cp ./node_modules/@clr/ui/clr-ui-dark.min.css.map public/clr-ui-dark.min.css.map && shx cp ./node_modules/@clr/ui/clr-ui.min.css.map public/clr-ui.min.css.map
warning ../../package.json: No license field
$ formatjs compile-folder lang …
```
=> Ensure craco build has enough heap space.

dashboard/src/shared/KubeappsGrpcClient.ts
Fixes static `baseUrl: /...` to be relative `baseUrl: ./...`
Restores previous functionality of working behind url subpath aka ingress
Unknown
- fixes #6314
=> Changed baseUrl to use relative path to support URL subpath

dashboard/src/components/LoginForm/LoginForm.test.tsx, dashboard/src/components/LoginForm/LoginForm.tsx, dashboard/src/shared/specs/mountWrapper.tsx
When switching from a container to a component with hooks, I missed that the prop was passed from the container as:
```
oauthLoginURI: authProxyEnabled ? oauthLoginURI : "",
```
but with the component the oauthLoginURI was always defined.
Can configure token auth again
- ref #6187
=> Ensure token auth can be configured while oauthLoginURI is defined.

dashboard/src/components/AppList/AppList.test.tsx, dashboard/src/components/AppList/AppList.tsx
Fixes an issue I'd noticed while upgrading react-router, in that sometimes the installed apps for the namespace would display, then seconds later, be updated with installed apps across all namespaces.
No longer have this confusing UI behaviour.
None.
- ref #6187
=> Ensure only single request for installed apps.

cmd/pinniped-proxy/Cargo.lock, cmd/pinniped-proxy/Cargo.toml
As per the dependabot PRs (see #6577), we need to upgrade these together.
Upgrade works.
Some difference in k8s 1.27 that tests don't catch.
=> Rust updates for k8s.

cmd/oci-catalog/src/providers/dockerhub.rs, cmd/oci-catalog/src/providers/mod.rs
Adds the implementation for retrieving and sending tags for dockerhub repositories.
Enables an initial integration to be tested.
- ref #6263 
IRL test:
```console
grpcurl -plaintext -proto ./proto/ocicatalog.proto -d '{ "repository": {"registry": "registry-1.docker.io", "namespace": "bitnamicharts", "name": "zookeeper" }}' 0.0.0.0:50001 ocicatalog.OCICatalog.ListTagsForRepository
{
"name": "11.4.10"
}
{
"name": "11.4.9"
}
{
"name": "11.4.8"
}
{
"name": "11.4.7"
}
{
"name": "11.4.6"
}
{
"name": "11.4.5"
}
{
"name": "11.4.4"
}
{
"name": "11.4.3"
}
{
"name": "11.4.2"
}
{
"name": "11.4.1"
}
{
"name": "11.3.2"
}
{
"name": "11.3.1"
}
{
"name": "11.2.1"
}
{
"name": "11.1.6"
}
{
"name": "11.1.5"
}
{
"name": "11.1.4"
}
{
"name": "11.1.3"
}
{
"name": "11.1.2"
}
{
"name": "11.1.1"
}
{
"name": …
```
=> Add DockerHub implementation for send_tags

cmd/kubeapps-apis/Dockerfile, site/content/docs/latest/reference/developer/release-process.md
Just a minor PR mainly sorting the `ARG`s and adding some comments to make it easier to find the latest release. Also, making the download of golangci-lint conditional.
Finally, adding `GRPC_HEALTH_PROBE_VERSION` to the docs, so that we can find it easily.
More clear dockerfile
N/A
N/A
N/A
=> Improve kubeapps-apis dockerfile and docs

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go
As described in #6584, we were returning wrong versions in some corner cases (mainly using pre-releases). It seems we were relying on `ChartVersions[0]` with the explicit assumption that it would always contain the latest version. However, this is not the case. Since the DB does not know about semver (unless we used some [extensions](https://github.com/theory/pg-semver)), the ORDER BY query might be wrong.
This PR is replacing the occurrences of `ChartVersions[0]` in favor of a previous semver sorting. The affected operations are: `GetAvailablePackageDetail`, `GetAvailablePackageSummaries`, `GetInstalledPackageSummaries` and `GetInstalledPackageDetail`.
The `latestVersion` returned by the API (and therefore used by the UI -as is-, we don't sort them in client-side) will be the one that …
=> Sort packages by version instead of relying on `ChartVersions[0]`

dashboard/src/components/PackageHeader/PackageReadme.test.tsx, dashboard/src/components/PackageHeader/PackageReadme.tsx, dashboard/src/components/PackageHeader/PackageView.tsx
When packages don't have any readme file, currently the spinner is never hidden. It gives the impression of something still unloaded, so the user should remain in that page because sth else will be displayed soon.
However, this is not true: once `! isFetching`, if there is no readme... it will never be available.
This PR passes the `isFetching` prop downstream so that the readme renderer can decide what to display.
No more endless spinner when no readme is provided.
N/A
N/A
=> Avoid endless spinner when no readme is provided

.github/workflows/kubeapps-general.yaml, script/chart_sync_utils.sh, script/e2e-test.sh
While setting up the dev chart changes, just realised I hadn't yet updated to publish the dev image.
Dev image for oci-catalog will be available.
- ref #6263
=> Build and push the dev oci-catalog image.

script/chart_sync_utils.sh
This PR is to actually fix #6220 by fetching from DockerHub the more recent (!=latest) published tag. I'm removing the workaround performed in https://github.com/vmware-tanzu/kubeapps/pull/6237. 
The script will continue to work as initially expected.
N/A
- fixes #6220 
N/A
=> Fix script to fetch the latest published container in dockerhub

.licenserc.yaml, cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/gen/core/packages/v1alpha1/packages.pb.go, cmd/kubeapps-apis/gen/core/packages/v1alpha1/repositories.pb.go, cmd/kubeapps-apis/gen/plugins/fluxv2/packages/v1alpha1/fluxv2.pb.go, cmd/kubeapps-apis/gen/plugins/helm/packages/v1alpha1/helm.pb.go, cmd/kubeapps-apis/proto/kubeappsapis/apidocs/v1alpha1/apidocs.proto, cmd/kubeapps-apis/proto/kubeappsapis/core/packages/v1alpha1/repositories.proto, cmd/kubeapps-apis/proto/kubeappsapis/core/plugins/v1alpha1/plugins.proto, cmd/kubeapps-apis/proto/kubeappsapis/plugins/fluxv2/packages/v1alpha1/fluxv2.proto, cmd/kubeapps-apis/proto/kubeappsapis/plugins/helm/packages/v1alpha1/helm.proto, cmd/kubeapps-apis/proto/kubeappsapis/plugins/kapp_controller/packages/v1alpha1/kapp_controller.proto, cmd/kubeapps-apis/proto/kubeappsapis/plugins/resources/v1alpha1/resources.proto
Just a small copyright date update in proto files and mechanical re-generation with current buf.
I was needing to run buf generate on my own work branch and was seeing distracting side-effects such as dates which had been manually (?) changed to 2023 in generated files being reverted back to 2022. So this PR just updates the dates in the proto files and regenerates so I won't have that noise in my own diff.
Easier reviewing.
- ref #6263
I'll land this once passing to continue.
=> Update proto copyright dates so generated matches existing dates.

chart/kubeapps/templates/_helpers.tpl, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/values.yaml, cmd/kubeapps-apis/Dockerfile, cmd/oci-catalog/Cargo.lock, cmd/oci-catalog/Cargo.toml, cmd/oci-catalog/Dockerfile, cmd/oci-catalog/src/main.rs
Adds the initial values and container for the oci-catalog to the kubeapps-apis service.
Leaving in draft for the moment as there are a number of things I want to check IRL while playing:
- ~~Use an actual grpc liveness check (to test that out, since we can remove the grpc health binary, as our oldest k8s version is now past 1.24)~~ Bitnami tests are still testing with 1.23 apparently.
- Evaluate whether kubeapps-apis is really the right pod for having this side-car. We'll need to use the service when validating a repo from the UX (which is kubeapps-apis), but also during the sync job. It could also run as a separate pod, but not sure it's worth the resources.
Note: I've got `ociCatalog.enabled` defaulting to false now, so no change to the chart output.
Can start integration.
- ref #6263 …
=> Add initial values and container to the kubeapps-apis service.

cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/test_util_test.go
First part of integration work to update the OCI repo support to use the oci-catalog service. This PR refactors the existing repository validation to remove the assumption of an `HTTPValidator` (since the gRPC validation doesn't use an httpclient etc.)
Step towards adding grpc validation for OCI repositories using the new service.
None
- ref #6263
=> Refactor repo validation so as to not require http-only validators.

chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/values.yaml, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, pkg/ocicatalogtest/ocicatalogtest.go
Follows on from #6620, uses the grpc Client to check if we can find repos for an OCI registry. While there I improved a couple of other things regarding the validation:
- a context.Context can (and must) now be passed through to the validation (we should always pass the request context through subsequent requests); and
- the getValidator function is now a method so that the different validators can have custom data set (such as the OCI catalog address, or the repo client getter).
I've added a basic test double grpc service for the OCI catalog to use here in tests, and will undoubtedly improve this test double when adding the actual sync functionality to use the OCI catalog service next.
OCI Catalog service can be used to check an OCI Registry, without impacting current behaviour.
None …
=> Use OCI catalog service when available for OCI validation

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.test.tsx, dashboard/src/components/Config/PkgRepoList/PkgRepoForm.tsx
When OCI support was added originally, we required people to specify an http/https URL for the registry, even though Helm itself allows oci://, because we're (Kubeapps) actually interacting with the OCI distribution spec in that code.
In addition, there was an issue in the dashboard that even if you did specify `oci://registry-1.docker.io/foo` the dashboard would assume the URI was missing a protocol since it doesn't start with `http` and add it, resulting in `https://oci://registry-1.docker.io/foo`.
This PR fixes the dashboard issue (so you can specify an oci protocol), updates the validation in the kubeapps-apis to use https in that case, and the sync code to do the same.
Users can specify the OCI registry the way they would with Helm or other tools (this actually tripped up someone …
=> Allow `oci://` protocol to be specified for OCI AppRepositories

cmd/asset-syncer/server/delete.go, cmd/asset-syncer/server/postgresql_db_test.go, cmd/asset-syncer/server/postgresql_utils.go, cmd/asset-syncer/server/postgresql_utils_test.go, cmd/asset-syncer/server/sync.go, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/integration_utils_test.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/oci_repo.go, cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/repo.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/postgres_db_test.go, cmd/kubeapps-apis/plugins/pkg/pkgutils/pkgutils_test.go, pkg/chart/models/chart.go, pkg/dbutils/dbutilstest/pgtest/pgtest.go, pkg/helm/index.go, pkg/helm/index_test.go, pkg/ocicatalog_client/ocicatalog_client.go, pkg/ocicatalog_client/ocicatalog_clienttest/ocicatalog_clienttest.go
The code currently talks about OCI repositories and Helm repositories and Helm repositories that are OCI registries. This PR is just splitting out some renaming to avoid the confusion, so instead we have:
- `Repo` model -> `AppRepository` which correspond to our `AppRepository` custom resource which can represent a Helm repository or an OCI registry (or a namespace within an OCI registry) which contains many oci repositories.
- `Repo` interace -> `ChartCatalog` interface, as this is implemented by both Helm and OCI versions
It contains another small refactor pulling out a `ocicatalog_client.NewClient` helper.
Leaving as draft for now in case I come across any other straight renames/refactors in the current work.
- ref #6263
=> Refactor some names to avoid confusion between OCI repositories and Helm repositories.

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation_test.go, pkg/ocicatalog_client/ocicatalog_client.go
This PR moves the validation code that checks the oci-catalog service into the existing OCIApiClient itself, so that we can use the same and encapsulate the functionality in the one place - the OCIApiClient - when adding the sync functionality.
Functionality encapsulated in the one client. Also improves existing code to use contexts in network calls.
Also removes the `AuthHeader` that was not being used, since some time ago we switched to creating the http client using the header, so the auth is present there already.
None that I can see (let CI determine).
- ref #6263
=> Update the OCIApiClient to be aware of (and use) oci-catalog service

chart/kubeapps/templates/apprepository/deployment.yaml, chart/kubeapps/templates/kubeappsapis/deployment.yaml, chart/kubeapps/templates/kubeappsapis/service.yaml, cmd/apprepository-controller/cmd/root.go, cmd/apprepository-controller/server/job_utils.go, cmd/apprepository-controller/server/server.go, cmd/asset-syncer/cmd/root.go, cmd/asset-syncer/server/sync.go, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go
Updates the dev chart and snippets of code so that if the OCI-Catalog service is enabled, the URL is passed all the way through to the sync job.
Verified from the logs:
```
I0829 01:33:33.729325       1 root.go:32] "The component 'asset-syncer' has been configured with" serverOptions={"DatabaseURL":"kubeapps-postgresql:5432","DatabaseName":"assets","DatabaseUser":"postgres","DatabasePassword":"REDACTED","Debug":false,"Namespace":"default","OciRepositories":[],"TlsInsecureSkipVerify":false,"FilterRules":"","PassCredentials":false,"UserAgent":"asset-syncer/903124d9eb9976d7cad846331c20440132b143df (kubeapps/DEVEL)","UserAgentComment":"kubeapps/DEVEL","GlobalPackagingNamespace":"kubeapps","KubeappsNamespace":"","AuthorizationHeader":"","DockerConfigJson":"","OCICatalogURL":"kubeapps-internal-k …
```
=> Pass OCI Catalog URL through to syncer.

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_validation.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/chart-client.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/chart-client_test.go, pkg/http-client/httpclient.go
Follows on from #6746 removing more uses of the httpclient.Client test interface that's causing pain when adding new features, and updates tests to use an `httptest.Server` instead of mocking the client.
See #6726 
Also fixes more tests that were feigning to assert that errors were equal, but were simply asserting that an error was raised.
- fixes #6726
~~One more PR following which removes the remainder and the interface itself.~~ (Ended up just adding to this PR).
=> Part two removing test interface httpclient.Client

cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go
Switches the `TagList` and `IsHelmChart` functions in the syncer to use the standard ORAS client (which handles getting tokens etc.)
Use the existing oras client to handle re-fetching tokens on 401s etc., so we don't need to (currently our code doesn't do this at all, which is why we can't currently use a public OCI repo).
- ref #6706 
More to follow.
=> Update TagList and helm check to use oras client.

cmd/asset-syncer/cmd/root.go, cmd/asset-syncer/server/postgresql_utils.go, cmd/asset-syncer/server/sync.go, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, pkg/helm/fake/helm.go
This PR update the way we pull OCI repos, so that we:
- Don't pull all manifests of all tags to verify that they are helm charts before syncing
- Don't do an all-or-nothing sync (previous code synced all tags from the repo if the checksum differed), instead only syncing those tags that don't exist in the cache.
- Reduces the number of workers to 5 for now, but I want to put this back to 10 in a subsequent PR with other changes.
We can pull large OCI catalogs from public repos (in particular, can pull the Bitnami catalog from Dockerhub) without hitting public pull limits.
The initial time until the catalog can be used is slightly longer. But I have two things I want to improve in a subsequent PR:
- Update the cache after each app/repo is synced so they can be viewed in the catalog more …
=> Less obnoxious OCI pulling on sync

cmd/apprepository-controller/Dockerfile, cmd/asset-syncer/Dockerfile, cmd/asset-syncer/server/postgresql_db_test.go, cmd/asset-syncer/server/postgresql_utils.go, cmd/asset-syncer/server/postgresql_utils_test.go, cmd/asset-syncer/server/sync.go, cmd/asset-syncer/server/utils.go, cmd/asset-syncer/server/utils_test.go, cmd/kubeapps-apis/Dockerfile, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/postgresql_utils.go, pkg/dbutils/postgresql_utils.go
Currently ensures that the existing (already synced) chart versions are included when syncing new chart versions, so that the full set of data is retained in the DB (since the chart versions aren't actually rows in the db, but rather within a json blob of the chart).
This PR refactored the way the syncing happens, specifically ensuring that data is synced to the db as each chart is processed, rather than when all charts are synced (so that we get better feedback in the UI when syincing OCI repos).
Before the change:
- a shallow + deep sync of the non-OCI Helm repo takes around 7s
- a shallow sync of the Bitnami OCI repo would see us hitting the rate limit and getting 429s.
With the changes,
- a shallow + deep sync of a non-OCI Helm repo takes around 10s (extra overhead of sycing to the DB …
=> Ensure already synced versions are included in the result.

go.mod
As part of #6706 I'd updated the go version in our Dockerfiles as well as the kubeapps-general.yaml CI config file, but not in the go.mod, which is used by Bitnami to determine the go version for the official images.
The bitnami builds should use the required 1.21 (excellent of Bitnami to automate that!)
=> Update go.mod's go version (already did Dockerfiles and CI).

cmd/kubeapps-apis/core/packages/v1alpha1/packages.go, cmd/kubeapps-apis/core/packages/v1alpha1/packages_test.go, cmd/kubeapps-apis/plugin_test/mock_plugin.go, cmd/kubeapps-apis/plugin_test/utils.go
Follows on from #6941 , adding the implementation for the core API service.
Next PR will add the implementation for the helm plugin using the OCI distribution spec API so that we can investigate UX options for displaying the data.
- ref #6548
=> Add implementation for the core API service.

chart/kubeapps/README.md, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/repositories_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server_test.go, site/content/docs/latest/reference/scripts/setup-demo-harbor-oci-metadata.sh
After a small refactor to re-use an existing test function, this PR adds the implementation for fetching the referrers of an OCI chart.
This includes using the annotations in the referrers for the name/description returned (for better UX) as well as an http fake for handling the OCI requests in tests.
- ref #7038
=> Adds implementation of Helm OCI refererrs endpoint.

script/makefiles/site.mk, site/content/docs/latest/reference/developer/release-process.md, site/netlify.toml
Bump the Hugo version to the latest one.
Keep our website template engine up to date.
N/A
N/A
N/A
=>  Bump Hugo from 0.116.1 to 0.121.2

.github/workflows/codeql-analysis.yml, site/content/docs/latest/reference/developer/release-process.md
I noticed we forgot to update the Go version used in the CodeQL Github Action. This PR is to bump it up and update the docs so that we don't forget again.
No failed CodeQL executions.
N/A
N/A
N/A
=> Update Go version used in the CodeQL action

.github/workflows/kubeapps-sync-chart-from-bitnami.yaml, .github/workflows/kubeapps-sync-chart-to-bitnami.yaml, script/chart_sync_utils.sh
As, sometimes, the sync chart from/to our official Bitnami repo fails, it is useful to have a manual way to trigger those events without having to fully trigger the whole integration test pipeline.
This PR, apart from fixing a small bug, adds two new GHA workflows indented to be manually triggered if necessary.
It's mostly a copy-paste thing for now, further refactor is required (but we need the manual trigger timely).
N/A
N/A
=> Add manual sync chart jobs in CI

script/chart_sync_utils.sh
This PR fixes the script for syncing the chart to the bitnami repo removing a not-always-true assumption.
The more generic approach is less prone to errors.
N/A
N/A
N/A
=> Fix chart_sync_utils.sh

site/config.yaml, site/themes/template/layouts/_default/baseof.html, site/themes/template/layouts/partials/base-footer.html
This PR update the cookie banner to use the Broadcom's OneTrust one.
Compliant website,
N/A
N/A
N/A
=> Update banner to broadcom's onetrust

cmd/apprepository-controller/Dockerfile, cmd/asset-syncer/Dockerfile, cmd/kubeapps-apis/Dockerfile, cmd/oci-catalog/Dockerfile, cmd/pinniped-proxy/Dockerfile
Make casing of `FROM` and `AS` keywords in dockerfiles consistent.
This change will remove the warning being shown when docker images are built.
```
1 warning found (use --debug to expand):
- FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 6)
```
Sample job: https://github.com/vmware-tanzu/kubeapps/actions/runs/9937352647/job/27449161644#step:6:978
=> Fix `FromAsCasing` warning in Dockerfiles

script/e2e-test.sh
After the last refactor of the integration tests, there is a bug when running the tests passing `all` as the `TESTS_GROUP` variable. The script is trying to run the tests under `all` directory for every test group instead of running the tests in each corresponding directory. This PR fixes that.
Intregration tests works properly when `all` is passed as the `TESTS_GROUP` to run.
N/A
N/A
=> Fix integration tests when running all tests

.github/workflows/linters.yml, site/themes/template/layouts/_default/baseof.html
Kubeapps implemented an external documentation site a few years ago. This documentation site is currently outdated and does not offer a complete vision of the Kubeapps features and use cases. This PR redirects users to the GitHub repository where the latest documentation will be available 
**Benefits**
The team can concentrate efforts on developing new features and fixing bugs rather than maintaining a documentation site that is redundant. 
Unrelated change, the golangci-lint process failed until reverted to the 1.59.1 version.
=> Redirect external site to GitHub

README.md, site/content/docs/latest/howto/OIDC/OAuth2OIDC-keycloak.md, site/content/docs/latest/howto/OIDC/OAuth2OIDC-oauth2-proxy.md, site/content/docs/latest/howto/custom-app-view-support.md, site/content/docs/latest/howto/deploying-to-multiple-clusters.md, site/content/docs/latest/howto/offline-installation.md, site/content/docs/latest/reference/scripts/setup-harbor.sh, site/content/docs/latest/reference/scripts/setup-kubeapps.sh, site/content/docs/latest/tutorials/getting-started.md, site/content/docs/latest/tutorials/kubeapps-on-tkg/step-2.md
Point all the references to the Bitnami Kubeapps chart in the `helm install` command to the OCI repository.
Docs and scripts are up-to-date and point to the OCI version of the Bitnami chart.
None.
N/A
N/A
=> Point Helm chart references to the OCI repository

cmd/asset-syncer/server/utils.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/server.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/chart-client.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/chart-client_test.go, cmd/kubeapps-apis/plugins/helm/packages/v1alpha1/utils/fake/chart.go, pkg/tarutil/tarutil.go
This PR aims to fix #8153 by resolving this error:
```
E1219 15:25:15.632218       1 utils.go:1024] Failed to import files, ID=bitnami/nginx, version=17.3.3: Get "oci://registry-1.docker.io/bitnamicharts/nginx:17.3.3": unsupported protocol scheme "oci"
```
Currently, the kubeapps-asset-syncer is unable to fetch the information when the chart URL is stored in OCI.
In this PR, the chart tarballUrl is transformed when the oci schema is detected and replaced by its OCI blob URL, so the asset syncer will be able to fetch the chart tarball the same way as it does for non-OCI charts.
None known.
- fixes #8153
=> Add support for OCI tarball url

script/e2e-test.sh
Fixes e2e tests by adding 'global.security.allowInsecureImages=true' to helm install/upgrade commands
This is required since the tests will use the custom built images for testing purposes.
=> Fix e2e tests by allowing custom images in helm install

README.md
After many years of growth and milestones, the time has come for the next chapter of Kubeapps. The current maintainers are concentrating their efforts on new projects. We are looking for volunteers to help us maintain the project going forward. Without new volunteers, the project will be deprecated and the repo archived on August 8th, 2025.
=> Add deprecation notice to indicate project will no longer be maintained
