vmware-tanzu/kubeapps

- README.md
- cmd/down.go
- cmd/up.go
- Default set to `~/.kubeapps`
- Use `--path` flag to provide the specific folder
> specify path to manifests

- cmd/down.go
- cmd/up.go
- glide.lock
- vendor/github.com/ksonnet/kubecfg/utils/meta.go
- vendor/github.com/ksonnet/kubecfg/utils/meta_test.go
> fix k8s version validation on GKE, set DefaultNamespace to `default`

- cmd/root.go
This enables verbosity then users can see what is actually happening with `--verbose/-v` flag.
> enable verbosity

- .gitignore
- Makefile
Instrument `Makefile` to only use dependencies from `vendor/`,
(i.e. ignore local `${GOPATH}/src` tree) to improve local builds
repeat-ability.
> [jjo] use only vendor/ dependencies

- cmd/down.go
- cmd/root.go
- cmd/up.go
This PR adds validation to k8s version before installing/uninstalling kubeapps and returns a warning message to let user aware of using k8s 1.7+ with RBAC enabled. This also contains several error messages which turns the tool to become more friendly.
> add validation to k8s version, improve error messages

- cmd/dashboard.go
- cmd/up.go
- static/kubeapps-objs.yaml
- updates manifests to the latest from kubeapps/manifest
- moves nginx-ingress-controller to the kubeapps namespace for isolation
- secures tiller and mongodb
- removes the mongodb-password secret as only mongodb-root-password is
used
> update manifests: secure tiller/mongo, isolate nginx

- static/kubeapps-objs.yaml
This will stop OOMKilled stopping Monocular from syncing and I also bumped the memory request to 512Mi just to be on the safe side.
https://github.com/kubeapps/manifest/pull/31 makes this change in the manifest
> remove monocular api resource limits and tweak mem request

- static/kubeapps-objs.yaml
Currently, adding a new repository in the Dashboard it can take up to an
hour to see charts from the new repo to appear. This reduces that time
greatly by configuring Monocular to sync every 15 mins.
> reduce chart refresh interval to 15 mins

- .travis.yml
- Makefile
This PR adds a build job for windows binary relying on the https://mingw-w64.org/ package for windows compiling on linux. The travis structure is changed to easily add more build for other platform (osx), motivated by [travis matrix](https://docs.travis-ci.com/user/customizing-the-build/#Build-Matrix)
> add cross compiling

- cmd/up.go
- cmd/up_test.go
- glide.lock
- glide.yaml
- vendor/github.com/ghodss/yaml/README.md
- vendor/github.com/ghodss/yaml/fields.go
- vendor/github.com/ghodss/yaml/yaml.go
- vendor/github.com/ghodss/yaml/yaml_test.go
- vendor/github.com/ksonnet/kubecfg/pkg/kubecfg/delete.go
- vendor/github.com/ksonnet/kubecfg/pkg/kubecfg/diff.go
- vendor/github.com/ksonnet/kubecfg/pkg/kubecfg/diff_test.go
- vendor/github.com/ksonnet/kubecfg/pkg/kubecfg/update.go
- vendor/github.com/ksonnet/kubecfg/utils/client.go
- vendor/github.com/ksonnet/kubecfg/utils/sort.go
- vendor/github.com/ksonnet/kubecfg/utils/sort_test.go
- vendor/gopkg.in/yaml.v2/.travis.yml
- vendor/gopkg.in/yaml.v2/LICENSE
- vendor/gopkg.in/yaml.v2/README.md
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/decode_test.go
- vendor/gopkg.in/yaml.v2/emitterc.go
- vendor/gopkg.in/yaml.v2/example_embedded_test.go
- vendor/gopkg.in/yaml.v2/parserc.go
- vendor/gopkg.in/yaml.v2/readerc.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
Kubecfg contains an improvement to the sort utility which, in
particular, ensures CustomResourceDefinitions are created before CRD
resources themselves. This is required for the upcoming AppRepository
stuff (improving the chart repo syncing).
I've updated Kubecfg to the latest commit as not much else has changed
since the sort improvement and latest.
This also contains glide updates to the YAML packages, let me know if
you'd like me to undo those.
> update kubecfg to latest

- docs/getting-started.md
I spent way too much time not realizing you were referencing version 0.0.2 in your "Getting started" readme, instead of the current release 0.2.0.  Ouch.  Please accept my simple changes, to help the next new user from hitting that trap.
> Update Kubeapps release build number in the Install command

- Makefile
minor change to ldflags on go build to reduce size of binary a little bit
> ldflags for go build

- .travis.yml
- Makefile
If you set `CGO_ENABLED=0`, the go tool has to rebuild all the standard lib packages at `$GOROOT`. 
`GOROOT` may be a system path on the developer host and thus would require dev's to execute `make` as a
privileged user.
This PR re-enables the use of cgo by default, while disabling it in CI builds
> disable use of cgo only for the ci builds

- README.md
- docs/install.md
Installation scripts does not work on OS X as `linux` is hardcoded in the filename for (OS aware) downloaded release `kubeapps-linux-amd64`
Both readme and install guide has been updated to select the respective os when moving the file.
> Fix installation script for OS X in documentation

- cmd/kubeapps/up.go
Since Kubeapps installs sealed secrets in the kube-system namespace, if you already have it installed it can accidentally override this. This PR adds a prompt to the user to check if they really want to override sealed-secrets.
> adds a guard to prevent overriding existing sealed-secrets installations

- dashboard/src/components/AppNew/AppNew.css
- dashboard/src/components/AppNew/AppNew.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
@sameersbn please, add a description here that explains a bit how you have implemented this
> AppNew: allow users to select a version in the appNew component

- cmd/kubeapps/up.go
kubeapps was not checking for the case where the sealed-secrets
deployment didn't exist, and was incorectly reporting that it did and
wasn't installed by kubeapps
> fix sealed-secrets check on kubeapps up

- README.md
- docs/getting-started.md
- docs/install.md
An RBAC-enabled cluster is not required, but it is encouraged.
fixes #205
> docs: update Kubeapps prereqs to mention RBAC not required

- cmd/chart-repo/chart_repo.go
- cmd/chart-repo/utils.go
- cmd/chart-repo/utils_test.go
Previously, when attempting to extract multiple files (README and
values) from the tarball, we were not resetting the file pointer when
reading through the tarball. This meant that only the first file we
searched for would actually be picked up.
This changes the logic to search for all files at the same time when
passing through the tarball, without needing to rewind the file pointer.
fixes #224
> chart-repo: fix bug indexing with missing files

- dashboard/src/actions/charts.ts
- dashboard/src/components/ChartView/ChartReadme.css
- dashboard/src/components/ChartView/ChartReadme.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/containers/ChartViewContainer/ChartViewContainer.tsx
- dashboard/src/reducers/charts.ts
- dashboard/src/shared/Chart.ts
- dashboard/src/shared/types.ts
> handle missing readme & values for chart versions

- dashboard/src/actions/charts.ts
- dashboard/src/components/AppEdit/AppEdit.tsx
- dashboard/src/components/AppEdit/index.tsx
- dashboard/src/components/AppView/AppControls.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/containers/AppEditContainer/AppEditContainer.tsx
- dashboard/src/containers/AppEditContainer/index.tsx
- dashboard/src/containers/Root.tsx
- dashboard/src/shared/HelmRelease.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Implements Helm Release feature
Status:
- User can deploy changes to an existing release. 
- The values.yaml file is populated from the existing release, so the user will be presented the values that were used previously
- Currently I have disabled the version selection which means only changes to values.yaml are possible. I need to figure out how to propogate the chartVersion changes to the Deployment form since this is a property field of the component.
> add support for upgrading helm releases

- dashboard/src/components/AppEdit/AppEdit.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/containers/AppEditContainer/AppEditContainer.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
This PR serializes the `getChartVersion` and ``getChartValues` call when the version is changed from the drop down ensuring the value of version is settled before applying the values from the `values.yaml` file.
Additionally, during upgrade of the use selects the currently deployed version from the dropdown, then the value.yaml from the current field is loaded rather than the one from the chart release
> highlight current release, persist values configuration for current version

- cmd/chart-repo/sync.go
- cmd/chart-repo/utils.go
- cmd/chart-repo/utils_test.go
Repo sync fails of the specified repo URL is sumbitted with
leading/trailing spaces.
> chart-repo: strip leading and trailing spaces for the repo URL

- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go
- cmd/chart-repo/sync.go
- cmd/chart-repo/types.go
- cmd/chart-repo/utils.go
- cmd/chart-repo/utils_test.go
- dashboard/src/actions/charts.ts
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/index.tsx
- dashboard/src/containers/RepoListContainer.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/types.ts
- manifests/helm-crd.jsonnet
Adds `auth` field to AppRepository spec to providing the authentication header for HTTP requests. `chart-repo sync` command use the specified header to make the requests
eg.
```
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
annotations: {}
labels:
created-by: kubeapps
name: fuloi
name: fuloi
namespace: kubeapps
spec:
type: helm
url: http://artifactory.fuloi.com/artifactory/helm
auth:
header: 
secretKeyRef:
name: apprepo-fuloi-secrets
key: authorizationHeader
```
> feature: support for specifying optional authorization token for HTTP requests

- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/FunctionView/FunctionView.tsx
- dashboard/src/shared/WebSocketHelper.ts
Added in a private function in 2 areas (AppView.tsx and FunctionView.tsx) to determine if browser is using HTTP or HTTPS, and use the corresponding ws or wss protocols in apiBase. Tested with both HTTP & HTTPS browsers and works in both situations.
NOTE: There may be a better location for a shared function, but couldn't determine the optimal shared functions area. (I'm not a developer by trade... I know just enough to get flamed on github, so be kind).
> Updated apiBase to use WSS if connection is established with HTTPS

- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go
- cmd/chart-repo/utils.go
- manifests/kube-api.jsonnet
The dashboard creates a Secret resource if a chart repo requires authentication. This 
PR adds a rule to the `kubeapps-kube-api` role to be able to do that.
Additionally some minor fixes have been imported from bitnami-labs/helm-crd/pull/23
> add rule to manage secrets in the kubeapps namespace

- dashboard/src/components/ChartList/ChartList.tsx
The charts tab errors out if there are no charts available in repos. To reproduce remove all chart repos from the app repository configuration page.
This PR displays a helpful message when no charts are available
> dashboard: adds no charts error message

- .travis.yml
Fixes an earlier conditional I mistakenly added that prevented tagged
image builds from being pushed!
> ci: fixes image builds to push tagged builds

- Makefile
see: https://github.com/golang/go/issues/24674
> Fixes building kubeapps on ubuntu 18.04 (with golang snap package)

- .travis.yml
- dashboard/.dockerignore
- dashboard/Dockerfile
> install application dependencies during the image build

- cmd/chartsvc/handler.go
- cmd/chartsvc/handler_test.go
- cmd/chartsvc/main.go
- cmd/chartsvc/main_test.go
> chartsvc: Unit and integration tests

- manifests/mongodb.jsonnet
Kubeapps uses mongodb for cache storage, we do not really need to attach persistent storage for this cache as it can be easily be populated automatically or on demand. This commit swaps out the pvc volume with a emptyDir volume which should not only reduce the system requirements of running kubeapps but also help alleviate any mongodb file permission issues.
closes #336
> manifests: Use non-persistent emptyDir volume for MongoDB

- dashboard/src/components/ProvisionButton/index.tsx
- dashboard/src/components/SchemaForm/CustomObjectField.tsx
- dashboard/src/components/SchemaForm/FieldTemplate.tsx
A two step form allows us to cleanly separate input that Kubeapps needs
from the generalised input from the Service Broker's schema. The first
form simply asks for the name of the Service Instance, and the second
form renders the parameters using the broker-provided instanceCreateParameterSchema.
fixes #362
> use two-step form for provisioning service instances

- manifests/mongodb.jsonnet
bitnami/mongodb:3.6.5-r31 enables ipv6 support by default. fixes #340
> manifests: upgrade to bitnami/mongodb:3.6.5-r31

- manifests/apprepository.jsonnet
The button `Refresh` of the app repositories view didn't work because of this error:
```
'events "artifactory.153c4d4c29911fd9" is forbidden: User "system:serviceaccount:kubeapps:apprepository-controller" cannot patch events in the namespace "kubeapps": Unknown user "system:serviceaccount:kubeapps:apprepository-controller"'
```
Adding the required permission.
> Fix app repository role

- .travis.yml
- Makefile
- cmd/tiller-proxy/Dockerfile
- cmd/tiller-proxy/Dockerfile.dev
- cmd/tiller-proxy/handler.go
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Improve response in case the request is forbidden returning a JSON with all the items that the user is not allowed to perform (instead of a string with the first item found).
This PR also improves the unit tests for the auth package.
> [tiller-proxy] Improve forbidden response

- cmd/kubeapps/up.go
- cmd/tiller-proxy/handler.go
- cmd/tiller-proxy/main.go
- manifests/tiller-proxy.jsonnet
Ref #354 
Secure Tiller adding a TLS certificate when installed with TLS flags:
```
./kubeapps up \
--tiller-tls \
--tiller-tls-cert /path/to/cert.pem \
--tiller-tls-key /path/to/key.pem \
--tls-ca-cert /path/to/ca.pem
```
This prevents unauthorized connections to the Tiller pod using the `helm` CLI:
```
▶ helm list --tiller-namespace kubeapps
Error: transport is closing
▶ helm list --tiller-namespace kubeapps \
--tls \
--tls-ca-cert /path/to/ca.pem \
--tls-cert /path/to/cert.pem \
--tls-key /path/to/key.pem  
NAME    REVISION        UPDATED                         STATUS          CHART           NAMESPACE
wp      2               Tue Jul  3 15:34:02 2018        DEPLOYED        wordpress-2.0.1 default
```
> Add support for TLS connection with tiller

- manifests/nginx-vhost.conf
Description: The catch-all `server_name` directive remove's the warning message listed in #361
fixes #361
> manifests: specify catch-all server_name for kubeapps vhost, closes #361

- cmd/kubeapps/migrate.go
- manifests/tiller-deployment.jsonnet
Fixes #350 
**Breaking change**
Store releases as secrets specifying the flag `--storage=secret` in the Tiller deployment. Added the command `migrate-configmaps-to-secrets` to simplify the upgrade process. To upgrade to the new version of Kubeapps users should execute (from v1.0.0-alpha.4):
```
kubeapps up
kubeapps migrate-configmaps-to-secrets
kubectl delete configmaps -n kubeapps -l OWNER=TILLER
kubectl get helmreleases -o=name | xargs kubectl patch $1 --type merge -p '{ "metadata": { "finalizers": [] } }'
```
> Store releases in Tiller as secrets

- README.md
- cmd/kubeapps/up.go
- docs/user/getting-started.md
We had some left overs about sealed secrets in the documentation. Removing those.
> Removed Sealed Secrets references from documentation

- dashboard/src/actions/catalog.ts
- dashboard/src/components/InstanceView/AddBindingButton.tsx
- dashboard/src/components/InstanceView/InstanceView.tsx
- dashboard/src/containers/InstanceView.tsx
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/ServiceCatalog.ts
> two-step binding form for providing binding parameters

- docs/user/access-control.md
- manifests/user-roles.jsonnet
Ref #393
The generic `view` role doesn't have access to read secrets which is useful when viewing apps in kubeapps. Add a specific role to access all the possible resources in a namespace.
> Add a role to grant read access

- docs/user/getting-started.md
Hi,
In the getting started page, the link to access control page was broken. I've fixed that.
> Fixed broken link to access control page

- chart/kubeapps/templates/dashboard-deployment.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
- manifests/kubeapps-dashboard.jsonnet
- manifests/nginx.jsonnet
> Use new vhost path

- dashboard/src/actions/apps.ts
- dashboard/src/actions/config.ts
- dashboard/src/actions/index.ts
- dashboard/src/actions/repos.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/index.tsx
- dashboard/src/components/DeploymentForm/DeploymentErrors.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/LoadingWrapper/LoadingWrapper.tsx
- dashboard/src/components/LoadingWrapper/index.ts
- dashboard/src/components/UpgradeForm/SelectRepoForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/containers/ConfigLoaderContainer/ConfigLoaderContainer.ts
- dashboard/src/containers/ConfigLoaderContainer/index.ts
- dashboard/src/containers/RepoListContainer.ts
- dashboard/src/containers/Root.tsx
- dashboard/src/reducers/config.ts
- dashboard/src/reducers/index.ts
- dashboard/src/shared/App.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/Config.ts
- dashboard/src/shared/types.ts
also moves config into the redux store
fixes #415
> fix hardcoded references to kubeapps namespace in dashboard

- cmd/kubeapps/migrate.go
Use "kube-system" as default namespace for migrating releases (since it's the default namespace for Tiller).
Ref https://github.com/kubeapps/kubeapps/pull/430/files#r207637932
> Use kube-system for migrating releases

- dashboard/package.json
- dashboard/src/shared/Config.test.ts
- dashboard/src/shared/Config.ts
- dashboard/yarn.lock
The latest release added support for deploying kubeapps in a custom namespace, this means that supports needs to be added to the local development as well. 
This patch takes a telepresence generated env variable representing the namespace the app is running locally and configures the app accordingly.
> Custom namespace support for local development

- cmd/tiller-proxy/README.md
- cmd/tiller-proxy/handler.go
- cmd/tiller-proxy/main.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Fixes #435 
- Re-implement listReleases(namespace) to not to rely on listing all elements in the namespace.
- Re-implement get method to not to rely on the global list.
- Add a flag to configure the max number of releases for the proxy to retrieve.
PD: It's not possible to create a unit test for the patch since the fake helm implementation ignores that limit.
> [tiller-proxy] Improve release list behavior

- chart/kubeapps/values.yaml
Fixes #465: Install `bitnami` repo by default
> Allow to upgrade Kubeapps through the Dashboard

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/NOTES.txt
This applies the change in the Notes.txt added upstream https://github.com/bitnami/charts/pull/752/files
Eventually, once we enable the automation of chart releases https://github.com/kubeapps/kubeapps/issues/414 we will make a one way update from this repo to upstream instead. But in the meantime, this workaround is in my opinion fine.
Fixes https://github.com/kubeapps/kubeapps/issues/482
> Update chart from upstream

- cmd/tiller-proxy/handler.go
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/DeploymentForm/DeploymentErrors.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.tsx
- dashboard/src/components/Footer/Footer.tsx
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/types.ts
- pkg/proxy/proxy.go
Fixes #318
- In the Dashboard we now validate that the name given by the user passes the regex expected. If that is not the case, it shows a red border and hides the "Submit" button. TODO: Show a warning message explaining why the name is not valid:
In case the basic validation doesn't catch the error:
- The Tiller proxy returns now a 422 error (Unprocessable entity) if it fails to deploy a release.
- The dashboard shows the raw error that Tiller returns for the user to debug:
Apart from that the `AppRepositoryButton` now catches as well name conflicts and unprocessable entities as well.
> Report unprocessable entity

- pkg/yaml/yaml.go
- pkg/yaml/yaml_test.go
This patch fixes the case in which the k8s manifest contains a valid yaml but useless from the POV of the YamlToJson parsing. This is the case for a manifest that only includes comments.
Fixes https://github.com/kubeapps/kubeapps/issues/487
> Ignore empty kubernetes resources

- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.css
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.tsx
Before this change a very long word in the `Terminal` error caused a very long line in the error message. Now it is truncated to respect the max width:
cc/ @Angelmmiguel
> Wrap console text

- dashboard/package.json
- dashboard/tsconfig.json
- dashboard/tsconfig.prod.json
- dashboard/yarn.lock
In this commit https://github.com/kubeapps/kubeapps/commit/03a7e33457e7356f51075d06c994503e816182d4 we removed setupTests from the excluded list of files.
Down the line this has the consequence that `yarn build` bundles the file and potentially tries to resolve a module that does not exist since it is in the package.json dev dependencies. Problem that we are running in this patch https://github.com/kubeapps/kubeapps/pull/514/files
In order to fix it, we need to create another tsconfig file for production mode, feature that is supported in react-scripts-ts 2.16+ and hence the update performed.
In the new tsconfig.prod.json file what we do is to extend the exclude array to ignore setupTests. Please note that we needed to duplicate the whole array because of a limitation in the extend …
> Upgrade react-ts-scripts and added production tsconfig file

- docs/developer/tiller-proxy.md
Minikube 0.26+ fails to start if the flag `--Authorization.Mode` is passed with the error
```
error: unknown flag: --Authorization.Mode
```
This updates the docs to use the configuration that Kubeadm understands.
https://github.com/kubernetes/minikube/issues/2712#issuecomment-381044516
> Update documentation about enabling RBAC in minikube

- chart/kubeapps/templates/apprepository-jobs-cleanup-rbac.yaml
the hook type had a typo as pre-delete but I believe this should be post-delete like the other resources
> chart: fix hook type in cleanup job

- dashboard/src/components/ChartList/ChartList.tsx
Previously, we would display the No Charts Found error alert if the
filtered chart array came back empty. However, this error only makes
sense to show when the charts from the server come back empty. This
patch fixes this to only show the error if there are no charts from
the server.
We may want to improve the way we show this message (for example, under
the Charts header), and we may also want to show a different alert if
the filter shows up empty in the future.
fixes #531
> ignore no charts error when filtering

- .circleci/config.yml
Also sets integration tests to only run on tagged and master builds.
CircleCI 2.0 doesn't run tagged builds by default, see https://circleci.com/docs/2.0/workflows/#executing-workflows-for-a-git-tag
cc @andresmgot
> Adds filters to CircleCI config to enable tagged builds

- chart/kubeapps/Chart.yaml
The appVersion doesn't matter much, but the chart version needs to be bumped for the release.
> bump chart version for v1.0.0-alpha.6 release

- dashboard/src/backport.d.ts
This PR fixes the Typescript compilation error raised during `yarn run start`
```
Failed to compile.
/home/migmartri/go/src/github.com/kubeapps/kubeapps/dashboard/node_modules/mock-socket/index.d.ts
(21,13): Cannot find name 'EventHandlerNonNull'.
```
After some digging, it seems that the issue is that those definitions use Typescript 3.x features while our package.json loads the 2.x branch.
We did not notice of this issue because the production env uses a tsconfig that does not load the file that imported the 3.x definitions and also VSCode is using 3.x which compiles just fine.
We have backported some of the types required by `/mock-socket/index.d.ts` but should be removed once Typescript is upgraded https://github.com/kubeapps/kubeapps/issues/534
> backport some Typescript 3.x types to fix compilation error

- .circleci/config.yml
Follow up #536
- CircleCI build filters are a bit verbose so I moved them to definitions
- Since we are using filters now some conditions doesn't make sense anymore
- Modify the `release` job to be run only on tags
> Simplify circleCI yaml

- dashboard/tslint.ci.json
The ordering rules are not very consistent and difficult to follow.
It's not possible to automate the ordering and doesn't provide a lot of value.
> Disable ordering rules for linter

- .circleci/config.yml
- script/chart_sync.sh
- script/release_utils.sh
Fixes #414
Automatically release a chart in the repository `bitnami/charts` for Kubeapps. The process for updating a version is:
1. Add a new tag for the repo (as always). This will generate all the images required for the new version.
2. Increase the version number of the chart at `chart/kubeapps/Chart.yaml`. Once that change is in `master` CircleCI will update the status of the `bitnami/charts` repo with the files in this repository.
**IMPORTANT**: The script in 2. will automatically change the references to `tag: latest` in the file `chart/kubeapps/values.yaml` with the latest tag available (normally the tag released in 1.). 
Update example: https://github.com/andresmgot/charts-1/commit/d3c69181bf0e40428b0c83e86d66207d867a98ae
> Automatically sync chart

- script/release_utils.sh
Discovered at https://github.com/kubeapps/kubeapps/pull/552#discussion_r213500706
The current approach is being executed when the tag is already committed so it's retrieving the latest tag instead of the previous one. If `git describe --tags` is used with the previous commit it shows a dirty tag (something like `v1.0.0-alpha.5-fdskl`). To avoid that we can use just the `git tag` command and use the second-to-last.
> Fix previous tag retrieval

- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- pkg/proxy/fake/proxy.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Ref: #481
Mimic the list behavior of the Helm CLI. If no `status` is specified it will return only `DEPLOYED` and `FAILED` apps. It's possible to specify a custom query like `http://tiller-proxy.kubeapps:8080/v1/releases?statuses=deleted`.
> Add status query for listing releases

- dashboard/tslint.json
We disabled this in #544 but I think we forgot to disable it in the dev
tslint config.
cc @andresmgot
> disable object-literal-sort-keys in dev tslint config

- dashboard/public/index.html
- dashboard/src/components/Card/Card.css
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/index.css
fixes #342 
Note that the link colour has changed in Hex to a different blue, and some links are now underlined. This is part of the default Hex theme and matches https://design.bitnami.com/. For example:
I noticed some issues when trying to override this behaviour in the Cards and buttons and have filed issues in Hex: https://github.com/bitnami/hex/issues/216 and https://github.com/bitnami/hex/issues/217.
> updates Hex to v3.2.0

- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppView/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/ConfirmDialog/index.tsx
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/index.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- pkg/proxy/fake/proxy.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Closes: #481
Requires: #563
- Adds a query parameter "purge" for the `DELETE` API call in tiller-proxy.
- Show a checkbox  when deleting an app in the UI to purge or not the application.
> Allow to not purge applications when deleting them

- script/start-gke-env.sh
Fixes #571
The notation `((cnt=cnt-1)) || (echo "Waited 20 seconds but cluster is not reachable" && exit 1)` was not working so I changed that with a boring `if` clause. I have also redirected the output of `kubectl get pods` to `/dev/null` so in case the condition somehow fails CircleCI will purge the job after 10 minutes without output.
I tried the changes in the CircleCI env:
```
circleci@9ed20a708281:~/project$ ./s.sh
Waiting for the cluster to respond...
Waited 20 seconds but cluster is not reachable
circleci@9ed20a708281:~/project$ echo $?
1
```
> [CI] Avoid getting stuck while checking if the cluster is available

- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/components/AppView/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/ConfirmDialog/index.tsx
- dashboard/src/components/PageHeader/PageHeader.tsx
- dashboard/src/containers/AppListContainer/AppListContainer.tsx
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/index.tsx
- dashboard/src/reducers/apps.test.ts
- dashboard/src/reducers/apps.ts
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- dashboard/src/shared/types.ts
- pkg/proxy/fake/proxy.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Issue ref: #481
Continuation of #557 
Now that tiller-proxy support status filtering, add the possibility to show all the apps regardless of the status from the UI:
> Show list-all checkbox in Apps view

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/kubeapps-frontend-service.yaml
- chart/kubeapps/values.yaml
It sdds support for metadata annotations to the frontend service.
This is useful if the user opts for exposing kubeapps via a LoadBalancer but want to tweak it by making it for example internal `'service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0'`
I have not modified the Readme because in my opinion, this is a power user feature, disabled by default, and not commonly required.
> [Chart] frontend service annotation

- .circleci/config.yml
- Makefile
- script/e2e-test.sh
- script/libtest.sh
Fixes #537
For the end-to-end tests:
- Build and push images using as tag `build-<git commit sha1>`
- Test the helm chart and set the tag to the images just built
- Ensure that we are using the correct tag
- If the e2e tests success push the images with another tag (`latest` or `v.*` for tagged builds)
Test: https://circleci.com/workflow-run/c369a345-eefb-46d5-a5ee-bc2e42c3fa45
> [CI] Push and use temporary images

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/actions/catalog.ts
- dashboard/src/actions/functions.ts
- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/ChartView/ChartDeployButton.tsx
- dashboard/src/components/ClassList/index.tsx
- dashboard/src/components/ClassView/index.tsx
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.tsx
- dashboard/src/components/DeploymentForm/DeploymentErrors.tsx
- dashboard/src/components/ErrorAlert/NotFoundErrorAlert.tsx
- dashboard/src/components/ErrorAlert/PermissionsListItem.tsx
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.test.tsx
- dashboard/src/components/ErrorAlert/UnexpectedErrorAlert.tsx
- dashboard/src/components/ErrorAlert/__snapshots__/UnexpectedErrorAlert.test.tsx.snap
- dashboard/src/components/ErrorAlert/helpers.tsx
- dashboard/src/components/Header/NamespaceSelector.tsx
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/url.ts
**DEPRECATED**, see updated section below
It sets the deploy chart link to include the default namespace in the route instead of the _all placeholder. It also contains some refactoring to start storing some hardcoded defined namespaces into a shared module.
The meat itself is in here https://github.com/kubeapps/kubeapps/pull/595/files#diff-4
NOTE: I decided to set modify the link instead of redirect within the NewApp container to not to add extra code to handle this behavior. At the end of the day it seems that today we only access to deploy app from that button, if that changes we can revisit it.
Also, I did not add a regexp in the route `/apps/new` that excludes `/ns/_all` because it seems that so far we are being permissive in that route so I thought that it was not worth it.
Fixes …
> Chart deploy. Show an error message if namespace is not selected

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
Based on this discussion https://github.com/kubeapps/kubeapps/pull/587/files#r215954708
See below the comparative based on the template render before and after the change with ingress enabled:
```bash
helm template . --set ingress.enabled=true > /tmp/[before/after]_change.yaml
```
The change does not affect the default outputs, the mongoDB password is expected to be generated
```bash
diff /tmp/before_change.yaml /tmp/after_change.yaml 
14c14
<   mongodb-root-password: "TTI2Qlc0dXY2Sg=="
---
>   mongodb-root-password: "NVplRXVTVVRvcQ=="
```
> Make annotations defaults consistent

- dashboard/src/components/ErrorAlert/__snapshots__/UnexpectedErrorAlert.test.tsx.snap
A stale version of a snapshot was added to master because a piece of code that updated a view and created its snapshot https://github.com/kubeapps/kubeapps/commit/f575efd9d44cafc1b888585f136f1fb1d8e709ea#diff-44512796d7db632d9db40ee9176e9aa3 was merged without rebasing master. In master there was already another commit that modified the same view https://github.com/kubeapps/kubeapps/commit/624bf97792e00eda8f3d49a13f49d86be03c3f00
> Fix tests in master due to stale snapshot

- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/actions/repos.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/DeploymentForm/DeploymentErrors.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/DeploymentForm/__snapshots__/DeploymentForm.test.tsx.snap
- dashboard/src/components/UpgradeForm/SelectRepoForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/shared/types.ts
Fixes: #511
Show a "Not found" error when the chart or the chart repository doesn't exist. It covers the chart view (e.g. `/charts/foo/bar`) and the deployment form (e.g. `apps/ns/default/new/foo/aerospike/versions/0.1.7`) components.
Caveat: This fixes #511 but I think we should refactor the way we handle errors in the views. I think that we can probably move the error checking to an upper lever to avoid having to reimplement the error handling in all the possible views.
> Check missing chart repository

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
Fixes #593
- Always show filter options even if the current list is empty
- Always show the `Deploy` button in the top-right corner.
- Remove `Deploy` button from welcome message to avoid duplicity
> Always show filter options

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/NOTES.txt
Fixes https://kubernetes.slack.com/archives/C9D3TSUG4/p1536328485000100
`kubectl port-forward` to a service is only available with `kubectl` +1.11. Use the previous approach to ensure that users won't see an error when trying those commands.
> [chart] Edit NOTES to use more compatible command

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/tiller-proxy-secret.yaml
As mentioned in the attached issue, the CA certificate is only useful if tls-verify is set. Before this patch, regardless of the value of tls-verify we were requiring it to be set.
This patch also validates that the CA is present if tls-verify is set.
Fixes https://github.com/kubeapps/kubeapps/issues/547
Examples:
The secret does not contain the data.ca key and it is not enforced.
```bash
helm template --set tillerProxy.tls.verify=false --set tillerProxy.tls.key="my-key"  --set tillerProxy.tls.cert="my-cert" . | grep kubeapps/templates/tiller-proxy-secret.yaml -A 20
kind: Secret
metadata:
name: RELEASE-NAME-kubeapps-tiller-proxy
labels:
app: RELEASE-NAME-kubeapps-tiller-proxy
chart: kubeapps-0.4.1
release: RELEASE-NAME
heritage: Tiller
data:
tls.crt: |-
bXktY2VydA==
tls.key: |-
bXkta2V5 …
```
> Tiller TLS CA validation

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/values.yaml
In order to avoid confusion around the `kubeapps-dashboard` and
`kubeapps` Service, we should rename the `kubeapps-dashboard` Service
to sound like more of an internal component rather than a possible
entrypoint to the dashboard.
fixes #602
> rename kubeapps-dashboard svc to sound more internal

- chart/kubeapps/values.yaml
fixes the current failing master build: https://circleci.com/gh/kubeapps/kubeapps/1641.
I haven't bumped the chart since the current chart version has not been pushed to bitnami/charts yet due to the failed build.
> fix chart missing value

- script/e2e-test.sh
in #603 we added a new prefix to deployment names for internal services,
but the e2e script was not updated to reflect the new names.
> e2e tests: update deployment names with internal prefix

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/tiller-proxy-secret.yaml
The code added here to validate that a CA was provided if tls.verify was true was buggy in the case in which tls.verify was not set (which is the default)
This means that if you try to install a chart setting the tiller proxy tls and did not set tls.verify to false you were forced to pass a CA. This bug did not have a big impact because it was only visible if tillerProxy.tls was set and in previous versions the CA was required anyways.
The bug was related to the way I was using the requires + the conditional. So I went back to a simpler to understand and maintain version of the code.
> Fix chart tiller proxy

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/tiller-proxy-secret.yaml
Without this fix, the apiVersion was being swamped as part of the comment
```
```
This was not detected by my local template tests, but would have been detected by e2e tests using tilelr-proxy tls, so I am going to bump priority on that one.
> Fix API version being merged into the comment

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/shared/Auth.ts
Looking into https://github.com/kubeapps/kubeapps/issues/546 I noticed that the main issue is that the releases page was not handling correctly errors from the API, regardless of being 503, 500. This is because our loading banner was being rendered as long as appOverview was empty.
This does some refactoring and tweaks in that page that:
* We show the "Applications" header so the viewport vertical space does not jump, this way the user always has the context.
* The deploy button nor the filtering options are shown.
* We show a message and like in the loading state we do not show the controls.
I have tested it by making the tiller-proxy crash and even disabling it all together.
* The view is shown as before, nothing has changed here.
* Note that I have added a 5 seconds to Axios to give …
> API error handling in releases list

- dashboard/src/components/ChartList/ChartList.tsx
- dashboard/src/components/ChartList/__snapshots__/ChartList.test.tsx.snap
I added this spurious semicolon by mistake during the latest application of the feedback received here https://github.com/kubeapps/kubeapps/pull/644/files#diff-10
Sorry about that. Thanks @prydonius for catching it up.
> Remove spurious semicolon from charts list

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/chartsvc-deployment.yaml
- chart/kubeapps/templates/dashboard-deployment.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- chart/kubeapps/values.yaml
Closes https://github.com/kubeapps/kubeapps/issues/643
Diff of rendered template before/after the change.
```bash
multidoc_yamldiff /tmp/before.yaml /tmp/after.yaml 
@@ .. @@
name: "RELEASE-NAME-kubeapps",
},
spec: {
-   replicas: 1,
+   replicas: 2,
selector: {
matchLabels: {
app: "RELEASE-NAME-kubeapps",
@@ .. @@
name: "RELEASE-NAME-kubeapps-internal-apprepository-controller",
},
spec: {
-   replicas: 1,
+   replicas: 2,
selector: {
matchLabels: {
app: "RELEASE-NAME-kubeapps-internal-apprepository-controller",
@@ .. @@
name: "RELEASE-NAME-kubeapps-internal-chartsvc",
},
spec: {
-   replicas: 1,
+   replicas: 2,
selector: {
matchLabels: {
app: "RELEASE-NAME-kubeapps-internal-chartsvc",
@@ .. @@
name: "RELEASE-NAME-kubeapps-internal-dashboard",
},
spec: {
-   replicas: 1,
+   replicas: 2, …
```
> Increase number of replicas and allow its configuration

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
No changes as expected since the port for chartsvc and tiller proxy are the same.
Bumping two versions so this PR will wait until this other one is landed https://github.com/kubeapps/kubeapps/pull/660
```
diff /tmp/before.yaml /tmp/after.yaml 
14c14
<   mongodb-root-password: "enVCdFRiZDZYRw=="
---
>   mongodb-root-password: "TzVseUNqZjFqWg=="
```
> Fix port reference in tiller-proxy deployment manifest

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
See https://github.com/kubeapps/kubeapps/issues/478#issuecomment-422979262 for some context.
Closes https://github.com/kubeapps/kubeapps/issues/478
After applying this patch pods moved to `burstable` as expected
```
k get pods -n kubeapps -l release=kubeapps -o jsonpath="{range .items[*]} ====> {.metadata.name} {'\n\n'}{'\t'}{.status.qosClass} | Requests: {.spec.containers[0].resources.requests} | Limits: {.spec.containers[0].resources.limits}{'\n\n'}{end}"
====> kubeapps-6b4dd6fdcd-9vb65 
Burstable | Requests: map[cpu:100m memory:32Mi] | Limits: map[cpu:500m memory:128Mi]
====> kubeapps-6b4dd6fdcd-rvmk4 
Burstable | Requests: map[memory:32Mi cpu:100m] | Limits: map[cpu:500m memory:128Mi]
====> kubeapps-internal-apprepository-controller-745879f84c-8trj5 
Burstable | Requests: map[cpu:100m …
```
> Apply limits and requests

- README.md
- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/NOTES.txt
- docs/user/getting-started.md
The `-o name` output lists both pods now that we have 2 replicas, which
the `port-forward` command does not like. This commit changes the NOTES
to use a jsonpath template to get the first pod's name only.
> chart: update NOTES.txt so select first pod to port-forward

- dashboard/src/components/AppView/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls.tsx
- dashboard/src/components/ConfirmDialog/index.tsx
Fixes #655
Don't show the `purge` check box when the application has been already deleted. Force to purge it if the user deletes it again.
> Refactor purge UX for deleted apps

- chart/kubeapps/README.md
I realized that the logo is not properly rendered in the chart view of kubeapps:
The logo is already there at the top and I haven't seen any other chart that includes the logo in the title so I think it's better to remove it.
> Remove logo from chart title

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/NOTES.txt
Testing a K8s cluster where LoadBalancer service returns `hostname` and not `ip`.
This PR change our current approach in bitnami helm charts where we report IP by doing 
```
-o jsonpath='{.status.loadBalancer.ingress[0].ip}'
``` 
The new approach is to use
```
--template "{{"{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}"}}"
```
where the `.` returns value for whatever field is in the map.
_Source: https://github.com/helm/charts/issues/84#issuecomment-257754892_
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>
> Improve getting LoadBalancer address in chart NOTES.txt

- dashboard/package.json
- dashboard/src/reducers/namespace.ts
- dashboard/yarn.lock
The issue with tslint is that it actually does not check that the compilation works, from [their documentation](https://palantir.github.io/tslint/usage/cli)
> Please ensure that the TypeScript source files compile correctly before running the linter.
So I've added a compilation step during the pre-hook. Please note that it was added in the husky hooks not in the `lint-staged`. This is because the compilation does not depend on the changed files (but on the tsconfig.json) so it can not be used there. More info [here](https://github.com/okonet/lint-staged/issues/468)
Closes https://github.com/kubeapps/kubeapps/issues/694 
Closes https://github.com/kubeapps/kubeapps/issues/158
> Add typescript compilation check and hooks update

- README.md
Followed a similar approach as seen in other projects like Minikube.
NOTE: I decided not to add this badge but let me know if you think otherwise
[![Slack](https://img.shields.io/badge/-%23kubeapps-00437B.svg?longCache=true&style=flat-square&logo=slack)](https://kubernetes.slack.com/messages/C9D3TSUG4)
Closes https://github.com/kubeapps/kubeapps/issues/610
> Add Slack link to Readme

- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Fixes #704
When getting a release, tell tiller to:
- Order them by date
- In descendent order
- Return only one
That's the release we return to the user. This way we avoid returning an old release.
Since this is just adding new options to the Helm request we cannot unit-test it. This is because the fake helm client doesn't have into account the given options. I checked that the issue is resolved manually in a cluster with the situation described in #704.
> Fix get to retrieve the latest release

- dashboard/src/components/ChartView/ChartReadme.test.tsx
- dashboard/src/components/ChartView/ChartReadme.tsx
- dashboard/src/components/ChartView/HeadingRenderer.tsx
Fixes #702
Add the "id" property to the headings when parsing markdown. The approach to do that is specified here:
https://github.com/rexxars/react-markdown/issues/69
The logic to transform the heading text into a link is the same than GitHub: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/toc_filter.rb#L42
> Add "id" to headings

- script/e2e-test.sh
We use the upstream built image for chartsvc and no longer build it in
the CI, so we shouldn't check for the image tag
> e2e test: remove check for chartsvc image

- dashboard/src/containers/RoutesContainer/Routes.tsx
Use the Container prefix in all imports in Routes for consistency
closes #682
> add container suffixes to all imports in Routes

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
- chart/kubeapps/templates/ingress.yaml
- chart/kubeapps/templates/tls-secrets.yaml
- chart/kubeapps/values.yaml
This PR allows the user to configure the proper annotations when using cert-manager to handle TLS certificates in an easy way. The user just needs to setup a boolean to true to do so.
E.g.:
```
helm install --name kubeapps --namespace kubeapps bitnami/kubeapps \
--set ingress.enabled=true \
--set ingress.hosts[0].name=kubeapps.custom.domain \
--set ingress.hosts[0].tls=true \
--set ingress.hosts[0].tlsSecret=kubeapps-tls \
--set ingress.hosts[0].certManager=true
```
This will generate the following ingress:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: kubeapps
namespace: kubeapps
labels:
app: kubeapps
chart: kubeapps-0.8.0
release: kubeapps
heritage: Tiller
annotations:
kubernetes.io/tls-acme: "true"
spec:
rules:
- host: kubeapps.custom.domain
http:
paths:
- path: / …
```
> [Kubeapps Chart] Simplify ingress configuration for cert-manager

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
Fixes our chart to be able to pull images from quay
NOTE: It seems that this is not an issue in regular K8s but it is in Openshift. I reproduced the fix there.
```
diff /tmp/before.txt /tmp/after.txt 
<         - --repo-sync-image=docker.io/quay.io/helmpack/chart-repo:v1.0.0
---
>         - --repo-sync-image=quay.io/helmpack/chart-repo:v1.0.0
950c950
<         image: docker.io/quay.io/helmpack/chartsvc:v1.0.0
---
>         image: quay.io/helmpack/chartsvc:v1.0.0
```
Closes https://github.com/kubeapps/kubeapps/issues/750
> Fix quay.io images FQDN

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/NOTES.txt
Notes shown after installing the chart are not fine when enabling Ingress as a consequence of https://github.com/kubeapps/kubeapps/pull/740
```
To access Kubeapps from outside your K8s cluster, follow the steps below:
1. Get the Kubeapps URL and associate Kubeapps hostname to your cluster external IP:
export CLUSTER_IP=$(minikube ip) # On Minikube. Use: `kubectl cluster-info` on others K8s clusters
echo "Kubeapps URL: http://map[tlsSecret:kubeapps-tls certManager:true name:kubeapps.two-k8s-1-10-8.aks.fuloi.com tls:true]"
echo "$CLUSTER_IP  map[certManager:true name:kubeapps.two-k8s-1-10-8.aks.fuloi.com tls:true tlsSecret:kubeapps-tls]" | sudo tee -a /etc/hosts
```
This PR adapts **NOTES.txt** to the new way of configuring ingress
> Adapt Notes.txt to new Ingress configuration

- pkg/proxy/proxy.go
Changes the way we retrieve a single release name. Instead of listing all the releases and retrieving the last one, we use what Helm itself uses instead.
I have also imported a helper to extract error messages from GRPC so we can imitate what helm does without the need of having extra error handling.
```json
// curl tiller-proxy...
{
"code": 404,
"message": "release: \"wordpress-miguel23\" not found"
}
```
Also note that this method does not require passing a namespace so changes will be made in further PRs
Refs #765
> Fix get release

- chart/kubeapps/values.yaml
Fixes an issue with syncing updated chart tarballs (#659) and the
timeout for connecting to MongoDB.
See https://github.com/helm/monocular/releases/tag/v1.0.1.
fixes #659
> bumps chart-repo and chartsvc to v1.0.1

- chart/kubeapps/templates/apprepository-rbac.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/main.go
The NewFilteredSharedInformerFactory was not available in previous versions
of client-go we were using. Now that we've upgraded, we can correctly
filter down to the namespace this controller is interested in
(the one Kubeapps is installed in).
chart: remove clusterrole for apprepository-controller
Now that we are able to watch on the specific namespace Kubeapps was
installed in, we no longer need the clusterrole to watch cluster-wide
CronJobs.
fixes #504
> namespace apprepo-controller kube informer

- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
This patch decouples the releaseName used in the controlled field in the form from the releaseName shown in the error message.
Fixes https://github.com/kubeapps/kubeapps/issues/757
> Show correct release name in case of error

- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
- enables JSON.parse behaviour for YAML parsing (allows manifests with
duplicate keys)
- switches to yaml.loadAll as safeLoadAll does not seem to support the
JSON.parse behaviour (https://github.com/kubeapps/kubeapps/issues/636#issuecomment-437197500). Ideally we can switch this back once this is
fixed upstream.
fixes #636
> relax YAML parsing for Helm release manifests

- cmd/tiller-proxy/internal/handler/handler_test.go
- dashboard/src/components/AppList/AppListItem.test.tsx
- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/ServiceInstanceList/ServiceInstanceCard.test.tsx
- dashboard/src/components/ServiceInstanceList/ServiceInstanceCard.tsx
- dashboard/src/components/ServiceInstanceList/ServiceInstanceCardList.tsx
- dashboard/src/components/ServiceInstanceList/__snapshots__/ServiceInstanceCard.test.tsx.snap
- dashboard/src/shared/types.ts
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Fixes #764 
Add the chart name to the app list and the service name in the service instance list:
Note that changes in tiller-proxy were required in order to return the chart name in the list overview.
> Add component information in app and service lists

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-rbac.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/main.go
This reverts commit 9c6ac74e20b96f41461d476cf41d3d3e06db195e, since it
contains a change in the chart that was not yet ready to release and is
currently causing the apprepository-controller fail due to insufficient
permissions.
> Revert "namespace apprepo-controller kube informer (#787)"

- .circleci/config.yml
- Makefile
- cmd/tiller-proxy/Dockerfile
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/main.go
- cmd/tiller-proxy/version.go
- cmd/tiller-proxy/version_test.go
- docs/developer/apprepository-controller.md
- docs/developer/build.md
- docs/developer/tiller-proxy.md
User Agent support in Tiller-proxy, 
* Support to bake the tiller-proxy version during release
* Support to receive user-agent comment that will injected via the chart
* Updated circle-ci config to bake the version
See below some example of the user-agent seen at the repository end
Tiller-proxy built in the CI during 1.2 release and ran inside the version 1.1.1 of the Kubeapps chart
```
> 100.100.0.23 - - [13/Nov/2018:21:53:30 +0000] "GET /index.yaml HTTP/1.1" 200 1555 "-" "tiller-proxy/1.2 (Kubeapps/v1.1.1)
```
Tiller built locally and run outside of the scope of Kubeapps
```
> 100.117.0.48 - - [13/Nov/2018:21:56:42 +0000] "GET /index.yaml HTTP/1.1" 200 1555 "-" "tiller-proxy/8a1ed0f59f59d4599307c96c23bd1da4d833946c
```
Refs #767
> Tiller proxy user agent support

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-crd.yaml
This patch basically moves the creation of the CRD to the hook lifecycle so Helm will not try to upgrade it causing the issue described here https://github.com/kubeapps/kubeapps/issues/812
I manually tested it
```bash
$ k get crd
No resources found.
$ helm install -n kubeapps-1 --namespace namespace-1 chart/kubeapps/
$ k get crd apprepositories.kubeapps.com -o jsonpath={.metadata.labels.release}
kubeapps-1
$ helm install -n kubeapps-2 --namespace namespace-2 chart/kubeapps/
$ helm list
NAME      	REVISION	UPDATED                 	STATUS  	CHART         	NAMESPACE  
kubeapps-1	1       	Tue Nov 13 15:56:02 2018	DEPLOYED	kubeapps-0.9.7	namespace-1
kubeapps-2	1       	Tue Nov 13 15:56:44 2018	DEPLOYED	kubeapps-0.9.7	namespace-2
$ k get crd apprepositories.kubeapps.com -o …
```
> Install app-repository CRD via a hook

- .circleci/config.yml
- script/e2e-test.sh
- script/libtest.sh
Revert changes in the CI helpers since it seems that GKE 1.9 constantly fails.
Before merging the change again we need to debug why it is happening (it does not show any error) and this other PR might be useful https://circleci.com/gh/kubeapps/kubeapps/4203
This reverts commit 2fdbc6ffe7856504b469e9568c8f316dd186a8eb.
Refs #831
> Revert "K8s helpers improvements (#833)"

- script/start-gke-env.sh
We use those cluster to only install Kubeapps, and the nodes selected are 7.5GB and 2 cores each so we should have enough with 2 nodes.
Closes https://github.com/kubeapps/kubeapps/issues/837
> Downsize the number of nodes in e2e tests

- .circleci/config.yml
- script/chart_sync.sh
- script/chart_sync_utils.sh
- script/e2e-test.sh
* Adds e2e tests support with current version images when releasing a new chart version. These parallel jobs only run if we are releasing a new chart version.
See https://circleci.com/workflow-run/0d20793b-c606-42ce-b44a-5cb5fcbc6da7 for an example. 
Closes https://github.com/kubeapps/kubeapps/issues/825
> Add e2e tests with stable images if a new chart is been released

- script/e2e-test.sh
- script/libtest.sh
Follow up #833 
Refactor e2e tests to wait for deployments instead of pods.
Improve completed job check.
Sample build: https://circleci.com/gh/kubeapps/kubeapps/4263 (at the end fails for debugging purposes)
> Refactor e2e tests

- .circleci/config.yml
- script/e2e-test.sh
- script/start-gke-env.sh
Fixes #822 
Fixes #834 
Changes:
- Add builds for GKE 1.11
- Pin `kubectl` version to `v1.12.0`
- Fixes issue for the 1.10 branch that was picking the wrong version (see https://github.com/kubeapps/kubeapps/issues/822#issuecomment-440330246)
~~- Enabled GKE builds for any build in the repository `kubeapps/kubeapps` so we can easily tests PRs like this one.~~
> Add builds for GKE 1.11

- .circleci/config.yml
Try if sourcing the script in the step is now required and fixes the issue shown here https://github.com/kubeapps/kubeapps/issues/870
This might not be the final fix but it might unblock our release process when we land code in master.
Closes https://github.com/kubeapps/kubeapps/issues/870
> source script in the specific step

- script/libtest.sh
Fix #869 
`k8s_wait_for_job_completed` was exiting prematurely. Check the comment below.
Tested on https://circleci.com/gh/kubeapps/kubeapps/4881
> Fix k8s_wait_for_job_completed

- dashboard/src/components/AppView/SecretsTable/SecretItem.test.tsx
- dashboard/src/components/AppView/SecretsTable/SecretItem.tsx
- dashboard/src/components/AppView/SecretsTable/__snapshots__/SecretItem.test.tsx.snap
I noticed that if a secret is empty (it doesn't contain `data`) the AppView crashes.
> Fix SecretTable for empty secrets

- dashboard/package.json
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/DeploymentForm/__snapshots__/DeploymentForm.test.tsx.snap
- dashboard/yarn.lock
Fixes: #485
Auto generate a random name for the release using moniker.
> Auto generate release name

- .circleci/config.yml
This removes the GKE 1.9 e2e tests from the CircleCI config to fix the
current failing tests. GKE stopped supporting k8s 1.9.
fixes #884
> drop e2e tests on k8s 1.9 on GKE

- dashboard/src/components/AppList/AppListItem.test.tsx
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/CatalogItem.scss
- dashboard/src/components/Catalog/CatalogItem.test.tsx
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
- dashboard/src/components/Catalog/__snapshots__/CatalogItem.test.tsx.snap
- dashboard/src/components/InfoCard/InfoCard.test.tsx
- dashboard/src/components/InfoCard/InfoCard.tsx
- dashboard/src/components/InfoCard/__snapshots__/InfoCard.test.tsx.snap
Fixes #793 
This PR adds the chart descriptions to the Catalog view. Since descriptions can be quite long, descriptions over 90 characters are trimmed. Users can still see the full description clicking on "Show more". This is the justification of why I chose to do it that way:
- The most common thing to trim text is using the CSS property `text-overflow: ellipsis`. Unfortunately that only works for text with just one line. One line in this case is not enough since it will never show a meaningful message.
- There are several options to trim texts of more than one line (three lines usually gives a good description) as explained in this [post](http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/). The most common way of doing that is with a CSS class that defines …
> Show chart descriptions

- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
Ref: 
https://github.com/kubeapps/kubeapps/pull/877#discussion_r241444613
Ensure that the release name changes between loads. cc/ @migmartri
> Refactor automatic release name test

- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-config.yaml
- dashboard/package.json
- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/kube.test.tsx
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/CatalogItem.test.tsx.snap
- dashboard/src/components/ChartIcon/ChartIcon.tsx
- dashboard/src/shared/App.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/Chart.ts
- dashboard/src/shared/ClusterServiceClass.ts
- dashboard/src/shared/Config.test.ts
- dashboard/src/shared/Config.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/ServiceCatalog.ts
- dashboard/src/shared/ServiceInstance.ts
- dashboard/src/shared/WebSocketHelper.ts
- dashboard/src/shared/url.ts
- dashboard/src/store/index.ts
- dashboard/yarn.lock
Add supports to deploy kubeapps under a custom prefix. 
To achieve it without requiring the user to do a custom build via webpack I needed to make the following modifications:
* In the package.json, set the `homepage` value relative so the bundled index.html contains a relative path to the assets.
```html
<script type="text/javascript" src="/static/js/main.c4bfc712.js">
<script type="text/javascript" src="./static/js/main.c4bfc712.js">
```
* Change React router history from push-state to hash-based. This simplified the setup since relative API calls defined in our code will ignore this hash state. This is not the case if we decided to modify the  push-state `basename` https://github.com/kubeapps/kubeapps/issues/402#issuecomment-448042009. Actually changing the basename would have been a …
> Add custom path support

- chart/kubeapps/values.yaml
Fix master e2e tests.
The template function is concatenating tags always with `:`. This produced a wrong image reference for the chart-repo temporary tag (`chart-repo:@sha256:...`). Applied a workaround to produce a valid image reference.
Note that this should be changed when a new chart-repo tag is released.
> Fix chart-repo image reference

- dashboard/src/components/AppView/OtherResourcesTable/OtherResourcesTable.tsx
- dashboard/src/components/AppView/OtherResourcesTable/__snapshots__/OtherResourcesTable.test.tsx.snap
Split from  #893
> I have also noticed that the table for other resources didn't have a header and that when the resource was not namespaces the field was blank. I've changed that as well to show more info:
> Improve Other Resources rendering

- chart/kubeapps/values.yaml
The current chart-repo image cannot be pulled since `latest` was rebuilt yesterday. Apparently it's not possible to use the `sha256` of an old image (that behavior is different from the Docker Hub). I am changing the tag to use `latest` until there is a new release.
Note that Quay.io is under an incident: http://status.quay.io/incidents/72jyq4322h85 so I am not sure if the issue (not able to pull an old sha256) is actually caused by that incident.
> Update chartsvc and chart-repo to v1.2.0

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/_helpers.tpl
Fixes https://github.com/bitnami/charts/issues/1007:
```
at <ne .path "/">: error calling ne: invalid type for comparison
```
This error appears because if a value is unset, it is returned as a nil value, so we need to replace
```diff
-{{- if ne .path "/" -}}
+{{- if (.path) and ne .path "/" -}}
```
> Fix comparison issue

- dashboard/src/components/Footer/Footer.test.tsx
- dashboard/src/components/Footer/Footer.tsx
- dashboard/src/components/Footer/__snapshots__/Footer.test.tsx.snap
Removes `v` prefix and adds link to the release page.
Fixes https://github.com/kubeapps/kubeapps/issues/905
> Remove version prefix

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/ingress.yaml
Based on this discussion https://github.com/kubeapps/kubeapps/pull/897#pullrequestreview-186802634 I've managed to extract the redirection logic to the Nginx configuration inside the dashboard container as well as made it generic. This is good since now, the redirect does not depend now on the specifics of the Ingress controller as well as the deployment mechanism (Helm chart).
In my previous tests the solution did not work because the redirection was including the internal port (8080)
NOTE: see location header in the following examples.
```bash
$ curl -I -H 'Cache-Control: no-cache' https://miguel-kubeapps-dev.k.dev.bitnami.net/kubeapps
HTTP/2 301 
server: nginx/1.15.6
date: Wed, 02 Jan 2019 21:16:01 GMT
content-type: text/html
content-length: 185
location: …
```
> Move ingress rewrite to dashboard Nginx

- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/AppView/DeploymentsTable/DeploymentItem.test.tsx
- dashboard/src/components/AppView/DeploymentsTable/DeploymentItem.tsx
- dashboard/src/components/AppView/DeploymentsTable/DeploymentsTable.test.tsx
- dashboard/src/components/AppView/DeploymentsTable/DeploymentsTable.tsx
- dashboard/src/components/AppView/DeploymentsTable/__snapshots__/DeploymentItem.test.tsx.snap
- dashboard/src/components/AppView/DeploymentsTable/__snapshots__/DeploymentsTable.test.tsx.snap
- dashboard/src/containers/DeploymentItemContainer/DeploymentItemContainer.test.tsx
- dashboard/src/containers/DeploymentItemContainer/DeploymentItemContainer.ts
- dashboard/src/containers/DeploymentItemContainer/index.ts
- dashboard/src/containers/DeploymentStatusContainer/DeploymentStatusContainer.test.tsx
- dashboard/src/containers/DeploymentStatusContainer/DeploymentStatusContainer.ts
- dashboard/src/containers/DeploymentStatusContainer/index.ts
- dashboard/src/shared/ResourceRef.ts
- wraps DeploymentItems in containers to load resources from Redux
- DeploymentItem initiates fetches for Deployments (loads faster than watching)
- Errors fetching Deployments are shown
refs #882
> Improves loading Deployment resources in AppView

- cmd/tiller-proxy/main.go
- cmd/tiller-proxy/version.go
- cmd/tiller-proxy/version_test.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/chart/fake/chart.go
Since v1.1.0 the `netClient` is created in the `chartUtils` pkg instead of the main one. This caused that the User-Agent that we were setting in the main package was not being used.
> Fix User-Agent header for Tiller-proxy

- dashboard/Dockerfile
It appears the older image contains some security vulnerabilities that have been fixed in more recent Debian versions. This PR bumps the nginx image used in the dashboard to upgrade the underlying Debian OS.
> Bump nginx image version for security vulns

- chart/kubeapps/values.yaml
- bumped chart-repo as it fixes a regression causing proxy env vars to not be used
- bumped chartsvc to keep version consistent ¯\_(ツ)_/¯ - I can undo this if we don't think it's necessary
see also #966
> bump chart-repo and chartsvc in chart

- .circleci/config.yml
Closes #972
GKE 1.10 has been deprecated. Release notes: https://cloud.google.com/kubernetes-engine/release-notes
> Disable builds for GKE 1.10

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
- script/chart_sync_utils.sh
It's now a requirement to use bitnami images wherever is possible for charts published at https://github.com/bitnami/charts.
Note that bitnami images are mirrored versions from the ones we are currently using but their tags doesn't contain the prefix `v`: `v1.3.0 -> 1.3.0`. They are hosted in the docker hub and have the prefix `kubeapps-<name of the image>`.
This is an example of changes performed from the dev version of the chart in this repository to the one that will be submitted to the bitnami repository:
```patch
--- a/chart/kubeapps/values.yaml
+++ b/chart/kubeapps/values.yaml
@@ -94,13 +94,13 @@ apprepository:
replicaCount: 1
image:
registry: docker.io
-    repository: kubeapps/apprepository-controller
-    tag: latest
+    repository: bitnami/kubeapps-apprepository-controller
+ …
```
> Use bitnami images before updating bitnami chart

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppList/AppListItem.test.tsx
- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
- dashboard/src/components/AppView/AppControls/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls/AppControls.tsx
- dashboard/src/components/AppView/ChartInfo.test.tsx
- dashboard/src/components/AppView/ChartInfo.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/reducers/apps.ts
- dashboard/src/shared/types.ts
Fixes #969 
The goal of this PR is to avoid the issue described in #969. Now, when clicking in the "Upgrade" button, we check if the application has `updateInfo`. In that case we skip the `SelectRepoForm` and we automatically choose the repo with the latest version.
> Refactor upgrade flow

- chart/kubeapps/README.md
- remove prereq for RBAC ClusterRoles as this is no longer necessary
- add prereq for creating CRDs
Technically the CRD prereq can be worked around by creating it out-of-band of the chart, but it then still requires that someone has that permission to be able to install it.
see #992
> docs: update prerequisites

- .circleci/config.yml
- script/start-gke-env.sh
Fixes #886 
Example build: https://circleci.com/workflow-run/d8a54f97-f424-4d56-88d1-a1e36607bedb
I have also added the label `team=kubeapps` for accounting purposes
> Add builds for GKE 1.12

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/PrivateRoute/PrivateRoute.test.tsx
- dashboard/src/components/PrivateRoute/PrivateRoute.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/PrivateRouteContainer/PrivateRouteContainer.ts
- dashboard/src/index.tsx
- dashboard/src/reducers/auth.test.ts
- dashboard/src/reducers/auth.ts
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/AxiosInstance.test.ts
- dashboard/src/shared/AxiosInstance.ts
- dashboard/src/shared/Chart.ts
- dashboard/src/shared/ClusterServiceClass.ts
- dashboard/src/shared/Kube.test.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/ServiceCatalog.ts
- dashboard/src/shared/ServiceInstance.ts
Fix #974 
With this PR we catch errors potentially thrown because the OIDC token is no longer valid. In that case we show a modal for the users  to notice that the application needs to reload. I used the Modal to avoid the user seing the application reloading without apparent reason.
Note that we are only checking request made by axios so to avoid issues I have replaced the current `fetch` calls with `axios.get` (so this PR also fixes #606).
> Reload OIDC token when needed

- .circleci/config.yml
- script/e2e-test.sh
This PR adds a new job that run our end-to-end tests (helm tests) that's run in a local Kubernetes cluster using [kind](https://github.com/kubernetes-sigs/kind). This enable us to use our end-to-end tests with untrusted code (PRs).
> Enable end-to-end tests for pull requests

- chart/kubeapps/templates/dashboard-deployment.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/values.yaml
- dashboard/Dockerfile
This version changes the mount path for vhosts to
`/opt/bitnami/nginx/conf/server_blocks`.
Note I am not updating the chart version here, as this requires a new build of the dashboard image. When we release a new version, the chart can be updated and published.
fixes #1015
> updates nginx dependency to bitnami/nginx:1.16

- dashboard/src/reducers/apps.test.ts
- dashboard/src/reducers/apps.ts
We weren't checking if we were actually able to find the release name in
the `listOverview`, if it wasn't there (which is usually the case after
installing a chart as you get directed to the app page not the app list)
then `appOverviewIndex` would be `-1` and we won't be slicing the array
correctly.
This patch checks that we actually found the release in the
`listOverview` before updating the entry. If we don't find it, we don't
need to do anything, as it will get fetched and set in the
`listOverview` when visiting the AppList page.
fixes #1019
> only update listOverview if release present when processing updateInfo

- pkg/auth/auth.go
- pkg/auth/auth_test.go
Ref #1025
For charts that contains both CRDs and CRs `tiller-proxy` is not able to check if the user has permissions to create CRs because the CRD doesn't exist yet.
> Bypass permission check for elements that are not found in the API

- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
Fixes #1026
Closes #1025
There are other type of lists apart than `List` (like `RoleBindingList`).
> [Dashboard] Treat anything with items as a list in AppView

- .circleci/config.yml
- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepositories.yaml
- chart/kubeapps/templates/apprepository-crd.yaml
> Bump chart version. Update apprepositories annotations

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppList/AppListItem.test.tsx
- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/AppView/ChartInfo.test.tsx
- dashboard/src/components/AppView/ChartInfo.tsx
- dashboard/src/shared/types.ts
Fixes #1036
The auto generated name of the app is well... auto generated :joy:
> Show a warning message for non semver versions

- dashboard/src/components/AppView/AccessURLTable/AccessURLItem/AccessURLIngressHelper.test.ts
- dashboard/src/components/AppView/AccessURLTable/AccessURLItem/AccessURLIngressHelper.tsx
Fixes #1040
Ensure that an Ingress object has `rules`, `paths` and `tls.hosts` defined before processing them to avoid errors.
> Catch possible errors with incomplete Ingress objects

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
Disable the default securityContext configuration for MongoDB since the image is already running as root and setting the securityContext causes some issues like #1043 or #1017
> Disable default securityContext for MongoDB

- dashboard/src/components/ApplicationStatus/ApplicationStatus.scss
- dashboard/src/components/ApplicationStatus/ApplicationStatus.test.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.tsx
- dashboard/src/components/ApplicationStatus/__snapshots__/ApplicationStatus.test.tsx.snap
Closes #439 
Implementation discussed at https://docs.google.com/document/d/1eWvabsnY5tfhGVyV3cDbh_YPrAsnmrn06nWUXjXzke4/
If the Helm status is different than "DEPLOYED" show that status.
Substitute the message `Deploying/Deployed` to avoid confusion with the Helm status.
> Application status message

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepositories.yaml
Currently, the apprepositories-sync job does not use the global securityContext defined in the values.yaml. If Kubeapps is being deployed on a cluster where this security context is required, apprepositories have to be configured individually, or else the sync job will fail.
This PR checks the value of securityContext, and will ensure the apprepository-sync job will run as the correct user.
> Use global security context for apprepositories-sync job

- chart/kubeapps/values.yaml
- pkg/chart/chart.go
- pkg/chart/chart_test.go
Fix #1052 
Cache the result of unmarshaling the `index.yaml` file of a repository.
Increase the memory limit for Tiller-proxy.
> Fix memory usage for tiller-proxy

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>
A new MongoDB version was released (https://github.com/helm/charts/pull/15229) fixing an issue in some k8s cluster when IPv6 was disabled in the host, i.e https://github.com/kubeapps/kubeapps/issues/577.
This version also contains other changes in the chart (from MongoDB chart 5.0.0): https://github.com/helm/charts/tree/master/stable/mongodb#to-500
And also the `bitnami/mongodb` image was moved [from nami to bash](https://github.com/bitnami/bitnami-docker-mongodb/blob/master/README.md#3613-debian-9-r15-3613-ol-7-r15-4010-debian-9-r23-4010-ol-7-r24-4113-debian-9-r22-4113-ol-7-r23-or-later).
> Update mongodb chart version in deps

- script/chart_sync_utils.sh
Fixes #1077 
Use the first revision when doing a release. We cannot use `debian-9` since some images (tiller-proxy, apprepository-controller) use `scratch` as their base image.
> Avoid using rolling tag

- docs/user/getting-started.md
The command `kubectl get secret ... | base 64 --decode` in getting-started.md
will print the secret text together with the bash shell prompt in one single line.
Sometimes users might carelessly copy the secret text with the bash shell prompt.
> [Doc] Append a new line after the account secret

- chart/kubeapps/values.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
Closes #1070
Closes #617
Updates the `chart-repo` image to the latest version. This allows us to execute as often as wanted. 
As an example, the `stable` repository takes ~35s to do a full sync while with the new changes it takes just about a second.
> Update chart repo

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoRefreshAllButton.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/types.ts
Close #582. Add a button next to 'Add App Repository'
to refresh all app repositories.
> Add 'Refresh All App Repositories' button

- pkg/chart/chart.go
The purpose of this PR is to fix #696 .
The net client built by func InitNetClient in  https://github.com/kubeapps/kubeapps/blob/master/pkg/chart/chart.go, used by tiller-proxy to download repositories index and charts now uses proxy settings defined by http_proxy/https_proxy/no_proxy env vars.
> Tiller proxy - use proxy settings from environment

- dashboard/src/reducers/auth.test.ts
- dashboard/src/reducers/auth.ts
Fixes #1092. See the issue for the problem description.
The cause turned out to be that when the login form is submitted with an invalid token, the state is updated to `authenticating: true`, but is not reset when handling the `authenticationError`. This code hadn't changed in a while so I assume it's been that way for a long time, but what did change more recently was the `render()` function of the login form, which had a guard added in 407cae2b5 which:
```
public render() {
+    if (this.props.authenticating) {
+      return <LoadingWrapper />;
+    }
```
The change makes sense, we just need to update to ensure we don't leave the state `authenticating`.
> Set authenticating to false on authError (fixes #1092)

- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
This is just something I noticed while investigating #1009: if `validateToken()` receives an error response other than `401`, we silently ignore it and set the user as `authenticated: true`. This is most easily seen in the dev environment (below) but would be the case if the k8s api responded with a 502 or whatever, I assume?
Here's what you see locally in the dev env without the telepresence setup after entering any token (and `validateToken()` results in a 404):
Note that the redux state shows `authenticated: true`.
With this PR `validateToken()` always throws an error for an error response when validating the authz to the k8s api, so that (with the separate #1009), the user sees an error message:
Note the redux state shows `authenticated: false`.
We could probably improve the default …
> State not set to authenticated when validateToken fails with non-401 error

- dashboard/.gitignore
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/ClusterServiceClass.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/ServiceCatalog.ts
- dashboard/src/shared/ServiceInstance.ts
- dashboard/src/shared/url.ts
The `shared/Kube` module exports the `APIBase` constant, but this was not being used in quite a bit of the application code.
The reason I bothered with this branch is a little convoluted: I want to be able to run the dashboard dev environment in a container, which works fine except I can't yet use `telepresence` within a container (due to fusefs issues).
That said, I don't need telepresence (or my own kubeapps running in k8s) to simply point the dashboard at a kubernetes host during development, I just need the dev server to proxy those requests.
All I should need is to add a [`src/setupProxy.[js|ts]`](https://facebook.github.io/create-react-app/docs/proxying-api-requests-in-development#configuring-the-proxy-manually). This would be perfect as it would not affect those using the …
> Use Kube.APIBase consistently

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
Related to #1085, `yaml.safeLoad` should be used rather than `yaml.load`. The included new test will fail (as it will load the unsafe yaml) `yaml.load`.
> Use yaml.safeLoad for pod template.

- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretContent.scss
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/SecretItem.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/SecretItem/__snapshots__/SecretItem.test.tsx.snap
I've included screenshots and reasoning for the choice in a [comment on the issue](https://github.com/kubeapps/kubeapps/issues/1109#issuecomment-519317900).
While there, I updated an existing use of the nonstandard, unprefixed MS extension `word-wrap: break-word` to `overflow-wrap: break-word`, as I saw that [`word-wrap` is an alias for the standard `overflow-wrap` property in all browsers](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap).
> Fix overflow for SecretType. Fixes #1109

- go.mod
- go.sum
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- vendor/github.com/google/go-cmp/LICENSE
- vendor/github.com/google/go-cmp/cmp/compare.go
- vendor/github.com/google/go-cmp/cmp/export_panic.go
- vendor/github.com/google/go-cmp/cmp/export_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_disable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/debug_enable.go
- vendor/github.com/google/go-cmp/cmp/internal/diff/diff.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/flags.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_legacy.go
- vendor/github.com/google/go-cmp/cmp/internal/flags/toolchain_recent.go
- vendor/github.com/google/go-cmp/cmp/internal/function/func.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
- vendor/github.com/google/go-cmp/cmp/internal/value/pointer_unsafe.go
- vendor/github.com/google/go-cmp/cmp/internal/value/sort.go
- vendor/github.com/google/go-cmp/cmp/internal/value/zero.go
- vendor/github.com/google/go-cmp/cmp/options.go
- vendor/github.com/google/go-cmp/cmp/path.go
- vendor/github.com/google/go-cmp/cmp/report.go
- vendor/github.com/google/go-cmp/cmp/report_compare.go
- vendor/github.com/google/go-cmp/cmp/report_reflect.go
- vendor/github.com/google/go-cmp/cmp/report_slices.go
- vendor/github.com/google/go-cmp/cmp/report_text.go
- vendor/github.com/google/go-cmp/cmp/report_value.go
- vendor/modules.txt
Initial diff related to #1110 enabling Tiller to parse requests containing the name of an app repository custom resource. See that issue for more details.
> Parsing of tiller request details accepts an AppRepositoryResourceName

- cmd/tiller-proxy/internal/handler/handler.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/chart/fake/chart.go
This is the next small installment for #1110 .
I'm planning to have `InitNetClient` fetching the `AppRepository` custom resource, when present in the request, but wasn't confident to change it before adding tests. So this PR just tests the existing functionality, with a tiny refactor to pass the `ChartDetails` into the call (as this will include the auth object for the current `Details.Auth.CustomCA` secret ref, as well as the `Details.AppRepository.ResourceName` which I'll pull from k8s and parse in a later PR).
I have one other small prep branch next, before I'll add the fetch of the custom resource in `InitNetClient`.
> Add tests for InitNetClient. Refactor to pass chart details

- pkg/chart/chart.go
- pkg/chart/chart_test.go
As mentioned on #1124, we should not be causing tiller-proxy to exit if it can't fetch a user-supplied secret.
There was another question I had, which I'll add inline.
> Handle error when specified CA cert secret is not present.

- pkg/chart/chart_test.go
Since the client will be able to pass an `AppRepository` name instead of the actual `Auth` object, I'll need to initialise the `authHeader` during `InitNetClient` when the custom resource will be fetched (as we already fetch the CustomCA there too).
In preparation for that, I want to move the existing code which fetches the auth header from the `GetChart` call to `InitNetClient`, so both will be consistent - that'll be the next PR. This PR just does a little preparation, refactoring the `GetChart` tests so that I can add the auth check cleanly in the next PR.
A few notes inline.
Ref #1110
> Test refactor in preparation for change authz header initialization

- pkg/chart/chart.go
- pkg/chart/chart_test.go
Follow-on from #1127 that generalises the `clientWithDefaultUserAgent` to enable specifying default headers.
This is so we can also store the `Authorization` header that we'll grab during `InitNetClient`. Also fixed (and tested) so that the defaults don't override the request headers.
Ref: #1110
> Update clientWithDefaultUserAgent to clientWithDefaultHeaders (and defaults don't override)

- pkg/chart/chart.go
- pkg/chart/chart_test.go
Follow on from #1128 , this moves the fetching of the Auth secret to the client initialization function, to match what we already do for the customCA and also allow me to do the same (in the next PR) when fetching the `AppRepository` to get the auth details.
Ref #1110
> Move fetching of Auth secret to client initialization (matching customCA)

- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackDialog.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/__snapshots__/RollbackDialog.test.tsx.snap
- dashboard/src/components/ConfirmDialog/ConfirmDialog.tsx
- dashboard/src/components/ConfirmDialog/__snapshots__/ConfirmDialog.test.tsx.snap
- dashboard/src/components/PrivateRoute/PrivateRoute.tsx
- dashboard/src/components/ServiceClassView/ProvisionButton.tsx
- dashboard/src/components/ServiceClassView/__snapshots__/ProvisionButton.test.tsx.snap
- dashboard/src/components/ServiceInstanceView/__snapshots__/ServiceInstanceView.test.tsx.snap
- dashboard/src/index.scss
Fixes #1123
Avoid to use inline style every time we use a Modal (in the case we want a small, centered Modal).
I have moved the resulting CSS to the index file so the class `centered-modal` can be used anywhere.
I have also slightly modified the `RollbackButton` modal, see inline.
> Refactor Modals style

- pkg/chart/chart.go
- pkg/chart/chart_test.go
Following up on a comment https://github.com/kubeapps/kubeapps/pull/1125/files#r315253073 this ensures that we don't swallow an error unnecessarily when getting the system certs.
So that I don't break anyone's test environment, an empty pool of certs can be explicitly allowed if necessary.
> Don't ignore system cert error

- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- pkg/proxy/fake/proxy.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Follow up #997
After the feedback from @absoludity I checked that it's actually not necessary to send the chart details to tiller-proxy in order to retrieve the chart manifest that a release has.
We can get the changes we are going to perform if we run the rollback with the dry-run option.
I tested this manually and it works but there is not anything useful to test here since we are depending on the result from tiller.
> Use dry-run to resolve manifest when rolling back

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppView/AppControls/AppControls.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.test.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.tsx
- dashboard/src/containers/RollbackButtonContainer/RollbackButtonContainer.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
Frontend changes related to #1133
Since we don't require to resolve the chart here, there is a lot of code we can delete.
> Remove code related to resolve chart when rolling back

- chart/kubeapps/Chart.yaml
Reverts kubeapps/kubeapps#1135
I have to revert this until the tags are available :/
> Revert "Bump chart version"

- chart/kubeapps/Chart.yaml
The images `bitnami/kubeapps-dashboard:v1.5.0-r0` `bitnami/kubeapps-tiller-proxy:v1.5.0-r0` and `bitnami/kubeapps-apprepository-controller:v1.5.0-r0` are already available so we can release.
cc/ @absoludity
> Bump chart version

- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- cmd/tiller-proxy/main.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
Adds a clientset for the app revision API and uses that to get the AppRepository custom resource, if a name was specified in the request. This will enable the client (Kubeapps dashboard) to send the app repository name, rather than having to fetch the app repo (which can fail if certain RBAC is not setup).
Ref: #1110
> Fetch AppRepo to obtain auth data (so client doesn't need to send it).

- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- docs/user/access-control.md
- pkg/chart/chart.go
- pkg/chart/chart_test.go
Updates the frontend to send the repository resource name (and relying on the recent tiller-proxy changes to fetch the custom repo resource to get the auth), rather than fetching the resource from the client.
This removes the need for users to have read access to the app repositories CRD to simply deploy a chart, as per #1110 .
Update the docs to say the same, after QAing locally.
I temporarily removed a restriction I'd added in tiller-proxy so that the frontend can still send the repoURL as part of the request. With this PR, the task is finished, but I've got a final cleanup to followup with that will:
* updating tiller-proxy to store the repoUrl from the fetched app repository,
* removing the repoURL option from the `Details` struct and from the frontend request.
> Client sends chart repo resource name rather than fetching auth data.

- pkg/chart/chart.go
- pkg/chart/chart_test.go
When initializing the `chart.Chart` util object, store the fetched `AppRepository` custom resource, and use this as the source of the repo URL (no longer depending on the Details.RepoURL, which will be removed in the next PR).
Ref #1110
> Use repo URL from the app repository (no longer requiring Details.RepoURL).

- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
Removes requiredRBAC role from DeploymentForm and updates the App.upgrade method to pass the app repo name, as per Andres' comment https://github.com/kubeapps/kubeapps/pull/1147#pullrequestreview-282873375
Also updates both create and upgrade to no longer send the repoURL (in #1150 tiller-proxy is updated to use the fetched app repo's repoURL instead).
Ref #1110
> App.upgrade sends app repo name

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
- chart/kubeapps/values.yaml
This PR updates some image with CVEs.
It also changes the dashboard image from kubeapps/dashboard:latest to bitnami/kubeapps-dashboard:1.5.0-debian-9-r14 until #1156 is fixed.
> Use fixed tag for bitnami/kubeapps-dashboard image

- chart/kubeapps/templates/tests/test-chartsvc.yaml
- chart/kubeapps/templates/tests/test-dashboard.yaml
- chart/kubeapps/templates/tests/test-tiller-proxy.yaml
- script/e2e-test.sh
Ref  #1146
Sometimes the helm tests fails but since we are not printing the logs we are not sure what could be happening. The goal of this PR is to add verbosity to the tests so we can find the cause of the issue when it appears.
> Increase debug of helm tests

- chart/kubeapps/values.yaml
- script/chart_sync_utils.sh
Fixes #1156
Retrieve the latest tag from GitHub instead of hardcoding the tag `-r0`.
This needs to set the env var TOKEN in CircleCI to avoid hitting the GitHub API quota.
Tested manually:
```patch
diff --git a/chart/kubeapps/values.yaml b/chart/kubeapps/values.yaml
index 59742084..938095cb 100644
--- a/chart/kubeapps/values.yaml
+++ b/chart/kubeapps/values.yaml
@@ -221,8 +221,8 @@ dashboard:
replicaCount: 2
image:
registry: docker.io
-    repository: kubeapps/dashboard
-    tag: latest
+    repository: bitnami/kubeapps-dashboard
+    tag: 1.5.0-debian-9-r16
service:
port: 8080
livenessProbe:
```
cc/ @tompizmor
> Retrieve latest tag from GitHub when syncing the chart

- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/NamespaceSelector.test.tsx
- dashboard/src/components/Header/NamespaceSelector.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/containers/RoutesContainer/RoutesContainer.tsx
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
Follows on from #1167 to fix #1162 .
Conceptually this just removes any `default` option for the header/namespace selector, replacing it with the `state.auth.defaultNamespace` set in the previous branch. When testing I had some issues because the redirect from the root route was using `state.namespaces.current` which is no longer necessary set - eg., when first logging in after a refresh.
Also includes a drive-by to no longer ignore errors when fetching namespaces (at least storing the error in the state).
I'll follow-up with one or two small drive-by's that I noticed (one is that we retain state when logging out, for namespaces etc.)
> Use default namespace from auth state rather than 'default'.

- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- cmd/apprepository-controller/main.go
Hi,
first time contributing to this project, so please bear with me. I don't know whether this change is something you want. Any feedback welcome! I stumbled across this leftover `TODO` in the code regarding the cron schedule of the apprepository sync controller. I made the crontab modifiable and resolved the `TODO`.
Cheers,
Fabian
**This is the original commit message on PR submission:** 
Customization for apprepository crontab.
Apprepository controller now has a configurable crontab. Defaults to
"*/10 * * * *", as this was the hard-coded value before this change.
The cli parameter for the controller is '--crontab' and the
configuration property in the helm-chart is 'apprepository.crontab'.
> Customization for apprepository crontab.

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/chartsvc-deployment.yaml
- chart/kubeapps/templates/dashboard-deployment.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
There are several deprecations in the API introduced in `K8s 1.16` (see https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals) which affect our manifests. The following APIs are no longer served by default:
- All resources under `apps/v1beta1` and `apps/v1beta2` - use `apps/v1` instead
- **daemonsets**, **deployments**, **replicasets** resources under `extensions/v1beta1` - use `apps/v1` instead
- **networkpolicies** resources under `extensions/v1beta1` - use `networking.k8s.io/v1` instead
- **podsecuritypolicies** resources under `extensions/v1beta1` - use `policy/v1beta1` instead
This PR address the changes to be done for Kubeapps' chart manifests.
> Kubeapps Chart -  Update apiVersion deployments

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/actions/namespace.ts
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
- dashboard/src/shared/AxiosInstance.test.ts
- dashboard/src/shared/Namespace.ts
Just two tiny clean-ups I'd noted in some earlier work.
First, ensure that we clear the namespaces in the client state when logging out: I kept finding that I would re-authenticate with a token for a user with access to only a single namespace, but find the UI still presented all namespaces, until I refreshed.
Second, avoid 302 permanent redirects when checking namespaces api endpoint.
> Clear namespaces on logout

- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/tiller-proxy/main.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Fixes #1090 
Add option to setup this through the chart.
I have tested this manually.
cc/ @agill17
> Allow to modify the default timeout for tiller

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
While investigating installation on k8s 1.16 for a Sahel [1] I noticed that installing the Kubeapps chart would fail because the mongodb dependency version was using old api endpoints too.
Even though we've recently updated the dep, 2.7.7 still has the removed endpoints for the standalone deployment:
```
~$ helm fetch --untar stable/mongodb --version 7.2.7 && cd mongodb
~/mongodb$ rg extensions
templates/ingress.yaml
2:apiVersion: extensions/v1beta1
templates/deployment-standalone.yaml
2:apiVersion: extensions/v1beta1
```
2.7.9 does not:
```
$ helm fetch --untar stable/mongodb --version 7.2.9 && rg extensions mongodb/                                                                                                                                          
mongodb/README.md
256:The allowed …
```
> Update mongodb dependency to support deployment on k8s 1.16

- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
I was wanting to better understand how the state is currently managed for values.yaml in charts.
Seems that we have global state in redux for the selected chart version, which we copy into the form's local state which the user can modify - which is fine, but while there, I noticed some redundant state, so added tests then removed it.
> Add tests for values.yaml state in DeploymentForm

- chart/kubeapps/crds/apprepository-crd.yaml
- chart/kubeapps/templates/apprepositories.yaml
This results in Kubeapps deploying without issue in helm 3, but obviously not runnable (tiller-proxy currently errors if it can't connect to tiller).
Nonetheless, without this change the chart errors with helm 3. With this change, the chart can be installed successfully multiple times. It utilises the support for a `crds` directory in the chart, but note that these CRD files cannot be templated (nor should they need to be, since they are system-wide and not reference-counted?).
Verified that I can also install this chart successfully with helm 2.13.1 .
> Update chart to be deployable with helm 3

- .circleci/config.yml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/values.yaml
GKE branch 1.11 is not available, replace it with 1.13 to fix the CI 
Also to avoid breaking changes. Avoid the `--crontab` flag by default for the apprepository controller.
Tested on: https://circleci.com/gh/kubeapps/kubeapps/9416?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
> Replace GKE 1.11 with 1.13

- dashboard/src/components/DeploymentForm/AdvancedDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/DeploymentForm/__snapshots__/DeploymentForm.test.tsx.snap
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Config.test.ts
- dashboard/src/shared/Config.ts
Based on the design document #1152 
Right now this feature flag is only usable using `telepresence`. To use it, execute:
```
▶ REACT_APP_KUBEAPPS_ENABLE_BASIC_FORM=true TELEPRESENCE_CONTAINER_NAMESPACE=kubeapps yarn run start
```
> Add feature flag for basic form

- chart/kubeapps/values.yaml
- dashboard/src/reducers/auth.test.ts
- dashboard/src/reducers/auth.ts
The issue was that the `initialState` for auth included `defaultNamespace = ""` rather than obtaining it from the token. With this change, defaultNamespace should never be empty.
The function `defaultNamespaceFromToken` already returns `DEFAULT_NAMESPACE` if it is unable to get it from the token (which is the case for OIDC tokens).
We may want to revert #1184 with this change? (as in, this issue also fixes the issue seen there, and the change there causes you to require logging in again when it is unnecessary - see what you think).
(Updated the test image to fix and test #1160 while there)
> Fix empty default namespace for good

- chart/kubeapps/templates/kubeapps-frontend-config.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/main.go
- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/shared/Chart.ts
Use `tiller-proxy` to proxy traffic to the chartsvc (instead of direct usage).
Regarding the `Dashboard` I have moved the `chart` functions to the `shared` folder and use `axiosWithAuth` when needed.
Tested manually.
> Proxy chartsvc requests

- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
I'm still getting some 404s since some components don't try to retrieve the default namespace from the `auth` state (only the root container does that):
```
▶ ag 'namespace.current' dashboard/src   
dashboard/src/components/Header/Header.tsx
105:                      <HeaderLink {...link} currentNamespace={namespace.current} />
dashboard/src/containers/AppListContainer/AppListContainer.tsx
18:    namespace: namespace.current,
dashboard/src/containers/ServiceInstanceListContainer/ServiceInstanceListContainer.ts
23:    namespace: namespace.current,
dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
30:    namespace: namespace.current,
dashboard/src/containers/ChartViewContainer/ChartViewContainer.tsx
23:    namespace: namespace.current, …
```
> Use auth default namespace in namespace reducer

- dashboard/src/actions/catalog.test.tsx
- dashboard/src/actions/repos.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/containers/RoutesContainer/RoutesContainer.tsx
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
Found a couple of issues while doing some QA:
- After https://github.com/kubeapps/kubeapps/pull/1190, the `namespace` in `Routes.tsx` is always defined (and is pointing to `default` since the token has not been read yet). So, regardless of the content of the token once logged in, it was redirecting me to the `default` namespace. To avoid that I have added the additional check to only redirect to `/apps/ns/{ns}` when accessing the root path (`/`) if the user is already authenticated.
- After login out the `current` namespace was cleared to the default value (`default`). This caused that after login out and in again the namespace changed from whatever it was to `default`. To avoid this, we should not remove the `current` namespace from the state.
> Fix currentNamespace

- docs/developer/chart-repo.md
- docs/user/access-control.md
- docs/user/getting-started.md
Fixes: https://github.com/kubeapps/kubeapps/issues/917
* Use builtin `base64decode` command that is included in `kubectl`, previously docs were piping output to `base64 --decode` command.
* Add bash syntax highlighting to - docs/user/access-control.md
Let me know if you want to drop any changes or make any improvements.
> Improve base64 decoding command usage in docs

- chart/kubeapps/templates/kubeapps-frontend-service.yaml
- chart/kubeapps/values.yaml
I'm using metallb in a bare-metal setup, I'd like to assign a static IP address to the frontend when installing kubeapps with helm. This PR enables that.
> Helm chart: Add ability to set static IP addr when using load balancer service type

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/actions/namespace.ts
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
Again I found more issues (mostly related to my changes, sorry). The issue is that `current.namespace` was now always set to `default` because it was read at the very beginning when the token is not yet introduced.
To avoid all the issues I have found with my tests I have added the action `SET_DEFAULT_NAMESPACE` and store it only if the `current.namespace` has never been set.
I have added more tests, hopefully this is the last PR related to the issue :crossed_fingers: 
Sorry for the noise.
> Revamp default namespace setup

- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/DeploymentForm/__snapshots__/DeploymentForm.test.tsx.snap
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/reducers/charts.ts
- dashboard/src/shared/Chart.ts
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Part 1 of 2
Ref #1182 
With this PR, the dashboard obtains the schema from the chartsvc (requires https://github.com/helm/monocular/pull/645) and pass it to the `DeploymentForm` component to parse it.
As an example, I have hardcoded the basic parameter `username` to show the proposed architecture.
I have defined a basic form parameter as:
```js
{
name: username, // Name of the basic parameter
path: account.username, // Path of the parameter in the JSON Object (e.g. {account: {username: "foo"} }
value: user // Current value of the parameter
}
```
Result:
> Read schema and add username to the basic form

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
- chart/kubeapps/values.yaml
--
The NGINX Ingress Controller annotations documentation was moved from:
https://github.com/kubernetes/ingress-nginx/blob/master/docs/annotations.md
to:
https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md
> Fix broken links to NGINX Ingress Annotations docs

- dashboard/package.json
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.scss
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/DiskSizeParam.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/DiskSizeParam.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/DiskSizeParam.test.tsx.snap
- dashboard/src/components/Slider/Slider.tsx
- dashboard/src/components/Slider/components.tsx
- dashboard/src/components/Slider/index.tsx
- dashboard/yarn.lock
Ref #1182 
This PR adds a slider to select the disk size in the simplified form.
It's possible to modify it either dragging the slider or adding a custom number in the input field close to it.
Note that apart than the component `react-compound-slider` it's necessary to add some boilerplate code to make the slider work so I have created a wrapper of that component with the code avaliable [here](https://sghall.github.io/react-compound-slider/#/slider-demos/horizontal) to expose a simplified `Slider` component. That boilerplate code is not covered by unit tests and doesn't require a thoughtful review.
> Add slider component for adding the disk size

- dashboard/package.json
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.scss
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BooleanParam.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BooleanParam.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/TextParam.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/TextParam.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/BooleanParam.test.tsx.snap
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/TextParam.test.tsx.snap
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/yarn.lock
Ref #1182 
This PR adds support to two new type of params (generic): integer and boolean:
The switch button is added with the package `react-switch`. The `StringParam` has been renamed to `TextParam` so it covers the use case for a number.
> Add support for integer and boolean params

- dashboard/package.json
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/IngressSection.tsx_
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/reducers/namespace.test.ts
- dashboard/yarn.lock
This PR fixes some small issues:
- Thanks to the fix of https://github.com/eemeli/yaml/issues/125 we can know parse the values.yaml as a YAML Document without major changes. The new version 0.7.1 includes that fix.
- In case the user changes the values in the "Advanced" form, the YAML is parsed and the basic parameters are recalculated to modify the basic form if needed.
- We only show the basic/advanced tabs if the application has some basic parameters defined.
> Basic form improvements

- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.scss
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BooleanParam.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/DatabaseSection.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/DatabaseSection.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/DatabaseSection.test.tsx.snap
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/shared/schema.test.ts
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/utils.ts
This is a dup of #1208. I mistakenly merge that PR against a temporary branch.
> Add support for enabling a external database

- dashboard/src/components/DeploymentForm/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/Subsection.test.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/Subsection.tsx
- dashboard/src/components/DeploymentForm/BasicDeploymentForm/__snapshots__/Subsection.test.tsx.snap
- dashboard/src/shared/schema.ts
Ref #1182
Added support for the resource specification:
I had to add more keys to the definition to have it as a subsection. My plan, in the close future, is to refactor the keys supported in the schema so it's not necessary to define them.
> Add support for resource elements

- dashboard/src/components/DeploymentFormBody/AdvancedDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.scss
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Subsection.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/SliderParam.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/TextParam.test.tsx.snap
- dashboard/src/components/Slider/Slider.tsx
I have added some minor changes to the style of the basic form:
- Added margin and separators between parameters
- Display the label and input in the same line
Before:
After:
> Style changes for basic form

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
Ref: #1182 
In order to avoid dependencies with hardcoded references to key names in the logic, I have set some new properties that an element can define in order to be rendered as a slider (instead of a string). For example, the disk size can be represented as:
```json
"size": { 
"type": "string",
"title": "Disk Size",
"form": "diskSize",
"render": "slider",
"sliderMin": 1,
"sliderMax": 100,
"sliderUnit": "Gi"
}
```
> Make the slider param customizable via the schema

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Subsection.tsx
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
Follow up of #1224 #1223 
As discussed in the above PRs, it's possible to define different types based on the information present in the param.
Let me know what you think (or if this is what you were suggesting @absoludity). I am not sure if this improves readability because you need to cast to the different types when needed, which can be confusing.
> Split types for the different params

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
I have added the hint to redirect people to GitHub in case they find issues with the basic form:
WDYT?
> Add hint to basic form

- chart/kubeapps/templates/apprepository-rbac.yaml
When repeatedly testing installation on openshift (minishift), I'd find that the app repository controller failed to create the cron-jobs, with the error:
```
E1018 01:25:15.595721       1 controller.go:239] error syncing 'kubeapps/incubator': cronjobs.batch "apprepo-sync-incubator" is forbidden: cannot set blockOwnerDeletion in this case because cannot find RESTMapping for APIVersion kubeapps.com/v1alpha1 Kind AppRepository: no matches for kind "AppRepository" in version "kubeapps.com/v1alpha1" 
```
yet, if I force container restarts (just updating the deployment pull policy, for eg), they would restart without issue. So it appears to be a timing issue, that if the app repository controllers are up and running before the RESTMapping for the kubeapps.com/v1alpha is available, it will …
> Add cronjob delete perm for app repo controller to avoid startup error

- chart/kubeapps/templates/apprepository-rbac.yaml
- script/openshift-cluster.mk
I'd previously assumed that `script/openshift-cluster.mk` would run without the user necessarily having sourced the output of `minishift oc-env`, but this is unnecessary (ie. it's a valid assumption that the user will have done this), and complicates the targets (as it required running only a single command per target after having sourced).
This also fixes `helm dep update` to `helm dep build` (I didn't realise update was pulling charts from requirements.yaml rather than requirements.lock... build is the one we want, as it just ensures that what is in the lock file is present), and updates that target to use the specific mongodb version (otherwise it pulls it every time).
Also fixes the `-reset` target to ensure all items run even if some fail (as if you have an incomplete deployment, it …
> Don't depend on sourcing minishift oc-env.

- Makefile
We were surprised by the fact that tiller-proxy wasn't compiled when running `make all`.
> Add tiller-proxy to the 'all' make target

- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- dashboard/src/shared/Auth.ts
- docs/user/using-an-OIDC-provider.md
Follows on from #1199. When QAing #1199, we noted that the websocket requests were 400ing. This was because with 1199, I've switched to no longer white-list requests to the k8s api, so they are sent via the proxy. The proxy handles adding any required auth headers for all requests (websocket requests included).
With this change, they upgrade without issue:
While there, I also removed the specific (key-cloak-based) cookie name which I'd added because I thought it would be referenced in the frontend and need updating there. Turns out its not at all, so we can just let `oauth2-proxy` use its default cookie name and avoid any confusion.
> Frontend injects wsprotocols only when not using oidc authn

- dashboard/src/containers/RoutesContainer/Routes.tsx
With [`const` assertions](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#const-assertions), TypeScript infers as specific types as it can (and `readonly` recursively for properties). I think they're great in many situations, so I figured I'd try them out real quick. What do you guys think?
> Use const assertions in Routes.tsx

- dashboard/src/containers/RoutesContainer/Routes.tsx
This is necessary for the `component` React property to be properly type checked. The reason is that, as far as TypeScript knows, `Object.keys` only returns plain strings, whereas with `Object.entries`, `component` in `[route, component]` is assigned as narrow a type as expected, derived from the values in the routes object.
Another advantage is that the routes objects are not repeated inside the mapped functions, so there is no risk of writing e.g.
<Route ... component={privateRoutes[route]} />
instead of
<Route ... component={routes[route]} />
**Possible caveat:** `Object.entries` is [not supported in IE](https://caniuse.com/#search=Object.entries). Will it be transpiled/polyfilled?
> Replace Object.keys with Object.entries

- dashboard/src/shared/Kube.test.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/ResourceKinds.ts
- dashboard/src/shared/ResourceRef.ts
- dashboard/src/shared/types.ts
This PR is intended to facilitate a discussion on the possibility of introducing stronger typings where `string` is used today. `ResourceKind` is just one example of a narrower type that might be useful.
Actually, just by making this change and building, I found two resource kinds in the code base that were not included in the map from resource kinds to their plural representations, namely [`ClusterRole`](https://github.com/kubeapps/kubeapps/blob/16b04b9868596ff84dd3bb1b8054df5eb94fc702/dashboard/src/components/AppView/AppView.test.tsx#L344) and [`ConfigMap`](https://github.com/kubeapps/kubeapps/blob/16b04b9868596ff84dd3bb1b8054df5eb94fc702/dashboard/src/components/AppView/ResourceTable/ResourceItem/OtherResourceItem/OtherResourceItem.test.tsx#L10). However, I'm not familiar enough with …
> Improve resource kind typing

- .circleci/config.yml
- integration/jest-puppeteer.config.js
- integration/jest.environment.js
- integration/jest.setup.js
- integration/use-cases/create-registry.js
- integration/use-cases/default-deployment.js
- integration/use-cases/missing-permissions.js
- script/e2e-test.sh
Fixes issues in master: https://circleci.com/workflow-run/aec97cdb-f9e7-40dc-b192-e102ddc8456e
- The `expect()` timeout is set using `setDefaultTimeout`.
~~- I have moved independent timeout sets from each test file to common configuration files.~~ Had to remove this. I don't know why it doesn't work in the CI environment.
- I have increased the size of the browser window so the screenshots are more useful.
- GKE doesn't use `coredns` so I removed the check for that component.
> Fix browser tests

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BooleanParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BooleanParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Subsection.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/Subsection.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BasicDeploymentForm.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/BooleanParam.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/__snapshots__/TextParam.test.tsx.snap
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/shared/schema.test.ts
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
Code refactor after #1257 
After removing the keys `enables` and `disables` we no longer need to use the `form` key as a unique ID. I have changed that for a boolean in the first commit (a0995aa).
Then, since the `form` is not a name or an ID, I have changed the code to use an array instead of a `map<string:IBasicFormParam>` when working with basic params (b85f936).
> Form key refactor

- docs/user/getting-started.md
Fixes #842 .
The service account created in this way with OpenShift has two secrets associated with it, and the kubeapps-operator token is not the first.
Unfortunately we can't use RegExp in jsonpath (see #842) but we can display the secrets one per line and simply grep. Confirmed this works with both openshift and vanilla K8s.
> Update instruction for getting token to work on vanilla k8s and openshift

- chart/kubeapps/README.md
- docs/user/manifests/openshift-tiller-with-apprepository-rbac.yaml
- docs/user/manifests/openshift-tiller-with-crd-rbac.yaml
- script/openshift-cluster.mk
Fixes #676 .
This PR fixes one remaining issue I had with the development environment on OpenShift, removing the need to use `cluster-admin` for tiller. Together with the work from the past iteration, Kubeapps now installs without issue on OpenShift.
I'm not keen to make a stronger statement about OpenShift support for a few reasons, so have updated the relevant part of the troubleshooting in the README to mention our tentative support and link to the RBAC policies as examples for the related issue.
As per TODOs in the doc, I don't think the RBAC requirements are specific to OpenShift, but rather we should be promoting these as the default (for helm2 / tiller - we don't seem to mention working with non-cluster-admin tiller anywhere that I can see. Checked our …
> Remove requirement for cluster-admin for tiller in openshift example.

- dashboard/src/components/Footer/Footer.tsx
The account `kubeapps` is not being used so I changed to a search of Kubeapps mentions (https://twitter.com/search?q=(kubeapps%20OR%20%23kubeapps))
> Update twitter link in the footer

- dashboard/src/components/ConfirmDialog/ConfirmDialog.test.tsx
- dashboard/src/components/ConfirmDialog/ConfirmDialog.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/DeploymentFormBody/__snapshots__/DeploymentFormBody.test.tsx.snap
Ref: #1235 
Add a button to restore the chart version defaults. I am adding a confirmation modal to avoid accidental clicks on the reset button (which causes the loss of any data introduced):
I am reusing the `ConfirmDialog` already existing for the confirmation modal, that's why there are changes there.
> Add Restore Defaults button

- dashboard/src/components/DeploymentFormBody/AdvancedDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/Tabs.scss
The code editor was being printed on top of the modal:
After the fix:
> Fix z-index of the editor

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/ChartView/ChartReadme.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/SliderParam.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/ServiceInstanceList/ServiceInstanceList.test.tsx
- dashboard/src/components/ServiceInstanceList/ServiceInstanceList.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceView.test.tsx
- dashboard/src/components/ServiceInstanceView/ServiceInstanceView.tsx
Closes #1200 
This PR removes `UNSAFE_*` methods. It also adds tests for the cases the related method were not covered.
> Remove unsafe methods

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
This PR adds basic templates for issues and pull requests so:
-  Users fill al the required information for Kubeapps maintainers to debug their issues and provide an efficient support.
- Contributors provide all the context Kubeapps maintainers need to review their contributions.
More info at: https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates
> Add templates for new issues and PRs

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
This is a prequel to re-enabling the logout option for oidc. When I first re-enabled logout, I found that the cookie would be removed as would the id_token (from localStorage), but then the client would just re-get the id_token from the server (`fetchOIDCToken`) and therefore assume it was logged in again.
One of the benefits of using OAuth/OIDC is that the client doesn't need to ever see (or store) the actual access token... the http-only cookie is all that is required (and the auth-proxy adds the id-token to the request), which is not only much safer, but means we can logout also :)
> Don't use or store id_token when using cookie-based auth

- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- dashboard/public/config.json
- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/Config.ts
This PR un-hides the logout action (it was previously explicitly hidden when logged in via oauth).
The `Auth.unsetAuthCookie` does the work (just redirecting to the configured logout point which removes the cookie - it's impossible to remove the cookie from the client-side JS as it is http-only).
A lot of fun was had (sarcasm) updating the `isAuthenticatedWithCookie` function to handle all cases. It's basically tricky because the the client can't detect an http-only cookie at all.
The result looks like this (sorry, low res):
This is a second prequel to #1249 (after #1294).
> Enable logout when logged in via cookie/oauth

- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
`componentDidUpdate` (a difference from `componentWillReceiveProps`) gets executed when the state changes.
If the `state.filter` of the `Catalog` changes, the value was being put back to whatever the `props.filter` said, losing the changes. This was working before since the hook `componentWillReceiveProps` was not being executed with changes in the state.
> Fix filter in Catalog view

- chart/kubeapps/Chart.yaml
- chart/kubeapps/crds/apprepository-crd.yaml
- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/apprepositories-secret.yaml
- chart/kubeapps/templates/apprepositories.yaml
- chart/kubeapps/templates/apprepository-crd.yaml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/apprepository-jobs-cleanup-rbac.yaml
- chart/kubeapps/templates/apprepository-jobs-cleanup.yaml
- chart/kubeapps/templates/apprepository-rbac.yaml
- chart/kubeapps/templates/chartsvc-deployment.yaml
- chart/kubeapps/templates/chartsvc-service.yaml
- chart/kubeapps/templates/dashboard-deployment.yaml
- chart/kubeapps/templates/dashboard-service.yaml
- chart/kubeapps/templates/ingress.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/templates/kubeapps-frontend-service.yaml
- chart/kubeapps/templates/mongodb-jobs-cleanup-rbac.yaml
- chart/kubeapps/templates/mongodb-jobs-cleanup.yaml
- chart/kubeapps/templates/tests/test-chartsvc.yaml
- chart/kubeapps/templates/tests/test-dashboard.yaml
- chart/kubeapps/templates/tests/test-tiller-proxy.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-secret.yaml
- chart/kubeapps/templates/tiller-proxy-service.yaml
- chart/kubeapps/templates/tls-secrets.yaml
- chart/kubeapps/values.yaml
- Change chart YAML(s) to make it follow Bitnami standards (and [Helm Best Practices](https://helm.sh/docs/topics/chart_best_practices))
- Some utilities such as **yamllint**, **kubeval** or **helm lint** have been used to ensure there are no syntax errors on the chart's manifests (see https://github.com/bitnami/charts/pull/1452)
> Kubeapps chart - Lint chart

- chart/kubeapps/templates/kubeapps-frontend-config.yaml
As we do for the calls to `tiller-proxy` and the kubernetes API, we need to forward the access_token to the chartsvc (because we are authenticating it through tiller-proxy).
> Add missing Nginx configuration for GKE

- dashboard/src/reducers/charts.ts
If found another issue, while downgrading from a version that contains a schema to one that doesn't, the form didn't got removed. This is because in the reducer, we were checking that the schema exists to be set in the state (maintaining the previous state otherwise).
> Fix downgrade when the schema is missing

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
I have noticed that the `componentDidUpdate` method of the `BasicFormBody` is being executed with every stroke of the keyboard while writing in the basic form. This cause a re-render of the whole values.yaml to look an parse params which made the form response slow.
To fix that, now the whole values are just re-rendered if the version changes (and the schema or the default values changes) or if it's the first time we receive values.
> Fix slow response of the form

- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
I noticed a race condition in the UpgradeForm, due to that the `getDeployedVersion` triggered the `selectChartVersion` action, sometimes, the form goes back to the current deployed version (instead of the last one. This PR fixes that, getting the deployed version doesn't mean the user is selecting it.
> Avoid SELECT action when requesting the deployed version

- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
Ensure there is a default value for the oauth logout URI
**Benefits**
If the current code is deployed with an older chart which does not define the `config.logoutURI`, then clicking logout (when authed via a cookie) redirects to `/undefined` and you are not logged out.
Just noticed this as unexpected behaviour on a recent environment. Turns out it's because `logoutURI` was not defined in the config (due to the older chart).
> Add default logout URI if non defined in config

- .circleci/config.yml
- cmd/apprepository-controller/Dockerfile
- cmd/tiller-proxy/Dockerfile
- go.mod
- go.sum
I think this will make it easier to use external modules going forward. Notably, this change is among the ones we made in order to be able to import `helm.sh/helm/v3` in #1309.
The `gopkg.in/DATA-DOG/go-sqlmock.v1` changes were made by `go mod tidy`.
> Upgrade to Go 1.13

- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- dashboard/public/config.json
- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/LoginForm/__snapshots__/LoginForm.test.tsx.snap
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Config.ts
Enables oauth login to use our normal Kubeapps login page (rather than the rather blank oauth2-proxy default).
**Benefits**
A unified login view for Kubeapps, regardless of whether token login or oauth/oidc is being used.
Also ensures we don't see a flash of the login screen after auth'ing.
- fixes #1249 
Enables the root route to pass through the proxy, so that our own login form can trigger the authentication as it currently does for token auth also.
> Oauth logout login 2

- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- pkg/handlerutil/handlerutil.go
- pkg/handlerutil/handlerutil_test.go
This PR moves a few types and (mostly pure) functions to a separate package.
The code in question becomes more reusable, which will help with implementing Helm 3 support down the road (see #1309).
Currently, this will expose some entities that weren't exposed before (`Params`, `WithParams`, `WithoutParams`, `ErrorCode` and `ErrorCodeWithDefault`). If this is undesired, I'd be happy to create the new package at e.g. `internal/handlerutil` or `cmd/internal/handlerutil` instead of `pkg/handlerutil`. (AFAIK, `pkg/internal/handlerutil` won't work because the moved entities need to be imported in `cmd`.)
> Move HTTP/handler utils to a separate package

- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.test.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.tsx
The component `AccessURLTable` is now being mounted *before* the references to the ingress objects are populated. This caused the AccessURLTable to be empty. To avoid that, we are now fetching also the ingresses when there are changes in the list.
Another subtle change is that instead of relying on the implementation of `fetchIngresses`, which was defined in the container, I have moved the implementation to the component so it's clear what it's doing.
Fixes #1307
> Fix URL table for ingresses

- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/main.go
Remove the hardcoded reference to the command executed in the chart-repo image. It's needed to replace `chart-repo` for something else.
**Benefits**
The image and the command can now change.
- ref #651
> Allow to configure the command for the sync image

- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- pkg/auth/authgate.go
Moving forward, it will be needed to implement Helm 3 support (see #1309), and it was in an internal package, so it couldn't be imported outside the `cmd/tiller-proxy` directory.
> Move AuthGate to pkg/auth

- cmd/tiller-proxy/Dockerfile
It modifies tiller-proxy's `Dockerfile` so that dependencies are kept between builds.
It becomes faster (or possible at all) to `make` tiller-proxy after modifying the source code. I saw a speedup from about 30 to under 20 seconds on a stable connection. On a slow or unstable connection, it wasn't possible to `make` tiller-proxy at all before this change (at least not after #1312).
> Cache dependencies between tiller-proxy builds

- cmd/asset-syncer/delete.go
- cmd/asset-syncer/main.go
- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
- go.mod
- go.sum
This PR adds the method `Delete` (which is simpler) for the postgres driver in the asset-syncer. To achieve that I have split the `utils.go` (and `utils_test.go`) in two different files, depending if the method required a database connection so we have now `mongodb_utils.go` and `postgresql_utils.go`. Each one of those with their tests.
It's only necessary to review the files `delete.go`, `main.go`, `postgresql_utlils.go` and `postgresql_utils_test.go`. The rest is just moving methods around.
- ref #651
> Add Delete method for the postgres driver in asset-syncer

- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
When creating a release, if it fails for some reason (like band inputs) clean up the release afterwards so the same name can be reused.
BTW, there is no an "atomic" flag that we can use in the CreateRelease action for helm, this is the code:
https://github.com/helm/helm/blob/456eb7f4118a635427bd43daa3d7aabf29304f13/pkg/action/install.go#L313
**Possible drawbacks**
If the release failed to be installed but it's not stored as a failed release (for example for an invalid name) we will be returning also an error for the missing release when trying to delete it, which might be confusing.
- fixes #1163
cc/ @SimonAlling since these changes affect to tiller-proxy
> Delete failed installations

- dashboard/src/components/AppView/AppNotes.scss
- dashboard/src/components/AppView/AppNotes.tsx
Before:
After:
**Benefits**
All text can be read without overflowing.
**Possible drawbacks**
Each line in the terminal text is no longer a single line necessarily?
- fixes #1326
We could instead use `overflow: hidden` but it's then difficult to actually see (or copy-n-paste) the text.
> Break a word in the console if there is no other wrap option.

- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/types.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
When refactoring the `Sync` logic, I didn't see that each chart entry in the database holds a copy of the `repo` struct. Since I added the actual repository content to that struct, the mongoDB connection was crashing (because it was trying to flush to much data).
**Benefits**
This PR fixes the e2e tests for the `assetSyncer` branch.
- ref #651
> Remove content from repo struct

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
It's much closer to what we actually _mean_ compared to plain bold text. (I've been replacing bold with headings manually for my latest PRs.)
> Use headings instead of bold in GitHub templates

- cmd/asset-syncer/delete.go
- cmd/asset-syncer/main.go
- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
Follow up of the conversation here:
https://github.com/kubeapps/kubeapps/pull/1328#pullrequestreview-325900983
The goal is to refactor the current flag initialization to reduce duplicated code and move code to the `main.go` flags.
Unfortunately, it's not possible to execute code in the `main.go` file *after* the flags are populated so still the manager initialization happens in the `sync.go` and `delete.go` files.
- ref #651
> Refactor flags and manager initialization

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
- chart/kubeapps/templates/NOTES.txt
- chart/kubeapps/templates/ingress.yaml
- chart/kubeapps/values.schema.json
- chart/kubeapps/values.yaml
- docs/user/login-alternatives.md
This PR includes a basic JSON schema for the Kubeapps chart. It doesn't cover all the possible values of the chart but just the ones that, in my opinion, are more likely to be modified.
This is valid for Helm 3 to validate some values and, at the same time, for Kubeapps to render a simple form so the chart containing it is easier to configure and deploy. See https://github.com/kubeapps/kubeapps/blob/master/docs/developer/basic-form-support.md for more information.
This is an example of the file rendered by Kubeapps:
This PR also standardizes the way we configure Ingress.
> Kubeapps - Add JSON Schema & standardize ingress configuration

- .circleci/config.yml
- Makefile
- cmd/tiller-proxy/Dockerfile
* [BuildKit](https://docs.docker.com/develop/develop-images/build_enhancements) is used for `docker build`.
* `COPY . .` is replaced with more explicit directives.
* `--mount` flag preserves Go build cache between builds.
* Removing the `-a` flag makes `go build` use Go build cache.
This brought the build time (after modifying the source code) down from 20 seconds to about 5 seconds on my laptop.
* BuildKit requires Docker 18.09 or later. I don't know if building still works on older versions of Docker.
> Improve tiller-proxy build time with BuildKit

- chart/kubeapps/templates/kubeapps-frontend-config.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-secret.yaml
- chart/kubeapps/templates/tiller-proxy-service.yaml
- chart/kubeapps/templates/tiller-proxy-serviceaccount.yaml
- chart/kubeapps/values.yaml
It doesn't work yet, but will be needed later on (see #1309).
As [pointed out](https://github.com/kubeapps/kubeapps/pull/1309#pullrequestreview-321255789) by @absoludity: "I think it's fine to land with the useHelm2/3 switch available but clearly document that it's not yet working, as long as it isn't changing current behaviour […]."
> Add useHelm3 flag

- cmd/apprepository-controller/Dockerfile
See #1342.
I haven't worked with apprepository-controller, but this PR is helpful for `make all` at least.
> Improve apprepository-controller build time

- cmd/kubeops/main.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
It rewrites `agent.ParseDriverType` to return an error instead of panicking if it doesn't recognize its input.
* `ParseDriverType` is made more faithful to its declared type.
* It's made more obvious in `main.go` that the application may panic.
* `ParseDriverType` becomes more verbose.
Excerpt from a [related discussion](https://github.com/kubeapps/kubeapps/pull/1359#discussion_r355911774) with @andresmgot in #1359:
> I'm much more inclined to make `agent.ParseDriverType` return an error instead of panicking, because, unlike `createStorage`, it promises that it can handle any `string`. Its current deceitfulness stems from my interpretation of @absoludity's [suggestion](https://github.com/kubeapps/kubeapps/pull/1309#discussion_r349377228) that Kubeops should refuse to start if an invalid …
> Don't panic in ParseDriverType

- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/types.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
The goal of this PR is to add support for fetching chart files for the PosgreSQL driver as we do for MongoDB. For doing that:
- I have moved common logic (logic that actually downloads files and icons from the source) to the common `utils`. For doing so I have added the struct `fileImporter` that defines the common methods.
- The struct `fileImporter` above has, as a property, an `assetManager` which has been extended to define the methods related to the database: `updateIcon`, `filesExist` and `insertFiles`.
- Each driver (`mongodb_utils` and `postgresql_utils`) define the methods above.
Note: I found that I was not closing the returned `rows` given by the `pq` library so I fixed that here.
- ref #651
> Asset Syncer: Fetch files for postgres

- dashboard/src/components/ChartIcon/ChartIcon.scss
- dashboard/src/components/ChartView/ChartHeader.scss
Fixes the icon size for the different charts while maintaining the current working ones:
- fixes #1365
> Fix chart icon size

- pkg/agent/agent_test.go
- Check the content of returned listed releases (not just size comparison).
- Complete information about returned apps in test cases.
- Add test case for release with same name, but different versions and namespaces.
Build and expand on the existing test of `TestListReleases` in `/pkg/agent`, by ensuring the equivalence between what is expected and the returned values of `ListReleases`.
The current test checks only if `|G| = |W|` where `W` is the expected result and `G` is the result of `ListReleases`.
- By populating the expected results of the test cases with `namespace` and `version`, better distinction between releases is achieved.
- This PR adds an additional constraint, namely `∀ g ∊ G : g ∊ W`, which together with the previous one i.e. `|G| = |W|`, ensures that `G = W`.
- The new …
> Improve TestListReleases for /pkg/agent

- cmd/tiller-proxy/README.md
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- go.mod
- go.sum
- pkg/proxy/fake/proxy.go
- pkg/proxy/proxy.go
- pkg/proxy/proxy_test.go
Change proposed in #1106 
New endpoint added to tiller-proxy
`GET /namespaces/{namespace}/releases/{releaseName}/test`
+ Release exists, tests are defined and passed 
```json
{
"data": {
"RUNNING": [
"RUNNING: kubeapps-chartsvc-test",
"RUNNING: kubeapps-dashboard-test",
"RUNNING: kubeapps-tiller-proxy-test"
],
"SUCCESS": [
"PASSED: kubeapps-chartsvc-test",
"PASSED: kubeapps-dashboard-test",
"PASSED: kubeapps-tiller-proxy-test"
]
}
}
```
+ Release doesn't exist
```json
{
"code": 404,
"message": "Unable to locate release: release: \"kubeapps2\" not found"
}
```
+ Release exists, no tests are defined
```json
{
"data": {
"UNKNOWN": [
"No Tests Found"
]
}
}
```
+ Release exists, tests fail to complete
```json
{
"data": {
"FAILURE": [
"ERROR: pods \"kubeapps-chartsvc-test\" already exists", …
```
> [tiller-proxy] Add endpoint for testing a release

- chart/kubeapps/templates/kubeapps-frontend-config.yaml
With `useHelm3: true`, the kubeapps pods wouldn't start properly:
$ kubectl logs -n kubeapps kubeapps-7c6ff86b88-44tmd
11:14:51.38
11:14:51.38 Welcome to the Bitnami nginx container
[...]
11:14:51.40 INFO  ==> ** Starting NGINX **
2019/12/13 11:14:51 [emerg] 1#0: host not found in upstream "kubeapps-internal-tiller-proxy" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:60
nginx: [emerg] host not found in upstream "kubeapps-internal-tiller-proxy" in /opt/bitnami/nginx/conf/server_blocks/vhost.conf:60
> Fix kubeapps CrashLoopBackOff with useHelm3

- chart/kubeapps/Chart.yaml
- chart/kubeapps/values.yaml
Just noticed this when upgrading Kubeapps itself:
Not a big deal, but we probably don't want it to be the first thing a user sees until it actually works.
> Move useHelm3 switch to end until we want it so visible.

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
In https://github.com/kubeapps/kubeapps/pull/1368#discussion_r356994225 @SimonAlling (fairly) didn't like the fact that we were needing to validate the `DriverType` after we'd already parsed it correctly.
This change removes the string `DriverType` constants, replacing them with a `StorageForDriver` function type.
This way, when the driver is parsed we return the corresponding `StorageForDriver` function which can be used to obtain the driver-specific storage, so we no longer need to validate the driver type.
Not sure if this fits what you want @SimonAlling ? Let me know :)
> Remove the need to validate DriverType

- chart/kubeapps/templates/tests/test-tiller-proxy.yaml
Since the introduction of the `useHelm3` flag in `values.yaml`, we ought to check for that before running `test-tiller-proxy`. We can't assume Tiller is installed when using Helm 3.
The test won't run when using Helm 3, which does not have the Tiller component.
- fixes #1380 
cc: @SimonAlling
> Toggle off test-tiller-proxy if useHelm3 is true

- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/kubeapps-frontend-config.yaml
It makes the `proxy_pass` configuration for Tiller Proxy or Kubeops (depending on the value of `useHelm3`) more DRY.
Suddenly, I couldn't get Kubeapps to start with `useHelm3: true`, making me spend several hours trying various more or less random fixes. (I thought I had messed something up with Docker or Minikube, so I didn't think of bisecting or inspecting the YAML files.) The reason turned out to be [this unconditional `proxy_pass` directive](https://github.com/kubeapps/kubeapps/pull/1347/files#diff-b0b5b871c8bf5a72f95d417c97266ae0R100) introduced in #1347 and fixed by me in #1382.
This PR is intended to prevent something similar from happening again; it's not at all obvious that the `proxy_pass` directives must be conditional.
Might be interesting to @lindhe and @absoludity.
> DRY up proxy_pass configuration

- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/utils_test.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main_test.go
- cmd/assetsvc/mongodb_utils.go
- cmd/assetsvc/postgresql_utils.go
- go.sum
- pkg/dbutils/dbutils.go
- pkg/dbutils/mongodb_utils.go
- pkg/dbutils/postgresql_utils.go
Follow up of #1381
There is a bit of duplicated code shared between the `assetsvc` and the `asset-syncer` related to how the assetManager is initialized. To avoid more clutter in #1381, I have split the code related to remove that duplicated code in this PR.
> Remove duplicated code

- cmd/tiller-proxy/internal/handler/handler.go
- pkg/handlerutil/handlerutil.go
I'm planning to use it in Kubeops as well.
I renamed it because I think `ParseAndGetChart` is more descriptive of what it actually does.
> Rename and move getChart to handlerutil

- cmd/tiller-proxy/internal/handler/handler.go
- pkg/handlerutil/handlerutil.go
This makes it usable in Kubeops (Helm 3) as well.
> Make ParseAndGetChart Helm version agnostic

- Makefile
the `include ./script/cluster-kind.mk....` statements introduce rules and the first rule is the default rule.
> Fix makefile default rule

- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
- go.mod
- go.sum
- pkg/chart/models/chart.go
After #1386 (`models` refactor), the `Repo` struct contained auth info that was stored in the `charts` database and was being returned for each chart request. This `auth` info should not be send to the client. To fix this, the `asset-syncer` will work with the struct `RepoInternal` (which has the auth info but it's not stored in the database) and the assetsvc will continue to work with the `Repo` struct.
Apart from that this PR includes a fix that was preventing the postgres driver to properly skip files import.
> Redefine Repo struct

- cmd/tiller-proxy/internal/handler/apprepos_handler.go
- cmd/tiller-proxy/internal/handler/apprepos_handler_test.go
- cmd/tiller-proxy/main.go
- docs/architecture/design-proposals/third-party-add-repository.md
Fills in the stub implementation of the `Create` handler for the app repository backend API
Note: this handler is similar in nature to the helm3 work in the respect that it picks up the in-cluster k8s config and uses that with the user token to access the API. But note that it's structured so that:
- the k8s config, with the blanked `BearerToken` is read from the system and created once only when the handler is created,
- an actual working config with the user token is created for each request. This is a copy of the blanked k8s config with the token set.
- it is tested using the (generated) fake clientset for the resource by injecting a dummy `clientsetForConfig` function when testing which just returns the fake. This ensures that external use of this handler will always have the real …
> Create handler for app repositories backend API.

- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/assetsvc/postgresql_utils.go
- pkg/dbutils/postgresql_utils.go
While the goal of this PR was to create programatically the tables used (if not exist), I found several small issues while testing this IRL so I added them to this PR:
- Use the table names defined in `dbutils`
- Fix a bug that was deleting the chart from the repositories not being evaluated
- Remove a debug `fmt.Print`
Note: I am not testing the new code because a test mocking the result doesn't help much and also because this is a basic functionality that will be tested in the e2e tests.
> Create tables before syncing content

- chart/kubeapps/templates/kubeops-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/kubeops/main.go
It does basically the same thing as #1348 but for Kubeops.
* Requests to Kubeops won't fail with `502 Bad Gateway`.
This PR is intended to be merged before #1406.
> Add readiness and liveness checks for Kubeops

- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/components/UpgradeForm/__snapshots__/UpgradeForm.test.tsx.snap
Reverts the change which updated the default value for the chart version on upgrade to the latest available version. We'd made this decision based on the assumption that "Upgrade" is only for upgrading a chart, but it seems a common use of "Upgrade" is also to update values without upgrading a chart at all, confusingly.
Don't surprise upgrade a chart for users who are intending to only update values.
Confuses the case for "Upgrade", but this is already confused in the helm CLI
#1407 
- fixes #
Sorry Andres, I think I convinced you why users, if upgrading, would want to have the most recent chart by default, without realising "Upgrade" isn't really always "upgrade". I've included a comment which would have ensured I had understood this and so not considered the change.
> Revert to select the chart version of the current release on upgrade

- cmd/kubeops/main.go
> It appears tiller-proxy isn't a great example here... can you add a TODO to add app specific health and readiness checks as per https://github.com/heptiolabs/healthcheck ? Thanks.
https://github.com/kubeapps/kubeapps/pull/1405#discussion_r363133504
@absoludity
> Add TODO for app-specific live/ready checks

- chart/kubeapps/templates/apprepository-deployment.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/main.go
- cmd/apprepository-controller/pkg/client/clientset/versioned/clientset.go
- docs/developer/apprepository-controller.md
- go.mod
- pkg/agent/agent.go
It replaces `github.com/golang/glog` and `k8s.io/klog` with `github.com/sirupsen/logrus`.
* Logging becomes more consistent.
* Before this PR, `V` from `glog` was sometimes used, for example like this:
```go
glog.V(4).Info("Hello!")
```
This PR simply replaces `glog.V(4)` with `log`, which might affect verbosity. I don't know if this matters.
* Fixes #1410.
> Use logrus consistently for logging

- cmd/kubeops/internal/handler/handler_test.go
- pkg/chart/fake/chart.go
Adds test framework for `/kubeops/internal/handler` to facilitate adding test scenarios in the future for all kinds of actions, such as creating a release, listing all releases, deleting etc.
Changes proposed are analogous to the file [`/tiller-proxy/internal/handler/handler_test.go`](https://github.com/kubeapps/kubeapps/blob/master/cmd/tiller-proxy/internal/handler/handler_test.go).
This PR adds only the skeleton without any test scenarios implemented as they are function-specific and are up to the author of future tests.
- Lays ground for future PR's for testing new Helm 3 functions.
- Uses Helm 3 library for representing releases, charts etc.
- Adds Helm 3 support in `GetChart` in `/pkg/chart/fake`
Planned to be used to write tests for #1399 and #1406 and #1359 
This is a minimal PR …
> [kubeops] Implement framework for testing /kubeops/internal/handler

- cmd/tiller-proxy/internal/handler/apprepos_handler.go
- cmd/tiller-proxy/internal/handler/apprepos_handler_test.go
Follows on from #1397
1. Fixes issue where clientset was still using service-account auth
2. Updates to also create and reference relevant secret for an app repo with credentials, as well as including other app repo details.
Next PR will update the UI to use this endpoint.
Also demonstrates testing of handlers using k8s clientsets (@SimonAlling - in case it's useful/relevant).
- Ref #1173
> Update apprepo create API to include appropriate secret

- cmd/kubeops/internal/handler/handler_test.go
- pkg/agent/agent_test.go
Adds tests for the functionality of creating releases with Helm 3.
Tests the functionality in both the HTTP handler and `/pkg/agent` (Helm 3 library wrapper).
Analogous to the tests done for `tiller-proxy` in [`/cmd/tiller-proxy/internal/handler`](https://github.com/kubeapps/kubeapps/blob/master/cmd/tiller-proxy/internal/handler/handler_test.go) and [`/pkg/proxy`](https://github.com/kubeapps/kubeapps/blob/master/pkg/proxy/proxy_test.go)
Covers and tests CreateRelease #1399 
_Should be merged after_ #1408
> [kubeops] Add tests for CreateRelease

- Makefile
It includes `assetsvc` and `asset-syncer` in the `all` make target.
* I think it will be easier to build and install Kubeapps locally.
* `assetsvc` and `asset-syncer` were added in #1323.
> Include assetsvc and asset-syncer in 'make all'

- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/assetsvc-deployment.yaml
- chart/kubeapps/templates/db-secret-bootstrap.yaml
- chart/kubeapps/values.yaml
Deploy PostgreSQL (by default) with one replica. Thanks to that, if any of the two PostgreSQL pods goes down, the service will still work.
The service `kubeapps-postgresql` will reach the `master` instance only while the `kubeapps-postgresql-headless` service hits both the `master` and `slave` replicas.
The slave replica is read-only. This means that if the master goes down, for the time that that pod is down, the data is immutable.
- fixes #1142
> Enable replication for PostgreSQL

- cmd/tiller-proxy/internal/handler/handler.go
It reuses `QueryParamIsTruthy`, introduced in #1420, in the Tiller Proxy code.
* Code becomes more DRY and readable.
> Use QueryParamIsTruthy in Tiller Proxy

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- pkg/agent/agent.go
This PR implements `UpgradeRelease` using the Helm 3 API.
* It will bring us one step closer to Helm 3 support.
* There are no tests yet.
* `OperateRelease` only supports upgrading at the moment (but it will support testing and rolling back later).
* Based on discussions in #1309.
* The logical next step after #1420.
The `switch` statement in `handler.OperateRelease` is currently redundant, but it will make sense when support for testing and rolling back is added (see [its Tiller Proxy counterpart](https://github.com/kubeapps/kubeapps/blob/4b4b14bff89e552506aea7170ec51a4aa32719e5/cmd/tiller-proxy/internal/handler/handler.go#L97:L110)).
> Add Helm 3 UpgradeRelease

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
It introduces an abstraction for defining routes, making the definitions clearer, shorter and DRYer.
* Easier to define routes in `main`.
* Reduced code repetition.
* Less clutter, highlighting actual content.
* Less room for mistakes.
* Routes are forced to be very similar in behavior to each other.
> Refactor Kubeops routes code

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/internal/handler/handler_test.go
- cmd/kubeops/main.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
It moves the types `Config` and `Options` from the `agent` package to the `handler` package and updates all depending code accordingly.
* The types in question will be more reasonably located. They are not actually used in `agent.go` (except by mistake in `CreateRelease`; fixed in this commit); the functions there only need an `action.Configuration`.
> Move Config and Options from agent to handler

- cmd/kubeops/internal/handler/handler.go
Add comments to exported functions. I was getting some linting warnings.
> Add comments to exported functions

- cmd/asset-syncer/postgresql_utils.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
Not setting a unique varchar column with PostgreSQL was causing the application to show duplicates instead of updating the existing chart. Now the chart ID (e.g. `bitnami/apache`) is used as that unique column.
It requires deleting the existing table (or restarting postgres pods) but the feature has not been released yet.
> Set unique chart ID column

- cmd/kubeops/internal/handler/handler_test.go
- pkg/agent/agent_test.go
Tests new functionality introduced by #1420 
- Adds test for DeleteRelease in /pkg/agent
- Adds action="delete" tests for /kubeops/handler
Skip tests blocked by memory driver bug
- Tests #1420 
- Related to #1434 
Contains a `TODO` in `/cmd/kubeops/internal/handler/handler_test.go` with instructions on what to do when the [memory driver bug](https://github.com/helm/helm/pull/7372) is fixed.
> Add tests for DeleteRelease

- cmd/kubeops/internal/handler/dashboardcompat_test.go
- cmd/kubeops/internal/handler/handler_test.go
- pkg/agent/agent_test.go
Tests new functionality introduced by #1406 . 
- Adds test for GetRelease in `/pkg/agent`
- Adds `action="get"` tests for `/kubeops/handler`
- Adds tests for `dashboardcompat.go` in `/kubeops/internal/handler`
Skip tests blocked by memory driver bug
Tests #1406 
Contains a `TODO` in `/cmd/kubeops/internal/handler/handler_test.go` with instructions on what to do when the [memory driver bug](https://github.com/helm/helm/pull/7372) is fixed.
Signed-off-by: Latiif <abdullatif.alshriaf@combitech.se>
> [kubeops] Add tests for GetRelease

- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
It's not explicit but the `chartVersion` returned by `getChartsWithFilters` should be the latest version in order to return it to the client. That's is later used by the dashboard to determine if there are updates available. Since the charts are ordered, it should return the first one of the array.
> [PG] Return latest chart version

- .circleci/config.yml
Updates to test against GKE 1.13 and 1.14 rather than 1.12 and 1.13.
Update kubectl version from 1.12 to 1.13.
CircleCI began failing today when testing GKE_1_12_MASTER with the error:
```
ERROR: (gcloud.container.clusters.create) ResponseError: code=400, message=No valid versions with the prefix "1.12" found.
```
It's not clear to my why this errored while GKE_1_12_LATEST_RELEASE did not (though they both use the same `GKE_BRANCH="1.12"` env var, but nonetheless I saw in the [release notes from a week ago](https://cloud.google.com/kubernetes-engine/docs/release-notes) that certain 1.12 cluster versions would no longer be available.
> Update to test with gke 1.13 and 1.14 rather than 1.12 and 1.13, since 1.12 master no longer available.

- cmd/kubeops/internal/handler/dashboardcompat.go
- cmd/kubeops/internal/handler/dashboardcompat_test.go
- cmd/kubeops/internal/handler/handler_test.go
Related to a question I had at https://github.com/kubeapps/kubeapps/pull/1434#discussion_r366069755 , it was unclear why we were handling panics in tests rather than eliminating them.
I added a number of test cases which caused a panic as mentioned in the above comment, then fixed with a guard clause. While there, I also added some tests for the parsing of the Deleted timestamp.
A number of conditions which could cause a panic have been eliminated.
The error for the failed parsing of the Deletion timestamp is less explicit (so I could test it without doing string comparisons - *guilty* I'll update it if you think it's important)
- fixes #
> Test and remove panic possibilities in newDashboardCompatibleRelease

- pkg/agent/agent_test.go
In 9c2df183d the Helm3 `AppOverview.Version` was explicitly changed from representing the release revision (`strconv.Itoa(r.Version)`) to the chart version (`Chart.Metadata.Version`), as it should to match the response from tiller proxy.
But the tests in `TestListReleases` was relying on the version to sort the results for consistent ordering (due to an issue with Helm's memory driver https://github.com/helm/helm/issues/7263). Since the new values used to sort in the test were identical, we get inconsistent ordering resulting in occasional test failures like:
https://circleci.com/gh/kubeapps/kubeapps/15198
```
--- FAIL: TestListReleases (0.00s)
--- FAIL: TestListReleases/include_uninstalled_apps_when_requesting_all_statuses (0.00s)
agent_test.go:437:   []proxy.AppOverview{
{
ReleaseName: …
```
> Consistent ordering in TestListReleases

- pkg/chart/helm3to2/dashboardcompat.go
- pkg/chart/helm3to2/dashboardcompat_test.go
In #1445 I removed some detail from an error because I couldn't figure out a good way to test the situation (without resorting to string comparisons). I had tried to use the new error wrapping ability, but since the underlying error (from `ptypes.timestamp`) doesn't return or expose a standard error, I was unable to use `errors.Is()` to identify it.
With a fresh mind this morning, I realised that `fmt.Errorf` intentionally allows you to wrap either error while still maintaining the same error string in the result. That allows this simple change to work. See what you think
Allows handling errors and identifying our own errors using `errors.Is` as is done here in a test (but not restricted to tests).
This is an alternative to #1447
> Use error wrapping to test without string comparison.

- cmd/kubeops/main.go
- cmd/tiller-proxy/main.go
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
In order to be able to create apprepositories when using kubeops (Helm 3), it's necessary to use the same code and endpoint than with tiller-proxy.
> Enable apprepositoriess endpoint for kubeops

- chart/kubeapps/templates/kubeops-rbac.yaml
- cmd/kubeops/internal/handler/handler.go
- go.sum
Kubeops is in charge of downloading the chart info and deploy it. For doing so, it needs to retrieve apprepositories and secrets in the `kubeapps` namespace. We are not using the user token for this task so the user doesn't need to have permissions for the above (context at: #1110).
cc/ @SimonAlling @latiif
> Use kubeops serviceaccount to retrieve charts

- dashboard/src/components/Config/ServiceBrokerList/__snapshots__/ServiceBrokerList.test.tsx.snap
- dashboard/src/components/ErrorAlert/ErrorSelector.tsx
- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.test.tsx
- dashboard/src/components/ErrorAlert/PermissionsErrorAlert.tsx
- dashboard/src/components/ErrorAlert/__snapshots__/ErrorSelector.test.tsx.snap
- dashboard/src/components/ErrorAlert/__snapshots__/PermissionsErrorAlert.test.tsx.snap
- pkg/handlerutil/handlerutil.go
With Helm 3, we are not pre-processing the chart to return the forbidden actions, we are leaving that to Helm. Then we are just returning the error given by Helm if it exists. We need to adapt the dashboard code and the response a bit in order to give an appropriated response.
Now forbidden errors are easier to debug with Helm 3:
If we compare this solution to the one in tiller-proxy (Helm 2) we have two drawbacks due to just forwarding the error given by Helm:
- The error message is more confusing (e.g. `create: failed to create: secrets is forbidden ...`
- Only one forbidden action is returned (the first one to fail I guess) instead of all the forbidden action.
This is the same error for Helm 2 for the sake of comparison:
To mitigate this a bit, we could parse the error returned by Helm …
> Show forbidden errors for Helm 3

- dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
I've found a bug when upgrading an application that is not possible to resolve it's source registry. In that case, we ask the user to introduce the chart registry and then we internally populate the `repo` info. The problem was that we were only tracking changes in the `app` info in order to retrieve the deployed chart data causing the app to show the default values in the upgrade form (without the user modifications).
> Request chart when both repo and app are populated

- chart/kubeapps/values.yaml
When enabling the ingress setup, two hosts with identical information are generated. One because the `hostname` is set and another one because the section `hosts` is also configured (the legacy mechanism to set ingresses).
cc/ @juan131
> Remove duplicated ingress in chart

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
Removes the `RawIcon` field from the json/bson responses.
I noticed while testing today that listing the (default) catalog is a 6M payload:
and looking at a specific wordpress chart is as 14M payload:
A large part of this is because we are now including the `RawIcon` data as part of the responses (for each chart, or for each version of a chart).
The request for the list of charts (default repos) goes down from 6M to 3M. The request for a chart's versions goes down from 14M to 4M.
I think this issue (of the huge payloads) appears to have begun with the switch away from the monocular repo, as I notice there that the chart model is explicitly defined to *not* serialize certain fields to (and from) json, including the RawIcon and ChartVersions: …
> Remove RawIcon from chart versions

- pkg/agent/agent.go
When installing a chart, if the installation fails, it's useful to cleanup the release so the same name can be reused. This was already implemented for Helm 2 (#1163) but was missing for Helm 3.
> Enable atomic installations for Helm 3

- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
After https://github.com/kubeapps/kubeapps/pull/1455/ I introduced a regression. When upgrading, if the repository can be auto-resolved, the properties of `AppUpgrade` are not being updated and the condition I introduced was always `true`, causing an infinity loop.
> Check repo state instead of props when upgrading

- pkg/agent/agent.go
When adding the atomic flag, I only checked wrong builds so it worked as expected but it seems that when the build should be successful, the connection just hangs. I have opened an issue in Helm (link in the code) but in the meantime, I am disabling the feature.
> Disable atomic installations

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
Follow up of https://github.com/kubeapps/kubeapps/pull/1460
Remove the ChartVersion list from the requests: `/charts/{repo}/{chartName}/versions` and `/charts/{repo}/{chartName}/versions/{version}` as the `chartsvc` does. This reduces the sice of the requests from several MBs to less than 500KB.
> Remove chartVersions when listing versions

- .circleci/config.yml
- cmd/kubeops/Dockerfile
- script/e2e-test.sh
- script/libtest.sh
Enable two more builds to run end-to-end tests using Helm 3 (both using MongoDB and PostgreSQL as database back-ends).
> Enable CI builds for Helm 3

- dashboard/src/components/AppUpgrade/AppUpgrade.test.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
- dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/reducers/repos.ts
- integration/use-cases/upgrade.js
- script/e2e-test.sh
I found an issue when doing some testing with a serviceaccount that didn't have permissions to interact with apprepositories (but has write permissions in the namespace). The `AppUpgrade` form was requesting the existing repositories regardless if it was necessary or not (it's only necessaary when the source repository cannot be auto-detected).
This PR refactors the `AppUpgrade` component so the `SelectRepoForm` is the one requesting apprepositories and it's only mounted if it's not possible to auto-resolve the source repository. I am also refactoring quite a bit the `AppUpgrade` component since the logic and error handling is quite messy.
For the sake of simplicity, I have removed a case in which the chart information is present but it doesn't have metadata (which is not a real …
> Allow to upgrade an application without RBAC permissions to read apprepositories

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/internal/handler/handler_test.go
- go.sum
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/handlerutil/handlerutil.go
Follow up of https://github.com/kubeapps/kubeapps/pull/1450
With Helm 3, we are currently not doing the pre-validation to check if the user has enough permissions. Because of that, we are currently returning the raw error to the user. That's a regression in the UX since with Helm 2 we give a detailed list of roles needed to perform the requested action.
What this PR proposes is to parse the error returned by Helm and give an user-friendly error (like we do in Helm 2) with the permissions needed.
When trying to do an operation over an application, we are parsing the error returned by the Helm client, returning all the information that we have:
The good thing about this approach is that we are not assuming anything. We are just leaving Helm do its work and forward its response.
From the …
> Parse forbidden errors to return forbidden actions

- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.test.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- integration/use-cases/upgrade.js
Fixes #1479 
Regression added in #1472
We were not taking into account the auto-resolved repository in order to populate the property `repoName`.
Since a `Container` is difficult to test with unit-tests I have covered this fix with the end-to-end test for upgrading.
> Fix upgrade modifications

- dashboard/src/actions/kube.test.tsx
- dashboard/src/actions/kube.tsx
- dashboard/src/reducers/kube.test.ts
- dashboard/src/reducers/kube.ts
- dashboard/src/shared/types.ts
This PR creates an `onError` handler that can be called if the socket connection throws an error. This triggers an interval to re-request resources every 5s. This interval can be closed the same way than the socket calling `closeTimer`.
I have tested this removing the Nginx configuration that allows the socket connection, in the GIF below, you can see how the application gets updated even without the socket. When leaving the view, the timer gets cleared so we don't re-request more those resources.
- fixes #1352
> Request resources asynchronously when the socket connection fails

- docs/developer/assetsvc.md
- docs/developer/basic-form-support.md
- docs/developer/dashboard.md
- docs/developer/kubeops.md
- docs/developer/tiller-proxy.md
- docs/user/access-control.md
- docs/user/getting-started.md
- docs/user/migrating-to-v1.0.0-alpha.5.md
- docs/user/migrating-to-v1.0.0.md
- docs/user/securing-kubeapps.md
- docs/user/service-catalog.md
- docs/user/using-an-OIDC-provider.md
This PR updates standardize the markdown syntax for code blocks:
- Use `'bash'` syntax for scripts and commands.
- Use `'console'` syntax for terminal outputs.
- Consistency
None
> Standardize code blocks on docs

- script/e2e-test.sh
There is a race condition in which we try to retrieve the serviceaccount tokens before they are ready. For example:
https://circleci.com/gh/kubeapps/kubeapps/16102
This PR reorders the token retrieval and adds a small sleep to avoid that.
> Add sleep before retrieving tokens

- script/e2e-test.sh
- script/liblog.sh
- script/libtest.sh
- script/libutil.sh
Improves CI tests scripts based on [bash best practices](https://github.com/juan131/bash-libraries#bash-best-practices).
- Robust bash scripts
- No warnings/errors using [shellcheck](https://www.shellcheck.net/)
I might break the CI tests 🤣
> Improve CI tests based on bash best practices

- integration/use-cases/create-registry.js
- script/e2e-test.sh
The end to end test to create a registry is quite flaky:
https://circleci.com/gh/kubeapps/kubeapps/16306
https://circleci.com/gh/kubeapps/kubeapps/16279
Checking the screenshot, the modal that renders the form is not being shown. My guess is that the click in the button is not behaving as expected in the browser so I have added a second click to ensure that the modal is opened. If this doesn't fix the issue I will investigate further.
> Fix flaky test

- cmd/kubeops/internal/handler/handler_test.go
- go.sum
- pkg/agent/agent.go
- pkg/agent/agent_test.go
From https://github.com/helm/helm/issues/7426 I noticed that the atomic flag requires to use the wait flag as well which doesn't fit our use case.
This PR mimics what we had in tiller-proxy: check if the release already exists, if not and the installation fails, clean it up.
> [Helm 3] Re-enable atomic installations

- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/ErrorAlert/NotFoundErrorAlert.tsx
- dashboard/src/components/ErrorBoundary/ErrorBoundary.test.tsx
- dashboard/src/components/ErrorBoundary/ErrorBoundary.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/NamespaceSelector.scss
- dashboard/src/components/Header/NamespaceSelector.test.tsx
- dashboard/src/components/Header/NamespaceSelector.tsx
- dashboard/src/components/Layout/Layout.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/ErrorBoundaryContainer/ErrorBoundaryContainer.test.tsx
- dashboard/src/containers/ErrorBoundaryContainer/ErrorBoundaryContainer.ts
- dashboard/src/containers/ErrorBoundaryContainer/index.ts
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
- dashboard/src/shared/Namespace.ts
Follow up of #1489 to fix #1364
When selecting a namespace that doesn't exists, shows an error so the namespace is created in advance:
- fixes #1364
cc/ @fabianschwarzfritz
> Return a valid error when using non-existing namespaces

- chart/kubeapps/templates/apprepository-jobs-cleanup-rbac.yaml
- chart/kubeapps/templates/apprepository-rbac.yaml
- chart/kubeapps/templates/db-secret-cleanup-rbac.yaml
- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
Update k8s api version for rbac. v1 has been GA since k8s 1.8 which is our minimum supported k8s version [according to our docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/getting-started.md).
Ref: #1495
> Switch rbac api version to v1 (GA from k8s 1.8)

- chart/kubeapps/templates/apprepository-rbac.yaml
Accidentally merged master rather than rebasing before landing this, which meant it had an older commit adding the ClusterRole unconditionally.
> Fix accidentally merged clusterrolebindings

- chart/kubeapps/templates/dashboard-config.yaml
- dashboard/public/config.json
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/containers/RoutesContainer/RoutesContainer.tsx
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Config.ts
- script/deploy-dev.mk
Ref: #1495 
This diff adds the `featureFlags` hash to the config so the frontend can also use it, which it does to:
- Update the route for the apprepo list when the feature is on
- Update the menu link for the apprepo list when the feature is on.
> AppRepositories list uses namespaced URI

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoRefreshAllButton.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
- dashboard/src/containers/RepoListContainer/RepoListContainer.test.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/AppRepository.ts
- docs/user/private-app-repository.md
Ref: #1495 . Updates so that AppRepositories are display per namespace (when the FeatureFlag is enabled).
I've also added a helper which can remain for a release or two after we remove the feature flag, which only displays if you're viewing app repos for a specific namespace.
In the next PR I plan to:
- Get rid of the jump that you see when changing namespace (by removing app repos from state immediately when the namespace changes, rather than when the new list is loaded). Perhaps we want a spinner here now too?
- Update the installRepo so that a new repo is created in the current namespace.
Quick example:
> 1495 5 app repos for namespace only

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/AppRepository.ts
Follows #1503. Ref #1495 .
As planned in the previous PR, this one:
- Adds the `LoadingWrapper` so that stale data doesn't flash when changing namespaces.
- Updates the installRepo action to pass the namespace with the request (the backend already supports this, from #1499)
The next PR will update the delete and refresh actions to work with per-namespace app repositories.
> 1495 6 app repos created in namespace

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoRefreshAllButton.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/types.ts
Follows #1504, Ref: #1495 
Enables delete, resync and resync all for repos using each repos own namespace (so each works fine on the All Namespaces view also).
> Enable deleting, resynching and resync all across namespaces.

- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- chart/kubeapps/values.yaml
- cmd/kubeops/main.go
- cmd/tiller-proxy/main.go
- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/url.ts
- go.sum
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
The goal of this PR is to allow users that don't have permission to list namespaces to discover the namespaces they have access to.
Now the dashboard, instead than hitting the k8s API to list namespaces, it contacts the "backend" service (either kubeops or tiller-proxy). This service first tries to list namespaces using the user serviceaccount (just like we do today). If the user doesn't have permissions to list namespaces, it uses the backed serviceaccount to do so. If the chart is installed with the flag `allowNamespaceDiscovery`, the backend will have permission to list those.
After that, for each one of the namespaces, the backend determines if the user has permission to access that namespace checking if they have permission to get secrets. Then it return the list of allowed …
> Allow to discover namespaces

- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
Ref: #1496 
Updates the apprepo handler so that a copy of an app repository credential is recorded in Kubeapps' own namespace.
> Store a copy of the repo secret in Kubeapps' namespace

- cmd/kubeops/main.go
- cmd/tiller-proxy/main.go
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/url.ts
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
Ref: #1496 . Small prequal for adding the apprepository delete URI in the backend. URIs for AppRepositories in the backend should be unique to be resh-ish (consider a `DELETE`). This just updates the route for the Create handler to include the namespace in the URI, which means using the `mux.Vars()`. Had some trouble testing this until I found https://github.com/gorilla/mux/pull/322/files .
While there, I extracted the setup of routes so we can just re-use that in tiller-proxy and kubeops, and while doing that I couldn't see what benefit we were getting from using negroni, and didn't want to import it in the handler module, so removed it.
> 1496 2 delete repo creds

- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/shared/AxiosInstance.test.ts
- dashboard/src/shared/AxiosInstance.ts
- dashboard/src/shared/types.ts
- pkg/agent/agent.go
- pkg/handlerutil/handlerutil.go
- pkg/handlerutil/handlerutil_test.go
The goal of this PR is to show an error that really represents the installation status when creating a new release. It gather fixes for #1464, #1508 and #1440.
Now, when there is an error when creating a release, instead of assuming the error, it shows it to the user.
Apart from showing the error, we display a message that changes depending if the error is Kubeapps related (a 500 error) or something else to help people to look for support in the right place.
These are some examples:
Wrong manifest:
Masked forbidden error:
Invalid manifest:
Missing repository:
Only when it's a forbidden error, we keep doing some additional parsing:
- fixes #1464 
- fixes #1508
- fixes #1440
> Show meaningful error when creating a release

- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- chart/kubeapps/values.yaml
- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/components/Header/NamespaceSelector.test.tsx
- dashboard/src/components/Header/NamespaceSelector.tsx
- dashboard/src/reducers/auth.test.ts
- dashboard/src/reducers/auth.ts
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
- dashboard/src/shared/AxiosInstance.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/url.ts
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
More info at #1507
Note that the default namespace has been changed from `default` to `All Namespaces` (until we have a better solution).
> Apply review comments of #1507

- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
- pkg/http-handler/http-handler.go
Explicitly delete kubeapps copy of secret when app repo with creds is deleted. Ensure normal secret deleted by propagation (tried to test, but as per comment, k8s fake client doesn't do finalizers/propagation, so tested IRL).
Fixed a couple of other things that I found with IRL testing: missing RBAC for service to create/delete secrets in its own namespace, as well as the name of created secrets: removed useless suffix of `-secret`.
Ref: #1496. Follows #1514
> Delete kubeapps copy of secret if app repo has creds.

- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/url.ts
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
- pkg/http-handler/http-handler.go
Ref #1496 . Adds a delete handler in the backend and switches the dashboard to use that. Following PR will ensure a repo secret is deleted from the Kubeapps namespace when appropriate.
While there, I've moved the use of `mux` back out to the http-handler. We'll still want to pull out the use of `http.Request` I assume.
> Add DeleteAppRepository handler and use that from frontend.

- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
Requires #1516
Finally remove all references to the HTTP request from the `pkg/apprepo`. This allow us to to be able to use the package from `pkg/chart`.
> Remove HTTP references from pkg/apprepo

- go.sum
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
Follow up of #1513
Convering `pkg/http-handler` with tests.
> Tests for pkg/http-handler

- chart/kubeapps/templates/apprepository-deployment.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- cmd/apprepository-controller/main.go
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
Ref :1496
With this change, the controller spawns cronjobs/jobs in the kubeapps namespace and successfully sync's public app repositories across all namespaces.
I also noticed that I was initially unable to delete app repositories in the kubeapps namespace, they'd stay in a deleting state with a finalizer. Turned out to be because the app repo controller was recreating cronjobs as soon as k8s was deleting them (as they were owned by the app repo).
The main changes are:
* extra cli arg when the feature flag is set, which updates the informer to receive events on app repositories cluster wide,
* Updating the controller struct to include a field for the kubeapps namespace so we can differentiate,
* Updating so that OwnerReferences are only added for resources created in the same namespace as …
> 1496 asset sync namespaces

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- cmd/tiller-proxy/main.go
- go.sum
- pkg/apprepo/apprepos_handler.go
- pkg/apprepo/apprepos_handler_test.go
- pkg/apprepo/fake.go
- pkg/apprepo/fake/apprepo-fake.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
Requires #1517
The goal of this PR is to complete the migration to the existing operations over k8s resources to the package `pkg/apprepo` (the name of the package is to be changed). The advantage of this package is that it allow callers to set a `token`. If set, it uses that token to do requests, if not it uses the backend serviceaccount.
Now the package `pkg/chart` uses this package thanks to the implementation of the methods `GetAppRepository` and `GetSecret` that use the same approach for the `token`.
The fake Handler has been moved to its own package so it can be reused.
> Move all k8s resources operations to pkg/apprepo

- cmd/kubeops/internal/handler/handler.go
- cmd/tiller-proxy/main.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Final piece of refactoring I was working on. Renaming the package `apprepo` for `kube` since it's not only related to AppRepositories but other resources like namespaces or secrets.
> Rename apprepo for kube handler

- script/chart_sync_utils.sh
The image for `kubeops` was missing from the list that is changed when generating the released chart (so it was pointing to the dev image).
> Replace kubeops image when releasing a chart

- chart/kubeapps/templates/kubeops-deployment.yaml
- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/kubeops-service.yaml
This PR adapts the manifests for Kubeops so they're consistent with the rest of manifests. It also ensure that `yamllint` doesn't complain about the syntax.
- Consistency
- Better Readability
None
> Kubeops manifests to follow YAML best practices

- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Updates the cronjob spec so that, when an app repository is from a namespace other than kubeapps, the correct secret ref is used for the repo.
Ref: #1521 .
> Use correct secret in kubeapps namespace when syncing an app repo

- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/apprepository-jobs-preupgrade.yaml
- cmd/asset-syncer/invalidate-cache.go
- cmd/asset-syncer/main.go
- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/postgresql_db_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/utils.go
Ref: #1521 
Following on from #1526, this PR adds a pre-upgrade hook which invalidates the database cache of charts. When postgres is being used, this drops and recreates the tables. For mongodb, it's currently a no-op. I've not added functionality to check for a schema change at the moment, so this will rebuild the cache on every upgrade.
IRL test:
Initial deploy dev environment and verify schema is the original (ie. without namespace field in repos table):
```
$ k -n kubeapps exec kubeapps-postgresql-0 -- sh -c 'PGPASSWORD=$POSTGRES_PASSWORD psql -d assets -U $POSTGRES_USER -c "\d repos;"'
Table "public.repos"
Column    |       Type        | Collation | Nullable |              Default
-------------+-------------------+-----------+----------+-----------------------------------
id …
```
> 1521 delete tables on upgrade

- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- cmd/asset-syncer/delete.go
- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_db_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/utils.go
Ref #1521 
Follows #1532, and updates the delete command to include the repo namespace.
Note that I've updated the schema slightly, so that both `charts` and `chartfiles` tables use a composite foreign key to the `repos` table. This means that we can let postgres handle the cascading delete (much simpler [1]) and data integrity generally, while still allowing us to reference the relationship in any table.
[1] I wrote the test first and actually found that the existing code was deleting related charts but not the chart files. Didn't look into why, but the new code fixed it.
> Update asset-syncer delete to use namespace.

- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/chart/fake/chart.go
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/fake.go
- pkg/kube/http_utils.go
- pkg/kube/http_utils_test.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Add an endpoint in the backed to validate a given AppRepository. This has been implemented as a different endpoint than the "Create" one to make it optional so users can choose to ignore errors if returned.
If the repository requires to use a proxy setting some environment variables, that's still not supported.
- Ref: #1330
I couldn't find a good way of testing the HTTP request but tested IRL.
It was necessary to move some code from the `chart` package to `kube`.
> Allow to validate apprepositories

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepository-jobs-preupgrade.yaml
I had landed the pre-upgrade template *after* the most recent kubeapps release (1.8.2) thinking that it was safe, as the next chart release would include support for the cache invalidation, but this was not a safe assumption, since we had a chart release on Monday to update the nginx image in #1536 . Since this release included the pre-upgrade template which calls a new command to invalidate cache, the upgrade fails as we have not yet released a kubeapps version including the cache invalidation (see https://kubernetes.slack.com/archives/C9D3TSUG4/p1582667703003300)
I'll land to get the release out.
I'm also keen to update our CI so that on a chart bump, we actually test the upgrade from the previous chart version and don't release.
> Hide pre-upgrade job unless feature flag set.

- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_db_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
Ref: #1521 , follows #1538 
Updates `repoAlreadyProcessed`, `updateIcon` and `fileExists` to work per-namespace, testing appropriately.
I think that's it for the PG functions, so I'll next see what's involved for mongo.
> Update repoAlreadyProcessed, updateIcon and fileExists.

- chart/kubeapps/Chart.yaml
- chart/kubeapps/requirements.lock
This PR bumps the version of MongoDB & PostgreSQL chart dependencies.
The PostgreSQL chart used a **initContainer** by default to adapt permissions. This **initContainer** was executed as a "root" container that is incompatible with some K8s distros such as [OpenShift](https://www.openshift.com/) or [VMware Tanzu Kubernetes Grid](https://my.vmware.com/web/vmware/info?slug=infrastructure_operations_management/vmware_tanzu_kubernetes_grid/1_16).
Since we're also enabling a **securityContext** by default to address the same issue, the **initContainer** is not mandatory and was disable by default at https://github.com/helm/charts/pull/20910
By bumping the PostgreSQL dependency to the latest version, we'll ensure no "root" containers are executed when installing Kubeapps using PostgreSQL as …
> Kubeapps Chart - Update PostgreSQL/MongoDB dependencies

- docs/developer/README.md
This PR fixes #1547   
`chartsvc` seems to have been renamed to  `assetsvc` and `chart-repo` to `asset-syncer`. `docs/develop/README.md` was not up-to-date.
> Fix dead links in dev documentation

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoButton.test.tsx.snap
- dashboard/src/components/Config/AppRepoList/__snapshots__/AppRepoForm.test.tsx.snap
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/reducers/repos.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/AxiosInstance.test.ts
- dashboard/src/shared/AxiosInstance.ts
- dashboard/src/shared/url.ts
Follow up of #1534 
Validate apprepositories from the dashboard before submitting them. As explained in the other PR, this validation is optional, allowing users to skip it if they think so:
Changing the spec of the sync job is not supported for the validation endpoint so the button is disabled if the template gets modified.
- fixes #1330
> Allow to validate apprepositories from the dashboard

- dashboard/src/actions/index.ts
- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/components/OperatorList/OLMNotFound.tsx
- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
- dashboard/src/components/OperatorList/index.ts
- dashboard/src/containers/OperatorsListContainer/OperatorsListContainer.tsx
- dashboard/src/reducers/index.ts
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Starting the `OperatorList` component. This PR adds the check to show a warning error if OLM is not installed. To check if it's installed we are checking if the CRD `clusterserviceversions.operators.coreos.com` exists.
- Ref #1552
> OperatorList check if OLM is installed

- chart/kubeapps/templates/apprepository-jobs-preupgrade.yaml
- chart/kubeapps/values.yaml
- script/deploy-dev.mk
- script/e2e-test.sh
Since we are going to release a new chart without a new kubeapps version, we need to ensure the cache invalidation is not run (since the subcommand is not available for current kubeapps).
At the same time, we want to ensure that it can be run optionally for dev/CI while testing current master, as it is required for the mongodb namespace work.
I had originally wanted to update the command run so it is run conditionally on whether the binary supports it, but since the container image is build from scratch, I don't have any shell to work with.
> Ensure invalidate-cache doesn't run by default.

- chart/kubeapps/templates/tests/test-assetsvc.yaml
- chart/kubeapps/templates/tests/test-dashboard.yaml
- chart/kubeapps/templates/tests/test-tiller-proxy.yaml
Signed-off-by: David Karlsen <david@davidkarlsen.com>
Use global image registry for testimages too
Consistency between resources
none
- fixes https://github.com/bitnami/charts/issues/2007
https://github.com/bitnami/charts/issues/2007
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeapps/kubeapps/1564)
> use global.registry for testimages too

- chart/kubeapps/templates/kubeops-rbac.yaml
- chart/kubeapps/templates/tiller-proxy-rbac.yaml
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Follow up of #1559 to retrieve operator icons. The backend is the one contacting the K8s API in order to get these resources using its serviceaccount. Since it's necessary to get icons from operators in any namespace this needs to be a ClusterRole/ClusterRoleBinding.
- ref #1552
> Use backend to retrieve operator icons

- cmd/tiller-proxy/internal/handler/handler.go
When err is not nil, chartMulti is nil
Signed-off-by: sayaoailun <guojianwei007@126.com>
When creating release, I got this `[negroni] PANIC: runtime error: invalid memory address or nil pointer dereference`. I checked the code and found this:
https://github.com/kubeapps/kubeapps/blob/b772c3b5d31ce06d93546b724095c8f009d42d65/cmd/tiller-proxy/internal/handler/handler.go#L64-L69
> Fix PANIC(runtime error) when creating release

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
While testing #1573 I found the icons weren't rendering because the frontend uses the icon url in the response [1], which hadn't been updated to be namespaced. Turns out there were a few others that I've also updated.
[1] Oddly, we don't have the dashboard using the similar links for the readme or schema.
Ref: #1521
> Return namespaced self-links in responses.

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
- dashboard/src/actions/apps.ts
- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/shared/Chart.ts
- dashboard/src/shared/url.ts
Follows #1567 , Ref #1521 
Updates the frontend URIs to match the new assetsvc's namespaced URIs. Currently it just uses the config kubeapps namespace so that this can land. I'll continue by making this dependent on the selected namespace, when the feature flag is set.
> Update the dashboard's assetsvc URIs to be namespaced.

- dashboard/src/components/OperatorView/OperatorHeader.test.tsx
- dashboard/src/components/OperatorView/OperatorHeader.tsx
- dashboard/src/components/OperatorView/OperatorInstallation.tsx
- dashboard/src/components/OperatorView/OperatorView.test.tsx
- dashboard/src/components/OperatorView/OperatorView.tsx
- dashboard/src/components/OperatorView/__snapshots__/OperatorHeader.test.tsx.snap
- dashboard/src/components/OperatorView/__snapshots__/OperatorView.test.tsx.snap
- dashboard/src/shared/types.ts
Add installation instructions for Operators. This is a provisional approach while we develop a proper form to create these Operators through Kubeapps. In this case, we point to the publicly available YAML that the operator hub provides:
There are two types of operators: namespaced or non-namespaced (global). This information is available in the channels that the PackageManifest specifies. The manifest published in the OperatorHub refers to the default channel so we need to check that one. 
Namespaced operators are installed in a namespace called `my-<operator>` while global are installed in the `operators` namespace.
- ref #1552
> Add installation instructions for operators

- chart/kubeapps/templates/tests/test-assetsvc.yaml
- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main.go
- script/e2e-test.sh
Last change for namespaced assetsvc to pass on CI, but I'm not landing this as it also would mean we can't release the chart for a previous version.
Other thoughts I had:
* Temporarily update the assetsvc to still respond for non-namespaced requests: this would turn in to a security issue later when we check to ensure the requestor has perms, also quite a bit of code just to work around a CI issue.
* Update the test URI to something like the live probe: fails to be a useful test at that point
* I don't think we can choose the URL conditionally because (a) it's going to depend on which app version is installed, and (b) helm template tags for testing semvers is dangerous (exits on error).
It seems like we really should be keeping a branch for the currently released chart, and if we want to …
> Update assetsvc chart test for namespaced URIs

- cmd/kubeops/main.go
- cmd/tiller-proxy/main.go
Notice that the URL in tiller-proxy/kubeops had the namespace missing.
> Fix icon URL with namespace

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/components/DeploymentFormBody/AdvancedDeploymentForm.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/components/DeploymentFormBody/__snapshots__/DeploymentFormBody.test.tsx.snap
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/components/OperatorInstanceForm/__snapshots__/OperatorInstanceForm.test.tsx.snap
- dashboard/src/components/OperatorInstanceForm/index.tsx
- dashboard/src/containers/OperatorInstanceCreateContainer/OperatorInstanceCreateContainer.tsx
- dashboard/src/containers/OperatorViewContainer/OperatorViewContainer.tsx
- dashboard/src/containers/OperatorsListContainer/OperatorsListContainer.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/types.ts
- dashboard/src/shared/url.ts
Once an operator is selected from the Catalog, render a deployment form for the custom resource, using as default the examples given as annotations:
This component reuses the same benefits than the Chart deployment (as the button to restore the default values and the tab to check the changes to be submitted).
- ref #1552
> Add form to create an operator instance

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- chart/kubeapps/values.yaml
- script/e2e-test.sh
Bitnami charts are no longer updated in the `stable` repository. This PR updates some references/links in the docs and also the `requirements.yaml` to pull the dependencies from the updated repository.
+info: https://github.com/helm/charts/issues/20969
As the `bitnami` repository already contains all the bitnami contributed charts, there are no drawbacks because:
- Changes in the docs shouldn't affect anything
- Charts included as deps are already in the "new" repository (new in terms of kubeapps `requirements.yaml`)
> Adapt kubeapps chart to stable deprecation

- chart/kubeapps/templates/assetsvc-deployment.yaml
- cmd/asset-syncer/delete.go
- cmd/asset-syncer/invalidate-cache.go
- cmd/asset-syncer/mongodb_utils.go
- cmd/asset-syncer/mongodb_utils_test.go
- cmd/asset-syncer/postgresql_utils.go
- cmd/asset-syncer/postgresql_utils_test.go
- cmd/asset-syncer/sync.go
- cmd/asset-syncer/utils.go
- cmd/asset-syncer/utils_test.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main.go
- cmd/assetsvc/mongodb_utils.go
- cmd/assetsvc/postgres_db_test.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
- cmd/assetsvc/utils.go
- pkg/dbutils/dbutilstest/dbutilstest.go
- pkg/dbutils/dbutilstest/mgtest/mgtest.go
- pkg/dbutils/dbutilstest/pgtest/pgtest.go
- pkg/dbutils/mongodb_utils.go
- pkg/dbutils/postgresql_utils.go
- pkg/dbutils/postgresql_utils_test.go
Ref #1521 . Gives the assetsvc knowledge of the kubeapps namespace and updates `getPaginatedChartList` so that it returns charts in a specific namespace together with those from the kubeapps (global) namespace.
While there, found, tested and fixed another issue related to the SQL params (need to use dynamic numbering for the params).
The asset-sync commands are updated to store the kubeappsNamespace but this is not yet set in the environment or used, though it may enable us to stop the frontend from needing to know the kubeapps namespace.
> Return charts for specific namespace and global namespace.

- dashboard/src/actions/operators.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/shared/types.ts
Clicked "merge" too soon in #1584 by mistake :/
> Review from #1584

- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/containers/CatalogContainer/CatalogContainer.tsx
- pkg/auth/auth.go
Ref #1521, follows #1592 so that the dashboard always includes the current namespace when requesting the chart catalog.
This can be done (in fact, needs to be done) without the feature flag switch because in the previous PR the assetsvc was updated to check access to the given namespace before returning the catalog, and Kubeapps users may not have access to kubeapps own namespace. It works because the assetsvc returns both charts for the given namespace together with the global ones (from kubeapps own namespace) as long as the user can access the given namespace.
In real-life testing showed that the AuthGate was failing when it should pass, turned out to be that the resource name was "secrets" rather than "Secret" :/ (even though `auth can-i` works with either).
TODO: Still need to fix up …
> Update fetchCharts to use namespace from UI

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/containers/OperatorInstanceViewContainer/OperatorInstanceViewContainer.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
Follow up of #1594. Reuses the ConfirmDialog component to delete an Operator instance:
- ref #1552
> Operator instance delete button

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main_test.go
- cmd/kubeops/main.go
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- pkg/auth/auth.go
- pkg/auth/authgate.go
- pkg/auth/fake/auth.go
- script/deploy-dev.mk
Ref #1521. A lot of churn, but only three real changes:
1. Remove the AuthGate from tiller proxy (as discussed yesterday, tiller-proxy checks the user auth explicitly in the handlers), which allows us to restrict it to the assetsvc use-case. (EDIT: CI showed that this also required removing the implicit passing of values via the request context which the AuthGate set, now removed, as it's not particularly type-safe).
2. Update AuthGate to allow access to the global repositories via the assetsvc (ie. in kubeapps' own namespace)
3. Ensure the assetsvc uses the namespace of the chart when rendering results, rather than the requested namespace for the query, since we're including the global charts in a request for specific namespaces and we need icons and other links to match the asset. …
> Use namespace from the chart when rendering responses.

- cmd/assetsvc/handler.go
- cmd/assetsvc/handler_test.go
- cmd/assetsvc/main_test.go
- cmd/kubeops/main.go
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- dashboard/src/actions/charts.test.tsx
- dashboard/src/actions/charts.ts
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/containers/CatalogContainer/CatalogContainer.tsx
- pkg/auth/auth.go
- pkg/auth/auth_test.go
- pkg/auth/authgate.go
- pkg/auth/fake/auth.go
- script/deploy-dev.mk
Ref #1521 This PR updates the AuthGate used by the assetsvc and tiller-proxy to verify whether the user has access to a particular namespace (or cluster-wide access to all namespaces), rather than whether they've valid credentials to authenticate.
It can't land as is (and will fail CI), as I need to update the frontend so that the namespace is always included (even if we're not running with the feature flag) so that users who do not have access to the kubeapps namespace can still view the catalog.
> Enable authz check for specific namespace.

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/CustomResourceListItem.tsx
- dashboard/src/components/AppView/AppNotes.scss
- dashboard/src/components/AppView/AppNotes.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/components/OperatorInstance/index.ts
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.test.tsx
- dashboard/src/components/OperatorInstanceForm/OperatorInstanceForm.tsx
- dashboard/src/containers/OperatorInstanceViewContainer/OperatorInstanceViewContainer.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/url.ts
Draft for the OperatorInstance view:
For the moment we are showing just some basic info. The current status (as a YAML) and the installation values along with a Card with basic information about the CRD and the ClusterServiceVersion. The plan is to keep adding things but in other PRs to facilitate the review. The next things I plan to add are:
- Make the Delete button works (currently is a dummy button)
- Retrieve resources associated to the operator instance and show the same things than for other apps:
- Application status (worklads running)
- Resource tables.
We should also be able to modify the instance but I will leave that for later.
- ref #1552
> OperatorInstance view

- cmd/tiller-proxy/README.md
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- pkg/auth/auth.go
Follow-up of #1596 (ref #1521), this PR:
1. Removes the `--disable-auth` flag and functionality
2. DRY up the tiller-proxy authz in the handlers
3. Removes the `Checker.Validate()` method from the interface, as its no longer used after 1596.
> 1521 remove disable auth check

- dashboard/src/actions/kube.test.tsx
- dashboard/src/actions/kube.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/__snapshots__/ResourceTableItem.test.tsx.snap
- dashboard/src/components/AppView/ResourceTable/__snapshots__/ResourceTable.test.tsx.snap
- dashboard/src/components/ApplicationStatus/ApplicationStatus.test.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/containers/CatalogContainer/CatalogContainer.tsx
- dashboard/src/reducers/kube.test.ts
- dashboard/src/reducers/kube.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/ResourceAPIVersion.ts
- dashboard/src/shared/ResourceKinds.ts
- dashboard/src/shared/ResourceRef.test.ts
- dashboard/src/shared/ResourceRef.ts
- dashboard/src/shared/types.ts
Show the ApplicationStatus along with the AccessURL table and all the other resource tables:
The CRD doesn't have a specific reference to the resources it will create, instead it just list the different Kinds that it will create (e.g. Service, Deployment). Because of that, we need to list all those resources in the given namespace and filter out the ones that doesn't have the Custom Resource as owner.
There are several minor things that I found while working on this that require special attention:
- When getting and watching a list of resources, first you get the resource list (e.g. DeploymentList) but then, you receive individual responses for each of the resoucers (e.g a Deployment) not the full list again.
- When getting a list (e.g. DeploymentList) the resources within the list …
> Add ApplicationStatus and resource tables to the OpeartorInstance

- dashboard/src/actions/charts.ts
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
- dashboard/src/reducers/charts.test.ts
- dashboard/src/reducers/charts.ts
- pkg/auth/authgate.go
The simple part of this PR was just switching the `authGate` to return a Forbidden rather than Unauthorized when a user requests the charts for a namespace to which they don't have access. This stopped the frontend from logging out, but a little more work was needed to display an error with an action the user can take.
This issue does not arise normally, because we already check whether a user has access to a namespace when selecting the namespace (ie. before we even attempt to get charts for the namespace), but because we currently use `All Namespaces` as the default when a user logs in, even though the user may not have access to resources across all namespaces, the issue appears when logging in as such a user and then selecting the catalog.
The correct solution, IMO, is to select the …
> Avoid re-auth on All Namespaces when selecting catalog

- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
Small follow-up to #1603 . The links from the app repo lists missed being updated to match the new route.
> Fix catalog links in app repo page.

- chart/kubeapps/values.yaml
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
- docs/user/private-app-repository.md
- integration/use-cases/create-registry.js
- script/deploy-dev.mk
- script/e2e-test.sh
Enables `allowNamespaceDiscovery` and `reposPerNamespace` to be on by default (as well as the invalidateCache which is required whenever we release a new Kubeapps version).
Updates the documentation for private app repos to match.
If we don't have any separate chart releases in the next few days, it might be good to land this and test it locally before releasing. Happy either way.
> Use per-namespace app repositories by default

- chart/kubeapps/templates/apprepository-rbac.yaml
- integration/use-cases/create-registry.js
Follow up of #1609
As explained there, the current test is giving a false positive in master. The reason is quite tricky. With the changes added in the RBAC templates, we were removing the blank line at the end of apprepository-rbac.yaml. This causes that the `Role` affected (`repositories-write`) was not being created and it fails quietly (note the `create---`):
```yaml
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
name: kubeapps2-repositories-write
rules:
- apiGroups:
- kubeapps.com
resources:
- apprepositories
verbs:
- "*"
- apiGroups:
- ""
resources:
- secrets
verbs:
- create---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
```
So giving write access to the operator serviceaccount was not doing anything. Fun bug...
> Restore test, fix apprepository-rbac

- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.test.tsx
- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/components/AppView/AccessURLTable/__snapshots__/AccessURLTable.test.tsx.snap
- dashboard/src/components/ApplicationStatus/ApplicationStatus.test.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.tsx
Two small bug fixes:
- When there are no workloads, say that instead of "Ready" since we cannot ensure that the application is actually ready.
- When there are no URL items, skip the URL table
Before these changes:
After:
- ref #1552
> Show proper message when there are no workloads or URLs

- dashboard/src/components/AppView/ResourceTable/ResourceItem/OtherResourceItem/OtherResourceItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/OtherResourceItem/OtherResourceItem.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/OtherResourceItem/__snapshots__/OtherResourceItem.test.tsx.snap
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/__snapshots__/ResourceTableItem.test.tsx.snap
- dashboard/src/components/AppView/ResourceTable/ResourceTable.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/shared/ResourceAPIVersion.ts
- dashboard/src/shared/ResourceKinds.ts
- dashboard/src/shared/ResourceRef.test.ts
- dashboard/src/shared/ResourceRef.ts
Add the Other Resources table to the Operator view to complete the view:
Note that even though we are just interested on knowing the name of the resources, we need to request the list of resources (in a namespace) and filter out.
There are a few tricky things in this PR:
1. Some resources listed are not shown later. For example, an Operator may define Pods as one of the resource it creates but since those pods are not directly linked to the Operator CRD (the Deployment is instead), these resources are not shown in the table.
2. Apart from the current workaround of guessing the apiVersion/plural, I needed to differentiate between namespaced and non-namespaced resources. This is becoming too hacky... but would work now for the alpha release.
To avoid any issues with the current approach for …
> Add OtherResources table to the operator view

- dashboard/src/actions/kube.test.tsx
- dashboard/src/actions/kube.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/StatefulSetItem/StatefulSetItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/StatefulSetItem/StatefulSetItem.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.test.tsx
- dashboard/src/components/ApplicationStatus/ApplicationStatus.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
- dashboard/src/shared/ResourceAPIVersion.ts
- dashboard/src/shared/ResourceKinds.ts
- dashboard/src/shared/ResourceRef.test.ts
- dashboard/src/shared/ResourceRef.ts
Fixes a couple of issues I've found trying different operators (at least the issues I could fix):
- `status.replicas` may not be defined for deployments/statefulsets so use the one in the spec instead.
- Avoid using the resource name defined in the Operator CRD since some operators use it wrongly (instead of the name of the resource they put something like `A Kubernetes Service`).
- Ref #1552
> Minor bug fixes

- chart/kubeapps/values.yaml
- integration/use-cases/create-registry.js
When I landed #1604 the other day, switching the default to use per-namespace app repos, it was with the thought that there was only a few small bugs to iron out, but there was quite a bit still missing, so switching off until I resolve that so that master isn't broken (CI doesn't show this only because it doesn't test per-namespace repos yet).
> Don't yet default to using repos per namespace

- chart/kubeapps/README.md
- docs/architecture/overview.md
- docs/user/getting-started.md
`docs/architecture/overview.md`
Fixed typos
`docs/user/getting-started.md`
`chart/kubeapps/README.md`
Added clearer separation of helm 2 and 3 commands. Add missing command.
It makes the docs clearer. Also adds a missing command.
None
N/A (let me know if you think this warrants creating an issue...)
N/A
> Update docs for a few typos and helm commands

- chart/kubeapps/templates/NOTES.txt
Updates the NOTES.txt for the Helm notes to match the getting started for port-forwarding.
Switching port forwarding from selecting the first pod to forwarding using the service. It should match the following:
```
kubectl port-forward -n kubeapps svc/kubeapps 8080:80
```
```
Kubeapps can be accessed via port 80 on the following DNS name from within your cluster:
kubeapps.kubeapps.svc.cluster.local
To access Kubeapps from outside your K8s cluster, follow the steps below:
1. Get the Kubeapps URL by running these commands:
echo "Kubeapps URL: http://127.0.0.1:8080"
kubectl port-forward --namespace kubeapps service/kubeapps 8080:80
2. Open a browser and access Kubeapps using the obtained URL.
> k -n kubeapps get svc
NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP …
```
> Update helm notes to match getting started for port-forward

- dashboard/src/components/Card/CardIcon.scss
Make the subIcon a bit smaller so it fits within the banner section when it appears.
Before:
After:
> Reduce subIcon size to fit in banner

- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
One doc and the helm chart still say 2.10+, but they should be updated to 2.14+ https://github.com/kubeapps/kubeapps/issues/1185
Updated helm versions
#1185
> Update outdated helm versions to 2.14+

- dashboard/src/components/OperatorList/OperatorList.scss
- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
- dashboard/src/components/OperatorList/__snapshots__/OperatorList.test.tsx.snap
Example of selecting "Database":
Selecting multiple categories act as an "OR". For example: Selecting Database and Security would show Operators of both categories.
- ref #1552
> Add a Categories section in the Operator list

- docs/user/using-an-OIDC-provider.md
When cookies become very big they might get cut up when using a reverse
proxy. This can easily happen when using Azure Active directory so we
should add a note about this in the setup instructions for this.
This is only a documentation change and follows the same format that is present in the document.
> Add note about increasing `proxy_buffer_size` with nginx and Azure.

- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/CatalogItem.test.tsx.snap
The button that takes to the catalog in the Application List is broken due to the change in the routes.
The same happens for the link to the repo in the cards of the catalog.
> Fix broken link in Deploy App buton

- chart/kubeapps/README.md
* Removes $ from code commands because it makes copy-pasting easier. Otherwise you have to make sure you skip the $, or you get an error (at least on my mac with zsh).
* Swaps `console` type to `bash` type for consistency and also because console is only really useful if you're showing commands to be run and the output to distinguish between them.
See above
> Update docs code blocks chart/kubeapps/readme

- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
Another couple of minor fixes:
- In the catalog, if a repository is selected we were still showing Operator instances
- When setting a value in the search bar that doesn't match any element, we were showing the MessageAlert (instead that showing an empty list).
> Fix repo filter in Catalog

- dashboard/src/actions/operators.test.tsx
- dashboard/src/actions/operators.ts
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
When loading the Operators view, the error and "No operators found" messages are shown for a bit:
This is because we are using the same isFetching properties for several things and once the first thing is fetched the flag is set to false (wrongly). This PR fixes that so `isFetching` is set to true only when everything has been fetched.
- ref #1552
> Fix temporary error message for Operators

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
Dashboard changes to send the chart namespace (`AppRepositoryResourceNamespace`) with the `App.create` and `App.Upgrade` requests.
Following PR will add the backend change.
> Fix namespaced chart deploy - dashboard

- dashboard/src/components/OperatorList/OperatorList.test.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
When the filter didn't match any Operator, the Categories column was disappearing, which caused the buttons there to be erased as well. This PR fixes that:
- ref #1552
> Include the Categories filter even if the result is empty

- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Fixes #1655 . With commit d5b277c, while adding the app repo validation of #1534, we inadvertently caused an app repo secret to be created without the owner reference UID.
This was because, prior to that change, the secret was not instantiated until we had created the repo with its UID, wherease after the change, the secret and app repo are instantiated in memory together before the app repo is actually created, so the secret ends up not knowing the UID of the app repo.
This was not caught by our tests because the `client-go` test fake does not set UIDs when creating objects (by default, though apparently we could add a reactor to fake this).
> Ensure AppRepo secret has owner references UID set.

- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
When there are less than 4 cards in the catalog, these cards shrink 
We need to set the CSS properties to fill the whole row.
> Fix card shrink in Catalog

- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/ChartView.tsx
I was trying to deploy chartmuseum with Kubeapps and it no longer contains `sources` in the chart information which caused a crash in the application.
> Omit chart sources if they don't exist

- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/chart/fake/chart.go
- pkg/handlerutil/handlerutil.go
- pkg/kube/kube_handler.go
Updates ChartDetails to include both the app repo namespace as well as the user token from the request, so that requests can be made on behalf of the user for the app repo in the specified namespace.
Ref #1521.
> Fix namespaced chart deploy backend

- chart/kubeapps/templates/apprepository-rbac.yaml
- docs/user/access-control.md
- docs/user/manifests/kubeapps-local-dev-users-rbac.yaml
- docs/user/private-app-repository.md
Renames the apprepositories-read cluster role so that it is no longer controller specific, and can be used to assign users to the role in specific namespaces. (Also removed the 'update' verb from this, not sure why it was there given the name, seems to work without it, but I assume the controller needed to update app repo resources at some point?).
Similarly, add a related apprepositories-write cluster role (unbound).
Updates the dev setup (which I use) so that the `kubeapps-operator` user can create app repos in the `kubeapps-user-namespace`, while the `kubeapps-user` user can only read them (so can deploy).
Include usage of these clusterroles in the docs.
Ref: #1521
> Update RBAC roles for apprepositories to be clusterroles so they can be used in many namespaces.

- cmd/apprepository-controller/pkg/apis/apprepository/v1alpha1/types.go
- pkg/http-handler/http-handler.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Ref: #1522 
Enables AppRepositories to be created with a list of docker registry secrets which should be included for matching registries.
Also ensures that a global AppRepository is not able to be created (or validated) with docker registry secrets.
> Docker registry secrets

- pkg/agent/docker_secrets_postrenderer.go
- pkg/agent/docker_secrets_postrenderer_test.go
Ref #1617. Implements adding imagePullSecrets to Pod resources (only - I'll update to handle other resources which also include pod templates).
> Implement adding imagePullSecrets to Pod resources.

- go.mod
- pkg/agent/docker_secrets_postrenderer.go
- pkg/agent/docker_secrets_postrenderer_test.go
Ref: #1617 . Updates the imagePullSecret injection in the post renderer for two cases:
- Dockerhub images use "docker.io" as the registry domain in the image ref (docker's `reference` library even adds it as such), while the credential in docker configs must be keyed with "https://index.docker.io/v1/".
- general registry domains in the docker credentials can be listed with or without an explicit protocol (https), so we update to append the imagePullSecret as long as the domain itself matches.
> Handle dockerhub secrets special case. Allow optional protocol.

- pkg/agent/docker_secrets_postrenderer.go
- pkg/agent/docker_secrets_postrenderer_test.go
Just updates the post renderer to support getting the pod spec from all other resources which includes pod specs as a template.
> Update postrenderer to support pod spec templates.

- pkg/agent/docker_secrets_postrenderer.go
- pkg/agent/docker_secrets_postrenderer_test.go
Based on [feedback from previous PR](https://github.com/kubeapps/kubeapps/pull/1678#discussion_r411754535), this updates to handle both CronJobs and all resource list types.
Ref: #1617
> Postrenderer support resourcelists

- cmd/kubeops/internal/handler/handler.go
- go.mod
- go.sum
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/docker_secrets_postrenderer.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/chart/fake/chart.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
Adds a function to create the map of docker registry servers to secret names and passes that in during Install and Upgrade functions.
I had to expose `kube.Handler`, but it was actually odd that it wasn't already exposed (it's an interface with public methods, and we use the public methods already). I haven't yet checked other uses of this, but will do. (I'll fix the errors).
With this, I hope to test deploying with a private repo tomorrow, which together with your UI work, might mean we can have a video demo or similar for the end of the week!
Ref: #1617
> Generate and use secretsPerDomain.

- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/components/UpgradeForm/__snapshots__/UpgradeForm.test.tsx.snap
In the upgrade form, we were recalculating the "deployed values" (the values stored in the release plus the comments) with every keystroke which caused a big delay when writing in the advanced form. This PR fixes that calculating that value just once.
- fixes #1667
> Avoid applying modifications when rendering

- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/shared/schema.test.ts
- dashboard/src/shared/schema.ts
So there are two issues when parsing a YAML that have `.` and `/`:
- `.` were interpreted as objects so if the key was `a.b`, it was interpreted as `a: {b:}`
- `/` is escaped as `~1` to avoid interpreting them as objects and we were not replacing that back.
I have modified our code to simply use `/` as the notification for objects (e.g. `a.b.c` -> `a/b/c`) which is the default for JSON patch. I have also added a step to unescape the character `~1`.
- fixes #1683
> Fix YAML parsing for keys with dots and slashes

- dashboard/src/components/Config/AppRepoList/AppRepoAddDockerCreds.tsx
I learned the hard way that `https://index.docker.io/v1` is not valid (it requires the trailing `/`), should we enforce that?
> Minor fixes in the docker-credentials form 

- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/values.yaml
These changes allow overriding the OAuth Login and Logout URIs which is useful when deploying the chart under a sub path.  For my deployment, I set the ingress to rewrite urls and change a few other values to properly know about the sub path.  I've included some sample values below however the sample values would need extra configuration to fully configure the authProxy service.
- Relevant Sample Values:
```
authProxy:
enabled: true
additionalFlags:
- -redirect-url=https://<hostname>/kubeapps/oauth2/callback
- -cookie-path=/kubeapps
oauthLoginURI: /kubeapps/oauth2/start?rd=/kubeapps/
oauthLogoutURI: /kubeapps/oauth2/sign_out
ingress:
enabled: true
annotations:
nginx.ingress.kubernetes.io/rewrite-target: /$2
extraHosts:
- name: <hostname>
path: /kubeapps(/|$)(.*)
extraTls:
- hosts:
- …
```
> Added config for OAuth login/logout URIs

- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
Fixes #1675 .
Without this change, the dashboard assumes the 403 response from the API server is from the auth proxy, since one of the ways we detect an api server response is via the json data and without this change the app repo creation (and other methods) are not returning the expected json data for errors:
With this change, the expected error is shown with the required RBAC:
> Return json responses for proxied requests to API server.

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/reducers/repos.test.ts
- dashboard/src/reducers/repos.ts
- dashboard/src/shared/types.ts
Requires #1705 
I have enabled the modify button which was mostly ready unless two minor things:
- I needed to re-fetch secrets in case the modification modify any of the related app repo secrets
- I have added the updatedRepo event in the reducer to update the updated app repo in the state.
Since the reducer for app repos didn't exist, I have covered part of that file with unit tests.
- fixes #1666
> Enable modify button for app repositories

- .circleci/config.yml
- integration/use-cases/operator-deployment.js
- script/e2e-test.sh
Fix the GKE tests in master. There are two problems for the Operator test:
- The OLM cannot be installed in GKE 1.14, the manifest fails to be installed so we need to skip the test in this build.
- The newer image that I am using to avoid the issue for limits too low doesn't work for GKE 1.15 so I need to use the default manifest and let the pod to be killed several times because of OOM until it populates the operator catalog (which is slow).
[EDIT]
At the end I had to disable the test also for GKE 1.15, it was too flaky because the operatorhub populator pod gets continuously restarted.
- ref #1708
> Fix operators test for GKE

- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/ChartView.tsx
This PR ensure the "Maintainers" section is omitted ChartView when this field doesn't exist in the corresponding **Chart.yaml**.
Before these changes:
After these changes:
None that I'm aware of
- Related to https://github.com/kubeapps/kubeapps/issues/1620
> Omit maintainers if they don't exist

- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorNew/OperatorNew.test.tsx
- dashboard/src/components/OperatorNew/OperatorNew.tsx
- dashboard/src/components/OperatorView/OperatorHeader.test.tsx
- dashboard/src/components/OperatorView/OperatorHeader.tsx
- dashboard/src/components/OperatorView/OperatorView.test.tsx
- dashboard/src/components/OperatorView/OperatorView.tsx
- dashboard/src/components/OperatorView/__snapshots__/OperatorView.test.tsx.snap
- dashboard/src/containers/OperatorInstanceCreateContainer/OperatorInstanceCreateContainer.tsx
- dashboard/src/containers/OperatorInstanceUpdateContainer/OperatorInstanceUpdateContainer.tsx
- dashboard/src/containers/OperatorInstanceViewContainer/OperatorInstanceViewContainer.tsx
- dashboard/src/containers/OperatorNewContainer/OperatorNewContainer.tsx
- dashboard/src/containers/OperatorViewContainer/OperatorViewContainer.tsx
- dashboard/src/containers/OperatorsListContainer/OperatorsListContainer.tsx
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Operators.ts
If an Operator has been already deployed in a namespace, disable the "Deploy" button to avoid confusion.
- fixes #1703 
There is a bigger change in the State for operators: before, the `errors` struct was shared between the different resource types (`errors.fetch` could be an error fetching operators or clusterserviceversions) so I had to expand it in order to ignore the missing error when requesting the CSV in the OperatorView.
> Disable "Deploy" button for deployed Operators

- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceItem/ResourceTableItem.tsx
When the `kind` of a resource is not available (for example, when receiving an element of a list), we rely in the `selfLink` of the component to discover its type. We were looking in the whole `selfLink` which caused that if a resource is deployed in the namespace "services" or is called "services" it would be treated as a service. To fix that we just look for the place in which the type is located.
- fixes #1695
> Fix selfLink assumption

- chart/kubeapps/README.md
Update and improve wording of exposing K8s API warning. I just noticed while working on the multi-cluster proposal that we'd not updated the wording since switching to auth-proxy and ensuring the APi is only available for authenticated request via the auth-proxy.
> Update and improve wording of exposing K8s API warning.

- chart/kubeapps/templates/apprepositories.yaml
We had added this to ensure that during installation of Kubeapps, the
creation of the app repository resources wouldn't trigger a sync job
to run before the upgrade job updates the schema. But one case we did
not anticipate is that if the installation is held up (network issues
or similar) and the helm install fails, the resources won't be present.
I think it's better to ensure they are always present so that the sync
job can eventually sync them (and update to safely migrate the schema
rather than recreating it - as per #1560).
As above
If the helm install command fails because a post-install job cannot run (yet), all resources are still present on the cluster.
AppRepository creation could trigger a sync job before the backend schema is recreated, which could mean another cycle until the …
> Remove post-install annotation for apprepositories

- chart/kubeapps/templates/kubeapps-frontend-config.yaml
Prep work so that we can soon route /api/clusters/cluster-name/ from
configuration to the correct k8s cluster. Adds a default cluster which
uses the local api server (to the pod), while leaving the existing
location for temporary backwards compat.
Ref: #1752
> Add a shared k8s-api-proxy.conf and default cluster location.

- chart/kubeapps/templates/kubeapps-frontend-config.yaml
- dashboard/src/actions/kube.test.tsx
- dashboard/src/components/AppView/ResourceTable/__snapshots__/ResourceTable.test.tsx.snap
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx
- dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx
- dashboard/src/containers/ResourceItemContainer/ResourceItemContainer.test.tsx
- dashboard/src/containers/helpers/index.test.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/Operators.test.ts
- dashboard/src/shared/Secret.test.ts
- integration/use-cases/create-private-registry.js
Ref #1752, follows #1757 
Updates the dashboard to use a named cluster endpoint for the k8s api (currently just using the default cluster).
> Update dashboard to use /api/clusters/default instead of /api/kube.

- chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
- cmd/asset-syncer/mongodb_utils.go
- pkg/dbutils/mongodb_utils.go
This job creates the db secret (if it hasn't been created at installation time) and cleans up the database. As far as I can tell none of these processes are necessary when installing the app. Related to #1754
> Run postupgrade job only when upgrading

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
First part of #1761 . Follow up will enable adding the mounted file to the pod when additional clusters defined.
> Update kubeops service to include arg for additonal cluster config.

- docs/user/offline-installation.md
Follow up of #1751. Documentation of how to install Kubeapps in an air-gapped environment.
> Add documentation about how to install Kubeapps offline

- docs/user/getting-started.md
Ensure people are aware that creating service-tokens for user login is only for easy demoing of Kubeapps, but SSO should be used for any real setup.
> Clarify token usage in getting started doc.

- dashboard/src/components/ChartView/ChartVersionsList.test.tsx
- dashboard/src/shared/url.ts
Signed-off-by: sayaoailun <guojianwei007@126.com>
change the dashboard to fix bug `chart version link`
When I click on the Chart Versions, I get 404.
I check the code, and find this:
https://github.com/kubeapps/kubeapps/blob/ea227231b7701594bf43b60c94fee51d3d7d55af/dashboard/src/shared/url.ts#L6-L9
So I made this change.
> Fix bug -> chart version link

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/internal/handler/handler_test.go
- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
Not yet tested IRL, I still need to check that the `kubehandler` here
works as expected or requires a separate in cluster config etc., but
this should maintain the current behaviour for non-multi-cluster.
> Enable kubeops to talk to other configured clusters.

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/BasicDeploymentForm.tsx
- dashboard/src/shared/schema.ts
- dashboard/src/shared/types.ts
- docs/developer/basic-form-support.md
This PR adds support for multiple conditions to hide an element on basic forms.
As it's explained in the developer docs, developers will be able to use an array of conditions, and the conditional operator to consider an element to be hidden.
More possibilities for chart developers to create their values.schemas.json
None that I'm aware of
- fixes https://github.com/kubeapps/kubeapps/issues/1336
> Add support to multiple conditions to hide an element on basic forms

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/internal/handler/handler_test.go
- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
- pkg/chart/chart.go
- pkg/http-handler/http-handler.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Moves NewClusterConfig (and tests) into the shared kube package so that
it can be used by other packages. Updates the AsUser helper (which
returns clientsets) to use NewClusterConfig, requiring a call-signature
change.
Also updates NewClusterConfig so as to not re-use default clusters TLS config if none configured for the selected cluster.
I'll followup with a related small fix to ensure we don't swallow errors
in AsUser.
Ref: #1761
> Update kube package handlers to be multi-cluster aware.

- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/main.go
- dashboard/public/config.json
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.test.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Config.ts
Removes the reposPerNamespace feature flag.
Removes related redundant code now that we've released the feature.
Leaves the flag available for the apprepository controller binary though
it does nothing (and can be removed later when people have upgraded).
> Remove reposPerNamespace feature flag.

- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/HeaderLink.tsx
- dashboard/src/components/Header/NamespaceSelector.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.test.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/containers/AppListContainer/AppListContainer.tsx
- dashboard/src/containers/ErrorBoundaryContainer/ErrorBoundaryContainer.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/containers/RoutesContainer/RoutesContainer.tsx
- dashboard/src/reducers/namespace.test.ts
- dashboard/src/reducers/namespace.ts
- dashboard/src/shared/url.ts
First of several PRs which will transition existing relevant routes in the UI to
be cluster-aware, defaulting to the "default" cluster so as to not break
the existing experience.
Ref: #1762
> Move AppListView route to be cluster-aware.

- .circleci/config.yml
- script/e2e-test.sh
The goal of this PR is to add a basic test to ensure we don't break the upgrade process (at least with the flags we use in our CI system). To avoid having another build or run the upgrade test for every build I am adding the env var `TEST_UPGRADE` to the PostgreSQL + Helm 3 scenario (the "recommended" setup).
The test is just installing the `kubeapps` chart from the `bitnami` repository and upgrading it afterwards with the status of the current `chart` folder.
Breaking changes in the chart will be noticed.
- fixes #1544
> Test chart upgrade

- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Catalog/CatalogItem.test.tsx
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
It's not perfect - there's more that could be DRY'd up and encapsulated,
but with this change you can actually use TypeScript's type system to
ensure the correct fields are present.
I've not done an IRL test, this is just to demo the thought.
Fixes #1803 (maybe). Ref #1762
> Use two separate types for IChartCatalogItem and IOperatorCatalogItem.

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Config.ts
Initializes the additional clusters redux state when receiving the application configuration.
Part of #1762
> Initialize the additional clusters state when receiving config.

- dashboard/src/actions/apps.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- script/cluster-kind.mk
As per #1815, the call used to getAppUpdateInfo was still using the
kubeapps namespace. Similarly, although the checkChart function was
passed the repo namespace, it was not used.
Fixes #1815.
I'll follow-up with the CI change.
> Fix non-namespaced calls during release upgrade.

- chart/kubeapps/templates/tests/test-assetsvc.yaml
- integration/use-cases/default-deployment.js
- integration/use-cases/missing-permissions.js
- script/e2e-test.sh
After adding the `upgrade` test, the scenario in which that test is run (helm3+pg) fails many times. After a bit of investigation I noticed that since we are running the install plus the upgrade in a short time, the `upgrade` hook may finish after the repos are populated. This causes that the catalog doesn't include the chart required for the tests.
This PR, adds:
- A retry for the assetsvc test so if the populate job are still running, we retry a few times.
- Use `bitnami` charts rather than `stable` (which is being deprecated).
- Ensure that the sync job is run and finishes after the upgrade.
> Fix flaky chart tests

- dashboard/src/actions/charts.ts
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/shared/Chart.ts
- dashboard/src/shared/Config.test.ts
Just a couple of small changes I wanted to check from #1823.
> Small adjustments to #1823

- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/AppListItem.test.tsx
- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/AppView/AppControls/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls/AppControls.tsx
- dashboard/src/components/AppView/AppControls/UpgradeButton.test.tsx
- dashboard/src/components/AppView/AppControls/UpgradeButton.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/AppView/ChartInfo.test.tsx
- dashboard/src/components/AppView/ChartInfo.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/shared/url.ts
- script/libtest.sh
Continues url updates for cluster requirement. Ref #1762 .
Starting to get some duplication of test setup, as the function components which use state need providers etc. I looked at options for creating the shared code, but `react-scripts` doesn't support the jest `setupFiles` option, so it might just be a separate `src/helpers.test.tsx` exporting some functions like `getWrapper(state, component, props)`? What do you think? (not for this PR, but I will cleanup the dups once decided).
The other thing that I had to wrangle here is that once wrapped in a provider, it seems that even our class-based components are no longer classes after wrapping - at least, I had to remove calls to `wrapper.state()` (also tried `wrapper.find(ComponentName).state()`) as jest kept failing saying that `state()` …
> Update url.app.apps.{get|upgrade} with required cluster arg.

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/components/Catalog/CatalogItem.test.tsx
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/CatalogItem.test.tsx.snap
- dashboard/src/components/ChartView/ChartHeader.test.tsx
- dashboard/src/components/ChartView/ChartHeader.tsx
- dashboard/src/components/ChartView/ChartView.test.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoListItem.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/ChartViewContainer/ChartViewContainer.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/url.ts
Follows #1833 . Ref #1762 .
Only unexpected here was the lack of ability to use `shallow` when rendering a connected component, and hence unable to do a small targeted snapshot.
A few fly-by fixes for non-typed data.
> Updates url.app.{catalog|repo} to require the cluster arg.

- dashboard/Dockerfile
- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/ConfigLoader/ConfigLoader.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.test.tsx
- dashboard/src/reducers/cluster.test.ts
The build (and hence CI) was still able to pass even though there were typescript errors (compile-time type checking) because although we'd updated to check prettier during the build, I missed the ts-compile-check.
Now the build fails if a typescript check fails - independently of an individual contributors setup (ie. it's not dependent on whether or not we run husky pre-commit hooks).
> Ensure that image building fails if typescript check fails.

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/Catalog/CatalogItem.tsx
- dashboard/src/components/Catalog/__snapshots__/CatalogItem.test.tsx.snap
- dashboard/src/components/ChartView/ChartVersionsList.test.tsx
- dashboard/src/components/ChartView/ChartVersionsList.tsx
- dashboard/src/components/ChartView/ChartView.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- dashboard/src/shared/url.ts
- script/cluster-kind.mk
Also then begins updating the backend url helpers - starting with `shared/App.create` to require cluster, (though I'm not yet using it in the URL, since the tests in this PR verify that the new `url.kubeops.releases` helper maintains the same endpoints.
Follows #1835, Ref: #1762
> Update url.app.charts.{get|version} to require cluster arg.

- cmd/tiller-proxy/main.go
- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.test.tsx
- dashboard/src/components/AppView/AppControls/RollbackButton/RollbackButton.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.tsx
- dashboard/src/containers/AppListContainer/AppListContainer.tsx
- dashboard/src/containers/AppUpgradeContainer/AppUpgradeContainer.tsx
- dashboard/src/containers/AppViewContainer/AppViewContainer.tsx
- dashboard/src/containers/RollbackButtonContainer/RollbackButtonContainer.tsx
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- dashboard/src/shared/url.ts
Follows #1837 Ref #1762 
Updates all calls related to the kubeops backend to require and use the cluster argument.
Last but not least will be the update to the shared backend API.
> Update calls to the kubeops service to require cluster.

- dashboard/src/components/Header/ContextSelector.scss
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.v2.scss
- dashboard/src/components/Header/Header.v2.tsx
- dashboard/src/components/js/hooks/useOutsideClick/index.js
- dashboard/src/components/js/hooks/useOutsideClick/useOutsideClick.js
- dashboard/src/components/js/hooks/useOutsideClick/useOutsideClick.test.js
Context Selector for Clarity UI. It allows to select the cluster and the namespace used.
- ref #1354 
Note that the `cluster` selector is still not working. That's a WIP in a different branch.
> Context Selector

- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/Header.v2.tsx
- dashboard/src/components/Header/NamespaceSelector.test.tsx
- dashboard/src/components/Header/NamespaceSelector.tsx
- dashboard/src/containers/AppNewContainer/AppNewContainer.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/containers/RoutesContainer/Routes.test.tsx
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/url.ts
Updates `url.backend.namespaces.list()` to require the cluster arg, and all affected call-sites/dependencies.
Ref #1762
> Update backend url for namespaces to require cluster.

- dashboard/src/components/AppView/AppNotes.v2.scss
- dashboard/src/components/AppView/AppNotes.v2.test.tsx
- dashboard/src/components/AppView/AppNotes.v2.tsx
- dashboard/src/components/AppView/AppValues/AppValues.scss
- dashboard/src/components/AppView/AppValues/AppValues.v2.test.tsx
- dashboard/src/components/AppView/AppValues/AppValues.v2.tsx
- dashboard/src/components/AppView/AppValues/__snapshots__/AppValues.v2.test.tsx.snap
Adaptation of the release notes and values (the values field is mostly the same, only the title style changed).
Notes:
Values:
- ref #1354
> Installation notes and values

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Operators.ts
- dashboard/src/shared/Secret.test.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/ServiceCatalog.ts
- dashboard/src/shared/url.ts
Follow on from #1843, where [Andres' review mentioned that the namespace
url should be using our url helper](https://github.com/kubeapps/kubeapps/pull/1843#discussion_r449450126). While there, I've grouped all the
existing helpers which hit the api server directly under `api.k8s` as
well as a few more, so that we can clearly identify (and
potentially remove - see #1686) where the dashboard assumes direct access to the k8s
api.
It also updates the shared Secrets helper to be cluster aware (though the call-sites for app repository functionality are not, and will-not be for now).
Ref #1762
> Update api server urls to use url helper.

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- cmd/tiller-proxy/main.go
- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
When testing end-to-end, one of the issues I found in the backend was that we weren't using the `additionalClusters` configuration when setting up handlers and the default routes.
This change fixes that and removes some lint.
Ref: #1762
> Pass additionalClusters to NewHandler and SetupDefaultRoutes.

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/LoginForm/LoginForm.v2.test.tsx
- dashboard/src/components/LoginForm/LoginForm.v2.tsx
- dashboard/src/components/LoginForm/__snapshots__/LoginForm.v2.test.tsx.snap
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
More code pulled out of the demo branch at #1844 . In particular, this PR updates the Auth helper, actions and usage in login forms to all include the cluster from the state.
Follows #1877, Ref: #1762
> Send cluster through to login form and actions.

- dashboard/src/components/AppView/AppControls/AppControls.test.tsx
- dashboard/src/components/AppView/AppControls/UpgradeButton.test.tsx
- dashboard/src/components/Catalog/CatalogItem.test.tsx
- dashboard/src/components/ChartView/ChartDeployButton.test.tsx
- dashboard/src/components/Header/ClusterSelector.test.tsx
- dashboard/src/components/Header/ClusterSelector.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/shared/specs/mountWrapper.tsx
Adds a cluster selector to the header iff more than one cluster is configured.
#1762 
I've also updated previous code I'd landed to use the new `mountWrapper` helper (and updated the helper lib to be able to create a store with some merged attributes).
> Add a cluster selector to header when more than one cluster.

- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- docs/user/manifests/kubeapps-local-dev-apiserver-config.json
- docs/user/manifests/kubeapps-local-dev-auth-proxy-values.yaml
- docs/user/manifests/kubeapps-local-dev-openldap-values.yaml
- docs/user/manifests/kubeapps-local-dev-users-rbac.yaml
Updates the oauth2-proxy settings to explicitly include the `groups` scope. Updates the (my) developer local setup to demonstrate using groups rather than users for RBAC when logging in with LDAP.
The only actual (non-dev) change here is to set the scope explicitly. It hadn't been set and had worked fine as most providers (including dex) assuming `oidc email` if not set, it seems. Explicitly including `groups` in the scope of the request from the auth proxy to dex causes dex to query the ldap service for groups also:
```
kubectl -n dex logs deployment/dex --tail 4
time="2020-07-24T04:10:10Z" level=info msg="performing ldap search ou=People,dc=example,dc=org sub (&(objectClass=person)(mail=kubeapps-user-ldap@example.org))"
time="2020-07-24T04:10:10Z" level=info msg="username …
```
> Update dev setup to document oidc RBAC with ldap groups.

- dashboard/src/actions/auth.ts
- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/components/AppList/AppList.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
Updates the namespace actions and the reducer to be cluster-aware, updating state per-cluster.
Required for multicluster.
None
Ref: #1762
> Update namespace actions/reducer to be cluster aware.

- dashboard/src/actions/kube.test.tsx
- dashboard/src/components/AppView/AppSecrets/AppSecrets.test.tsx
- dashboard/src/components/AppView/AppView.test.tsx
- dashboard/src/components/AppView/AppView.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.v2.test.tsx
- dashboard/src/components/AppView/ResourceTable/__snapshots__/ResourceTable.test.tsx.snap
- dashboard/src/components/OperatorInstance/OperatorInstance.tsx
- dashboard/src/components/OperatorInstance/__snapshots__/OperatorInstance.test.tsx.snap
- dashboard/src/containers/AccessURLTableContainer/AccessURLTableContainer.test.tsx
- dashboard/src/containers/ApplicationStatusContainer/ApplicationStatusContainer.test.tsx
- dashboard/src/containers/ResourceItemContainer/ResourceItemContainer.test.tsx
- dashboard/src/containers/helpers/index.test.ts
- dashboard/src/reducers/kube.test.ts
- dashboard/src/shared/Kube.test.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/ResourceRef.test.ts
- dashboard/src/shared/ResourceRef.ts
Follows on from #1886, updating ResourceRefs to include the cluster (in the constructor as a required arg) then updating all the call-sites to use it (mainly in tests, other than AppView and OperatorInstance (which uses fromCRD)).
It was a pain to audit because the typechecker can't find everything, as the 3rd arg is an optional string. Anyway, I think I've audited all call-sites now.
This is slightly different to how I did the change in the demo branch, and has the benefit that the resource refs just calculate multicluster URLs once created, so users of the objects don't need to care.
Required for multicluster support.
Danger of missing a call-site.
Ref: #1762
> Update all call-sites to ensure ResourceRefs use cluster.

- dashboard/src/components/AppUpgrade/AppUpgrade.tsx
- dashboard/src/components/AppUpgrade/__snapshots__/AppUpgrade.test.tsx.snap
- dashboard/src/components/Catalog/Catalog.test.tsx
- dashboard/src/components/Catalog/Catalog.tsx
- dashboard/src/components/Catalog/Catalog.v2.test.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/Catalog/__snapshots__/Catalog.test.tsx.snap
- dashboard/src/components/Catalog/__snapshots__/Catalog.v2.test.tsx.snap
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/components/Header/Menu.tsx
- dashboard/src/components/SelectRepoForm/SelectRepoForm.tsx
- dashboard/src/containers/CatalogContainer/CatalogContainer.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/shared/url.ts
- integration/use-cases/create-private-registry.js
- integration/use-cases/create-registry.js
Updates the app repo config route and all call-sites to be clustered (last point on #1762).
A follow-up will ensure that if you select another cluster while browsing the app repos you will be unable to view them and see an appropriate info.
Since the cluster selector will be visible for all pages, we need to ensure appropriate behaviour or info is displayed when switching clusters.. Created #1894 to ensure other ones are done.
Ref: #1762
> Update the app repo config route to be clustered.

- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- docs/user/manifests/kubeapps-local-dev-additional-kind-cluster.yaml
- pkg/agent/agent.go
- pkg/kube/kube_handler.go
- script/cluster-kind.mk
- script/deploy-dev.mk
Ensures that if a user navigates to an additional cluster while viewing the config for app repos, or visits the config with the additional cluster already selected, that an informative message is displayed regarding their options:
We don't leave people not knowing why app repos aren't working for additional clusters.
Follows #1893 Ref: #1762
The next PR will ensure that an `--insecure` flag is passed before accepting additional clusters without CAData, as well as fixing the issue when CAData is provided and calls fail.
> Do not allow app repo listing for other clusterss.

- dashboard/package.json
- docs/developer/dashboard.md
After https://github.com/kubeapps/kubeapps/pull/1884, the expected host is `127.0.0.1` when running the server locally, this breaks my local dev environment because I am using `kubeapps.local`. Disabling the host check since we don't need it for the dev setup.
> Disable host check for dev setup

- chart/kubeapps/values.yaml
- dashboard/Dockerfile
Updates the bitnami charts in the values.yaml to their latest versions.
Some providers delete older tags (odd?) breaking chart deployments without manual configuration.
See if CI passes without issue.
Longer term, we should not pin these in our Kubeapps main branch, but pin them to the current latest when releasing the Kubeapps chart.
> Update pinned bitnami charts in values.yaml

- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/values.yaml
- docs/user/manifests/kubeapps-local-dev-auth-proxy-values.yaml
The only breaking change is that flags now require -- .
For details of breaking changes in 6.x:
https://github.com/oauth2-proxy/oauth2-proxy/blob/master/CHANGELOG.md#breaking-changes-1
Using more secure latest oauth2-proxy (project migrated earlier this year).
Users who have set `.Values.authProxy.additionalFlags` will need to update those (auth-proxy container will refuse to start).
> Update oauth2-proxy from 5.x to 6.x

- chart/kubeapps/templates/kubeops-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
- docs/user/manifests/kubeapps-local-dev-additional-kind-cluster.yaml
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
- script/deploy-dev.mk
There were two issues stopping secure connections to additional clusters:
* The base64-encoded ca data was not being decode before being used, and
* the `genericclioptions.ConfigFlags` struct used by Helm does not support CAData, but only a CAFile field
The latter required adding an emptydir /tmp mount so we can write the cafile for each additional cluster and Helm can use that.
It turns the only reason this wasn't working yesterday was that I had misconfigured the additional clusters cadata with that of the main cluster :/
With this change, I can create and delete releases on the additional cluster, as per the earlier video, but using a secure connection.
#1762 
Also noticed that the RBAC on the additional cluster works fine when using a user with explicit rolebindings, but not when …
> Enable secure config multicluster

- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/templates/apprepository-jobs-postupgrade.yaml
- chart/kubeapps/templates/assetsvc-deployment.yaml
- chart/kubeapps/templates/db-secret-bootstrap.yaml
- chart/kubeapps/templates/db-secret-jobs-cleanup.yaml
- chart/kubeapps/values.yaml
Upgrade the MongoDB chart. As far as I can tell, the only breaking change for us is that `existingSecret` is now under an "auth" subsection. We still need to manually check if upgrading using MongoDB fails (our CI only checks PostgreSQL).
> Update MongoDB chart from 7.X to 8.X

- chart/kubeapps/README.md
- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-config.yaml
- chart/kubeapps/values.yaml
After https://github.com/kubeapps/kubeapps/pull/1856/ the installation of Kubeapps will fail if the cluster doesn't support IPv6.
> Allow to disable ipv6

- .circleci/config.yml
- chart/kubeapps/Chart.yaml
Bumps the chart minor version to trigger a chart release. Also re-enables the latest release test (disabled in #1863).
> Bump chart 3.8.0

- chart/kubeapps/README.md
A user noticed the typo in https://github.com/bitnami/bitnami-docker-dreamfactory/pull/20. We are fixing it in our READMEs. Anchors shouldn't be affected: `README.md#tldr` it omits the semicolons.
> Fix TL;DR typo

- docs/user/manifests/kubeapps-local-dev-additional-apiserver-config.json
- script/deploy-dev.mk
While testing last week I'd noticed I was unable to use group RBAC (via an LDAP login) to authenticate with the additional cluster in my dev env, though it worked fine for the main cluster.
Checked now to find it was just missing oidc config for the additional cluster.
Also upgraded the dex chart to the latest stable.
- fixes #1896
> Fix dev additional cluster groups

- chart/kubeapps/values.yaml
Removes stable and incubator from the default app repositories since they will cease to be included in helm-hub and helm2 charts no longer being updated / maintained. 
I've also removed the `svc-cat` repo from the default values, as it is applicable for service catalog functionality only and can be enabled as required.
We don't advertise stale charts in the Kubeapps UI by default.
We don't advertise charts people are used to seeing - but they can be configured and bitnami will begin to publish some that were only available in stable (I hope?)
> Remove stable, svc-cat and incubator from default app repositories.

- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/values.yaml
Ensures that the chart won't render if additional clusters are configured but the oidc auth proxy is not configured.
If people use an externally configured auth proxy, we also want to enable configuring additional clusters.
Note that since we switched to oauth2-proxy (well, in particular, started supporting http-only cookies for auth), people have experienced issues with using an external auth proxy, as the frontend assumed cookie authn iff `.Values.authProxy.enabled` (see #1579). The new `.Values.authProxy.externallyEnabled` means we can trivially fix that in the frontend also, as done below.
So, configuring additional clusters but not using oidc fails:
```
$ helm install kubeapps ./chart/kubeapps --namespace kubeapps --values ./docs/user/manifests/kubeapps-local-dev-additional-kind-clust …
```
> Ensure chart will not render if additional clusters configured without oidc

- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.test.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
Updates the main menu to display the Service Instances (alpha?!) menu item only if a broker has been configured.
I think this option won't even be visible in the new UI. I'm only doing this here so that I don't need to make all the routes for service instances cluster aware, plus we had a recent request along these lines on the related issue (and it'll be a few weeks yet before the new UI is complete).
Users don't see a useless menu entry when service brokers have not even been configured.
- fixes #605
> Only show the Service Instances menu if the broker is configured.

- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.test.tsx
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.tsx
- dashboard/src/components/Config/ServiceBrokerList/__snapshots__/ServiceBrokerList.test.tsx.snap
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/RoutesContainer/Routes.tsx
- dashboard/src/containers/ServiceBrokerListContainer/ServiceBrokerListContainer.ts
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
- dashboard/src/shared/url.ts
Updates the service broker configuration to be clear its only supported on the default cluster:
While there, also included a commit addressing the [feedback from Andres](https://github.com/kubeapps/kubeapps/pull/1897#issuecomment-666983924) from the similar app repository info
Users who switch clusters when viewing the service broker config won't mistakenly think it's supported there.
- Ref #1894
> Ensure service brokers are default cluster only

- pkg/handlerutil/handlerutil.go
Simplifies said function.
`ErrorCodeWithDefault` becomes simpler and more to the point.
What made me react to this in the first place was the fact that [it seemed like _I_ had written the code in question](https://github.com/kubeapps/kubeapps/commit/db3fc03ba9830ab5b984884fa4b6d9b037ed09e9#diff-029683c5a8f545ea1c9238132ed2978cR50-R62), and I was confused because I never use that style. (In fact I had just moved the code from another file.)
> Simplify ErrorCodeWithDefault

- chart/kubeapps/README.md
- chart/kubeapps/values.yaml
In  #1910 this flag was added but defaulting to true. This has caught out a number of people as [dual stack IPv4/IPv6 is still alpha in kubernetes](https://kubernetes.io/docs/concepts/services-networking/dual-stack/), and not supported on some standard cluster setups (eg. Tanzu Kubernetes Grid).
> Switch the default for IPv6 support to false.

- docs/user/manifests/ingress-nginx-kind-with-large-proxy-buffers.yaml
- script/cluster-kind.mk
It turns out the issue with LDAP login I'd found on the previous #1939 wasn't specific to my own env, as @vrabbi also gets a 500 when logging in via LDAP on a TKG cluster.
I found the issue in my local ingres-nginx logs:
```
2020/08/17 00:56:00 [error] 50#50: *76751 upstream sent too big header while reading response header from upstream, client: 172.18.0.1, server: localhost, request: "GET /oauth2/callback?code=of4d542tl3zhphasig2cuvisx&state=0c27e351936a66b7540a438a745687ba%3A%2F HTTP/2.0", upstream: "http://10.244.0.15:3000/oauth2/callback?code=of4d542tl3zhphasig2cuvisx&state=0c27e351936a66b7540a438a745687ba%3A%2F", host: "localhost", referrer: "https://172.18.0.2:32000/auth/ldap?req=ahe3hmcoa2u367pprrdv2v6qh"
172.18.0.1 - - [17/Aug/2020:00:56:00 +0000] "GET …
```
> Ensure local ingress-nginx has larger proxy-buffer sizes.

- dashboard/src/components/ErrorAlert/ServiceCatalogNotInstalledAlert.tsx
As per the [comment on #1922](https://github.com/kubeapps/kubeapps/pull/1922#issuecomment-674796484), this link has been broken for some time, but is doubly broken now that the svc-cat app repository is not installed by default.
> Remove broken link.

- chart/kubeapps/templates/dashboard-config.yaml
Just sanitizes the templated output so it looks like:
```
config.json: |-
{
"namespace": "kubeapps",
"appVersion": "DEVEL",
"authProxyEnabled": true,
"oauthLoginURI": "/oauth2/start",
"oauthLogoutURI": "/oauth2/sign_out",
"featureFlags": {"invalidateCache":true,"operators":false,"ui":"hex"},
"clusters": [{"apiServiceURL":"https://172.18.0.3:6443","name":"second-cluster"},{"apiServiceURL":"https://example.com:6443","name":"third-cluster"}]
}
```
Not sure if there's a better way to filter a list of dicts?
> Sanitize the multicluster config when sending to frontend.

- dashboard/package.json
- dashboard/yarn.lock
When updating from `react-scripts-ts` to `react-scripts` we missed that we'd [pinned the version matcher for react-scripts to `3.4.1` rather than `^3.4.1`](https://github.com/kubeapps/kubeapps/pull/1823/files#diff-8a93884670d48666f7da0af337381d92R126).
A side-effect of this is that we were still depending (in our dev env) on out-of-date packages.
This updates to use the correct matcher to get updated packages.
> Fix the version matcher for react-scripts so that serialize-javascript is updated.

- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/values.yaml
On #1926 Andres mentioned:
> the comment's are not that clear, people may enable both `authProxy.enabled` and `authProxy.externallyEnabled` (mostly because we don't say anything about not setting `enabled` to true). I think the UX would be better if the params are:
> 
> ```
> enabled: false
> deployOauth2Proxy: true
> ```
> 
> so if people want to use their own auth proxy they disable that. WDYT?
I think in both my original PR and your suggestion above, the confusion is that it becomes ambiguous exactly what the `authProxy` section of the values is controlling (an init container resource? enabling an externally defined auth proxy? configuring oauth login/logout URIs for the dashboard?). And it's hard to find a way which doesn't have some ambiguity without breaking the existing options. If …
> Improve wording and semantics for external oauth proxy support.

- dashboard/src/components/Clarity/clarity.ts
- dashboard/src/components/Config/AppRepoList/AppRepoButton.v2.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoButton.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoControl.scss
- dashboard/src/components/Config/AppRepoList/AppRepoControl.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoControl.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoForm.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.scss
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoRefreshAllButton.v2.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoRefreshAllButton.v2.tsx
- dashboard/src/components/Config/AppRepoList/index.ts
- dashboard/src/components/Config/AppRepoList/index.tsx
- dashboard/src/components/Header/Header.v2.scss
- dashboard/src/components/LoginForm/LoginForm.v2.scss
- dashboard/src/components/PageHeader/PageHeader.v2.scss
- dashboard/src/containers/RepoListContainer/RepoListContainer.test.tsx
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/shared/specs/mountWrapper.tsx
- dashboard/src/shared/types.ts
First PR for adding support for the App Repo list management view:
Since this view is quite complex, this PR only contains the code related to the repository table and  the different buttons. I will send other PRs for:
- The form for adding/editing a repo
- The split between global and namespace repositories as detailed here: https://www.figma.com/proto/q8ZXJAU2JD1riZg2c47OeE/Wireframes?node-id=108%3A3164&scaling=min-zoom
Note that the buttons in the table are "outlined" rather than "flat" because I found a weird behavior: it's not possible to set the color to red ("danger") for flat buttons, the parameter gets ignored.
> AppRepoList v2

- docs/user/deploying-to-multiple-clusters.md
Fills in the "Updating multi-cluster options" section and adds a "Running a local multi-cluster development environment"
Rendered markdown at https://github.com/absoludity/kubeapps/blob/1764-document-update-config/docs/user/deploying-to-multiple-clusters.md
See last comments on #1951
> More multi-cluster documentation

- pkg/http-handler/http-handler.go
- pkg/http-handler/http-handler_test.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
This is needed to show the list of both the app repositories in the global namespace and other namespaces. Note that in the case that the request is for the `kubeapps` namespace, the request is made using the backend serviceaccount. This is to allow unprivileged users to list global apprepositories.
> Allow to list repositories using the backend

- go.mod
- pkg/kube/http_utils.go
- pkg/kube/http_utils_test.go
Configures the http client used to fetch the chart with the same `http_proxy` vars specifiied in the AppRepository's sync job pod template, if any.
You can now actually install a chart from an app repository that requires a proxy.
- fixes #1962 
Verified the fix in my local env setup as per 1962 as well.
> Use AppRepo http_proxy env when fetching chart.

- chart/kubeapps/Chart.yaml
Bump chart to release app v1.11.2 with more UI behind FF and fix for #1962
> Bump chart to release app v1.11.2 with chart 3.9.1

- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/components/Config/AppRepoList/AppRepoList.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.test.tsx
- dashboard/src/components/Config/AppRepoList/AppRepoList.v2.tsx
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.test.tsx
- dashboard/src/components/Config/ServiceBrokerList/ServiceBrokerList.tsx
- dashboard/src/components/Config/ServiceBrokerList/__snapshots__/ServiceBrokerList.test.tsx.snap
- dashboard/src/containers/RepoListContainer/RepoListContainer.ts
- dashboard/src/containers/ServiceBrokerListContainer/ServiceBrokerListContainer.ts
Part 1 of updating the dashboard components to use the `kubeappsCluster` config and remove "default" assumptions.
Work towards #1942
> Update dashboard components to use config.kubeappsCluster pt1

- cmd/assetsvc/mongodb_utils.go
- cmd/assetsvc/postgres_db_test.go
- cmd/assetsvc/postgresql_utils.go
- cmd/assetsvc/postgresql_utils_test.go
- integration/use-cases/upgrade.js
- script/e2e-test.sh
Fixes #1980 first by ensuring the integration test fails as it should have and then updating the assetsvc function in question to do what was intended - return charts from both the specific namespace as well as the global charts.
Still TODO: update the mongodb driver in the same way.
Can upgrade charts deployed from the global namespace.
- fixes #1980 
More of the problem investigation and description on the issue.
> Include global charts when filtering for charts available in a namespace

- cmd/tiller-proxy/internal/handler/handler.go
Avoid accessing a nil result by moving to after the error check.
Not sure how that slipped through review.
Example of the panic on #1985 
Fixes #1985
> Fix incorrect error handling to avoid panic.

- integration/use-cases/upgrade.js
I noticed yesterday while testing CI for other things that one spurious failure is due to the `apache` chart from the *wrong* repository being clicked on. Even before the change landed yesterday, the `upgrade.js` test just goes to the catalog and clicks on `apache` which, depending on luck, may be the bitnami one and so have the old 7.3.2 version, but if not, the `upgrade.js` test fails with:
as the `apache` from the private repo created in the earlier test has been clicked on instead, and it only has two very specific versions.
This change just ensures that the upgrade.js test uses the bitnami catalog.
> Ensure which repo chart is used during upgrade.

- dashboard/src/components/Header/ContextSelector.scss
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Menu.scss
The script `create-react-app` doesn't play well with percentages in SCSS (apparently): https://stackoverflow.com/questions/58853844/the-opacity-value-was-changed-to-1-after-building-the-reacjs-project which caused the `opacity` of the context selector to be `1%`.
Apart from the fix for the above, this PR includes another small fix for the namespace and cluster selector that was not setting a default `value`.
- ref #1354
> Fix opacity and select issue

- dashboard/src/components/ChartView/ChartHeader.v2.test.tsx
- dashboard/src/components/ChartView/ChartHeader.v2.tsx
Small fix for the update form. There, the version in the selector was forced to `currentVersion` so even after changing it, the currentVersion was always displayed in the selector.
> Fix version selector in update form

- dashboard/src/actions/catalog.test.tsx
- dashboard/src/actions/catalog.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/ClusterServiceClass.ts
- dashboard/src/shared/Kube.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/ServiceCatalog.ts
- dashboard/src/shared/ServiceInstance.ts
- dashboard/src/shared/url.ts
Updates shared helpers for AppRepositories, ServiceBrokers and ServiceInstances to no longer rely on the non-cluster-aware backend URIs.
Required for #1995 to be able to pass CI.
Ref: #1942
> 1942 app repos use cluster

- cmd/kubeops/internal/handler/handler.go
- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
- cmd/tiller-proxy/main.go
- pkg/chart/chart.go
- pkg/chart/chart_test.go
- pkg/http-handler/http-handler.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Another prep branch for the actual change of 1942: this PR removes the const `kube.DefaultClusterName` to instead be included in the clustersConfig for `kubeops`, still using the value `default`, though this will change in the next PR
I've one concern about the change of the cli arg, which I'll note below.
Ref #1942
> Remove dependence on const kube.DefaultClusterName, moving to config.

- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-config.yaml
- chart/kubeapps/templates/kubeapps-frontend-deployment.yaml
- chart/kubeapps/templates/kubeops-config.yaml
- chart/kubeapps/templates/kubeops-deployment.yaml
- chart/kubeapps/templates/tiller-proxy-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/kubeops/main.go
- cmd/kubeops/main_test.go
- cmd/tiller-proxy/main.go
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
- docs/user/manifests/kubeapps-local-dev-additional-kind-cluster.yaml
- script/deploy-dev.mk
Updates the `.Values.clusters` list of clusters to be definitive, enabling the cluster on which kubeapps is installed to have a name other than `default` or to not be a target cluster at all for users.
See #1942 and #1943 
TL;DR is that with this change, the cluster on which Kubeapps is running can be called whatever the user likes, but still defaults to `default`, and this is included in the definitive list of `.Values.clusters`.
- fixes #1942 
- fixes #1943
> Update chart's clusters list to be definitive.

- dashboard/src/components/AppList/AppListItem.v2.test.tsx
- dashboard/src/components/AppList/AppListItem.v2.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.test.tsx
- dashboard/src/components/AppList/CustomResourceListItem.v2.tsx
- dashboard/src/components/Catalog/ChartCatalogItem.tsx
- dashboard/src/components/Catalog/OperatorCatalogItem.tsx
- dashboard/src/components/InfoCard/InfoCard.v2.scss
- dashboard/src/components/InfoCard/InfoCard.v2.test.tsx
- dashboard/src/components/InfoCard/InfoCard.v2.tsx
- dashboard/src/components/InfoCard/__snapshots__/InfoCard.v2.test.tsx.snap
~~- [ ] Add status for operator instances~~ This cannot be done since there is no a generic way to obtain a short status from arbitrary instances
Screenshots:
- ref #1907
> Refactor cards

- dashboard/src/components/Catalog/Catalog.v2.test.tsx
- dashboard/src/components/Catalog/Catalog.v2.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.v2.test.tsx
- dashboard/src/components/DeploymentForm/DeploymentForm.v2.tsx
Follow up of #2015. If the namespace has not been selected (it's using "All Namespaces"), the catalog shows a warning so it's clear that a namespace should be selected first:
In any case, if someone manually introduces the `_all` namespaces in the deployment form, an error is shown:
- ref #1907
> Force selection of a single namespace

- dashboard/src/components/Header/ContextSelector.scss
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.v2.tsx
- dashboard/src/shared/specs/mountWrapper.tsx
Added the item for "All Namespaces" in the context selector as we have it today:
For the moment I am just matching current functionality, it's not the goal to rethink about the desired UX.
I have also fixed a small bug I noticed. The `select` input for the namespace were showing the wrong namespace when the namespace was changed outside the selector (for example when clicking on a link).
- ref #1907
> Add option for all namespaces in the namespace selector

- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/components/Header/ContextSelector.scss
- dashboard/src/components/Header/ContextSelector.test.tsx
- dashboard/src/components/Header/ContextSelector.tsx
- dashboard/src/components/Header/Header.test.tsx
- dashboard/src/components/Header/Header.tsx
- dashboard/src/containers/HeaderContainer/HeaderContainer.ts
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
I tried the multi-cluster support using the local dev environment to check how it behaves with the new UI. Found several bugs that has been fixed here:
- When selecting a new cluster, the namespace selector was not being populated with the available namespaces of that selector.
- The action `setNamespace` was not cluster-aware. This caused a race condition in which that is called before changing the `currentCluster` in the state, causing requesting resources from the wrong cluster.
- When selection a cluster, a default namespace should be `selected`.
- The `cluster` state reducer had a hard-coded reference to the `default` cluster.
- ref #1907
> Fix bugs for multicluster selector

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.v2.tsx
- dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.v2.test.tsx
- dashboard/src/components/OperatorInstanceFormBody/OperatorInstanceFormBody.v2.tsx
I noticed this bug, `type="button"` is not taking effect using the React wrapper for Clarity Core components. I may be missing something so I opened an issue for them to check. In the meantime, added this workaround.
> Workaround to avoid type=button issue

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.v2.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.test.tsx
- dashboard/src/components/UpgradeForm/UpgradeForm.v2.tsx
Noticed a couple of issues related to the existing state when upgrading a second application:
- The first application `schema` was being rendered.
- The "Changes" tab was using the first application deployed values as old values.
- ref #1907
> Fix some state issues

- chart/kubeapps/values.yaml
- cmd/kubeops/main.go
- cmd/tiller-proxy/internal/handler/handler.go
- cmd/tiller-proxy/internal/handler/handler_test.go
- cmd/tiller-proxy/main.go
- pkg/auth/auth.go
- pkg/auth/authgate.go
Updates the auth gate so that when requesting the charts available for a cluster and namespace, that it queries that cluster rather than using the incluster config.
On TKG (or otherwise) when Kubeapps is installed on a cluster itself without OIDC but configured for OIDC for the workload clusters, enables viewing the catalog of charts.
Fixes #2026
See #2037
> Ensure that the correct cluster is queried by authgate for catalog.

- chart/kubeapps/templates/ingress.yaml
Ingress apiVersion extensions/v1beta1 got deprecated and is now removed
in 1.16.
https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/
Its the same approach as the grafana (and prometheus-operator) chart are taking:
https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml#L6
It adds a helm based capability check to switch between both apiVersions;
This is possible as the ingress apiVersions are compatible (which is not always the case, see DaemonSet)
This change enables the current Ingress spec to be used in Kubernetes Version >= 1.16 while keeping compatibility to Kubernetes Versions < 1.16.
> add apiVersion check for ingress apiVersion

- chart/kubeapps/templates/kubeops-serviceaccount.yaml
The label `app.kubernetes.io/name` was being duplicated for the kubeops serviceaccount.
> Remove duplicated label

- script/release_notes.tpl
The release notes for the 2.0 beta included the no longer supported tiller-proxy-based install as an option.
This removes that from the template and I've updated the 2.0 beta 1 release notes.
- fixes #2068
> Update the release notes removing tiller-based install instructions

- dashboard/src/components/AppView/AccessURLTable/AccessURLTable.tsx
- dashboard/src/components/AppView/AccessURLTable/__snapshots__/AccessURLTable.test.tsx.snap
- dashboard/src/components/Layout/Layout.scss
Fix the style for the Access URL table when there is more than one URL per svc/ingress (before it was shown everything in the same line without spaces):
> Fix style for several Access URLs

- docs/user/access-control.md
- docs/user/using-an-OIDC-provider.md
While writing some unrelated Kubeapps content, I went to link to the
access-control user doc and saw that it is still referring to service tokens as
the normal way to authenticate (and even referring to the generic token auth on
k8s, which should not be used for similar reasons).
> Update the access-control doc to prefer OIDC.

- dashboard/src/components/OperatorList/OperatorItems.tsx
- dashboard/src/components/OperatorList/OperatorList.tsx
Similar to the catalog, Operators should be browsed using a namespace (if not, the final form would allow you to install them in the namespace `_all`). Also noticed that the icons where being fetched using the current namespace rather than the operator namespace (not that relevant when `_all` cannot be selected).
- found while investigating #2076
> Check namespace when listing operators

- dashboard/src/actions/apps.test.tsx
- dashboard/src/actions/apps.ts
- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppListGrid.tsx
- dashboard/src/components/AppList/AppListItem.tsx
- dashboard/src/components/AppList/__snapshots__/AppList.test.tsx.snap
- dashboard/src/containers/AppListContainer/AppListContainer.tsx
- dashboard/src/reducers/apps.test.ts
- dashboard/src/reducers/apps.ts
- dashboard/src/shared/App.test.ts
- dashboard/src/shared/App.ts
- dashboard/src/shared/types.ts
Fix an issue causing the request for the chart to use the current namespace (`_all` if all namespaces is selected) rather than the app namespace.
Apart from that, I found a small bug that two releases in different namespaces were using the same `key` in the list.
- fixes #2075
> Fix wrong namespace when requesting chart info

- chart/kubeapps/README.md
While going through the backlog I noticed that 1111 can now be considered
closed. We've come a long way with demoing OIDC integration and docs already
warn against service token auth for users etc.
> Improve wording for exposing kubeapps and remove link to closed issue.

- cmd/apprepository-controller/main.go
See the recent discussion on #1923.
Switching this flag on, for a specific case required by @davidkarlsen , would require updating the apprepository controller deployment to set the flag as `--repos-per-namespace=false`.
That said, I'm guessing you'd also need this flag on the deployment running tiller-proxy?
Enables manually configuring the app-repository controller deployment to only watch the kubeapps namespace.
Requires manual configuration, but this is OK IMO as it's a fix for a temporary
issue (where David is running Kubeapps with tiller-proxy in one namespace and
without in another.
- fixes #1923
> Enable manually switching repos-per-namespace to false. Fixes #1923

- .github/stale.yml
I've enabled probot-stale on the kubeapps/kubeapps repo only. This is just the
default configuration as per https://github.com/probot/stale
Is it not obvious? :)
- fixes #576
> Configuration for probot-stale. Fixes #576

- chart/kubeapps/values.yaml
- dashboard/src/components/OperatorList/OperatorList.tsx
- docs/user/deploying-to-multiple-clusters.md
- docs/user/manifests/kubeapps-local-dev-namespace-discovery-rbac.yaml
- integration/jest.environment.js
- pkg/chart/chart.go
- pkg/http-handler/http-handler.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
Similar to the approach when retrieving namespaces in other clusters, where a internal service token is used, use that token to retrieve logos. Note that it's not possible to use the user token because the logos are requested as `img` `src` so no authentication info is given for that request.
- fixes #2076
> Use cluster ServiceToken to retrieve operator logos

- chart/kubeapps/templates/apprepository-deployment.yaml
- chart/kubeapps/values.yaml
- cmd/apprepository-controller/main.go
Follows on from #2084 and the discussion there.
I initially didn't want to expose this via a chart option, but @andresmgot pointed out that there's another case where this would be useful: a cluster setup for training and learning where different users each have Kubeapps installed in their own namespace (in which case, we wouldn't want each installation picking up the app repositories of the other installations).
> Enable watching only the namespace in which Kubeapps is running.

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/apprepositories-secret.yaml
Reported in slack:
https://kubernetes.slack.com/archives/C9D3TSUG4/p1601819799005800
If several initialRepos have an associated secret, only the last one gets created. The three dashes line was (accidentally?) removed in #1299.
> Fix initialRepos setup when there are multiple secrets

- chart/kubeapps/templates/kubeops-rbac.yaml
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/url.ts
- pkg/http-handler/http-handler.go
Use `kubeops` for retrieving appRepositories. This allows to retrieve global app repositories for any user.
- fixes #2098
> Enable and use endpoint for listing appRepositories

- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.test.tsx
- dashboard/src/components/DeploymentFormBody/BasicDeploymentForm/TextParam.tsx
Found that the default value for number values was not being set in the form (e.g. `replicas: 1`). Turned out that `isEmpty(1)` returns `true`.
> Fix setting number values in form

- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.test.tsx
- dashboard/src/components/DeploymentFormBody/DeploymentFormBody.tsx
- dashboard/src/shared/schema.ts
Avoid showing non important changes (like deleted blank lines), when showing the difference between the default values and the ones to submit.
Note that these blank lines (and other changes) are performed when the values are parsed as YAML objects (in order to react to a change in the form).
- fixes #1293
> Avoid irrelevant changes in diff

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/actions/namespace.ts
- dashboard/src/reducers/auth.test.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Auth.ts
This is a quick workaround to avoid selecting all namespaces by default for users that don't have an associated namespace (OIDC scenario).
It's a workaround since IMO, we should completely remove the current behavior of automatically selecting the namespace from the given token and decouple the namespace selection from the authorization flow but didn't want to include that to be able to improve the UX for the final release of 2.0.
- fixes #2107
> Select the first namespace available by default

- docs/user/access-control.md
- docs/user/dashboard.md
- docs/user/deploying-to-multiple-clusters.md
- docs/user/getting-started.md
- docs/user/offline-installation.md
The goal of this PR is to prepare docs under the `user/` folder to be served in kubeapps.com. When parsing docs outside of Github, some links need to point to the full URL while other require some adaptation in their relative paths. The good thing is that links will still work both when reading them in Github or in the future docs site.
- fixes #2073
> Adapt links in docs

- docs/user/using-an-OIDC-provider.md
I believe this changed with a recent version of auth-proxy, and that we
just missed updating this documentation.
Just close this PR if I'm wrong.
> Change `-` to `--` for auth-proxy additionalFlags

- dashboard/src/components/AppView/ResourceTable/ResourceTable.test.tsx
- dashboard/src/components/AppView/ResourceTable/ResourceTable.tsx
At the moment, the code was assuming that there were one resource reference per resource in the state. Sometimes the reference points to a list so there will be more resources than references.
This PR also handles the case in which there are no references at all (but this is not happening IRL).
- fixes #2120
> Fix resource table when working with lists

- dashboard/src/components/AppList/AppListItem.test.tsx
- dashboard/src/components/AppList/AppListItem.tsx
- script/chart_sync_utils.sh
The appVersion field in the `Chart.yaml` may contain already the `v` prefix, and we are prefixing another `v` again:
In any case, the `appVersion` doesn't need that prefix so I am also removing it from our chart release process.
I'd swear I fixed this already but I couldn't find it, maybe I forgot to create the PR :thinking:
> Avoid double v prefix in the AppList

- dashboard/Dockerfile
- dashboard/package.json
- dashboard/src/components/Layout/Clarity.tsx
- dashboard/yarn.lock
For newcomers developers, it is a bit weird to have to manually include the Clarity dependency (as dockerfile did). Despite the docs mentions the only command to run the dashboard is `yarn install` and `yarn run start`, it was necessary to manually put the clarity `clr-ui.min.css` file.
What's more, the clarity dependency was already included in the package.json, but with major version = 2 (instead of 4).
This PR removes every manual importation of the  `clr-ui.min.css` file (and the old one from the HEX UI) and changes the importation to the `node_modules` folder (`../../../node_modules/@clr/ui/clr-ui.min.css` instead of `../../clr-ui.min.css`).
Since developers already have to exec `yarn install` in order to install the required deps, including Clarity in the list of deps improves …
> Consistent semver usage of @clr/ui dependency

- chart/kubeapps/templates/dashboard-config.yaml
After #2123, we have removed the `v` prefix from the chart appVersion. The problem is that we are using that version to generate some links to the documentation (e.g. `href={https://github.com/kubeapps/kubeapps/blob/${appVersion}/docs/user/getting-started.md}`) so we need to match the GitHub tag there.
> Restore v prefix in app configmap

- dashboard/src/components/AppView/AppValues/AppValues.tsx
- dashboard/src/components/DeploymentFormBody/AdvancedDeploymentForm.tsx
ACE text editors have lots of features out-of-the-box ready to be used. For instance,  the keybind Crtl+F should trigger a search box for searching within the text. However, this feature was not enabled. This PR is to support that.
Crtl+F will now trigger a searchbox to appear.
N/A
N/A
See the full list of ACE modules here: https://github.com/ajaxorg/ace-builds/blob/master/ace-modules.d.ts
> Add search (crtl+F) in ACE editors

- docs/developer/README.md
- docs/developer/apprepository-controller.md
- docs/developer/basic-form-support.md
- docs/developer/dashboard.md
- docs/developer/end-to-end-tests.md
- docs/developer/kubeops.md
Minor fixes in the developer documentation. Add a note for users deploying kubeops using a Kind cluster.
Kind cluster users won't get stuck when trying to update the kubeops image :P
N/A
N/A
N/A
> Minor fixes in devel docs

- CONTRIBUTING.md
- README.md
- chart/kubeapps/README.md
- docs/architecture/design-proposals/README.md
- docs/architecture/design-proposals/helm3.md
- docs/architecture/overview.md
- docs/developer/apprepository-controller.md
- docs/developer/asset-syncer.md
- docs/developer/assetsvc.md
- docs/developer/dashboard.md
- docs/developer/kubeops.md
- docs/developer/testing-environment.md
- docs/user/access-control.md
- docs/user/dashboard.md
- docs/user/deploying-to-multiple-clusters.md
- docs/user/getting-started.md
- docs/user/offline-installation.md
- docs/user/operators.md
- docs/user/private-app-repository.md
- docs/user/using-an-OIDC-provider.md
Across the years, some external links have changed (e.g., v2 Helm docs, oauth2-proxy was renamed, Harbor moved docs from GitHub, etc.). Besides, a bunch of relative links was pointing to nowhere.
This PR intents to keep up to date the Kubeapps documentation links.
The broken links from the Kubeapps GitHub docs should not exist (al least for, hopefully, a while).
If any external action is automatically using this docs source in order to generate an external documentation portal, this PR could affect it. Please, check it before merging.
No issue 
During this process, I've noticed that contacting the project team belongs to a former member. I didn't take further action, but I suppose it should be changed at some point.
https://github.com/kubeapps/kubeapps/blob/master/CONTRIBUTING.md#enforceme …
> Broken links docs fix

- dashboard/public/manifest.json
Wrong favicon declaration was causing a mismatch and, therefore, a console warning was being thrown: `Error while trying to use the following icon from the Manifest: http://localhost:8080/favicon.ico (Resource size is not correct - typo in the Manifest?)`.
This PR simply declares the existing favicons in the manifest.json.
No error is thrown in the console.
N/A
N/A
N/A
> Update app manifest to match with actual favicons

- docs/developer/dashboard.md
Since we use methods like .flat() a ^11.0.0 version is required. Docker image currently uses 12, so the version in the docs is being updated to match.
Dashboard developers won't get misleading information regarding the proper Node version to use.
N/A
N/A
N/A
> Update node version in docs

- dashboard/src/actions/catalog.test.tsx
- dashboard/src/actions/catalog.ts
- dashboard/src/actions/repos.test.tsx
- dashboard/src/actions/repos.ts
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/Namespace.ts
- dashboard/src/shared/Secret.test.ts
- dashboard/src/shared/Secret.ts
- dashboard/src/shared/ServiceBinding.ts
- dashboard/src/shared/url.ts
`cluster, others, namespace` and `cluster, namespace, others` orderings were mixed up across the code. This PR review each file using these methods and changes the order properly. Tests changed accordingly.
Now the two first arguments will be `cluster, namespace`. It was quite odd to be constantly mixing these two orderings and may lead to accidental errors due to a parameter misteaching (note normally they are both _string_ so no type alert will be thrown).
Despite the best effort applied in looking up each method usage, it is slightly possible to have missed some reference.
- This PR has been generated after the discussion in PR #2138.
N/A
> Change ordering in some arguments to "cluster, namespace, other args"

- docs/architecture/design-proposals/sso-without-oidc-api-server.md
Adds the overview and link to the design proposal for supporting SSO without requiring k8s API server configuration.
> Add design proposal for sso without oidc api server.

- dashboard/src/actions/repos.test.tsx
- dashboard/src/shared/AppRepository.ts
- dashboard/src/shared/url.ts
- pkg/http-handler/http-handler.go
- pkg/kube/fake.go
- pkg/kube/kube_handler.go
As discussed in #2062 , an endpoint to trigger a refresh in a given repository was requested. Internally, a refresh is being triggered when resyncRequests property changes. This PR creates an endpoint for doing so.
It also has implications on the frontend side, since it is no longer need to use de old logic (GET the appRepo, increase the resyncRequests and PUT it back).
This PR enables third-party integrations (i.e., Harbor webhooks) to manually trigger an update in a given AppRepository whenever needed.
Furthermore, on the frontend side, we no longer need to perform two requests, one is enough.
I can't see any negative implications in the short term. Perhaps we should re-think webhook and subscription mechanisms in the future and revisit this /refresh approach
- fixes #2062
For example, …
> Add a /refresh endpoint for forcing an update in an AppRepository

- chart/kubeapps/Chart.yaml
- chart/kubeapps/templates/dashboard-config.yaml
- chart/kubeapps/values.yaml
- dashboard/public/config.json
- dashboard/src/actions/auth.ts
- dashboard/src/components/LoginForm/LoginForm.test.tsx
- dashboard/src/components/LoginForm/LoginForm.tsx
- dashboard/src/components/LoginForm/__snapshots__/LoginForm.test.tsx.snap
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.test.tsx
- dashboard/src/containers/LoginFormContainer/LoginFormContainer.ts
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/config.ts
- dashboard/src/shared/Auth.test.ts
- dashboard/src/shared/Config.ts
As per #2109, allow users to configure Kubeapps so it skips the login/welcome page and redirect directly to the OAuth login URI.
To use it, a value is exposed in the chart: `--set authProxy.skipKubeappsLoginPage=true`.
- fixes #2109
> Allow to bypass the oauth loading page

- docs/user/syncing-apprepository-webhook.md
As suggested by https://github.com/kubeapps/kubeapps/pull/2151#discussion_r519640663, this PR is simply a rename from `apprepositories-webhook` to `apprepositories-refresh`.
More uniformity in naming.
Since the webhook /refresh has not been included in any release yet, there is no possible backward compatibility issue.
- Rel #2151 
N/A
> Rename apprepositories-webhook to apprepositories-refresh

- dashboard/src/components/Config/AppRepoList/AppRepoForm.scss
- dashboard/src/components/Layout/Layout.scss
- dashboard/src/components/OperatorNew/OperatorNew.scss
Refactor some style regarding form inputs. With the latest changes (importing the CSS package only), I noticed that the input size got shrank.
Before:
Fixed:
> Restore input style

- pkg/kube/kube_handler.go
- pkg/kube/kube_handler_test.go
This PR address two minor issues when listing namespaces:
- Filter out namespaces in which the user don't have permissions (regardless if the user has permission to list namespace). This is to avoid showing unusable namespaces for the user.
- Filter out namespaces that are in terminating status (which are not usable either).
- ref #2018 (points 1 and 3)
> Filter out forbidden and terminating namespaces

- chart/kubeapps/templates/_helpers.tpl
- chart/kubeapps/templates/apprepository-deployment.yaml
- cmd/apprepository-controller/controller.go
- cmd/apprepository-controller/controller_test.go
- cmd/apprepository-controller/main.go
- cmd/apprepository-controller/main_test.go
The problem described in #2144 and replicated following the steps in https://github.com/kubeapps/kubeapps/issues/2144#issuecomment-724805837 is pretty straightforward to be solved. `ImagePullSecrets` value is not being passed through the created jobs.
In order to make apprepository-controller accept this value, it should be passed as new arg param in the go binary.
For this purpose, the param `repo-sync-image-pullsecrets` has been created. It accepts a list of comma separated values with then names of the secrets used as ImagePullSecrets.
For this param to work, it is necessary that the Helm chart properly handles the values.global.imagePullSecrets. This PR also introduces a change in the chart for generating a comma-separated list based on the list of ImagePullSecrets.
We henceforth will …
> 2144 pull secrets in jobs fix

- chart/kubeapps/crds/apprepository-crd.yaml
- chart/kubeapps/templates/apprepository-crd.yaml
- cmd/apprepository-controller/artifacts/examples/crd.yaml
In k8s 1.16+ a deprecation warning of `apiextensions.k8s.io/v1beta1` in favor of `apiextensions.k8s.io/v1` appeared. In 1.22+ it will be fully deprecated.
This PR bumps `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`.
Users won't get a deprecation warning. Besides, k8s 1.22+ users still will be able to install Kubeapps.
Prior to <1.16 it won't be compatible (but these versions already reached EOL).
N/A
Perhaps it should be landed with other chart-related PRs to also bump up the chart version.
> Bump CRD from v1beta1 to v1 (k8s  1.16+)

- dashboard/src/actions/auth.test.tsx
- dashboard/src/actions/auth.ts
- dashboard/src/actions/namespace.test.tsx
- dashboard/src/actions/namespace.ts
- dashboard/src/reducers/charts.test.ts
- dashboard/src/reducers/charts.ts
- dashboard/src/reducers/cluster.test.ts
- dashboard/src/reducers/cluster.ts
- dashboard/src/reducers/operators.test.ts
- dashboard/src/reducers/operators.ts
- dashboard/src/shared/Namespace.ts
Another item for #2018, store the latest namespace used in the browser so it's easier to resume previous work.
When logging out of the system (or when the session expires), this information is cleaned up.
- ref #2018
> Store the last namespace used in the browser storage

- chart/kubeapps/Chart.lock
- chart/kubeapps/Chart.yaml
- chart/kubeapps/README.md
- chart/kubeapps/requirements.lock
- chart/kubeapps/requirements.yaml
- Bump `apiVersion` from `v1` to `v2` in _Chart.yaml_
- Fields in _Chart.yaml_ file has been ordered alphabetically (standardization for all Bitnami Helm Charts)
- Move dependency information from the _requirements.yaml_ to the _Chart.yaml_
- After running `helm dependency update`, a new _Chart.lock_ file is generated containing the same structure used in the previous _requirements.lock_
- Update _README.md_
- There is a new PostgreSQL subchart major version containing the same changes described here about the apiVersion and also a terminology renaming from master/slave to primary/read
**Possible drawbacks**
Helm v2 is no longer supported
> [bitnami/kubeapps] Major version. Adapt Chart to apiVersion: v2

- integration/use-cases/upgrade.js
Due to a new input in the apache form, the `#replicaCount-1` selector is not available (now it's `replicaCount-2`). In this PR I'm using a different selector to avoid that issue in the future (but it will still break if there is another number input).
- fixes master builds
> Fix upgrade test

- script/chart_sync_utils.sh
When syncing the chart with the bitnami repo, the version in the commit message is wrong since it's picking the PosgreSQL dependency:
https://github.com/bitnami/charts/commit/cbe4ff5431459d4f037d905aa9ed2cbc89e6c16a
Note that the `Chart.yaml` now contains both versions:
```yaml
dependencies:
- name: postgresql
repository: https://charts.bitnami.com/bitnami
version: '10.X.X'
name: kubeapps
version: 5.0.0
```
> Fix version retrieval when pushing commit

- dashboard/src/components/AppList/AppList.test.tsx
- dashboard/src/components/AppList/AppList.tsx
Depends on: #2179
Normal users won't have permission to list apps in all namespaces so hide the switch in that case.
> Hide all-namespace switch if not allowed

- chart/kubeapps/README.md
- docs/user/manifests/kubeapps-local-dev-auth-proxy-values.yaml
- docs/user/using-an-OIDC-provider.md
After the question received in https://github.com/kubeapps/kubeapps/issues/2152 we noticed there was no documentation explaining how to set up Kubeapps to be accessed in a subpath (eg., console.example.com/catalog).
This PR adds a new FAQ section in the chart readme and, specifically, focuses upon explaining the changes in different parts to have a running Kubeapps with OIDC under a subpath.
Besides the `authProxy.oauth{Login|Logout}URI` flags already documented, Dex has to be configured with the `--proxy-prefix=/subpath/oauth2` flag
Users deploying Kubeapps with OIDC under a subpath will have docs to do so.
Despite I have manually tested the basic functionality was working fine, perhaps there exists some problem we are not aware of yet (such as the chart names containing slashes).
- …
> Add FAQ section in the chart readme (+ focus on subpath and OIDC)
